export default [
    {"id": "document-empty", "class": "document/empty", "document": "", "rule": "document: a document is const* export", "host": "accepts"},
    {"id": "document-whitespace-only", "class": "document/whitespace-only", "document": " \n", "rule": "document: a document is const* export", "host": "accepts"},
    {"id": "document-no-export", "class": "document/export/missing", "document": "const $0=1;", "rule": "document: export default is required", "host": "accepts"},
    {"id": "document-export-not-last", "class": "document/export/not-last", "document": "export default 1;const $0=1;", "rule": "document: export default is the last statement", "host": "accepts"},
    {"id": "document-export-twice", "class": "document/export/twice", "document": "export default 1;export default 2;", "rule": "document: one export default", "host": "syntaxError"},
    {"id": "document-semicolon-const", "class": "document/semicolon/const", "document": "const $0=1 export default $0;", "rule": "document: every statement ends with ;", "host": "syntaxError"},
    {"id": "document-semicolon-export", "class": "document/semicolon/export", "document": "export default 1", "rule": "document: every statement ends with ;", "host": "accepts"},
    {"id": "document-semicolon-export-newline", "class": "document/semicolon/export/newline", "document": "export default 1\n", "rule": "document: every statement ends with ;", "host": "accepts"},
    {"id": "document-semicolon-double", "class": "document/empty-statement/double", "document": "export default 1;;", "rule": "document: there is no empty statement", "host": "accepts"},
    {"id": "document-semicolon-leading", "class": "document/empty-statement/leading", "document": ";export default 1;", "rule": "document: there is no empty statement", "host": "accepts"},
    {"id": "document-semicolon-between", "class": "document/empty-statement/between", "document": "const $0=1;;export default $0;", "rule": "document: there is no empty statement", "host": "accepts"},
    {"id": "document-comment-line", "class": "document/comment/line", "document": "// a\nexport default 1;", "rule": "document: there are no comments", "host": "accepts"},
    {"id": "document-comment-block", "class": "document/comment/block", "document": "/* a */export default 1;", "rule": "document: there are no comments", "host": "accepts"},
    {"id": "document-comment-trailing", "class": "document/comment/trailing", "document": "export default 1;// a", "rule": "document: there are no comments", "host": "accepts"},
    {"id": "document-import", "class": "document/import", "document": "import \"data:text/javascript,\";export default 1;", "rule": "document: there is no import", "host": "accepts"},
    {"id": "document-import-binding", "class": "document/import/binding", "document": "import * as $m from \"data:text/javascript,\";export default 1;", "rule": "document: there is no import", "host": "accepts"},
    {"id": "document-statement-let", "class": "document/statement/let", "document": "let $0=1;export default 1;", "rule": "document: a statement is a const or the export default, and nothing else", "host": "accepts"},
    {"id": "document-statement-var", "class": "document/statement/var", "document": "var $0=1;export default 1;", "rule": "document: a statement is a const or the export default, and nothing else", "host": "accepts"},
    {"id": "document-statement-function", "class": "document/statement/function", "document": "function $f(){}export default 1;", "rule": "document: a statement is a const or the export default, and nothing else", "host": "accepts"},
    {"id": "document-statement-expression", "class": "document/statement/expression", "document": "1;export default 1;", "rule": "document: a statement is a const or the export default, and nothing else", "host": "accepts"},
    {"id": "document-trailing-reference", "class": "document/trailing/reference", "document": "const $0=1;export default 1;$0;", "rule": "document: a statement is a const or the export default, and nothing else", "host": "accepts"},
    {"id": "document-trailing-value", "class": "document/trailing/value", "document": "export default 1;2;", "rule": "document: a statement is a const or the export default, and nothing else", "host": "accepts"},
    {"id": "const-name-no-dollar", "class": "const/name/no-dollar", "document": "const a=1;export default a;", "rule": "identifiers: a const name is an id, which begins with $", "host": "accepts"},
    {"id": "const-name-reserved", "class": "const/name/reserved", "document": "const class=1;export default 1;", "rule": "identifiers: a const name is an id, which begins with $", "host": "syntaxError"},
    {"id": "const-name-value-word", "class": "const/name/value-word", "document": "const undefined=1;export default 1;", "rule": "identifiers: a const name is an id, which begins with $", "host": "accepts"},
    {"id": "const-name-dollar-inside", "class": "const/name/dollar-inside", "document": "const a$=1;export default a$;", "rule": "identifiers: a const name is an id, which begins with $", "host": "accepts"},
    {"id": "const-duplicate", "class": "const/duplicate", "document": "const $0=1;const $0=2;export default $0;", "rule": "const names: each name is bound at most once", "host": "syntaxError"},
    {"id": "const-duplicate-same-value", "class": "const/duplicate/same-value", "document": "const $0=1;const $0=1;export default $0;", "rule": "const names: each name is bound at most once", "host": "syntaxError"},
    {"id": "const-declarators", "class": "const/declarators", "document": "const $a=1,$b=2;export default [$a,$b];", "rule": "document: a const is one name bound to one value", "host": "accepts"},
    {"id": "const-destructuring-array", "class": "const/destructuring/array", "document": "const [$a]=[1];export default $a;", "rule": "document: a const is one name bound to one value", "host": "accepts"},
    {"id": "const-destructuring-object", "class": "const/destructuring/object", "document": "const {$a}={\"$a\":1};export default $a;", "rule": "document: a const is one name bound to one value", "host": "accepts"},
    {"id": "const-no-value", "class": "const/no-value", "document": "const $a;export default 1;", "rule": "document: a const is one name bound to one value", "host": "syntaxError"},
    {"id": "const-no-name", "class": "const/no-name", "document": "const =1;export default 1;", "rule": "document: a const is one name bound to one value", "host": "syntaxError"},
    {"id": "reference-unbound", "class": "reference/unbound", "document": "export default $0;", "rule": "sharing: a reference names a previously declared const", "host": "runtimeError"},
    {"id": "reference-unbound-among", "class": "reference/unbound/among", "document": "const $0=1;export default $1;", "rule": "sharing: a reference names a previously declared const", "host": "runtimeError"},
    {"id": "reference-forward", "class": "reference/forward", "document": "const $0=$1;const $1=1;export default $0;", "rule": "sharing: a reference names a previously declared const", "host": "runtimeError"},
    {"id": "reference-self", "class": "reference/self", "document": "const $0=[$0];export default $0;", "rule": "sharing: a reference names a previously declared const", "host": "runtimeError"},
    {"id": "reference-case", "class": "reference/case", "document": "const $a=1;export default $A;", "rule": "sharing: a reference names a previously declared const", "host": "runtimeError"},
    {"id": "reference-prefix", "class": "reference/prefix", "document": "const $ab=1;export default $a;", "rule": "sharing: a reference names a previously declared const", "host": "runtimeError"},
    {"id": "reference-member", "class": "reference/member", "document": "const $a={\"b\":1};export default $a.b;", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "reference-index", "class": "reference/index", "document": "const $a=[1];export default $a[0];", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "export-named", "class": "export/form/named", "document": "const $a=1;export{$a};export default $a;", "rule": "document: the export is export default value", "host": "accepts"},
    {"id": "export-const", "class": "export/form/const", "document": "export const $a=1;export default $a;", "rule": "document: the export is export default value", "host": "accepts"},
    {"id": "export-no-default", "class": "export/form/no-default", "document": "export 1;", "rule": "document: the export is export default value", "host": "syntaxError"},
    {"id": "export-default-only", "class": "export/form/no-value", "document": "export default;", "rule": "document: the export is export default value", "host": "syntaxError"},
    {"id": "value-parenthesized", "class": "value/expression/parenthesized", "document": "export default (1);", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-binary", "class": "value/expression/binary", "document": "export default 1+1;", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-index", "class": "value/expression/index", "document": "export default [1][0];", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-call", "class": "value/expression/call", "document": "export default String(1);", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-void", "class": "value/expression/void", "document": "export default void 0;", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-double-negation", "class": "value/expression/double-negation", "document": "export default -(-1);", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-ternary", "class": "value/expression/ternary", "document": "export default true?1:2;", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-typeof", "class": "value/expression/typeof", "document": "export default typeof 1;", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-comma", "class": "value/expression/comma", "document": "export default (1,2);", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-new", "class": "value/expression/new", "document": "export default new Array();", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-this", "class": "value/expression/this", "document": "export default this;", "rule": "value: a value is one of the closed list, not an expression", "host": "accepts"},
    {"id": "value-sign-nan", "class": "value/sign/nan", "document": "export default -NaN;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-undefined", "class": "value/sign/undefined", "document": "export default -undefined;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-true", "class": "value/sign/true", "document": "export default -true;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-null", "class": "value/sign/null", "document": "export default -null;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-string", "class": "value/sign/string", "document": "export default -\"1\";", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-array", "class": "value/sign/array", "document": "export default -[];", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-reference", "class": "value/sign/reference", "document": "const $0=1;export default -$0;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-bare", "class": "value/sign/bare", "document": "export default -;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "syntaxError"},
    {"id": "value-sign-double", "class": "value/sign/double", "document": "export default --1;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "syntaxError"},
    {"id": "value-sign-space", "class": "value/sign/space", "document": "export default - 1;", "rule": "tokens: - belongs to a number, a bigint or Infinity, and nothing else", "host": "accepts"},
    {"id": "value-sign-plus-infinity", "class": "value/sign/plus-infinity", "document": "export default +Infinity;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "array-trailing-comma", "class": "array/trailing-comma", "document": "export default [1,];", "rule": "document: there are no trailing commas", "host": "accepts"},
    {"id": "array-trailing-comma-two", "class": "array/trailing-comma/two", "document": "export default [1,2,];", "rule": "document: there are no trailing commas", "host": "accepts"},
    {"id": "array-elision-leading", "class": "array/elision/leading", "document": "export default [,1];", "rule": "array: no elisions", "host": "accepts"},
    {"id": "array-elision-medial", "class": "array/elision/medial", "document": "export default [1,,2];", "rule": "array: no elisions", "host": "accepts"},
    {"id": "array-elision-trailing", "class": "array/elision/trailing", "document": "export default [1,,];", "rule": "array: no elisions", "host": "accepts"},
    {"id": "array-elision-only", "class": "array/elision/only", "document": "export default [,];", "rule": "array: no elisions", "host": "accepts"},
    {"id": "array-spread", "class": "array/spread", "document": "export default [...[1]];", "rule": "array: no spread", "host": "accepts"},
    {"id": "array-unclosed", "class": "array/unclosed", "document": "export default [1;", "rule": "value: a value is one of the closed list, not an expression", "host": "syntaxError"},
    {"id": "array-unopened", "class": "array/unopened", "document": "export default 1];", "rule": "value: a value is one of the closed list, not an expression", "host": "syntaxError"},
    {"id": "array-no-comma", "class": "array/no-comma", "document": "export default [1 2];", "rule": "value: a value is one of the closed list, not an expression", "host": "syntaxError"},
    {"id": "array-semicolon", "class": "array/separator/semicolon", "document": "export default [1;2];", "rule": "value: a value is one of the closed list, not an expression", "host": "syntaxError"},
    {"id": "object-trailing-comma", "class": "object/trailing-comma", "document": "export default {\"a\":1,};", "rule": "document: there are no trailing commas", "host": "accepts"},
    {"id": "object-trailing-comma-two", "class": "object/trailing-comma/two", "document": "export default {\"a\":1,\"b\":2,};", "rule": "document: there are no trailing commas", "host": "accepts"},
    {"id": "object-leading-comma", "class": "object/leading-comma", "document": "export default {,\"a\":1};", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "object-double-comma", "class": "object/double-comma", "document": "export default {\"a\":1,,\"b\":2};", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "object-spread", "class": "object/spread", "document": "export default {...{\"a\":1}};", "rule": "object: a member is a key, a colon and a value", "host": "accepts"},
    {"id": "object-method", "class": "object/method", "document": "export default {\"a\"(){}};", "rule": "object: a member is a key, a colon and a value", "host": "accepts"},
    {"id": "object-getter", "class": "object/accessor/getter", "document": "export default {get \"a\"(){}};", "rule": "object: a member is a key, a colon and a value", "host": "accepts"},
    {"id": "object-setter", "class": "object/accessor/setter", "document": "export default {set \"a\"($v){}};", "rule": "object: a member is a key, a colon and a value", "host": "accepts"},
    {"id": "object-no-colon", "class": "object/no-colon", "document": "export default {\"a\" 1};", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "object-equals", "class": "object/equals", "document": "export default {\"a\"=1};", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "object-no-value", "class": "object/no-value", "document": "export default {\"a\":};", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "object-unclosed", "class": "object/unclosed", "document": "export default {\"a\":1;", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "object-key-only", "class": "object/key-only", "document": "export default {\"a\"};", "rule": "object: a member is a key, a colon and a value", "host": "syntaxError"},
    {"id": "key-identifier", "class": "key/identifier", "document": "export default {a:1};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-identifier-dollar", "class": "key/identifier/dollar", "document": "export default {$a:1};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-numeric", "class": "key/numeric", "document": "export default {1:2};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-numeric-float", "class": "key/numeric/float", "document": "export default {1.5:2};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-computed-string", "class": "key/computed/string", "document": "export default {[\"x\"]:1};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-computed-number", "class": "key/computed/number", "document": "export default {[1]:2};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-computed-reference", "class": "key/computed/reference", "document": "const $k=\"a\";export default {[$k]:1};", "rule": "key: a key is a string or the one computed spelling [\"__proto__\"]", "host": "accepts"},
    {"id": "key-proto-bare", "class": "key/proto/bare", "document": "export default {__proto__:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-string", "class": "key/proto/string", "document": "export default {\"__proto__\":1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-string-escaped", "class": "key/proto/string/escaped", "document": "export default {\"\\u005f_proto__\":1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-string-escaped-all", "class": "key/proto/string/escaped-all", "document": "export default {\"\\u005f\\u005f\\u0070\\u0072\\u006f\\u0074\\u006f\\u005f\\u005f\":1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-string-among", "class": "key/proto/string/among", "document": "export default {\"a\":1,\"__proto__\":2,\"b\":3};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-string-nested", "class": "key/proto/string/nested", "document": "export default [{\"a\":{\"__proto__\":1}}];", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-escaped", "class": "key/proto/computed/escaped", "document": "export default {[\"\\u005f_proto__\"]:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-space-both", "class": "key/proto/computed/space/both", "document": "export default {[ \"__proto__\" ]:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-space-left", "class": "key/proto/computed/space/left", "document": "export default {[ \"__proto__\"]:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-space-right", "class": "key/proto/computed/space/right", "document": "export default {[\"__proto__\" ]:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-single-quoted", "class": "key/proto/computed/single-quoted", "document": "export default {['__proto__']:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-template", "class": "key/proto/computed/template", "document": "export default {[`__proto__`]:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "key-proto-computed-bare", "class": "key/proto/computed/bare", "document": "export default {[__proto__]:1};", "rule": "objects: __proto__ has one spelling, the exact computed form", "host": "accepts"},
    {"id": "number-hex", "class": "number/hex", "document": "export default 0x10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-hex", "class": "number/hex/neg", "document": "export default -0x10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-hex-upper", "class": "number/hex-upper", "document": "export default 0X10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-hex-upper", "class": "number/hex-upper/neg", "document": "export default -0X10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-binary", "class": "number/binary", "document": "export default 0b10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-binary", "class": "number/binary/neg", "document": "export default -0b10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-binary-upper", "class": "number/binary-upper", "document": "export default 0B10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-binary-upper", "class": "number/binary-upper/neg", "document": "export default -0B10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-octal", "class": "number/octal", "document": "export default 0o10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-octal", "class": "number/octal/neg", "document": "export default -0o10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-octal-upper", "class": "number/octal-upper", "document": "export default 0O10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-octal-upper", "class": "number/octal-upper/neg", "document": "export default -0O10;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-separator", "class": "number/separator", "document": "export default 1_0;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-separator", "class": "number/separator/neg", "document": "export default -1_0;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-leading-point", "class": "number/leading-point", "document": "export default .5;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-leading-point", "class": "number/leading-point/neg", "document": "export default -.5;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-trailing-point", "class": "number/trailing-point", "document": "export default 1.;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-trailing-point", "class": "number/trailing-point/neg", "document": "export default -1.;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-leading-zero", "class": "number/leading-zero", "document": "export default 01;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-leading-zero", "class": "number/leading-zero/neg", "document": "export default -01;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-leading-zeros", "class": "number/leading-zeros", "document": "export default 007;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-leading-zeros", "class": "number/leading-zeros/neg", "document": "export default -007;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-plus", "class": "number/plus", "document": "export default +1;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-plus-zero", "class": "number/plus/zero", "document": "export default +0;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-exp-no-digits", "class": "number/exp/no-digits", "document": "export default 1e;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-exp-no-digits", "class": "number/exp/no-digits/neg", "document": "export default -1e;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-exp-sign-no-digits", "class": "number/exp/sign/no-digits", "document": "export default 1e+;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-exp-sign-no-digits", "class": "number/exp/sign/no-digits/neg", "document": "export default -1e+;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-exp-double-sign", "class": "number/exp/double-sign", "document": "export default 1e--2;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-exp-double-sign", "class": "number/exp/double-sign/neg", "document": "export default -1e--2;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-frac-exp-no-digits", "class": "number/frac/no-digits/exp", "document": "export default 1.e2;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-neg-frac-exp-no-digits", "class": "number/frac/no-digits/exp/neg", "document": "export default -1.e2;", "rule": "numbers: a number is a JSON number", "host": "accepts"},
    {"id": "number-exp-point", "class": "number/exp/point", "document": "export default 1e2.5;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-exp-point", "class": "number/exp/point/neg", "document": "export default -1e2.5;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-double-point", "class": "number/double-point", "document": "export default 1.5.5;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-double-point", "class": "number/double-point/neg", "document": "export default -1.5.5;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-exp-word", "class": "number/exp/infinity", "document": "export default 1eInfinity;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "number-neg-exp-word", "class": "number/exp/infinity/neg", "document": "export default -1eInfinity;", "rule": "numbers: a number is a JSON number", "host": "syntaxError"},
    {"id": "bigint-hex", "class": "bigint/hex", "document": "export default 0x10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-hex", "class": "bigint/hex/neg", "document": "export default -0x10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-hex-upper", "class": "bigint/hex-upper", "document": "export default 0X10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-hex-upper", "class": "bigint/hex-upper/neg", "document": "export default -0X10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-binary", "class": "bigint/binary", "document": "export default 0b10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-binary", "class": "bigint/binary/neg", "document": "export default -0b10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-binary-upper", "class": "bigint/binary-upper", "document": "export default 0B10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-binary-upper", "class": "bigint/binary-upper/neg", "document": "export default -0B10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-octal", "class": "bigint/octal", "document": "export default 0o10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-octal", "class": "bigint/octal/neg", "document": "export default -0o10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-octal-upper", "class": "bigint/octal-upper", "document": "export default 0O10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-octal-upper", "class": "bigint/octal-upper/neg", "document": "export default -0O10n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-separator", "class": "bigint/separator", "document": "export default 1_0n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-neg-separator", "class": "bigint/separator/neg", "document": "export default -1_0n;", "rule": "bigints: a bigint is an int and n", "host": "accepts"},
    {"id": "bigint-leading-point", "class": "bigint/leading-point", "document": "export default .5n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-leading-point", "class": "bigint/leading-point/neg", "document": "export default -.5n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-trailing-point", "class": "bigint/trailing-point", "document": "export default 1.n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-trailing-point", "class": "bigint/trailing-point/neg", "document": "export default -1.n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-leading-zero", "class": "bigint/leading-zero", "document": "export default 01n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-leading-zero", "class": "bigint/leading-zero/neg", "document": "export default -01n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-fraction", "class": "bigint/fraction", "document": "export default 1.5n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-fraction", "class": "bigint/fraction/neg", "document": "export default -1.5n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-exponent", "class": "bigint/exponent", "document": "export default 1e2n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-exponent", "class": "bigint/exponent/neg", "document": "export default -1e2n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-exponent-upper", "class": "bigint/exponent-upper", "document": "export default 1E2n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-exponent-upper", "class": "bigint/exponent-upper/neg", "document": "export default -1E2n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-plus", "class": "bigint/plus", "document": "export default +1n;", "rule": "bigints: a bigint is an int and n", "host": "runtimeError"},
    {"id": "bigint-suffix-upper", "class": "bigint/suffix/upper", "document": "export default 1N;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-suffix-upper", "class": "bigint/suffix/upper/neg", "document": "export default -1N;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-suffix-double", "class": "bigint/suffix/double", "document": "export default 1nn;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-suffix-double", "class": "bigint/suffix/double/neg", "document": "export default -1nn;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-suffix-space", "class": "bigint/suffix/space", "document": "export default 1 n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "bigint-neg-suffix-space", "class": "bigint/suffix/space/neg", "document": "export default -1 n;", "rule": "bigints: a bigint is an int and n", "host": "syntaxError"},
    {"id": "string-quote-single", "class": "string/quote/single", "document": "export default 'a';", "rule": "strings: a string is a JSON string, double-quoted", "host": "accepts"},
    {"id": "key-quote-single", "class": "key/string/quote/single", "document": "export default {'a':0};", "rule": "strings: a string is a JSON string, double-quoted", "host": "accepts"},
    {"id": "string-quote-template", "class": "string/quote/template", "document": "export default `a`;", "rule": "strings: a string is a JSON string, double-quoted", "host": "accepts"},
    {"id": "key-quote-template", "class": "key/string/quote/template", "document": "export default {`a`:0};", "rule": "strings: a string is a JSON string, double-quoted", "host": "syntaxError"},
    {"id": "string-quote-template-empty", "class": "string/quote/template/empty", "document": "export default ``;", "rule": "strings: a string is a JSON string, double-quoted", "host": "accepts"},
    {"id": "key-quote-template-empty", "class": "key/string/quote/template/empty", "document": "export default {``:0};", "rule": "strings: a string is a JSON string, double-quoted", "host": "syntaxError"},
    {"id": "string-escape-v", "class": "string/escape/v", "document": "export default \"\\v\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-v", "class": "key/string/escape/v", "document": "export default {\"\\v\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-0", "class": "string/escape/0", "document": "export default \"\\0\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-0", "class": "key/string/escape/0", "document": "export default {\"\\0\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-single-quote", "class": "string/escape/single-quote", "document": "export default \"\\'\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-single-quote", "class": "key/string/escape/single-quote", "document": "export default {\"\\'\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-backtick", "class": "string/escape/backtick", "document": "export default \"\\`\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-backtick", "class": "key/string/escape/backtick", "document": "export default {\"\\`\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-x", "class": "string/escape/x", "document": "export default \"\\x41\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-x", "class": "key/string/escape/x", "document": "export default {\"\\x41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-u-braces", "class": "string/escape/u-braces", "document": "export default \"\\u{41}\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-u-braces", "class": "key/string/escape/u-braces", "document": "export default {\"\\u{41}\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-octal", "class": "string/escape/octal", "document": "export default \"\\101\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-octal", "class": "key/string/escape/octal", "document": "export default {\"\\101\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-octal-8", "class": "string/escape/octal/8", "document": "export default \"\\8\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-octal-8", "class": "key/string/escape/octal/8", "document": "export default {\"\\8\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-identity", "class": "string/escape/identity", "document": "export default \"\\z\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-identity", "class": "key/string/escape/identity", "document": "export default {\"\\z\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-identity-a", "class": "string/escape/identity/a", "document": "export default \"\\a\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-identity-a", "class": "key/string/escape/identity/a", "document": "export default {\"\\a\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-uppercase-n", "class": "string/escape/uppercase", "document": "export default \"\\N\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-uppercase-n", "class": "key/string/escape/uppercase", "document": "export default {\"\\N\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-uppercase-u", "class": "string/escape/uppercase/u", "document": "export default \"\\U0041\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-uppercase-u", "class": "key/string/escape/uppercase/u", "document": "export default {\"\\U0041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-escape-space", "class": "string/escape/space", "document": "export default \"\\ \";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-escape-space", "class": "key/string/escape/space", "document": "export default {\"\\ \":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-continuation", "class": "string/continuation", "document": "export default \"a\\\nb\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-continuation", "class": "key/string/continuation", "document": "export default {\"a\\\nb\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-continuation-crlf", "class": "string/continuation/crlf", "document": "export default \"a\\\r\nb\";", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "key-continuation-crlf", "class": "key/string/continuation/crlf", "document": "export default {\"a\\\r\nb\":0};", "rule": "strings: the escapes are JSON's nine", "host": "accepts"},
    {"id": "string-raw-0000", "class": "string/raw-control/0000", "document": "export default \"\u0000\";", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "accepts"},
    {"id": "key-raw-0000", "class": "key/string/raw-control/0000", "document": "export default {\"\u0000\":0};", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "accepts"},
    {"id": "string-raw-0009", "class": "string/raw-control/0009", "document": "export default \"\t\";", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "accepts"},
    {"id": "key-raw-0009", "class": "key/string/raw-control/0009", "document": "export default {\"\t\":0};", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "accepts"},
    {"id": "string-raw-001f", "class": "string/raw-control/001f", "document": "export default \"\u001f\";", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "accepts"},
    {"id": "key-raw-001f", "class": "key/string/raw-control/001f", "document": "export default {\"\u001f\":0};", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "accepts"},
    {"id": "string-raw-000a", "class": "string/raw-control/000a", "document": "export default \"\n\";", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "syntaxError"},
    {"id": "key-raw-000a", "class": "key/string/raw-control/000a", "document": "export default {\"\n\":0};", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "syntaxError"},
    {"id": "string-raw-000d", "class": "string/raw-control/000d", "document": "export default \"\r\";", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "syntaxError"},
    {"id": "key-raw-000d", "class": "key/string/raw-control/000d", "document": "export default {\"\r\":0};", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "syntaxError"},
    {"id": "string-raw-quote", "class": "string/raw-quote", "document": "export default \"a\"b\";", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "syntaxError"},
    {"id": "key-raw-quote", "class": "key/string/raw-quote", "document": "export default {\"a\"b\":0};", "rule": "strings: no unescaped \", \\ or code point below U+0020", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-002f-0", "class": "string/escape/u/non-hex/002f/0", "document": "export default \"\\u/041\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-002f-0", "class": "key/string/escape/u/non-hex/002f/0", "document": "export default {\"\\u/041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-002f-1", "class": "string/escape/u/non-hex/002f/1", "document": "export default \"\\u0/41\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-002f-1", "class": "key/string/escape/u/non-hex/002f/1", "document": "export default {\"\\u0/41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-002f-2", "class": "string/escape/u/non-hex/002f/2", "document": "export default \"\\u00/1\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-002f-2", "class": "key/string/escape/u/non-hex/002f/2", "document": "export default {\"\\u00/1\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-002f-3", "class": "string/escape/u/non-hex/002f/3", "document": "export default \"\\u004/\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-002f-3", "class": "key/string/escape/u/non-hex/002f/3", "document": "export default {\"\\u004/\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-003a-0", "class": "string/escape/u/non-hex/003a/0", "document": "export default \"\\u:041\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-003a-0", "class": "key/string/escape/u/non-hex/003a/0", "document": "export default {\"\\u:041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-003a-1", "class": "string/escape/u/non-hex/003a/1", "document": "export default \"\\u0:41\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-003a-1", "class": "key/string/escape/u/non-hex/003a/1", "document": "export default {\"\\u0:41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-003a-2", "class": "string/escape/u/non-hex/003a/2", "document": "export default \"\\u00:1\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-003a-2", "class": "key/string/escape/u/non-hex/003a/2", "document": "export default {\"\\u00:1\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-003a-3", "class": "string/escape/u/non-hex/003a/3", "document": "export default \"\\u004:\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-003a-3", "class": "key/string/escape/u/non-hex/003a/3", "document": "export default {\"\\u004:\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0040-0", "class": "string/escape/u/non-hex/0040/0", "document": "export default \"\\u@041\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0040-0", "class": "key/string/escape/u/non-hex/0040/0", "document": "export default {\"\\u@041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0040-1", "class": "string/escape/u/non-hex/0040/1", "document": "export default \"\\u0@41\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0040-1", "class": "key/string/escape/u/non-hex/0040/1", "document": "export default {\"\\u0@41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0040-2", "class": "string/escape/u/non-hex/0040/2", "document": "export default \"\\u00@1\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0040-2", "class": "key/string/escape/u/non-hex/0040/2", "document": "export default {\"\\u00@1\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0040-3", "class": "string/escape/u/non-hex/0040/3", "document": "export default \"\\u004@\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0040-3", "class": "key/string/escape/u/non-hex/0040/3", "document": "export default {\"\\u004@\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0047-0", "class": "string/escape/u/non-hex/0047/0", "document": "export default \"\\uG041\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0047-0", "class": "key/string/escape/u/non-hex/0047/0", "document": "export default {\"\\uG041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0047-1", "class": "string/escape/u/non-hex/0047/1", "document": "export default \"\\u0G41\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0047-1", "class": "key/string/escape/u/non-hex/0047/1", "document": "export default {\"\\u0G41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0047-2", "class": "string/escape/u/non-hex/0047/2", "document": "export default \"\\u00G1\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0047-2", "class": "key/string/escape/u/non-hex/0047/2", "document": "export default {\"\\u00G1\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0047-3", "class": "string/escape/u/non-hex/0047/3", "document": "export default \"\\u004G\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0047-3", "class": "key/string/escape/u/non-hex/0047/3", "document": "export default {\"\\u004G\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0060-0", "class": "string/escape/u/non-hex/0060/0", "document": "export default \"\\u`041\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0060-0", "class": "key/string/escape/u/non-hex/0060/0", "document": "export default {\"\\u`041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0060-1", "class": "string/escape/u/non-hex/0060/1", "document": "export default \"\\u0`41\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0060-1", "class": "key/string/escape/u/non-hex/0060/1", "document": "export default {\"\\u0`41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0060-2", "class": "string/escape/u/non-hex/0060/2", "document": "export default \"\\u00`1\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0060-2", "class": "key/string/escape/u/non-hex/0060/2", "document": "export default {\"\\u00`1\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0060-3", "class": "string/escape/u/non-hex/0060/3", "document": "export default \"\\u004`\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0060-3", "class": "key/string/escape/u/non-hex/0060/3", "document": "export default {\"\\u004`\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0067-0", "class": "string/escape/u/non-hex/0067/0", "document": "export default \"\\ug041\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0067-0", "class": "key/string/escape/u/non-hex/0067/0", "document": "export default {\"\\ug041\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0067-1", "class": "string/escape/u/non-hex/0067/1", "document": "export default \"\\u0g41\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0067-1", "class": "key/string/escape/u/non-hex/0067/1", "document": "export default {\"\\u0g41\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0067-2", "class": "string/escape/u/non-hex/0067/2", "document": "export default \"\\u00g1\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0067-2", "class": "key/string/escape/u/non-hex/0067/2", "document": "export default {\"\\u00g1\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-non-hex-0067-3", "class": "string/escape/u/non-hex/0067/3", "document": "export default \"\\u004g\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-non-hex-0067-3", "class": "key/string/escape/u/non-hex/0067/3", "document": "export default {\"\\u004g\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-short-3", "class": "string/escape/u/short/3", "document": "export default \"\\u004\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-short-3", "class": "key/string/escape/u/short/3", "document": "export default {\"\\u004\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "string-escape-u-short-0", "class": "string/escape/u/short/0", "document": "export default \"\\u\";", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "key-escape-u-short-0", "class": "key/string/escape/u/short/0", "document": "export default {\"\\u\":0};", "rule": "strings: the escapes are JSON's nine", "host": "syntaxError"},
    {"id": "id-non-ascii", "class": "id/non-ascii", "document": "const $é=1;export default $é;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-non-ascii-cjk", "class": "id/non-ascii/cjk", "document": "const $中=1;export default $中;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-escaped-reference", "class": "id/escaped/reference", "document": "const $a=1;export default \\u0024a;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-escaped-declaration", "class": "id/escaped/declaration", "document": "const \\u0024a=1;export default $a;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-escaped-both", "class": "id/escaped/both", "document": "const \\u0024a=1;export default \\u0024a;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-escaped-tail", "class": "id/escaped/tail", "document": "const $\\u0061=1;export default $a;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-escaped-braces", "class": "id/escaped/braces", "document": "const \\u{24}a=1;export default $a;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "id-tail-hyphen", "class": "id/tail/hyphen", "document": "const $a-b=1;export default 1;", "rule": "identifiers: ASCII only, with no escape", "host": "syntaxError"},
    {"id": "id-tail-hash", "class": "id/tail/hash", "document": "const $a#=1;export default 1;", "rule": "identifiers: ASCII only, with no escape", "host": "syntaxError"},
    {"id": "id-non-ascii-zwj", "class": "id/non-ascii/zwj", "document": "const $a‍=1;export default 1;", "rule": "identifiers: ASCII only, with no escape", "host": "accepts"},
    {"id": "ws-other-000b", "class": "whitespace/other/000b", "document": "export default 1\u000b;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-000c", "class": "whitespace/other/000c", "document": "export default 1\f;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2028", "class": "whitespace/other/2028", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2029", "class": "whitespace/other/2029", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-feff", "class": "whitespace/other/feff", "document": "export default 1﻿;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-00a0", "class": "whitespace/other/00a0", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-1680", "class": "whitespace/other/1680", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2000", "class": "whitespace/other/2000", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2001", "class": "whitespace/other/2001", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2002", "class": "whitespace/other/2002", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2003", "class": "whitespace/other/2003", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2004", "class": "whitespace/other/2004", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2005", "class": "whitespace/other/2005", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2006", "class": "whitespace/other/2006", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2007", "class": "whitespace/other/2007", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2008", "class": "whitespace/other/2008", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2009", "class": "whitespace/other/2009", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-200a", "class": "whitespace/other/200a", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-202f", "class": "whitespace/other/202f", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-205f", "class": "whitespace/other/205f", "document": "export default 1 ;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-3000", "class": "whitespace/other/3000", "document": "export default 1　;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-feff-first", "class": "whitespace/other/feff/first", "document": "﻿export default 1;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-2028-required", "class": "whitespace/other/2028/required", "document": "export default 1;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-00a0-container", "class": "whitespace/other/00a0/container", "document": "export default [1, 2];", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-000c-leading", "class": "whitespace/other/000c/leading", "document": "\fexport default 1;", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-other-3000-trailing", "class": "whitespace/other/3000/trailing", "document": "export default 1;　", "rule": "whitespace: exactly space, tab, LF and CR", "host": "accepts"},
    {"id": "ws-required-const", "class": "whitespace/required/const", "document": "const$0=1;export default $0;", "rule": "whitespace: required after const, export and default", "host": "runtimeError"},
    {"id": "ws-required-export", "class": "whitespace/required/export", "document": "const $0=1;exportdefault $0;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-name", "class": "whitespace/required/default/name", "document": "const $0=1;export default$0;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-true", "class": "whitespace/required/default/true", "document": "export defaulttrue;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-false", "class": "whitespace/required/default/false", "document": "export defaultfalse;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-null", "class": "whitespace/required/default/null", "document": "export defaultnull;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-undefined", "class": "whitespace/required/default/undefined", "document": "export defaultundefined;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-nan", "class": "whitespace/required/default/nan", "document": "export defaultNaN;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-infinity", "class": "whitespace/required/default/infinity", "document": "export defaultInfinity;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-number", "class": "whitespace/required/default/number", "document": "export default1;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-bigint", "class": "whitespace/required/default/bigint", "document": "export default1n;", "rule": "whitespace: required after const, export and default", "host": "syntaxError"},
    {"id": "ws-required-default-array", "class": "whitespace/required/default/array", "document": "export default[1];", "rule": "whitespace: required after const, export and default", "host": "accepts"},
    {"id": "ws-required-default-object", "class": "whitespace/required/default/object", "document": "export default{};", "rule": "whitespace: required after const, export and default", "host": "accepts"},
    {"id": "ws-required-default-string", "class": "whitespace/required/default/string", "document": "export default\"a\";", "rule": "whitespace: required after const, export and default", "host": "accepts"},
    {"id": "ws-required-default-negative", "class": "whitespace/required/default/negative", "document": "export default-1;", "rule": "whitespace: required after const, export and default", "host": "accepts"},
    {"id": "ws-required-default-negative-infinity", "class": "whitespace/required/default/negative-infinity", "document": "export default-Infinity;", "rule": "whitespace: required after const, export and default", "host": "accepts"},
    {"id": "ws-required-default-negative-bigint", "class": "whitespace/required/default/negative-bigint", "document": "export default-1n;", "rule": "whitespace: required after const, export and default", "host": "accepts"},
    {"id": "byte-lead-invalid-low", "class": "byte/lead/invalid/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 c0 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-lead-invalid-high", "class": "byte/lead/invalid/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 c1 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-lead-none-low", "class": "byte/lead/none/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 fe 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-lead-none-high", "class": "byte/lead/none/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ff 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-lead-past-max-low", "class": "byte/lead/past-max/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f5 80 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-lead-past-max-high", "class": "byte/lead/past-max/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f7 bf bf bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-continuation-stray-low", "class": "byte/continuation/stray/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-continuation-stray-high", "class": "byte/continuation/stray/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-overlong-2-low", "class": "byte/overlong/2/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 c0 a0 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-overlong-2-high", "class": "byte/overlong/2/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 c1 bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-overlong-3-low", "class": "byte/overlong/3/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e0 80 a0 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-overlong-3-high", "class": "byte/overlong/3/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e0 9f bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-overlong-4-low", "class": "byte/overlong/4/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 80 80 a0 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-overlong-4-high", "class": "byte/overlong/4/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 8f bf bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-obsolete-5-low", "class": "byte/obsolete/5/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f8 88 80 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-obsolete-5-high", "class": "byte/obsolete/5/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 fb bf bf bf bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-obsolete-6-low", "class": "byte/obsolete/6/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 fc 84 80 80 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-obsolete-6-high", "class": "byte/obsolete/6/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 fd bf bf bf bf bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-surrogate-low", "class": "byte/surrogate/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ed a0 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-surrogate-high", "class": "byte/surrogate/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ed bf bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-above-max-low", "class": "byte/above-max/low", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 90 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-above-max-high", "class": "byte/above-max/high", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 bf bf bf 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-obsolete-5-overlong", "class": "byte/obsolete/5/overlong", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f8 80 80 80 a0 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-obsolete-6-overlong", "class": "byte/obsolete/6/overlong", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 fc 80 80 80 80 a0 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-c2-1-ascii", "class": "byte/non-continuation/c2/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 c2 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-c2-1-lead", "class": "byte/non-continuation/c2/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 c2 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e0-1-ascii", "class": "byte/non-continuation/e0/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e0 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e0-1-lead", "class": "byte/non-continuation/e0/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e0 c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e0-2-ascii", "class": "byte/non-continuation/e0/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e0 a0 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e0-2-lead", "class": "byte/non-continuation/e0/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e0 a0 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e1-ec-1-ascii", "class": "byte/non-continuation/e1-ec/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e2 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e1-ec-1-lead", "class": "byte/non-continuation/e1-ec/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e2 c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e1-ec-2-ascii", "class": "byte/non-continuation/e1-ec/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e2 82 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-e1-ec-2-lead", "class": "byte/non-continuation/e1-ec/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 e2 82 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ed-1-ascii", "class": "byte/non-continuation/ed/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ed 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ed-1-lead", "class": "byte/non-continuation/ed/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ed c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ed-2-ascii", "class": "byte/non-continuation/ed/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ed 80 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ed-2-lead", "class": "byte/non-continuation/ed/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ed 80 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ee-ef-1-ascii", "class": "byte/non-continuation/ee-ef/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ee 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ee-ef-1-lead", "class": "byte/non-continuation/ee-ef/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ee c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ee-ef-2-ascii", "class": "byte/non-continuation/ee-ef/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ee 80 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-ee-ef-2-lead", "class": "byte/non-continuation/ee-ef/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 ee 80 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f0-1-ascii", "class": "byte/non-continuation/f0/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 41 98 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f0-1-lead", "class": "byte/non-continuation/f0/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 c2 98 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f0-2-ascii", "class": "byte/non-continuation/f0/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 9f 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f0-2-lead", "class": "byte/non-continuation/f0/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 9f c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f0-3-ascii", "class": "byte/non-continuation/f0/3/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 9f 98 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f0-3-lead", "class": "byte/non-continuation/f0/3/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f0 9f 98 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f1-f3-1-ascii", "class": "byte/non-continuation/f1-f3/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f1 41 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f1-f3-1-lead", "class": "byte/non-continuation/f1-f3/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f1 c2 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f1-f3-2-ascii", "class": "byte/non-continuation/f1-f3/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f1 80 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f1-f3-2-lead", "class": "byte/non-continuation/f1-f3/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f1 80 c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f1-f3-3-ascii", "class": "byte/non-continuation/f1-f3/3/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f1 80 80 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f1-f3-3-lead", "class": "byte/non-continuation/f1-f3/3/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f1 80 80 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f4-1-ascii", "class": "byte/non-continuation/f4/1/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 41 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f4-1-lead", "class": "byte/non-continuation/f4/1/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 c2 80 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f4-2-ascii", "class": "byte/non-continuation/f4/2/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 80 41 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f4-2-lead", "class": "byte/non-continuation/f4/2/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 80 c2 80 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f4-3-ascii", "class": "byte/non-continuation/f4/3/ascii", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 80 80 41 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-non-continuation-f4-3-lead", "class": "byte/non-continuation/f4/3/lead", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 f4 80 80 c2 22 3b"], "rule": "document: a document is UTF-8", "host": "accepts"},
    {"id": "byte-bom-first", "class": "byte/bom/first", "document": ["hex", "ef bb bf 65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 31 3b"], "rule": "document: a document has no BOM", "host": "accepts"}
];
