const $n0 = [0];
const $n1 = {};
const $n2 = [0];
const $n3 = [[]];
const $n4 = [0];
const $n5 = [$n4];
const $n6 = {};
const $n7 = {"x": $n6};
const $n8 = [0];
const $n9 = {"x": $n8};
const $n10 = {};
const $n11 = [$n10];
const $n12 = [0];
const $n13 = {};
const $n14 = [0];
const $n15 = {};
const $n16 = [0];
const $n17 = {};
const $n18 = {};
const $n19 = {};
const $n20 = {};
const $n21 = {};
const $n22 = {};
const $n23 = {};
const $n24 = {};
const $n25 = {};
const $n26 = {};
const $n27 = {};
const $n28 = {};
const $s1 = [1, 2];
const $n29 = [1];
const $n30 = ["\u2028", "\ud800", "\u0000"];
const $n31 = {"\u2028": 0};
const $n32 = [0];
const $n33 = [null, true, false, undefined, NaN, Infinity, -Infinity, 0, -0, 9, -9, 1.5, 1e2, 1n, -1n, "", "a", "\u2028", "\ud800", "\u0000", [], {}, 1];
const $n34 = {"a": null, "b": true, "c": false, "d": undefined, "e": NaN, "f": Infinity, "g": -Infinity, "h": 0, "i": -0, "j": 9, "k": -9, "l": 1.5, "m": 1e2, "n": 1n, "o": -1n, "p": "", "q": "a", "r": "\u2028", "s": "\ud800", "t": "\u0000", "u": [], "v": {}, "w": 1};
export default [
    {"id": "norm-string-escape-quote", "class": "string/escape/quote", "input": "\"", "text": "export default \"\\\"\";"},
    {"id": "norm-key-escape-quote", "class": "key/string/escape/quote", "input": {"\"": 0}, "text": "export default {\"\\\"\":0};"},
    {"id": "norm-string-escape-backslash", "class": "string/escape/backslash", "input": "\\", "text": "export default \"\\\\\";"},
    {"id": "norm-key-escape-backslash", "class": "key/string/escape/backslash", "input": {"\\": 0}, "text": "export default {\"\\\\\":0};"},
    {"id": "norm-string-escape-b", "class": "string/escape/b", "input": "\u0008", "text": "export default \"\\b\";"},
    {"id": "norm-key-escape-b", "class": "key/string/escape/b", "input": {"\u0008": 0}, "text": "export default {\"\\b\":0};"},
    {"id": "norm-string-escape-t", "class": "string/escape/t", "input": "\u0009", "text": "export default \"\\t\";"},
    {"id": "norm-key-escape-t", "class": "key/string/escape/t", "input": {"\u0009": 0}, "text": "export default {\"\\t\":0};"},
    {"id": "norm-string-escape-n", "class": "string/escape/n", "input": "\u000a", "text": "export default \"\\n\";"},
    {"id": "norm-key-escape-n", "class": "key/string/escape/n", "input": {"\u000a": 0}, "text": "export default {\"\\n\":0};"},
    {"id": "norm-string-escape-f", "class": "string/escape/f", "input": "\u000c", "text": "export default \"\\f\";"},
    {"id": "norm-key-escape-f", "class": "key/string/escape/f", "input": {"\u000c": 0}, "text": "export default {\"\\f\":0};"},
    {"id": "norm-string-escape-r", "class": "string/escape/r", "input": "\u000d", "text": "export default \"\\r\";"},
    {"id": "norm-key-escape-r", "class": "key/string/escape/r", "input": {"\u000d": 0}, "text": "export default {\"\\r\":0};"},
    {"id": "norm-string-escape-u00-0000", "class": "string/escape/u00/0000", "input": "\u0000", "text": "export default \"\\u0000\";"},
    {"id": "norm-key-escape-u00-0000", "class": "key/string/escape/u00/0000", "input": {"\u0000": 0}, "text": "export default {\"\\u0000\":0};"},
    {"id": "norm-string-escape-u00-0007", "class": "string/escape/u00/0007", "input": "\u0007", "text": "export default \"\\u0007\";"},
    {"id": "norm-key-escape-u00-0007", "class": "key/string/escape/u00/0007", "input": {"\u0007": 0}, "text": "export default {\"\\u0007\":0};"},
    {"id": "norm-string-escape-u00-000b", "class": "string/escape/u00/000b", "input": "\u000b", "text": "export default \"\\u000b\";"},
    {"id": "norm-key-escape-u00-000b", "class": "key/string/escape/u00/000b", "input": {"\u000b": 0}, "text": "export default {\"\\u000b\":0};"},
    {"id": "norm-string-escape-u00-000e", "class": "string/escape/u00/000e", "input": "\u000e", "text": "export default \"\\u000e\";"},
    {"id": "norm-key-escape-u00-000e", "class": "key/string/escape/u00/000e", "input": {"\u000e": 0}, "text": "export default {\"\\u000e\":0};"},
    {"id": "norm-string-escape-u00-000f", "class": "string/escape/u00/000f", "input": "\u000f", "text": "export default \"\\u000f\";"},
    {"id": "norm-key-escape-u00-000f", "class": "key/string/escape/u00/000f", "input": {"\u000f": 0}, "text": "export default {\"\\u000f\":0};"},
    {"id": "norm-string-escape-u00-0010", "class": "string/escape/u00/0010", "input": "\u0010", "text": "export default \"\\u0010\";"},
    {"id": "norm-key-escape-u00-0010", "class": "key/string/escape/u00/0010", "input": {"\u0010": 0}, "text": "export default {\"\\u0010\":0};"},
    {"id": "norm-string-escape-u00-0019", "class": "string/escape/u00/0019", "input": "\u0019", "text": "export default \"\\u0019\";"},
    {"id": "norm-key-escape-u00-0019", "class": "key/string/escape/u00/0019", "input": {"\u0019": 0}, "text": "export default {\"\\u0019\":0};"},
    {"id": "norm-string-escape-u00-001a", "class": "string/escape/u00/001a", "input": "\u001a", "text": "export default \"\\u001a\";"},
    {"id": "norm-key-escape-u00-001a", "class": "key/string/escape/u00/001a", "input": {"\u001a": 0}, "text": "export default {\"\\u001a\":0};"},
    {"id": "norm-string-escape-u00-001f", "class": "string/escape/u00/001f", "input": "\u001f", "text": "export default \"\\u001f\";"},
    {"id": "norm-key-escape-u00-001f", "class": "key/string/escape/u00/001f", "input": {"\u001f": 0}, "text": "export default {\"\\u001f\":0};"},
    {"id": "norm-string-surrogate-lone-d800", "class": "string/surrogate/lone/d800", "input": "\ud800", "text": "export default \"\\ud800\";"},
    {"id": "norm-key-surrogate-lone-d800", "class": "key/string/surrogate/lone/d800", "input": {"\ud800": 0}, "text": "export default {\"\\ud800\":0};"},
    {"id": "norm-string-surrogate-lone-dbff", "class": "string/surrogate/lone/dbff", "input": "\udbff", "text": "export default \"\\udbff\";"},
    {"id": "norm-key-surrogate-lone-dbff", "class": "key/string/surrogate/lone/dbff", "input": {"\udbff": 0}, "text": "export default {\"\\udbff\":0};"},
    {"id": "norm-string-surrogate-lone-dc00", "class": "string/surrogate/lone/dc00", "input": "\udc00", "text": "export default \"\\udc00\";"},
    {"id": "norm-key-surrogate-lone-dc00", "class": "key/string/surrogate/lone/dc00", "input": {"\udc00": 0}, "text": "export default {\"\\udc00\":0};"},
    {"id": "norm-string-surrogate-lone-dfff", "class": "string/surrogate/lone/dfff", "input": "\udfff", "text": "export default \"\\udfff\";"},
    {"id": "norm-key-surrogate-lone-dfff", "class": "key/string/surrogate/lone/dfff", "input": {"\udfff": 0}, "text": "export default {\"\\udfff\":0};"},
    {"id": "norm-string-raw-slash", "class": "string/raw/slash", "input": "/", "text": "export default \"/\";"},
    {"id": "norm-key-raw-slash", "class": "key/string/raw/slash", "input": {"/": 0}, "text": "export default {\"/\":0};"},
    {"id": "norm-string-raw-0020", "class": "string/raw/range/0020-0021/low", "input": " ", "text": "export default \" \";"},
    {"id": "norm-key-raw-0020", "class": "key/string/raw/range/0020-0021/low", "input": {" ": 0}, "text": "export default {\" \":0};"},
    {"id": "norm-string-raw-0021", "class": "string/raw/range/0020-0021/high", "input": "!", "text": "export default \"!\";"},
    {"id": "norm-key-raw-0021", "class": "key/string/raw/range/0020-0021/high", "input": {"!": 0}, "text": "export default {\"!\":0};"},
    {"id": "norm-string-raw-0023", "class": "string/raw/range/0023-005b/low", "input": "#", "text": "export default \"#\";"},
    {"id": "norm-key-raw-0023", "class": "key/string/raw/range/0023-005b/low", "input": {"#": 0}, "text": "export default {\"#\":0};"},
    {"id": "norm-string-raw-005b", "class": "string/raw/range/0023-005b/high", "input": "[", "text": "export default \"[\";"},
    {"id": "norm-key-raw-005b", "class": "key/string/raw/range/0023-005b/high", "input": {"[": 0}, "text": "export default {\"[\":0};"},
    {"id": "norm-string-raw-005d", "class": "string/raw/range/005d-10ffff/low", "input": "]", "text": "export default \"]\";"},
    {"id": "norm-key-raw-005d", "class": "key/string/raw/range/005d-10ffff/low", "input": {"]": 0}, "text": "export default {\"]\":0};"},
    {"id": "norm-string-raw-007f", "class": "string/raw/007f", "input": "", "text": "export default \"\u007f\";"},
    {"id": "norm-key-raw-007f", "class": "key/string/raw/007f", "input": {"": 0}, "text": "export default {\"\u007f\":0};"},
    {"id": "norm-string-raw-d7ff", "class": "string/raw/surrogate-hole/d7ff", "input": "퟿", "text": "export default \"\ud7ff\";"},
    {"id": "norm-key-raw-d7ff", "class": "key/string/raw/surrogate-hole/d7ff", "input": {"퟿": 0}, "text": "export default {\"\ud7ff\":0};"},
    {"id": "norm-string-raw-e000", "class": "string/raw/surrogate-hole/e000", "input": "", "text": "export default \"\ue000\";"},
    {"id": "norm-key-raw-e000", "class": "key/string/raw/surrogate-hole/e000", "input": {"": 0}, "text": "export default {\"\ue000\":0};"},
    {"id": "norm-string-raw-ffff", "class": "string/raw/bmp/ffff", "input": "￿", "text": "export default \"\uffff\";"},
    {"id": "norm-key-raw-ffff", "class": "key/string/raw/bmp/ffff", "input": {"￿": 0}, "text": "export default {\"\uffff\":0};"},
    {"id": "norm-string-raw-10000", "class": "string/raw/astral/10000", "input": "𐀀", "text": "export default \"\ud800\udc00\";"},
    {"id": "norm-key-raw-10000", "class": "key/string/raw/astral/10000", "input": {"𐀀": 0}, "text": "export default {\"\ud800\udc00\":0};"},
    {"id": "norm-string-raw-10ffff", "class": "string/raw/range/005d-10ffff/high", "input": "􏿿", "text": "export default \"\udbff\udfff\";"},
    {"id": "norm-key-raw-10ffff", "class": "key/string/raw/range/005d-10ffff/high", "input": {"􏿿": 0}, "text": "export default {\"\udbff\udfff\":0};"},
    {"id": "norm-string-empty", "class": "string/empty", "input": "", "text": "export default \"\";"},
    {"id": "norm-key-empty", "class": "key/string/empty", "input": {"": 0}, "text": "export default {\"\":0};"},
    {"id": "norm-string-mixed", "class": "string/mixed", "input": "\u0009a\"é\udfff", "text": "export default \"\\ta\\\"\u00e9\\udfff\";"},
    {"id": "norm-key-mixed", "class": "key/string/mixed", "input": {"\u0009a\"é\udfff": 0}, "text": "export default {\"\\ta\\\"\u00e9\\udfff\":0};"},
    {"id": "norm-hoist-only-if-array", "class": "const/hoist/only-if/array", "input": [], "text": "export default [];"},
    {"id": "norm-hoist-only-if-object", "class": "const/hoist/only-if/object", "input": {}, "text": "export default {};"},
    {"id": "norm-shared-leaf", "class": "const/shared/leaf", "input": [1, 1], "text": "export default [1,1];"},
    {"id": "norm-shared-twice", "class": "const/shared/twice", "input": [$n0, $n0], "text": "const $0=[0];export default [$0,$0];"},
    {"id": "norm-shared-object", "class": "const/shared/object", "input": {"a": $n1, "b": $n1}, "text": "const $0={};export default {\"a\":$0,\"b\":$0};"},
    {"id": "norm-shared-mixed", "class": "const/shared/mixed", "input": [[$n2], {"x": $n2}], "text": "const $0=[0];export default [[$0],{\"x\":$0}];"},
    {"id": "norm-unshared-array-empty", "class": "array/unshared", "input": [[], []], "text": "export default [[],[]];"},
    {"id": "norm-hoist-occurrences", "class": "const/hoist/occurrences", "input": [$n3, $n3], "text": "const $0=[[]];export default [$0,$0];"},
    {"id": "norm-name-post-order-array-array", "class": "const/name/post-order/array/array", "input": [$n5, $n5, $n4], "text": "const $0=[0];const $1=[$0];export default [$1,$1,$0];"},
    {"id": "norm-name-post-order-object-object", "class": "const/name/post-order/object/object", "input": {"a": $n7, "b": $n7, "c": $n6}, "text": "const $0={};const $1={\"x\":$0};export default {\"a\":$1,\"b\":$1,\"c\":$0};"},
    {"id": "norm-name-post-order-object-array", "class": "const/name/post-order/object/array", "input": {"a": $n9, "b": $n9, "c": $n8}, "text": "const $0=[0];const $1={\"x\":$0};export default {\"a\":$1,\"b\":$1,\"c\":$0};"},
    {"id": "norm-name-post-order-array-object", "class": "const/name/post-order/array/object", "input": [$n11, $n11, $n10], "text": "const $0={};const $1=[$0];export default [$1,$1,$0];"},
    {"id": "norm-shared-two-nodes", "class": "const/shared/two-nodes", "input": [$n12, $n13, $n12, $n13], "text": "const $0=[0];const $1={};export default [$0,$1,$0,$1];"},
    {"id": "norm-shared-two-nodes-object", "class": "const/shared/two-nodes/object", "input": {"a": $n14, "b": $n15, "c": $n14, "d": $n15}, "text": "const $0=[0];const $1={};export default {\"a\":$0,\"b\":$1,\"c\":$0,\"d\":$1};"},
    {"id": "norm-shared-two-nodes-key-order", "class": "const/shared/two-nodes/key-order", "input": {"b": $n16, "0": $n17, "c": $n16, "1": $n17}, "text": "const $0={};const $1=[0];export default {\"0\":$0,\"1\":$0,\"b\":$1,\"c\":$1};"},
    {"id": "norm-name-counter-two-digits", "class": "const/name/counter/two-digits", "input": [$n18, $n18, $n19, $n19, $n20, $n20, $n21, $n21, $n22, $n22, $n23, $n23, $n24, $n24, $n25, $n25, $n26, $n26, $n27, $n27, $n28, $n28], "text": "const $0={};const $1={};const $2={};const $3={};const $4={};const $5={};const $6={};const $7={};const $8={};const $9={};const $10={};export default [$0,$0,$1,$1,$2,$2,$3,$3,$4,$4,$5,$5,$6,$6,$7,$7,$8,$8,$9,$9,$10,$10];"},
    {"id": "norm-number-0", "class": "number/int/zero", "input": 0, "text": "export default 0;"},
    {"id": "norm-number-neg-0", "class": "number/int/zero/neg", "input": -0, "text": "export default -0;"},
    {"id": "norm-number-109", "class": "number/int/digits", "input": 109, "text": "export default 109;"},
    {"id": "norm-number-neg-109", "class": "number/int/digits/neg", "input": -109, "text": "export default -109;"},
    {"id": "norm-number-1.5", "class": "number/frac", "input": 1.5, "text": "export default 1.5;"},
    {"id": "norm-number-neg-1.5", "class": "number/frac/neg", "input": -1.5, "text": "export default -1.5;"},
    {"id": "norm-number-1e20", "class": "number/notation/fixed/high", "input": 1e20, "text": "export default 100000000000000000000;"},
    {"id": "norm-number-neg-1e20", "class": "number/notation/fixed/high/neg", "input": -1e20, "text": "export default -100000000000000000000;"},
    {"id": "norm-number-1e21", "class": "number/notation/exp/high", "input": 1e21, "text": "export default 1e+21;"},
    {"id": "norm-number-neg-1e21", "class": "number/notation/exp/high/neg", "input": -1e21, "text": "export default -1e+21;"},
    {"id": "norm-number-1e-6", "class": "number/notation/fixed/low", "input": 1e-6, "text": "export default 0.000001;"},
    {"id": "norm-number-neg-1e-6", "class": "number/notation/fixed/low/neg", "input": -1e-6, "text": "export default -0.000001;"},
    {"id": "norm-number-1e-7", "class": "number/notation/exp/low", "input": 1e-7, "text": "export default 1e-7;"},
    {"id": "norm-number-neg-1e-7", "class": "number/notation/exp/low/neg", "input": -1e-7, "text": "export default -1e-7;"},
    {"id": "norm-number-subnormal", "class": "number/binary64/subnormal", "input": 5e-324, "text": "export default 5e-324;"},
    {"id": "norm-number-neg-subnormal", "class": "number/binary64/subnormal/neg", "input": -5e-324, "text": "export default -5e-324;"},
    {"id": "norm-number-max", "class": "number/binary64/max", "input": 1.7976931348623157e308, "text": "export default 1.7976931348623157e+308;"},
    {"id": "norm-number-neg-max", "class": "number/binary64/max/neg", "input": -1.7976931348623157e308, "text": "export default -1.7976931348623157e+308;"},
    {"id": "norm-number-shortest-int", "class": "number/shortest/int", "input": 1000000000000000128, "text": "export default 1000000000000000100;"},
    {"id": "norm-number-neg-shortest-int", "class": "number/shortest/int/neg", "input": -1000000000000000128, "text": "export default -1000000000000000100;"},
    {"id": "norm-number-shortest-frac", "class": "number/shortest/frac", "input": 0.1, "text": "export default 0.1;"},
    {"id": "norm-number-neg-shortest-frac", "class": "number/shortest/frac/neg", "input": -0.1, "text": "export default -0.1;"},
    {"id": "norm-infinity", "class": "infinity/plus", "input": Infinity, "text": "export default Infinity;"},
    {"id": "norm-neg-infinity", "class": "infinity/minus", "input": -Infinity, "text": "export default -Infinity;"},
    {"id": "norm-bigint-0", "class": "bigint/zero", "input": 0n, "text": "export default 0n;"},
    {"id": "norm-bigint-109", "class": "bigint/digits", "input": 109n, "text": "export default 109n;"},
    {"id": "norm-bigint-neg-109", "class": "bigint/digits/neg", "input": -109n, "text": "export default -109n;"},
    {"id": "norm-document-spelling-one-line", "class": "document/spelling/one-line", "input": [$s1, {"a": $s1, "b": 0}], "text": "const $0=[1,2];export default [$0,{\"a\":$0,\"b\":0}];"},
    {"id": "norm-ws-required-default-true", "class": "whitespace/required/default/true", "input": true, "text": "export default true;"},
    {"id": "norm-ws-required-default-false", "class": "whitespace/required/default/false", "input": false, "text": "export default false;"},
    {"id": "norm-ws-required-default-null", "class": "whitespace/required/default/null", "input": null, "text": "export default null;"},
    {"id": "norm-ws-required-default-undefined", "class": "whitespace/required/default/undefined", "input": undefined, "text": "export default undefined;"},
    {"id": "norm-ws-required-default-nan", "class": "whitespace/required/default/nan", "input": NaN, "text": "export default NaN;"},
    {"id": "norm-ws-required-default-number", "class": "whitespace/required/default/number", "input": 1, "text": "export default 1;"},
    {"id": "norm-ws-required-default-negative", "class": "whitespace/required/default/negative", "input": -1, "text": "export default -1;"},
    {"id": "norm-ws-required-default-bigint", "class": "whitespace/required/default/bigint", "input": 1n, "text": "export default 1n;"},
    {"id": "norm-ws-required-default-negative-bigint", "class": "whitespace/required/default/negative-bigint", "input": -1n, "text": "export default -1n;"},
    {"id": "norm-ws-required-default-array", "class": "whitespace/required/default/array", "input": [1], "text": "export default [1];"},
    {"id": "norm-ws-required-default-object", "class": "whitespace/required/default/object", "input": {"a": 1}, "text": "export default {\"a\":1};"},
    {"id": "norm-ws-required-default-string", "class": "whitespace/required/default/string", "input": "a", "text": "export default \"a\";"},
    {"id": "norm-object-key-order-index-before-name", "class": "object/key-order/index-before-name", "input": {"10": 1, "2": 2, "z": 3, "a": 4}, "text": "export default {\"2\":2,\"10\":1,\"z\":3,\"a\":4};"},
    {"id": "norm-object-key-order-names-first-occurrence", "class": "object/key-order/names/first-occurrence", "input": {"b": 0, "a": 1, "c": 2}, "text": "export default {\"b\":0,\"a\":1,\"c\":2};"},
    {"id": "norm-key-proto", "class": "key/proto", "input": {["__proto__"]: 1}, "text": "export default {[\"__proto__\"]:1};"},
    {"id": "norm-key-proto-among", "class": "key/proto/among", "input": {"a": 1, ["__proto__"]: 2, "b": 3}, "text": "export default {\"a\":1,[\"__proto__\"]:2,\"b\":3};"},
    {"id": "norm-number-exp-low-mantissa", "class": "number/notation/exp/low/mantissa", "input": 1.5e-7, "text": "export default 1.5e-7;"},
    {"id": "norm-number-exp-low-mantissa-neg", "class": "number/notation/exp/low/mantissa/neg", "input": -1.5e-7, "text": "export default -1.5e-7;"},
    {"id": "norm-string-raw-bmp-latin", "class": "string/raw/bmp", "input": "é", "text": "export default \"é\";"},
    {"id": "norm-key-raw-bmp-latin", "class": "key/string/raw/bmp", "input": {"é": 0}, "text": "export default {\"é\":0};"},
    {"id": "norm-string-raw-astral-emoji", "class": "string/raw/astral", "input": "😀", "text": "export default \"😀\";"},
    {"id": "norm-key-raw-astral-emoji", "class": "key/string/raw/astral", "input": {"😀": 0}, "text": "export default {\"😀\":0};"},
    {"id": "norm-bigint-2p53", "class": "bigint/past-2p53", "input": 9007199254740993n, "text": "export default 9007199254740993n;"},
    {"id": "norm-bigint-neg-2p53", "class": "bigint/past-2p53/neg", "input": -9007199254740993n, "text": "export default -9007199254740993n;"},
    {"id": "norm-bigint-2p64", "class": "bigint/past-2p64", "input": 18446744073709551617n, "text": "export default 18446744073709551617n;"},
    {"id": "norm-bigint-neg-2p64", "class": "bigint/past-2p64/neg", "input": -18446744073709551617n, "text": "export default -18446744073709551617n;"},
    {"id": "norm-bigint-2p128", "class": "bigint/past-2p128", "input": 340282366920938463463374607431768211457n, "text": "export default 340282366920938463463374607431768211457n;"},
    {"id": "norm-bigint-neg-2p128", "class": "bigint/past-2p128/neg", "input": -340282366920938463463374607431768211457n, "text": "export default -340282366920938463463374607431768211457n;"},
    {"id": "norm-unshared-array-equal", "class": "array/unshared/equal", "input": [[1], [1]], "text": "export default [[1],[1]];"},
    {"id": "norm-unshared-object-equal", "class": "object/unshared/equal", "input": [{"a": 0}, {"a": 0}], "text": "export default [{\"a\":0},{\"a\":0}];"},
    {"id": "norm-object-key-order-boundaries", "class": "object/key-order/boundaries", "input": {"z": 0, "4294967295": 0, "4294967294": 0, "2147483648": 0, "1": 0, "01": 0, "1.0": 0, "0": 0}, "text": "export default {\"0\":0,\"1\":0,\"2147483648\":0,\"4294967294\":0,\"z\":0,\"4294967295\":0,\"01\":0,\"1.0\":0};"},
    {"id": "norm-array-elements-every-value", "class": "array/elements/every-value", "input": [null, true, false, undefined, NaN, Infinity, -Infinity, 0, -0, 9, -9, 1.5, 1e2, 1n, -1n, "", "a", "\u2028", "\ud800", "\u0000", [], {}, 1], "text": "export default [null,true,false,undefined,NaN,Infinity,-Infinity,0,-0,9,-9,1.5,100,1n,-1n,\"\",\"a\",\"\u2028\",\"\\ud800\",\"\\u0000\",[],{},1];"},
    {"id": "norm-object-members-every-value", "class": "object/members/every-value", "input": {"a": null, "b": true, "c": false, "d": undefined, "e": NaN, "f": Infinity, "g": -Infinity, "h": 0, "i": -0, "j": 9, "k": -9, "l": 1.5, "m": 1e2, "n": 1n, "o": -1n, "p": "", "q": "a", "r": "\u2028", "s": "\ud800", "t": "\u0000", "u": [], "v": {}, "w": 1}, "text": "export default {\"a\":null,\"b\":true,\"c\":false,\"d\":undefined,\"e\":NaN,\"f\":Infinity,\"g\":-Infinity,\"h\":0,\"i\":-0,\"j\":9,\"k\":-9,\"l\":1.5,\"m\":100,\"n\":1n,\"o\":-1n,\"p\":\"\",\"q\":\"a\",\"r\":\"\u2028\",\"s\":\"\\ud800\",\"t\":\"\\u0000\",\"u\":[],\"v\":{},\"w\":1};"},
    {"id": "norm-string-raw-ws-like-2028", "class": "string/raw/ws-like/2028", "input": "\u2028", "text": "export default \"\u2028\";"},
    {"id": "norm-key-raw-ws-like-2028", "class": "key/string/raw/ws-like/2028", "input": {"\u2028": 0}, "text": "export default {\"\u2028\":0};"},
    {"id": "norm-string-raw-ws-like-2029", "class": "string/raw/ws-like/2029", "input": "\u2029", "text": "export default \"\u2029\";"},
    {"id": "norm-key-raw-ws-like-2029", "class": "key/string/raw/ws-like/2029", "input": {"\u2029": 0}, "text": "export default {\"\u2029\":0};"},
    {"id": "norm-string-raw-ws-like-feff", "class": "string/raw/ws-like/feff", "input": "\ufeff", "text": "export default \"\ufeff\";"},
    {"id": "norm-key-raw-ws-like-feff", "class": "key/string/raw/ws-like/feff", "input": {"\ufeff": 0}, "text": "export default {\"\ufeff\":0};"},
    {"id": "norm-string-raw-ws-like-00a0", "class": "string/raw/ws-like/00a0", "input": "\u00a0", "text": "export default \"\u00a0\";"},
    {"id": "norm-key-raw-ws-like-00a0", "class": "key/string/raw/ws-like/00a0", "input": {"\u00a0": 0}, "text": "export default {\"\u00a0\":0};"},
    {"id": "norm-string-raw-ws-like-1680", "class": "string/raw/ws-like/1680", "input": "\u1680", "text": "export default \"\u1680\";"},
    {"id": "norm-key-raw-ws-like-1680", "class": "key/string/raw/ws-like/1680", "input": {"\u1680": 0}, "text": "export default {\"\u1680\":0};"},
    {"id": "norm-string-raw-ws-like-2000", "class": "string/raw/ws-like/2000", "input": "\u2000", "text": "export default \"\u2000\";"},
    {"id": "norm-key-raw-ws-like-2000", "class": "key/string/raw/ws-like/2000", "input": {"\u2000": 0}, "text": "export default {\"\u2000\":0};"},
    {"id": "norm-string-raw-ws-like-2001", "class": "string/raw/ws-like/2001", "input": "\u2001", "text": "export default \"\u2001\";"},
    {"id": "norm-key-raw-ws-like-2001", "class": "key/string/raw/ws-like/2001", "input": {"\u2001": 0}, "text": "export default {\"\u2001\":0};"},
    {"id": "norm-string-raw-ws-like-2002", "class": "string/raw/ws-like/2002", "input": "\u2002", "text": "export default \"\u2002\";"},
    {"id": "norm-key-raw-ws-like-2002", "class": "key/string/raw/ws-like/2002", "input": {"\u2002": 0}, "text": "export default {\"\u2002\":0};"},
    {"id": "norm-string-raw-ws-like-2003", "class": "string/raw/ws-like/2003", "input": "\u2003", "text": "export default \"\u2003\";"},
    {"id": "norm-key-raw-ws-like-2003", "class": "key/string/raw/ws-like/2003", "input": {"\u2003": 0}, "text": "export default {\"\u2003\":0};"},
    {"id": "norm-string-raw-ws-like-2004", "class": "string/raw/ws-like/2004", "input": "\u2004", "text": "export default \"\u2004\";"},
    {"id": "norm-key-raw-ws-like-2004", "class": "key/string/raw/ws-like/2004", "input": {"\u2004": 0}, "text": "export default {\"\u2004\":0};"},
    {"id": "norm-string-raw-ws-like-2005", "class": "string/raw/ws-like/2005", "input": "\u2005", "text": "export default \"\u2005\";"},
    {"id": "norm-key-raw-ws-like-2005", "class": "key/string/raw/ws-like/2005", "input": {"\u2005": 0}, "text": "export default {\"\u2005\":0};"},
    {"id": "norm-string-raw-ws-like-2006", "class": "string/raw/ws-like/2006", "input": "\u2006", "text": "export default \"\u2006\";"},
    {"id": "norm-key-raw-ws-like-2006", "class": "key/string/raw/ws-like/2006", "input": {"\u2006": 0}, "text": "export default {\"\u2006\":0};"},
    {"id": "norm-string-raw-ws-like-2007", "class": "string/raw/ws-like/2007", "input": "\u2007", "text": "export default \"\u2007\";"},
    {"id": "norm-key-raw-ws-like-2007", "class": "key/string/raw/ws-like/2007", "input": {"\u2007": 0}, "text": "export default {\"\u2007\":0};"},
    {"id": "norm-string-raw-ws-like-2008", "class": "string/raw/ws-like/2008", "input": "\u2008", "text": "export default \"\u2008\";"},
    {"id": "norm-key-raw-ws-like-2008", "class": "key/string/raw/ws-like/2008", "input": {"\u2008": 0}, "text": "export default {\"\u2008\":0};"},
    {"id": "norm-string-raw-ws-like-2009", "class": "string/raw/ws-like/2009", "input": "\u2009", "text": "export default \"\u2009\";"},
    {"id": "norm-key-raw-ws-like-2009", "class": "key/string/raw/ws-like/2009", "input": {"\u2009": 0}, "text": "export default {\"\u2009\":0};"},
    {"id": "norm-string-raw-ws-like-200a", "class": "string/raw/ws-like/200a", "input": "\u200a", "text": "export default \"\u200a\";"},
    {"id": "norm-key-raw-ws-like-200a", "class": "key/string/raw/ws-like/200a", "input": {"\u200a": 0}, "text": "export default {\"\u200a\":0};"},
    {"id": "norm-string-raw-ws-like-202f", "class": "string/raw/ws-like/202f", "input": "\u202f", "text": "export default \"\u202f\";"},
    {"id": "norm-key-raw-ws-like-202f", "class": "key/string/raw/ws-like/202f", "input": {"\u202f": 0}, "text": "export default {\"\u202f\":0};"},
    {"id": "norm-string-raw-ws-like-205f", "class": "string/raw/ws-like/205f", "input": "\u205f", "text": "export default \"\u205f\";"},
    {"id": "norm-key-raw-ws-like-205f", "class": "key/string/raw/ws-like/205f", "input": {"\u205f": 0}, "text": "export default {\"\u205f\":0};"},
    {"id": "norm-string-raw-ws-like-3000", "class": "string/raw/ws-like/3000", "input": "\u3000", "text": "export default \"\u3000\";"},
    {"id": "norm-key-raw-ws-like-3000", "class": "key/string/raw/ws-like/3000", "input": {"\u3000": 0}, "text": "export default {\"\u3000\":0};"},
    {"id": "norm-string-surrogate-adjacent-hh-d800", "class": "string/surrogate/adjacent/hh-d800", "input": "\ud800\ud800", "text": "export default \"\\ud800\\ud800\";"},
    {"id": "norm-key-surrogate-adjacent-hh-d800", "class": "key/string/surrogate/adjacent/hh-d800", "input": {"\ud800\ud800": 0}, "text": "export default {\"\\ud800\\ud800\":0};"},
    {"id": "norm-string-surrogate-adjacent-lh-dc00-d800", "class": "string/surrogate/adjacent/lh-dc00-d800", "input": "\udc00\ud800", "text": "export default \"\\udc00\\ud800\";"},
    {"id": "norm-key-surrogate-adjacent-lh-dc00-d800", "class": "key/string/surrogate/adjacent/lh-dc00-d800", "input": {"\udc00\ud800": 0}, "text": "export default {\"\\udc00\\ud800\":0};"},
    {"id": "norm-string-surrogate-adjacent-ll-dc00", "class": "string/surrogate/adjacent/ll-dc00", "input": "\udc00\udc00", "text": "export default \"\\udc00\\udc00\";"},
    {"id": "norm-key-surrogate-adjacent-ll-dc00", "class": "key/string/surrogate/adjacent/ll-dc00", "input": {"\udc00\udc00": 0}, "text": "export default {\"\\udc00\\udc00\":0};"},
    {"id": "norm-string-surrogate-adjacent-hh-dbff", "class": "string/surrogate/adjacent/hh-dbff", "input": "\udbff\udbff", "text": "export default \"\\udbff\\udbff\";"},
    {"id": "norm-key-surrogate-adjacent-hh-dbff", "class": "key/string/surrogate/adjacent/hh-dbff", "input": {"\udbff\udbff": 0}, "text": "export default {\"\\udbff\\udbff\":0};"},
    {"id": "norm-string-surrogate-adjacent-lh-dfff-dbff", "class": "string/surrogate/adjacent/lh-dfff-dbff", "input": "\udfff\udbff", "text": "export default \"\\udfff\\udbff\";"},
    {"id": "norm-key-surrogate-adjacent-lh-dfff-dbff", "class": "key/string/surrogate/adjacent/lh-dfff-dbff", "input": {"\udfff\udbff": 0}, "text": "export default {\"\\udfff\\udbff\":0};"},
    {"id": "norm-string-surrogate-adjacent-ll-dfff", "class": "string/surrogate/adjacent/ll-dfff", "input": "\udfff\udfff", "text": "export default \"\\udfff\\udfff\";"},
    {"id": "norm-key-surrogate-adjacent-ll-dfff", "class": "key/string/surrogate/adjacent/ll-dfff", "input": {"\udfff\udfff": 0}, "text": "export default {\"\\udfff\\udfff\":0};"},
    {"id": "norm-string-surrogate-adjacent-hh-d800-dbff", "class": "string/surrogate/adjacent/hh-d800-dbff", "input": "\ud800\udbff", "text": "export default \"\\ud800\\udbff\";"},
    {"id": "norm-key-surrogate-adjacent-hh-d800-dbff", "class": "key/string/surrogate/adjacent/hh-d800-dbff", "input": {"\ud800\udbff": 0}, "text": "export default {\"\\ud800\\udbff\":0};"},
    {"id": "norm-object-key-order-non-index-negative", "class": "object/key-order/non-index/negative", "input": {"-1": 0, "1": 1}, "text": "export default {\"1\":1,\"-1\":0};"},
    {"id": "norm-object-key-order-non-index-negative-zero", "class": "object/key-order/non-index/negative-zero", "input": {"-0": 0, "0": 1}, "text": "export default {\"0\":1,\"-0\":0};"},
    {"id": "norm-object-key-order-non-index-plus", "class": "object/key-order/non-index/plus", "input": {"+1": 0, "1": 1}, "text": "export default {\"1\":1,\"+1\":0};"},
    {"id": "norm-object-key-order-non-index-space", "class": "object/key-order/non-index/space", "input": {" 1": 0, "1": 1}, "text": "export default {\"1\":1,\" 1\":0};"},
    {"id": "norm-object-key-order-non-index-hex", "class": "object/key-order/non-index/hex", "input": {"0x1": 0, "1": 1}, "text": "export default {\"1\":1,\"0x1\":0};"},
    {"id": "norm-object-key-order-non-index-exp", "class": "object/key-order/non-index/exp", "input": {"1e0": 0, "1": 1}, "text": "export default {\"1\":1,\"1e0\":0};"},
    {"id": "norm-object-key-order-non-index-above", "class": "object/key-order/non-index/above", "input": {"4294967296": 0, "4294967294": 1}, "text": "export default {\"4294967294\":1,\"4294967296\":0};"},
    {"id": "norm-key-proto-nested", "class": "key/proto/nested", "input": [{["__proto__"]: {["__proto__"]: 1}}], "text": "export default [{[\"__proto__\"]:{[\"__proto__\"]:1}}];"},
    {"id": "norm-number-rounding", "class": "number/binary64/rounding", "input": 9007199254740992, "text": "export default 9007199254740992;"},
    {"id": "norm-number-neg-rounding", "class": "number/binary64/rounding/neg", "input": -9007199254740992, "text": "export default -9007199254740992;"},
    {"id": "norm-string-raw-0080", "class": "string/raw/bmp", "input": "\u0080", "text": "export default \"\u0080\";"},
    {"id": "norm-key-raw-0080", "class": "key/string/raw/bmp", "input": {"\u0080": 0}, "text": "export default {\"\u0080\":0};"},
    {"id": "norm-string-raw-07ff", "class": "string/raw/bmp", "input": "\u07ff", "text": "export default \"\u07ff\";"},
    {"id": "norm-key-raw-07ff", "class": "key/string/raw/bmp", "input": {"\u07ff": 0}, "text": "export default {\"\u07ff\":0};"},
    {"id": "norm-string-raw-0800", "class": "string/raw/bmp", "input": "\u0800", "text": "export default \"\u0800\";"},
    {"id": "norm-key-raw-0800", "class": "key/string/raw/bmp", "input": {"\u0800": 0}, "text": "export default {\"\u0800\":0};"},
    {"id": "norm-shared-three-paths", "class": "const/shared/three-paths", "input": [$n29, {"a": $n29}, {"b": [$n29]}], "text": "const $0=[1];export default [$0,{\"a\":$0},{\"b\":[$0]}];"},
    {"id": "norm-unshared-object-parent-array", "class": "array/unshared/equal", "input": {"a": [1], "b": [1]}, "text": "export default {\"a\":[1],\"b\":[1]};"},
    {"id": "norm-unshared-object-parent-object", "class": "object/unshared/equal", "input": {"a": {"x": 0}, "b": {"x": 0}}, "text": "export default {\"a\":{\"x\":0},\"b\":{\"x\":0}};"},
    {"id": "norm-key-raw-ws-like-2028-nested", "class": "key/string/raw/ws-like/2028", "input": {"a": {"\u2028": 0}}, "text": "export default {\"a\":{\"\u2028\":0}};"},
    {"id": "norm-const-body-escaping-values", "class": "const/shared/twice", "input": [$n30, $n30], "text": "const $0=[\"\u2028\",\"\\ud800\",\"\\u0000\"];export default [$0,$0];"},
    {"id": "norm-const-body-escaping-key", "class": "const/shared/object", "input": [$n31, $n31], "text": "const $0={\"\u2028\":0};export default [$0,$0];"},
    {"id": "norm-key-proto-value-shared", "class": "key/proto/value/shared", "input": {["__proto__"]: $n32, "a": $n32}, "text": "const $0=[0];export default {[\"__proto__\"]:$0,\"a\":$0};"},
    {"id": "norm-const-every-value-array", "class": "const/shared/twice", "input": [$n33, $n33], "text": "const $0=[null,true,false,undefined,NaN,Infinity,-Infinity,0,-0,9,-9,1.5,100,1n,-1n,\"\",\"a\",\"\u2028\",\"\\ud800\",\"\\u0000\",[],{},1];export default [$0,$0];"},
    {"id": "norm-const-every-value-object", "class": "const/shared/object", "input": [$n34, $n34], "text": "const $0={\"a\":null,\"b\":true,\"c\":false,\"d\":undefined,\"e\":NaN,\"f\":Infinity,\"g\":-Infinity,\"h\":0,\"i\":-0,\"j\":9,\"k\":-9,\"l\":1.5,\"m\":100,\"n\":1n,\"o\":-1n,\"p\":\"\",\"q\":\"a\",\"r\":\"\u2028\",\"s\":\"\\ud800\",\"t\":\"\\u0000\",\"u\":[],\"v\":{},\"w\":1};export default [$0,$0];"},
    {"id": "norm-string-surrogate-pair-mixed", "class": "string/surrogate/pair/mixed", "input": "\ud800\udfff", "text": "export default \"\ud800\udfff\";"},
    {"id": "norm-key-surrogate-pair-mixed", "class": "key/string/surrogate/pair/mixed", "input": {"\ud800\udfff": 0}, "text": "export default {\"\ud800\udfff\":0};"},
    {"id": "norm-array-elements-negative-first", "class": "array/elements/negative-first", "input": [-1, -1n, -Infinity], "text": "export default [-1,-1n,-Infinity];"}
];
