// @generated by `npm run gen` from `fjs/effects/schema/rust/dispatch/module.f.mjs`.
// Do not edit: change the schemas in `fjs/effects/schema/module.f.mjs` and regenerate.

use crate::*;
use nanvm_lib::vm::{Any, IVm};

#[rustfmt::skip]
fn decode_make_directory_options<A: IVm>(any: Any<A>) -> Result<MakeDirectoryOptions, Malformed> {
    let object = decode_object(any, &["recursive"])?;
    decode_true(required(&object, "recursive")?)?;
    Ok(MakeDirectoryOptions)
}

#[rustfmt::skip]
fn decode_readdir_options<A: IVm>(any: Any<A>) -> Result<ReaddirOptions, Malformed> {
    let object = decode_object(any, &["recursive"])?;
    Ok(ReaddirOptions {
        recursive: decode_flag(member(&object, "recursive"))?,
    })
}

#[rustfmt::skip]
fn decode_write_consoles<A: IVm>(any: Any<A>) -> Result<WriteConsoles, Malformed> {
    Ok(match decode_choice(any, &["stdout", "stderr"])? {
        0 => WriteConsoles::Stdout,
        _ => WriteConsoles::Stderr,
    })
}

#[rustfmt::skip]
fn encode_not_implemented<A: IVm>(value: NotImplemented) -> Any<A> {
    encode_tuple("notImplemented", vec![encode_string(value.0)])
}

#[rustfmt::skip]
fn encode_io_error_info<A: IVm>(value: IoErrorInfo) -> Any<A> {
    encode_object(vec![
        value.code.map(|v| ("code", encode_string(v))),
        Some(("message", encode_string(value.message))),
    ])
}

#[rustfmt::skip]
fn encode_io_channel<A: IVm>(value: IoChannel) -> Any<A> {
    match value {
        IoChannel::NotImplemented(f0) => encode_tuple("notImplemented", vec![encode_string(f0)]),
        IoChannel::IoError(f0) => encode_tuple("ioError", vec![encode_io_error_info(f0)]),
    }
}

#[rustfmt::skip]
fn encode_file_module<A: IVm>(value: FileModule) -> Any<A> {
    encode_object(vec![
        Some(("id", encode_string(value.id))),
        Some(("path", encode_string(value.path))),
    ])
}

#[rustfmt::skip]
fn encode_dirent<A: IVm>(value: Dirent) -> Any<A> {
    encode_object(vec![
        Some(("name", encode_string(value.name))),
        Some(("parentPath", encode_string(value.parent_path))),
        Some(("isFile", encode_bool(value.is_file))),
        Some(("isDirectory", encode_bool(value.is_directory))),
    ])
}

#[rustfmt::skip]
fn call_mkdir<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 2)?;
    let path = decode_string(argument(payload, 0, "path")?)?;
    let options = decode_optional(payload.get(1).cloned(), decode_make_directory_options)?;
    Ok(encode_result(runner.mkdir(path, options), encode_nothing, encode_io_channel))
}

#[rustfmt::skip]
fn call_read_file<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 1)?;
    let path = decode_string(argument(payload, 0, "path")?)?;
    Ok(encode_result(runner.read_file(path), encode_bytes, encode_io_channel))
}

#[rustfmt::skip]
fn call_resolve_file_module<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 2)?;
    let name = decode_string(argument(payload, 0, "name")?)?;
    let parent = decode_nullable(argument(payload, 1, "parent")?, decode_string)?;
    Ok(encode_result(runner.resolve_file_module(name, parent), encode_file_module, encode_io_channel))
}

#[rustfmt::skip]
fn call_readdir<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 2)?;
    let path = decode_string(argument(payload, 0, "path")?)?;
    let options = decode_readdir_options(argument(payload, 1, "options")?)?;
    Ok(encode_result(runner.readdir(path, options), |v| encode_array(v, encode_dirent), encode_io_channel))
}

#[rustfmt::skip]
fn call_write_file<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 2)?;
    let path = decode_string(argument(payload, 0, "path")?)?;
    let data = decode_bytes(argument(payload, 1, "data")?)?;
    Ok(encode_result(runner.write_file(path, data), encode_nothing, encode_io_channel))
}

#[rustfmt::skip]
fn call_write_bytes<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 3)?;
    let path = decode_string(argument(payload, 0, "path")?)?;
    let offset = decode_number(argument(payload, 1, "offset")?)?;
    let data = decode_bytes(argument(payload, 2, "data")?)?;
    Ok(encode_result(runner.write_bytes(path, offset, data), encode_nothing, encode_io_channel))
}

#[rustfmt::skip]
fn call_rm<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 1)?;
    let path = decode_string(argument(payload, 0, "path")?)?;
    Ok(encode_result(runner.rm(path), encode_nothing, encode_io_channel))
}

#[rustfmt::skip]
fn call_write<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 2)?;
    let stream = decode_write_consoles(argument(payload, 0, "stream")?)?;
    let data = decode_bytes(argument(payload, 1, "data")?)?;
    Ok(encode_result(runner.write(stream, data), encode_nothing, encode_not_implemented))
}

#[rustfmt::skip]
fn call_read<A: IVm, R: Operations>(runner: &mut R, payload: &[Any<A>]) -> Result<Any<A>, Malformed> {
    arity(payload, 1)?;
    decode_literal(argument(payload, 0, "stream")?, "stdin")?;
    Ok(encode_result(runner.read(), |v| encode_nullable(v, encode_number), encode_not_implemented))
}

/// The operation `command` names run against `payload`, or `None` where this
/// runner has no such operation.
#[rustfmt::skip]
pub fn dispatch<A: IVm, R: Operations>(runner: &mut R, command: &str, payload: &[Any<A>]) -> Option<Result<Any<A>, Malformed>> {
    match command {
        "mkdir" => Some(call_mkdir(runner, payload)),
        "readFile" => Some(call_read_file(runner, payload)),
        "resolveFileModule" => Some(call_resolve_file_module(runner, payload)),
        "readdir" => Some(call_readdir(runner, payload)),
        "writeFile" => Some(call_write_file(runner, payload)),
        "writeBytes" => Some(call_write_bytes(runner, payload)),
        "rm" => Some(call_rm(runner, payload)),
        "write" => Some(call_write(runner, payload)),
        "read" => Some(call_read(runner, payload)),
        _ => None,
    }
}
