// @generated by `npm run ci-update` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared operator test data and regenerate.

use super::harness::*;

#[rustfmt::skip]
fn eq<A: IVm>() {
    let empty_array: Any<A> = Array::default().to_any();
    let string_array: Any<A> = [string_any("0")].to_array().to_any();
    let object: Any<A> = [(string_key("0"), string_any("0"))].to_object().to_any();
    check_eq::<A>("nullByNull", Nullish::Null.to_any(), Nullish::Null.to_any(), true);
    check_eq::<A>("undefinedByUndefined", Nullish::Undefined.to_any(), Nullish::Undefined.to_any(), true);
    check_eq::<A>("nullByUndefined", Nullish::Null.to_any(), Nullish::Undefined.to_any(), false);
    check_eq::<A>("trueByTrue", true.to_any(), true.to_any(), true);
    check_eq::<A>("falseByFalse", false.to_any(), false.to_any(), true);
    check_eq::<A>("trueByFalse", true.to_any(), false.to_any(), false);
    check_eq::<A>("falseByUndefined", false.to_any(), Nullish::Undefined.to_any(), false);
    check_eq::<A>("falseByNull", false.to_any(), Nullish::Null.to_any(), false);
    check_eq::<A>("numberBySameNumber", (2.3f64).to_any(), (2.3f64).to_any(), true);
    check_eq::<A>("numberByOtherNumber", (2.3f64).to_any(), (-5.4f64).to_any(), false);
    check_eq::<A>("nanByNan", (f64::NAN).to_any(), (f64::NAN).to_any(), false);
    check_eq::<A>("zeroByNegativeZero", (0f64).to_any(), (-0f64).to_any(), true);
    check_eq::<A>("infinityByInfinity", (f64::INFINITY).to_any(), (f64::INFINITY).to_any(), true);
    check_eq::<A>("negativeInfinityByNegativeInfinity", (f64::NEG_INFINITY).to_any(), (f64::NEG_INFINITY).to_any(), true);
    check_eq::<A>("infinityByNegativeInfinity", (f64::INFINITY).to_any(), (f64::NEG_INFINITY).to_any(), false);
    check_eq::<A>("undefinedByNan", Nullish::Undefined.to_any(), (f64::NAN).to_any(), false);
    check_eq::<A>("undefinedByZero", Nullish::Undefined.to_any(), (0f64).to_any(), false);
    check_eq::<A>("stringBySameString", string_any("hello"), string_any("hello"), true);
    check_eq::<A>("stringByOtherString", string_any("hello"), string_any("world"), false);
    check_eq::<A>("zeroByStringZero", (0f64).to_any(), string_any("0"), false);
    check_eq::<A>("bigintBySameBigint", bigint_any(12), bigint_any(12), true);
    check_eq::<A>("bigintByNegatedBigint", bigint_any(12), bigint_any(-12), false);
    check_eq::<A>("bigintByOtherBigint", bigint_any(12), bigint_any(13), false);
    check_eq::<A>("twelveByStringTwelve", bigint_any(12), string_any("12"), false);
    check_eq::<A>("arrayByItself", empty_array.clone(), empty_array.clone(), true);
    check_eq::<A>("arrayByEqualArray", Array::default().to_any(), Array::default().to_any(), false);
    check_eq::<A>("stringArrayByItself", string_array.clone(), string_array.clone(), true);
    check_eq::<A>("objectByItself", object.clone(), object.clone(), true);
    check_eq::<A>("objectByEqualObject", object.clone(), [(string_key("0"), string_any("0"))].to_object().to_any(), false);
}

#[rustfmt::skip]
fn unary_plus<A: IVm>() {
    check::<A>("null", Any::unary_plus(Nullish::Null.to_any()), (0f64).to_any());
    check::<A>("undefined", Any::unary_plus(Nullish::Undefined.to_any()), (f64::NAN).to_any());
    check::<A>("booleanFalse", Any::unary_plus(false.to_any()), (0f64).to_any());
    check::<A>("booleanTrue", Any::unary_plus(true.to_any()), (1f64).to_any());
    check::<A>("numberZero", Any::unary_plus((0f64).to_any()), (0f64).to_any());
    check::<A>("numberPositive", Any::unary_plus((2.3f64).to_any()), (2.3f64).to_any());
    check::<A>("numberNegative", Any::unary_plus((-2.3f64).to_any()), (-2.3f64).to_any());
    check::<A>("numberLarge", Any::unary_plus((-239f64).to_any()), (-239f64).to_any());
    check::<A>("numberInfinity", Any::unary_plus((f64::INFINITY).to_any()), (f64::INFINITY).to_any());
    check::<A>("numberNegativeInfinity", Any::unary_plus((f64::NEG_INFINITY).to_any()), (f64::NEG_INFINITY).to_any());
    check::<A>("numberNan", Any::unary_plus((f64::NAN).to_any()), (f64::NAN).to_any());
    check::<A>("stringEmpty", Any::unary_plus(string_any("")), (0f64).to_any());
    check::<A>("stringZero", Any::unary_plus(string_any("0")), (0f64).to_any());
    check::<A>("stringNumber", Any::unary_plus(string_any("2.3")), (2.3f64).to_any());
    check::<A>("stringExponent", Any::unary_plus(string_any("2.3e2")), (230f64).to_any());
    check::<A>("stringNotANumber", Any::unary_plus(string_any("a")), (f64::NAN).to_any());
    check::<A>("arrayEmpty", Any::unary_plus(Array::default().to_any()), (0f64).to_any());
    check::<A>("arrayNumber", Any::unary_plus([(2.3f64).to_any()].to_array().to_any()), (2.3f64).to_any());
    check::<A>("arrayNegativeNumber", Any::unary_plus([(-0.3f64).to_any()].to_array().to_any()), (-0.3f64).to_any());
    check::<A>("arrayString", Any::unary_plus([string_any("-2.3")].to_array().to_any()), (-2.3f64).to_any());
    check::<A>("arrayPositiveString", Any::unary_plus([string_any("0.3")].to_array().to_any()), (0.3f64).to_any());
    check::<A>("arrayNull", Any::unary_plus([Nullish::Null.to_any()].to_array().to_any()), (0f64).to_any());
    check::<A>("arrayPair", Any::unary_plus([Nullish::Null.to_any(), Nullish::Null.to_any()].to_array().to_any()), (f64::NAN).to_any());
    check::<A>("objectEmpty", Any::unary_plus(Object::default().to_any()), (f64::NAN).to_any());
    check::<A>("function", Any::unary_plus(function_any()), (f64::NAN).to_any());
    check_throws::<A>("bigint", Any::unary_plus(bigint_any(0)));
}

#[rustfmt::skip]
fn neg<A: IVm>() {
    check::<A>("null", -(Nullish::Null.to_any()), (-0f64).to_any());
    check::<A>("undefined", -(Nullish::Undefined.to_any()), (f64::NAN).to_any());
    check::<A>("booleanFalse", -(false.to_any()), (-0f64).to_any());
    check::<A>("booleanTrue", -(true.to_any()), (-1f64).to_any());
    check::<A>("numberZero", -((0f64).to_any()), (-0f64).to_any());
    check::<A>("numberPositive", -((2.3f64).to_any()), (-2.3f64).to_any());
    check::<A>("numberNegative", -((-2.3f64).to_any()), (2.3f64).to_any());
    check::<A>("numberLarge", -((-239f64).to_any()), (239f64).to_any());
    check::<A>("numberInfinity", -((f64::INFINITY).to_any()), (f64::NEG_INFINITY).to_any());
    check::<A>("numberNegativeInfinity", -((f64::NEG_INFINITY).to_any()), (f64::INFINITY).to_any());
    check::<A>("numberNan", -((f64::NAN).to_any()), (f64::NAN).to_any());
    check::<A>("stringEmpty", -(string_any("")), (-0f64).to_any());
    check::<A>("stringZero", -(string_any("0")), (-0f64).to_any());
    check::<A>("stringNumber", -(string_any("2.3")), (-2.3f64).to_any());
    check::<A>("stringExponent", -(string_any("2.3e2")), (-230f64).to_any());
    check::<A>("stringNotANumber", -(string_any("a")), (f64::NAN).to_any());
    check::<A>("arrayEmpty", -(Array::default().to_any()), (-0f64).to_any());
    check::<A>("arrayNumber", -([(2.3f64).to_any()].to_array().to_any()), (-2.3f64).to_any());
    check::<A>("arrayNegativeNumber", -([(-0.3f64).to_any()].to_array().to_any()), (0.3f64).to_any());
    check::<A>("arrayString", -([string_any("-2.3")].to_array().to_any()), (2.3f64).to_any());
    check::<A>("arrayPositiveString", -([string_any("0.3")].to_array().to_any()), (-0.3f64).to_any());
    check::<A>("arrayNull", -([Nullish::Null.to_any()].to_array().to_any()), (-0f64).to_any());
    check::<A>("arrayPair", -([Nullish::Null.to_any(), Nullish::Null.to_any()].to_array().to_any()), (f64::NAN).to_any());
    check::<A>("objectEmpty", -(Object::default().to_any()), (f64::NAN).to_any());
    check::<A>("function", -(function_any()), (f64::NAN).to_any());
    check::<A>("bigintPositive", -(bigint_any(1)), bigint_any(-1));
    check::<A>("bigintNegative", -(bigint_any(-1)), bigint_any(1));
}

#[rustfmt::skip]
fn mul<A: IVm>() {
    check::<A>("nullByNull", Nullish::Null.to_any() * Nullish::Null.to_any(), (0f64).to_any());
    check::<A>("nullByNullSwapped", Nullish::Null.to_any() * Nullish::Null.to_any(), (0f64).to_any());
    check::<A>("nullByZero", Nullish::Null.to_any() * (0f64).to_any(), (0f64).to_any());
    check::<A>("nullByZeroSwapped", (0f64).to_any() * Nullish::Null.to_any(), (0f64).to_any());
    check::<A>("undefinedByZero", Nullish::Undefined.to_any() * (0f64).to_any(), (f64::NAN).to_any());
    check::<A>("undefinedByZeroSwapped", (0f64).to_any() * Nullish::Undefined.to_any(), (f64::NAN).to_any());
    check::<A>("trueByZero", true.to_any() * (0f64).to_any(), (0f64).to_any());
    check::<A>("trueByZeroSwapped", (0f64).to_any() * true.to_any(), (0f64).to_any());
    check::<A>("trueByOne", true.to_any() * (1f64).to_any(), (1f64).to_any());
    check::<A>("trueByOneSwapped", (1f64).to_any() * true.to_any(), (1f64).to_any());
    check::<A>("trueByTen", true.to_any() * (10f64).to_any(), (10f64).to_any());
    check::<A>("trueByTenSwapped", (10f64).to_any() * true.to_any(), (10f64).to_any());
    check::<A>("falseByZero", false.to_any() * (0f64).to_any(), (0f64).to_any());
    check::<A>("falseByZeroSwapped", (0f64).to_any() * false.to_any(), (0f64).to_any());
    check::<A>("falseByOne", false.to_any() * (1f64).to_any(), (0f64).to_any());
    check::<A>("falseByOneSwapped", (1f64).to_any() * false.to_any(), (0f64).to_any());
    check::<A>("falseByTen", false.to_any() * (10f64).to_any(), (0f64).to_any());
    check::<A>("falseByTenSwapped", (10f64).to_any() * false.to_any(), (0f64).to_any());
    check::<A>("zeroByZero", (0f64).to_any() * (0f64).to_any(), (0f64).to_any());
    check::<A>("zeroByZeroSwapped", (0f64).to_any() * (0f64).to_any(), (0f64).to_any());
    check::<A>("zeroByOne", (0f64).to_any() * (1f64).to_any(), (0f64).to_any());
    check::<A>("zeroByOneSwapped", (1f64).to_any() * (0f64).to_any(), (0f64).to_any());
    check::<A>("oneByOne", (1f64).to_any() * (1f64).to_any(), (1f64).to_any());
    check::<A>("oneByOneSwapped", (1f64).to_any() * (1f64).to_any(), (1f64).to_any());
    check::<A>("oneByMinusOne", (1f64).to_any() * (-1f64).to_any(), (-1f64).to_any());
    check::<A>("oneByMinusOneSwapped", (-1f64).to_any() * (1f64).to_any(), (-1f64).to_any());
    check::<A>("oneByTen", (1f64).to_any() * (10f64).to_any(), (10f64).to_any());
    check::<A>("oneByTenSwapped", (10f64).to_any() * (1f64).to_any(), (10f64).to_any());
    check::<A>("minusOneByTen", (-1f64).to_any() * (10f64).to_any(), (-10f64).to_any());
    check::<A>("minusOneByTenSwapped", (10f64).to_any() * (-1f64).to_any(), (-10f64).to_any());
    check::<A>("tenByTen", (10f64).to_any() * (10f64).to_any(), (100f64).to_any());
    check::<A>("tenByTenSwapped", (10f64).to_any() * (10f64).to_any(), (100f64).to_any());
    check::<A>("minusTenByTen", (-10f64).to_any() * (10f64).to_any(), (-100f64).to_any());
    check::<A>("minusTenByTenSwapped", (10f64).to_any() * (-10f64).to_any(), (-100f64).to_any());
    check::<A>("bigZeroByZero", bigint_any(0) * bigint_any(0), bigint_any(0));
    check::<A>("bigZeroByZeroSwapped", bigint_any(0) * bigint_any(0), bigint_any(0));
    check::<A>("bigZeroByOne", bigint_any(0) * bigint_any(1), bigint_any(0));
    check::<A>("bigZeroByOneSwapped", bigint_any(1) * bigint_any(0), bigint_any(0));
    check::<A>("bigOneByOne", bigint_any(1) * bigint_any(1), bigint_any(1));
    check::<A>("bigOneByOneSwapped", bigint_any(1) * bigint_any(1), bigint_any(1));
    check::<A>("bigOneByMinusOne", bigint_any(1) * bigint_any(-1), bigint_any(-1));
    check::<A>("bigOneByMinusOneSwapped", bigint_any(-1) * bigint_any(1), bigint_any(-1));
    check::<A>("bigOneByTen", bigint_any(1) * bigint_any(10), bigint_any(10));
    check::<A>("bigOneByTenSwapped", bigint_any(10) * bigint_any(1), bigint_any(10));
    check::<A>("bigMinusOneByTen", bigint_any(-1) * bigint_any(10), bigint_any(-10));
    check::<A>("bigMinusOneByTenSwapped", bigint_any(10) * bigint_any(-1), bigint_any(-10));
    check::<A>("bigTenByTen", bigint_any(10) * bigint_any(10), bigint_any(100));
    check::<A>("bigTenByTenSwapped", bigint_any(10) * bigint_any(10), bigint_any(100));
    check::<A>("bigMinusTenByTen", bigint_any(-10) * bigint_any(10), bigint_any(-100));
    check::<A>("bigMinusTenByTenSwapped", bigint_any(10) * bigint_any(-10), bigint_any(-100));
    check::<A>("emptyStringByOne", string_any("") * (1f64).to_any(), (0f64).to_any());
    check::<A>("emptyStringByOneSwapped", (1f64).to_any() * string_any(""), (0f64).to_any());
    check::<A>("stringTenByOne", string_any("10") * (1f64).to_any(), (10f64).to_any());
    check::<A>("stringTenByOneSwapped", (1f64).to_any() * string_any("10"), (10f64).to_any());
    check::<A>("stringLetterByOne", string_any("a") * (1f64).to_any(), (f64::NAN).to_any());
    check::<A>("stringLetterByOneSwapped", (1f64).to_any() * string_any("a"), (f64::NAN).to_any());
    check::<A>("stringBigintByOne", string_any("1n") * (1f64).to_any(), (f64::NAN).to_any());
    check::<A>("stringBigintByOneSwapped", (1f64).to_any() * string_any("1n"), (f64::NAN).to_any());
    check::<A>("emptyArrayByOne", Array::default().to_any() * (1f64).to_any(), (0f64).to_any());
    check::<A>("emptyArrayByOneSwapped", (1f64).to_any() * Array::default().to_any(), (0f64).to_any());
    check::<A>("arrayTenByOne", [(10f64).to_any()].to_array().to_any() * (1f64).to_any(), (10f64).to_any());
    check::<A>("arrayTenByOneSwapped", (1f64).to_any() * [(10f64).to_any()].to_array().to_any(), (10f64).to_any());
    check::<A>("arrayStringTenByOne", [string_any("10")].to_array().to_any() * (1f64).to_any(), (10f64).to_any());
    check::<A>("arrayStringTenByOneSwapped", (1f64).to_any() * [string_any("10")].to_array().to_any(), (10f64).to_any());
    check::<A>("arrayPairByOne", [(0f64).to_any(), (0f64).to_any()].to_array().to_any() * (1f64).to_any(), (f64::NAN).to_any());
    check::<A>("arrayPairByOneSwapped", (1f64).to_any() * [(0f64).to_any(), (0f64).to_any()].to_array().to_any(), (f64::NAN).to_any());
    check::<A>("emptyObjectByOne", Object::default().to_any() * (1f64).to_any(), (f64::NAN).to_any());
    check::<A>("emptyObjectByOneSwapped", (1f64).to_any() * Object::default().to_any(), (f64::NAN).to_any());
    check_throws::<A>("numberByBigint", (1f64).to_any() * bigint_any(1));
    check_throws::<A>("numberByBigintSwapped", bigint_any(1) * (1f64).to_any());
}

#[rustfmt::skip]
fn string_coercion<A: IVm>() {
    check::<A>("number", (123f64).to_any().to_string().map(|v| v.to_any()), string_any("123"));
    check::<A>("negativeNumber", (-456f64).to_any().to_string().map(|v| v.to_any()), string_any("-456"));
    check::<A>("zero", (0f64).to_any().to_string().map(|v| v.to_any()), string_any("0"));
    check::<A>("negativeZero", (-0f64).to_any().to_string().map(|v| v.to_any()), string_any("0"));
    check::<A>("infinity", (f64::INFINITY).to_any().to_string().map(|v| v.to_any()), string_any("Infinity"));
    check::<A>("negativeInfinity", (f64::NEG_INFINITY).to_any().to_string().map(|v| v.to_any()), string_any("-Infinity"));
    check::<A>("nan", (f64::NAN).to_any().to_string().map(|v| v.to_any()), string_any("NaN"));
    check::<A>("booleanTrue", true.to_any().to_string().map(|v| v.to_any()), string_any("true"));
    check::<A>("booleanFalse", false.to_any().to_string().map(|v| v.to_any()), string_any("false"));
    check::<A>("null", Nullish::Null.to_any().to_string().map(|v| v.to_any()), string_any("null"));
    check::<A>("undefined", Nullish::Undefined.to_any().to_string().map(|v| v.to_any()), string_any("undefined"));
    check::<A>("string", string_any("already").to_string().map(|v| v.to_any()), string_any("already"));
    // TODO: nanvm-lib prints bigints in hexadecimal; see nanvm-lib/todo/bigint-decimal-string-coercion.md
    // check::<A>("bigint", bigint_any(123).to_string().map(|v| v.to_any()), string_any("123"));
    // TODO: nanvm-lib prints bigints in hexadecimal; see nanvm-lib/todo/bigint-decimal-string-coercion.md
    // check::<A>("negativeBigint", bigint_any(-456).to_string().map(|v| v.to_any()), string_any("-456"));
    check::<A>("emptyArray", Array::default().to_any().to_string().map(|v| v.to_any()), string_any(""));
    check::<A>("singletonArray", [(1f64).to_any()].to_array().to_any().to_string().map(|v| v.to_any()), string_any("1"));
    check::<A>("array", [(1f64).to_any(), (2f64).to_any(), (3f64).to_any()].to_array().to_any().to_string().map(|v| v.to_any()), string_any("1,2,3"));
    check::<A>("nestedArray", [(1f64).to_any(), [(2f64).to_any(), (3f64).to_any()].to_array().to_any(), (4f64).to_any()].to_array().to_any().to_string().map(|v| v.to_any()), string_any("1,2,3,4"));
    check::<A>("arrayWithNullish", [Nullish::Null.to_any(), Nullish::Undefined.to_any(), (1f64).to_any()].to_array().to_any().to_string().map(|v| v.to_any()), string_any(",,1"));
    check::<A>("emptyObject", Object::default().to_any().to_string().map(|v| v.to_any()), string_any("[object Object]"));
    check::<A>("object", [(string_key("a"), (1f64).to_any())].to_object().to_any().to_string().map(|v| v.to_any()), string_any("[object Object]"));
}

pub fn all<A: IVm>() {
    eq::<A>();
    unary_plus::<A>();
    neg::<A>();
    mul::<A>();
    string_coercion::<A>();
}
