/**
 * Dockerfile generator: renders the contents of `docker/Dockerfile` from the
 * version pins in `../config/module.f.ts` — the same source the GitHub Actions
 * workflow is generated from, so the image and CI never drift apart — plus the
 * jobs that build it, one per architecture.
 *
 * Nothing enters the image unpinned. The base image is referenced by digest,
 * `apt` resolves against a dated archive snapshot, every tool comes from a
 * version-specific release URL, and every downloaded archive is checked
 * against a committed SHA-256 — a release asset can be replaced under its tag,
 * so the URL alone is not an integrity guarantee. The exceptions are the two
 * npm-installed CLIs, pinned to exact versions and integrity-checked by npm
 * against the registry rather than by a committed hash.
 *
 * @module
 */
import { actions, bun, deno, dockerBase, dockerSnapshot, functionalscript, images, node, playwright, rustComponents, rustup, sha256, wasmer, wasmtime } from '../config/module.f.ts'
import { type Image, type Job, type Jobs, test, toSteps } from '../common/module.f.ts'
import { definedEntries, type StringMap } from '../../types/object/module.f.ts'
import { browsers } from '../playwright/module.f.ts'
import { i686Linux, wasmTargets } from '../rust/module.f.ts'

/** One value per architecture the image supports, keyed as `dpkg` names them. */
export type ArchNames = {
    readonly amd64: string
    readonly arm64: string
}

/** A `RUN` instruction whose commands are chained with `&&`, one per line. */
const run = (commands: readonly string[]): string =>
    `RUN ${commands.join(' \\\n    && ')}`

/** The `name=value` shell assignments of `vars` for one architecture. */
const assignments = (vars: StringMap<string, ArchNames>) => (a: keyof ArchNames): string =>
    definedEntries(vars).map(([name, value]) => `${name}=${value[a]}`).join('; ')

/**
 * Commands setting `$arch` from `dpkg`, then one shell variable per entry of
 * `vars` to its value for that architecture. An unsupported architecture fails
 * the build instead of downloading from a URL assembled out of a wrong name.
 */
const arch = (vars: StringMap<string, ArchNames>): readonly string[] => [
    'arch="$(dpkg --print-architecture)"',
    `case "$arch" in amd64) ${assignments(vars)('amd64')} ;; arm64) ${assignments(vars)('arm64')} ;; *) echo "unsupported architecture: $arch" >&2; exit 1 ;; esac`,
]

/** Checks a downloaded file against the SHA-256 held in `$<name>`. */
const verify = (name: string, file: string): string =>
    `echo "$${name}  ${file}" | sha256sum -c -`

const env = (name: string, value: string): string => `ENV ${name}=${value}`

/** One documented block of instructions: a `#` comment, then the instructions. */
const block = (comment: string, instructions: readonly string[]): string =>
    [`# ${comment}`, ...instructions].join('\n')

const release = (repo: string, tag: string): string =>
    `https://github.com/${repo}/releases/download/${tag}`

const header = [
    '# Generated by `fjs ci` from fjs/ci/docker/module.f.ts. Do not edit by hand.',
    '#',
    '# Every version below is pinned in fjs/ci/config/module.f.ts, the same source',
    '# .github/workflows/ci.yml is generated from. Change a pin there and rerun',
    '# `npm run ci-update`; CI fails when the committed files no longer match.',
].join('\n')

const from = block(
    'Base image by digest: the distribution the `ubuntu-26.04` runners use.',
    [
        `FROM ${dockerBase}`,
        // `-e` and `pipefail` make a failing stage of the checksum pipeline
        // below fail the build instead of being masked by the exit code of the
        // last command.
        'SHELL ["/bin/bash", "-euo", "pipefail", "-c"]',
    ])

const packages: readonly string[] = [
    'build-essential',
    'ca-certificates',
    'curl',
    'git',
    'gnupg',
    'libssl-dev',
    'pkg-config',
    'unzip',
    'xz-utils',
]

// `apt` reaches the snapshot service over HTTPS (it redirects there from
// HTTP), but the base image ships no CA bundle — `ca-certificates` is one of
// the packages installed below. Rather than fetch a trust anchor from the
// unpinned live archive first, peer verification is disabled for that one host
// until `ca-certificates` lands: integrity of the packages comes from the
// archive's GPG signature, checked by the `gpgv` and `ubuntu-keyring` the base
// image does ship, which is the same guarantee a plain-HTTP mirror gives.
const noTlsVerify = '/etc/apt/apt.conf.d/99snapshot-bootstrap' as const

const apt = (rust: boolean): string => block(
    'Build prerequisites, resolved against a dated archive snapshot so that a rebuild installs the same packages.',
    [
        env('UBUNTU_SNAPSHOT', dockerSnapshot),
        env('DEBIAN_FRONTEND', 'noninteractive'),
        run([
            `echo 'Acquire::https::snapshot.ubuntu.com::Verify-Peer "false";' > ${noTlsVerify}`,
            // `sed` fails the build if the base image ever stops using deb822
            // sources, rather than silently leaving `apt` unpinned.
            'sed -i "s|^URIs: .*|URIs: https://snapshot.ubuntu.com/ubuntu/$UBUNTU_SNAPSHOT|" /etc/apt/sources.list.d/ubuntu.sources',
            // The 32-bit development files exist on Intel only, and only the
            // Rust i686 checks need them, so `$extra_packages` is empty
            // everywhere else and expands to nothing.
            ...(rust ? arch({ extra_packages: { amd64: i686Linux.package, arm64: '' } }) : []),
            'apt-get update',
            `apt-get install -y --no-install-recommends ${packages.join(' ')}${rust ? ' $extra_packages' : ''}`,
            // Every later `apt` call — Playwright's `install --with-deps` among
            // them — verifies the certificate normally.
            `rm ${noTlsVerify}`,
            'rm -rf /var/lib/apt/lists/*',
        ]),
    ])

const nodeBlock = block(
    'Node.js: official build.',
    [
        env('NODE_VERSION', node.default),
        run([
            ...arch({
                node_arch: { amd64: 'x64', arm64: 'arm64' },
                node_sha256: sha256.node,
            }),
            'node_archive="node-v$NODE_VERSION-linux-$node_arch.tar.xz"',
            'curl -fsSLo "/tmp/$node_archive" "https://nodejs.org/dist/v$NODE_VERSION/$node_archive"',
            verify('node_sha256', '/tmp/$node_archive'),
            'tar -xJf "/tmp/$node_archive" -C /usr/local --strip-components=1 --no-same-owner',
            'rm "/tmp/$node_archive"',
        ]),
    ])

const denoBlock = block(
    'Deno: official release archive.',
    [
        env('DENO_VERSION', deno),
        run([
            ...arch({
                deno_arch: { amd64: 'x86_64-unknown-linux-gnu', arm64: 'aarch64-unknown-linux-gnu' },
                deno_sha256: sha256.deno,
            }),
            `curl -fsSLo /tmp/deno.zip "${release('denoland/deno', 'v$DENO_VERSION')}/deno-$deno_arch.zip"`,
            verify('deno_sha256', '/tmp/deno.zip'),
            'unzip -q -d /usr/local/bin /tmp/deno.zip',
            'chmod +x /usr/local/bin/deno',
            'rm /tmp/deno.zip',
        ]),
    ])

const bunBlock = block(
    'Bun: official release archive.',
    [
        env('BUN_VERSION', bun),
        run([
            ...arch({
                bun_arch: { amd64: 'x64', arm64: 'aarch64' },
                bun_sha256: sha256.bun,
            }),
            `curl -fsSLo /tmp/bun.zip "${release('oven-sh/bun', 'bun-v$BUN_VERSION')}/bun-linux-$bun_arch.zip"`,
            verify('bun_sha256', '/tmp/bun.zip'),
            'unzip -q -d /tmp /tmp/bun.zip',
            'mv "/tmp/bun-linux-$bun_arch/bun" /usr/local/bin/bun',
            'chmod +x /usr/local/bin/bun',
            'rm -rf /tmp/bun.zip "/tmp/bun-linux-$bun_arch"',
        ]),
    ])

const rustBlock = block(
    'Rust: pinned rustup installs the pinned toolchain, its components and targets.',
    [
        env('RUSTUP_VERSION', rustup),
        env('RUST_VERSION', actions['dtolnay/rust-toolchain']),
        env('RUSTUP_HOME', '/usr/local/rustup'),
        env('CARGO_HOME', '/usr/local/cargo'),
        env('PATH', '/usr/local/cargo/bin:$PATH'),
        run([
            ...arch({
                rust_host: { amd64: 'x86_64-unknown-linux-gnu', arm64: 'aarch64-unknown-linux-gnu' },
                rustup_sha256: sha256.rustup,
                // Intel additionally cross-compiles to 32-bit, as the Ubuntu
                // Intel job does; the ARM runners have no such target.
                rust_targets: {
                    amd64: [...wasmTargets, i686Linux.target].join(','),
                    arm64: wasmTargets.join(','),
                },
            }),
            'curl -fsSLo /tmp/rustup-init "https://static.rust-lang.org/rustup/archive/$RUSTUP_VERSION/$rust_host/rustup-init"',
            verify('rustup_sha256', '/tmp/rustup-init'),
            'chmod +x /tmp/rustup-init',
            // `--component` and `--target` take one comma-separated list each;
            // space-separated values are rejected as unexpected arguments.
            `/tmp/rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --component ${rustComponents} --target $rust_targets`,
            'rm /tmp/rustup-init',
            // Non-root users of the image need a writable toolchain directory
            // to add a target or run `cargo` against a fresh registry cache.
            'chmod -R a+w $RUSTUP_HOME $CARGO_HOME',
        ]),
    ])

const wasmtimeBlock = block(
    'Wasmtime: runner for the WASM targets.',
    [
        env('WASMTIME_VERSION', wasmtime),
        run([
            ...arch({
                wasmtime_arch: { amd64: 'x86_64', arm64: 'aarch64' },
                wasmtime_sha256: sha256.wasmtime,
            }),
            'wasmtime_dir="wasmtime-v$WASMTIME_VERSION-$wasmtime_arch-linux"',
            `curl -fsSLo /tmp/wasmtime.tar.xz "${release('bytecodealliance/wasmtime', 'v$WASMTIME_VERSION')}/$wasmtime_dir.tar.xz"`,
            verify('wasmtime_sha256', '/tmp/wasmtime.tar.xz'),
            'tar -xJf /tmp/wasmtime.tar.xz -C /tmp',
            'mv "/tmp/$wasmtime_dir/wasmtime" /usr/local/bin/wasmtime',
            'rm -rf /tmp/wasmtime.tar.xz "/tmp/$wasmtime_dir"',
        ]),
    ])

const wasmerBlock = block(
    'Wasmer: runner used by .cargo/config.wasmer.toml, including the threads target.',
    [
        env('WASMER_VERSION', wasmer),
        env('WASMER_DIR', '/usr/local'),
        run([
            ...arch({
                wasmer_arch: { amd64: 'amd64', arm64: 'aarch64' },
                wasmer_sha256: sha256.wasmer,
            }),
            `curl -fsSLo /tmp/wasmer.tar.gz "${release('wasmerio/wasmer', 'v$WASMER_VERSION')}/wasmer-linux-$wasmer_arch.tar.gz"`,
            verify('wasmer_sha256', '/tmp/wasmer.tar.gz'),
            'tar -xzf /tmp/wasmer.tar.gz -C /usr/local',
            'rm /tmp/wasmer.tar.gz',
        ]),
    ])

const playwrightBlock = block(
    'Playwright and its browsers. Browser builds are pinned by the Playwright version.',
    [
        env('PLAYWRIGHT_VERSION', playwright),
        // Browsers are installed outside `$HOME` so every user of the image
        // finds them, not just the one that built it.
        env('PLAYWRIGHT_BROWSERS_PATH', '/usr/local/ms-playwright'),
        run([
            'npm install -g playwright@$PLAYWRIGHT_VERSION',
            `playwright install --with-deps ${browsers.join(' ')}`,
            'rm -rf /var/lib/apt/lists/*',
        ]),
    ])

const fjsBlock = block(
    'The published FunctionalScript CLI (`fjs`) used by the generated smoke tests.',
    [
        env('FUNCTIONALSCRIPT_VERSION', functionalscript),
        run(['npm install -g functionalscript@$FUNCTIONALSCRIPT_VERSION']),
    ])

const workspace = block(
    'The repository is mounted or checked out here; the image itself carries only tools.',
    [
        'WORKDIR /workspace',
        'CMD ["bash"]',
    ])

/**
 * The full text of the generated `docker/Dockerfile`. `rust` follows the
 * workflow: a project with no `Cargo.toml` runs no `cargo` step, so its image
 * carries no toolchain and neither WASM runner either — they exist only to run
 * the crate's WASM targets.
 */
export const dockerfile = (rust: boolean): string => [
    header,
    from,
    apt(rust),
    nodeBlock,
    denoBlock,
    bunBlock,
    ...(rust ? [rustBlock, wasmtimeBlock, wasmerBlock] : []),
    playwrightBlock,
    fjsBlock,
    workspace,
].join('\n\n') + '\n'

/** Tag the CI jobs build the image under, matching docker/README.md. */
const tag = 'functionalscript' as const

// Every tool the image exists to provide, asked for its version. A build that
// succeeds while leaving a tool off `PATH` — the wrong install prefix, an
// archive whose layout changed — still fails here.
const smokeTest = (rust: boolean): string => [
    ...[
        'node',
        'npm',
        'deno',
        'bun',
        ...(rust ? ['rustc', 'cargo', 'wasmtime', 'wasmer'] : []),
        'playwright',
    ].map(tool => `${tool} --version`),
    // The FunctionalScript CLI has no `--version`; `help` is its cheapest
    // command that exits zero.
    'fjs help',
].join(' && ')

/**
 * Shell resolving `$ref`: the image published for exactly this Dockerfile on
 * exactly this architecture.
 *
 * The tag is the hash of the generated file, so it covers every input that
 * shapes the image — version pins, package list, install commands alike — and
 * needs no maintenance when one of them changes shape rather than value. The
 * registry comes from `$GITHUB_REPOSITORY` (lowercased, as GHCR requires), so
 * a fork publishes into its own namespace instead of failing against ours.
 */
const resolveRef: readonly string[] = [
    'image="ghcr.io/${GITHUB_REPOSITORY,,}/ci"',
    'tag="$(sha256sum docker/Dockerfile | cut -d\' \' -f1)-$(dpkg --print-architecture)"',
    'ref="$image:$tag"',
]

/**
 * Builds the image only when the registry has no copy for this Dockerfile.
 *
 * Any failure of `manifest inspect` counts as a miss — including the 401 a
 * fork PR gets while the package is private — so the worst case is a slow
 * build rather than a broken job.
 */
const buildIfMissing: string = [
    ...resolveRef,
    'echo "image: $ref"',
    'if docker manifest inspect "$ref" > /dev/null 2>&1; then',
    `  docker pull "$ref" && docker tag "$ref" ${tag}`,
    'else',
    `  docker build -t ${tag} -t "$ref" ./docker`,
    'fi',
].join('\n')

/**
 * Publishes the image so later runs, and the jobs that will run inside it, can
 * skip the build. Pushing an image that was pulled rather than built is a
 * no-op: every layer already exists under that digest.
 */
const push: string = [
    ...resolveRef,
    'echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin',
    'docker push "$ref"',
].join('\n')

/**
 * A pull request from a fork gets a read-only token whatever the job asks for,
 * so pushing there would fail; such a run builds and verifies without
 * publishing. A fork's own runs are not affected — `$GITHUB_REPOSITORY` is the
 * fork, and its token can write to its own packages.
 */
const canPush = "github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository" as const

const dockerJob = (rust: boolean) => (runsOn: Image): Job => ({
    'runs-on': runsOn,
    // `packages: write` is scoped to this job rather than the workflow, so no
    // other job carries a token that can publish.
    permissions: {
        contents: 'read',
        packages: 'write',
    },
    steps: toSteps([
        test({ run: buildIfMissing }),
        test({ run: `docker run --rm ${tag} bash -c "${smokeTest(rust)}"` }),
        test({
            run: push,
            if: canPush,
            env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
        }),
    ]),
})

/**
 * One build job per architecture. Each GitHub-hosted runner builds natively for
 * its own — the image picks its architecture up from `dpkg` at build time — so
 * no cross-architecture emulation is involved. A single multi-platform build
 * would be correct but would emulate the foreign half, which for a Rust
 * toolchain install and three browser downloads is the worst case for QEMU.
 *
 * A full build takes around fifteen minutes, which is why it is conditional:
 * the image is published to GHCR under the hash of the Dockerfile that
 * produced it, so a run whose Dockerfile is unchanged pulls in seconds and
 * only a genuine change to the image pays for a build.
 */
export const dockerJobs = (rust: boolean): Jobs => ({
    'docker-intel': dockerJob(rust)(images.ubuntu.intel),
    'docker-arm': dockerJob(rust)(images.ubuntu.arm),
})
