/**
 * Dockerfile generator: renders the contents of `docker/Dockerfile` from the
 * version pins in `../config/module.f.ts` — the same source the GitHub Actions
 * workflow is generated from, so the image and CI never drift apart.
 *
 * Nothing enters the image unpinned. The base image is referenced by digest,
 * `apt` resolves against a dated archive snapshot, every tool comes from a
 * version-specific release URL, and every downloaded archive is checked
 * against a committed SHA-256 — a release asset can be replaced under its tag,
 * so the URL alone is not an integrity guarantee. The exceptions are the two
 * npm-installed CLIs, pinned to exact versions and integrity-checked by npm
 * against the registry rather than by a committed hash.
 *
 * @module
 */
import { actions, bun, deno, dockerBase, dockerSnapshot, functionalscript, node, playwright, rustComponents, rustup, sha256, wasmer, wasmtime } from '../config/module.f.ts'
import { browsers } from '../playwright/module.f.ts'
import { wasmTargets } from '../rust/module.f.ts'

/** One value per architecture the image supports, keyed as `dpkg` names them. */
export type ArchNames = {
    readonly amd64: string
    readonly arm64: string
}

const { entries } = Object

/** A `RUN` instruction whose commands are chained with `&&`, one per line. */
const run = (commands: readonly string[]): string =>
    `RUN ${commands.join(' \\\n    && ')}`

/**
 * Commands setting `$arch` from `dpkg`, then one shell variable per entry of
 * `vars` to its value for that architecture. An unsupported architecture fails
 * the build instead of downloading from a URL assembled out of a wrong name.
 */
const arch = (vars: { readonly [name in string]: ArchNames }): readonly string[] => {
    const set = (a: keyof ArchNames): string =>
        entries(vars).map(([name, value]) => `${name}=${value[a]}`).join('; ')
    return [
        'arch="$(dpkg --print-architecture)"',
        `case "$arch" in amd64) ${set('amd64')} ;; arm64) ${set('arm64')} ;; *) echo "unsupported architecture: $arch" >&2; exit 1 ;; esac`,
    ]
}

/** Checks a downloaded file against the SHA-256 held in `$<name>`. */
const verify = (name: string, file: string): string =>
    `echo "$${name}  ${file}" | sha256sum -c -`

const env = (name: string, value: string): string => `ENV ${name}=${value}`

/** One documented block of instructions: a `#` comment, then the instructions. */
const block = (comment: string, instructions: readonly string[]): string =>
    [`# ${comment}`, ...instructions].join('\n')

const release = (repo: string, tag: string): string =>
    `https://github.com/${repo}/releases/download/${tag}`

const header = [
    '# Generated by `fjs ci` from fjs/ci/docker/module.f.ts. Do not edit by hand.',
    '#',
    '# Every version below is pinned in fjs/ci/config/module.f.ts, the same source',
    '# .github/workflows/ci.yml is generated from. Change a pin there and rerun',
    '# `npm run ci-update`; CI fails when the committed files no longer match.',
].join('\n')

const from = block(
    'Base image by digest: the distribution the `ubuntu-26.04` runners use.',
    [
        `FROM ${dockerBase}`,
        // `-e` and `pipefail` make a failing stage of the checksum pipeline
        // below fail the build instead of being masked by the exit code of the
        // last command.
        'SHELL ["/bin/bash", "-euo", "pipefail", "-c"]',
    ])

const packages: readonly string[] = [
    'build-essential',
    'ca-certificates',
    'curl',
    'git',
    'gnupg',
    'libssl-dev',
    'pkg-config',
    'unzip',
    'xz-utils',
]

// `apt` reaches the snapshot service over HTTPS (it redirects there from
// HTTP), but the base image ships no CA bundle — `ca-certificates` is one of
// the packages installed below. Rather than fetch a trust anchor from the
// unpinned live archive first, peer verification is disabled for that one host
// until `ca-certificates` lands: integrity of the packages comes from the
// archive's GPG signature, checked by the `gpgv` and `ubuntu-keyring` the base
// image does ship, which is the same guarantee a plain-HTTP mirror gives.
const noTlsVerify = '/etc/apt/apt.conf.d/99snapshot-bootstrap'

const apt = block(
    'Build prerequisites, resolved against a dated archive snapshot so that a rebuild installs the same packages.',
    [
        env('UBUNTU_SNAPSHOT', dockerSnapshot),
        env('DEBIAN_FRONTEND', 'noninteractive'),
        run([
            `echo 'Acquire::https::snapshot.ubuntu.com::Verify-Peer "false";' > ${noTlsVerify}`,
            // `sed` fails the build if the base image ever stops using deb822
            // sources, rather than silently leaving `apt` unpinned.
            'sed -i "s|^URIs: .*|URIs: https://snapshot.ubuntu.com/ubuntu/$UBUNTU_SNAPSHOT|" /etc/apt/sources.list.d/ubuntu.sources',
            'apt-get update',
            `apt-get install -y --no-install-recommends ${packages.join(' ')}`,
            // Every later `apt` call — Playwright's `install --with-deps` among
            // them — verifies the certificate normally.
            `rm ${noTlsVerify}`,
            'rm -rf /var/lib/apt/lists/*',
        ]),
    ])

const nodeBlock = block(
    'Node.js: official build.',
    [
        env('NODE_VERSION', node.default),
        run([
            ...arch({
                node_arch: { amd64: 'x64', arm64: 'arm64' },
                node_sha256: sha256.node,
            }),
            'node_archive="node-v$NODE_VERSION-linux-$node_arch.tar.xz"',
            'curl -fsSLo "/tmp/$node_archive" "https://nodejs.org/dist/v$NODE_VERSION/$node_archive"',
            verify('node_sha256', '/tmp/$node_archive'),
            'tar -xJf "/tmp/$node_archive" -C /usr/local --strip-components=1 --no-same-owner',
            'rm "/tmp/$node_archive"',
        ]),
    ])

const denoBlock = block(
    'Deno: official release archive.',
    [
        env('DENO_VERSION', deno),
        run([
            ...arch({
                deno_arch: { amd64: 'x86_64-unknown-linux-gnu', arm64: 'aarch64-unknown-linux-gnu' },
                deno_sha256: sha256.deno,
            }),
            `curl -fsSLo /tmp/deno.zip "${release('denoland/deno', 'v$DENO_VERSION')}/deno-$deno_arch.zip"`,
            verify('deno_sha256', '/tmp/deno.zip'),
            'unzip -q -d /usr/local/bin /tmp/deno.zip',
            'chmod +x /usr/local/bin/deno',
            'rm /tmp/deno.zip',
        ]),
    ])

const bunBlock = block(
    'Bun: official release archive.',
    [
        env('BUN_VERSION', bun),
        run([
            ...arch({
                bun_arch: { amd64: 'x64', arm64: 'aarch64' },
                bun_sha256: sha256.bun,
            }),
            `curl -fsSLo /tmp/bun.zip "${release('oven-sh/bun', 'bun-v$BUN_VERSION')}/bun-linux-$bun_arch.zip"`,
            verify('bun_sha256', '/tmp/bun.zip'),
            'unzip -q -d /tmp /tmp/bun.zip',
            'mv "/tmp/bun-linux-$bun_arch/bun" /usr/local/bin/bun',
            'chmod +x /usr/local/bin/bun',
            'rm -rf /tmp/bun.zip "/tmp/bun-linux-$bun_arch"',
        ]),
    ])

const rustBlock = block(
    'Rust: pinned rustup installs the pinned toolchain, its components and targets.',
    [
        env('RUSTUP_VERSION', rustup),
        env('RUST_VERSION', actions['dtolnay/rust-toolchain']),
        env('RUSTUP_HOME', '/usr/local/rustup'),
        env('CARGO_HOME', '/usr/local/cargo'),
        env('PATH', '/usr/local/cargo/bin:$PATH'),
        run([
            ...arch({
                rust_host: { amd64: 'x86_64-unknown-linux-gnu', arm64: 'aarch64-unknown-linux-gnu' },
                rustup_sha256: sha256.rustup,
            }),
            'curl -fsSLo /tmp/rustup-init "https://static.rust-lang.org/rustup/archive/$RUSTUP_VERSION/$rust_host/rustup-init"',
            verify('rustup_sha256', '/tmp/rustup-init'),
            'chmod +x /tmp/rustup-init',
            // `--component` and `--target` take one comma-separated list each;
            // space-separated values are rejected as unexpected arguments.
            `/tmp/rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --component ${rustComponents} --target ${wasmTargets.join(',')}`,
            'rm /tmp/rustup-init',
            // Non-root users of the image need a writable toolchain directory
            // to add a target or run `cargo` against a fresh registry cache.
            'chmod -R a+w $RUSTUP_HOME $CARGO_HOME',
        ]),
    ])

const wasmtimeBlock = block(
    'Wasmtime: runner for the WASM targets.',
    [
        env('WASMTIME_VERSION', wasmtime),
        run([
            ...arch({
                wasmtime_arch: { amd64: 'x86_64', arm64: 'aarch64' },
                wasmtime_sha256: sha256.wasmtime,
            }),
            'wasmtime_dir="wasmtime-v$WASMTIME_VERSION-$wasmtime_arch-linux"',
            `curl -fsSLo /tmp/wasmtime.tar.xz "${release('bytecodealliance/wasmtime', 'v$WASMTIME_VERSION')}/$wasmtime_dir.tar.xz"`,
            verify('wasmtime_sha256', '/tmp/wasmtime.tar.xz'),
            'tar -xJf /tmp/wasmtime.tar.xz -C /tmp',
            'mv "/tmp/$wasmtime_dir/wasmtime" /usr/local/bin/wasmtime',
            'rm -rf /tmp/wasmtime.tar.xz "/tmp/$wasmtime_dir"',
        ]),
    ])

const wasmerBlock = block(
    'Wasmer: runner used by .cargo/config.wasmer.toml, including the threads target.',
    [
        env('WASMER_VERSION', wasmer),
        env('WASMER_DIR', '/usr/local'),
        run([
            ...arch({
                wasmer_arch: { amd64: 'amd64', arm64: 'aarch64' },
                wasmer_sha256: sha256.wasmer,
            }),
            `curl -fsSLo /tmp/wasmer.tar.gz "${release('wasmerio/wasmer', 'v$WASMER_VERSION')}/wasmer-linux-$wasmer_arch.tar.gz"`,
            verify('wasmer_sha256', '/tmp/wasmer.tar.gz'),
            'tar -xzf /tmp/wasmer.tar.gz -C /usr/local',
            'rm /tmp/wasmer.tar.gz',
        ]),
    ])

const playwrightBlock = block(
    'Playwright and its browsers. Browser builds are pinned by the Playwright version.',
    [
        env('PLAYWRIGHT_VERSION', playwright),
        // Browsers are installed outside `$HOME` so every user of the image
        // finds them, not just the one that built it.
        env('PLAYWRIGHT_BROWSERS_PATH', '/usr/local/ms-playwright'),
        run([
            'npm install -g playwright@$PLAYWRIGHT_VERSION',
            `playwright install --with-deps ${browsers.join(' ')}`,
            'rm -rf /var/lib/apt/lists/*',
        ]),
    ])

const fjsBlock = block(
    'The published FunctionalScript CLI (`fjs`) used by the generated smoke tests.',
    [
        env('FUNCTIONALSCRIPT_VERSION', functionalscript),
        run(['npm install -g functionalscript@$FUNCTIONALSCRIPT_VERSION']),
    ])

const workspace = block(
    'The repository is mounted or checked out here; the image itself carries only tools.',
    [
        'WORKDIR /workspace',
        'CMD ["bash"]',
    ])

/** The full text of the generated `docker/Dockerfile`. */
export const dockerfile: string = [
    header,
    from,
    apt,
    nodeBlock,
    denoBlock,
    bunBlock,
    rustBlock,
    wasmtimeBlock,
    wasmerBlock,
    playwrightBlock,
    fjsBlock,
    workspace,
].join('\n\n') + '\n'
