/**
 * Dockerfile generator: renders the contents of `docker/Dockerfile` from the
 * version pins in `../config/module.f.ts` — the same source the GitHub Actions
 * workflow is generated from, so the image and CI never drift apart.
 *
 * Every tool is fetched from an immutable, version-specific release URL. There
 * is no `latest` tag, no rolling base-image tag, and no unpinned installer
 * script: the exact versions are visible in the generated text, and a rebuild
 * of an unchanged Dockerfile installs the same versions it installed before.
 *
 * @module
 */
import { actions, bun, deno, dockerBase, functionalscript, node, playwright, rustup, wasmer, wasmtime } from '../config/module.f.ts'
import { browsers } from '../playwright/module.f.ts'
import { wasmTargets } from '../rust/module.f.ts'

/** A tool's own spelling of the architectures the image supports. */
export type ArchNames = {
    /** Name used for `dpkg --print-architecture` = `amd64`. */
    readonly amd64: string
    /** Name used for `dpkg --print-architecture` = `arm64`. */
    readonly arm64: string
}

/** A `RUN` instruction whose commands are chained with `&&`, one per line. */
const run = (commands: readonly string[]): string =>
    `RUN ${commands.join(' \\\n    && ')}`

/**
 * Commands setting `$arch` from `dpkg` and `$<name>` to the tool's spelling of
 * it. An unsupported architecture fails the build instead of downloading from
 * a URL assembled out of a wrong name.
 */
const arch = (name: string, { amd64, arm64 }: ArchNames): readonly string[] => [
    'arch="$(dpkg --print-architecture)"',
    `case "$arch" in amd64) ${name}=${amd64} ;; arm64) ${name}=${arm64} ;; *) echo "unsupported architecture: $arch" >&2; exit 1 ;; esac`,
]

const env = (name: string, value: string): string => `ENV ${name}=${value}`

/** One documented block of instructions: a `#` comment, then the instructions. */
const block = (comment: string, instructions: readonly string[]): string =>
    [`# ${comment}`, ...instructions].join('\n')

const release = (repo: string, tag: string): string =>
    `https://github.com/${repo}/releases/download/${tag}`

const header = [
    '# Generated by `fjs ci` from fjs/ci/docker/module.f.ts. Do not edit by hand.',
    '#',
    '# Every version below is pinned in fjs/ci/config/module.f.ts, the same source',
    '# .github/workflows/ci.yml is generated from. Change a pin there and rerun',
    '# `npm run ci-update`; CI fails when the committed files no longer match.',
].join('\n')

const from = block(
    'Date-stamped snapshot of the distribution the `ubuntu-26.04` runners use.',
    [
        `FROM ${dockerBase}`,
        // `-e` and `pipefail` make a failing stage of the checksum pipeline
        // below fail the build instead of being masked by the exit code of the
        // last command.
        'SHELL ["/bin/bash", "-euo", "pipefail", "-c"]',
    ])

const packages: readonly string[] = [
    'build-essential',
    'ca-certificates',
    'curl',
    'git',
    'gnupg',
    'libssl-dev',
    'pkg-config',
    'unzip',
    'xz-utils',
]

const apt = block(
    'Build prerequisites. Their versions come from the pinned base-image snapshot.',
    [
        env('DEBIAN_FRONTEND', 'noninteractive'),
        run([
            'apt-get update',
            `apt-get install -y --no-install-recommends ${packages.join(' ')}`,
            'rm -rf /var/lib/apt/lists/*',
        ]),
    ])

const nodeBlock = block(
    'Node.js: official build, verified against the release SHASUMS256.txt.',
    [
        env('NODE_VERSION', node.default),
        run([
            ...arch('node_arch', { amd64: 'x64', arm64: 'arm64' }),
            'node_url="https://nodejs.org/dist/v$NODE_VERSION"',
            'node_archive="node-v$NODE_VERSION-linux-$node_arch.tar.xz"',
            'curl -fsSLo "/tmp/$node_archive" "$node_url/$node_archive"',
            'curl -fsSL "$node_url/SHASUMS256.txt" | grep " $node_archive$" | (cd /tmp && sha256sum -c -)',
            'tar -xJf "/tmp/$node_archive" -C /usr/local --strip-components=1 --no-same-owner',
            'rm "/tmp/$node_archive"',
        ]),
    ])

const denoBlock = block(
    'Deno: official release archive.',
    [
        env('DENO_VERSION', deno),
        run([
            ...arch('deno_arch', { amd64: 'x86_64-unknown-linux-gnu', arm64: 'aarch64-unknown-linux-gnu' }),
            `curl -fsSLo /tmp/deno.zip "${release('denoland/deno', 'v$DENO_VERSION')}/deno-$deno_arch.zip"`,
            'unzip -q -d /usr/local/bin /tmp/deno.zip',
            'chmod +x /usr/local/bin/deno',
            'rm /tmp/deno.zip',
        ]),
    ])

const bunBlock = block(
    'Bun: official release archive.',
    [
        env('BUN_VERSION', bun),
        run([
            ...arch('bun_arch', { amd64: 'x64', arm64: 'aarch64' }),
            `curl -fsSLo /tmp/bun.zip "${release('oven-sh/bun', 'bun-v$BUN_VERSION')}/bun-linux-$bun_arch.zip"`,
            'unzip -q -d /tmp /tmp/bun.zip',
            'mv "/tmp/bun-linux-$bun_arch/bun" /usr/local/bin/bun',
            'chmod +x /usr/local/bin/bun',
            'rm -rf /tmp/bun.zip "/tmp/bun-linux-$bun_arch"',
        ]),
    ])

const rustBlock = block(
    'Rust: pinned rustup installs the pinned toolchain, its components and targets.',
    [
        env('RUSTUP_VERSION', rustup),
        env('RUST_VERSION', actions['dtolnay/rust-toolchain']),
        env('RUSTUP_HOME', '/usr/local/rustup'),
        env('CARGO_HOME', '/usr/local/cargo'),
        env('PATH', '/usr/local/cargo/bin:$PATH'),
        run([
            ...arch('rust_host', { amd64: 'x86_64-unknown-linux-gnu', arm64: 'aarch64-unknown-linux-gnu' }),
            'curl -fsSLo /tmp/rustup-init "https://static.rust-lang.org/rustup/archive/$RUSTUP_VERSION/$rust_host/rustup-init"',
            'chmod +x /tmp/rustup-init',
            `/tmp/rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --component rustfmt clippy --target ${wasmTargets.join(' ')}`,
            'rm /tmp/rustup-init',
            // Non-root users of the image need a writable toolchain directory
            // to add a target or run `cargo` against a fresh registry cache.
            'chmod -R a+w $RUSTUP_HOME $CARGO_HOME',
        ]),
    ])

const wasmtimeBlock = block(
    'Wasmtime: runner for the WASM targets.',
    [
        env('WASMTIME_VERSION', wasmtime),
        run([
            ...arch('wasmtime_arch', { amd64: 'x86_64', arm64: 'aarch64' }),
            'wasmtime_dir="wasmtime-v$WASMTIME_VERSION-$wasmtime_arch-linux"',
            `curl -fsSLo /tmp/wasmtime.tar.xz "${release('bytecodealliance/wasmtime', 'v$WASMTIME_VERSION')}/$wasmtime_dir.tar.xz"`,
            'tar -xJf /tmp/wasmtime.tar.xz -C /tmp',
            'mv "/tmp/$wasmtime_dir/wasmtime" /usr/local/bin/wasmtime',
            'rm -rf /tmp/wasmtime.tar.xz "/tmp/$wasmtime_dir"',
        ]),
    ])

const wasmerBlock = block(
    'Wasmer: runner used by .cargo/config.wasmer.toml, including the threads target.',
    [
        env('WASMER_VERSION', wasmer),
        env('WASMER_DIR', '/usr/local'),
        run([
            ...arch('wasmer_arch', { amd64: 'amd64', arm64: 'aarch64' }),
            `curl -fsSLo /tmp/wasmer.tar.gz "${release('wasmerio/wasmer', 'v$WASMER_VERSION')}/wasmer-linux-$wasmer_arch.tar.gz"`,
            'tar -xzf /tmp/wasmer.tar.gz -C /usr/local',
            'rm /tmp/wasmer.tar.gz',
        ]),
    ])

const playwrightBlock = block(
    'Playwright and its browsers. Browser builds are pinned by the Playwright version.',
    [
        env('PLAYWRIGHT_VERSION', playwright),
        // Browsers are installed outside `$HOME` so every user of the image
        // finds them, not just the one that built it.
        env('PLAYWRIGHT_BROWSERS_PATH', '/usr/local/ms-playwright'),
        run([
            'npm install -g playwright@$PLAYWRIGHT_VERSION',
            `playwright install --with-deps ${browsers.join(' ')}`,
            'rm -rf /var/lib/apt/lists/*',
        ]),
    ])

const fjsBlock = block(
    'The published FunctionalScript CLI (`fjs`) used by the generated smoke tests.',
    [
        env('FUNCTIONALSCRIPT_VERSION', functionalscript),
        run(['npm install -g functionalscript@$FUNCTIONALSCRIPT_VERSION']),
    ])

const workspace = block(
    'The repository is mounted or checked out here; the image itself carries only tools.',
    [
        'WORKDIR /workspace',
        'CMD ["bash"]',
    ])

/** The full text of the generated `docker/Dockerfile`. */
export const dockerfile: string = [
    header,
    from,
    apt,
    nodeBlock,
    denoBlock,
    bunBlock,
    rustBlock,
    wasmtimeBlock,
    wasmerBlock,
    playwrightBlock,
    fjsBlock,
    workspace,
].join('\n\n') + '\n'
