import { dockerfile, dockerJobs } from './module.f.ts'
import { actions, bun, deno, dockerBase, dockerSnapshot, functionalscript, images, node, playwright, rustComponents, rustup, sha256, wasmer, wasmtime } from '../config/module.f.ts'
import { browsers } from '../playwright/module.f.ts'
import { i686Linux, wasmTargets } from '../rust/module.f.ts'
import { assert, assertEq } from '../../asserts/module.f.ts'

const { entries } = Object

/** The image of a project with a `Cargo.toml`, i.e. this repository's own. */
const withRust: string = dockerfile(true)

const has = (s: string, msg: string): void => assert(withRust.includes(s), msg)

const hasNot = (s: string, msg: string): void => assert(!withRust.includes(s), msg)

const lines: readonly string[] = withRust.split('\n')

const instructions: readonly string[] =
    lines.filter(line => line !== '' && !line.startsWith('#') && !line.startsWith(' '))

export const proof = {
    generatedHeader: () => {
        assert(withRust.startsWith('# Generated by `fjs ci`'), 'expected a generated-file header')
        has('fjs/ci/config/module.f.ts', 'expected a pointer to the version pins')
    },
    base: () => {
        has(`FROM ${dockerBase}`, 'expected the pinned base image')
        // A tag can be repointed, a digest cannot.
        has('FROM ubuntu:resolute-20260707@sha256:', 'expected the base image pinned by digest')
    },
    pinnedVersions: () => {
        for (const [name, version] of [
            ['UBUNTU_SNAPSHOT', dockerSnapshot],
            ['NODE_VERSION', node.default],
            ['DENO_VERSION', deno],
            ['BUN_VERSION', bun],
            ['RUSTUP_VERSION', rustup],
            ['RUST_VERSION', actions['dtolnay/rust-toolchain']],
            ['WASMTIME_VERSION', wasmtime],
            ['WASMER_VERSION', wasmer],
            ['PLAYWRIGHT_VERSION', playwright],
            ['FUNCTIONALSCRIPT_VERSION', functionalscript],
        ] as const) {
            has(`ENV ${name}=${version}`, `expected ${name} pinned to ${version}`)
        }
    },
    aptSnapshot: () => {
        // Without this the base image's digest pins only the initial
        // filesystem: `apt-get update` would resolve whatever the archive
        // holds that day.
        has('snapshot.ubuntu.com/ubuntu/$UBUNTU_SNAPSHOT', 'expected apt pinned to the archive snapshot')
        has('/etc/apt/sources.list.d/ubuntu.sources', 'expected the deb822 sources to be repointed')
        // No package may be resolved before the pin — not even the trust
        // anchor, which is why peer verification is relaxed for that one host
        // instead, and only until `ca-certificates` is installed.
        assertEq(withRust.split('apt-get update').length - 1, 1, 'expected exactly one apt-get update')
        assert(
            withRust.indexOf('snapshot.ubuntu.com/ubuntu/$UBUNTU_SNAPSHOT') < withRust.indexOf('apt-get update'),
            'expected every package to resolve after the snapshot pin')
        has('Acquire::https::snapshot.ubuntu.com::Verify-Peer "false"', 'expected the relaxation scoped to the snapshot host')
        assert(
            withRust.indexOf('rm /etc/apt/apt.conf.d/99snapshot-bootstrap') > withRust.indexOf('ca-certificates'),
            'expected the relaxation removed once ca-certificates is installed')
    },
    noFloatingVersions: () => {
        // A tool installed from a `latest` URL, a rolling image tag, or an
        // unpinned installer script would silently change what the image
        // contains between two builds of the same file.
        hasNot('latest', 'unexpected floating version')
        hasNot('archive.ubuntu.com', 'unexpected unpinned apt archive')
        hasNot('ports.ubuntu.com', 'unexpected unpinned apt archive')
        hasNot(`FROM ${dockerBase.split(':')[0]}\n`, 'unexpected untagged base image')
        hasNot('rustup.rs', 'unexpected unpinned rustup installer script')
        hasNot('deno.land/x/install', 'unexpected unpinned Deno installer script')
        hasNot('bun.sh/install', 'unexpected unpinned Bun installer script')
        hasNot('wasmtime.dev/install.sh', 'unexpected unpinned Wasmtime installer script')
        hasNot('get.wasmer.io', 'unexpected unpinned Wasmer installer script')
    },
    // A version-specific URL is not immutable — a release asset can be replaced
    // under its tag — so every archive is checked against a committed hash.
    checksums: () => {
        const downloads = withRust.split('curl -fsSLo').length - 1
        assertEq(downloads, 6, 'expected six downloaded archives')
        assertEq(withRust.split('sha256sum -c -').length - 1, downloads, 'expected every download verified')
        for (const [tool, { amd64, arm64 }] of entries(sha256)) {
            has(`${tool}_sha256=${amd64}`, `expected the committed amd64 hash of ${tool}`)
            has(`${tool}_sha256=${arm64}`, `expected the committed arm64 hash of ${tool}`)
        }
    },
    everyToolInstalled: () => {
        has('nodejs.org/dist/v$NODE_VERSION', 'expected the pinned Node.js archive')
        has('denoland/deno/releases/download/v$DENO_VERSION', 'expected the pinned Deno release')
        has('oven-sh/bun/releases/download/bun-v$BUN_VERSION', 'expected the pinned Bun release')
        has('rustup/archive/$RUSTUP_VERSION', 'expected the pinned rustup installer')
        has('--default-toolchain $RUST_VERSION', 'expected the pinned Rust toolchain')
        has('bytecodealliance/wasmtime/releases/download/v$WASMTIME_VERSION', 'expected the pinned Wasmtime release')
        has('wasmerio/wasmer/releases/download/v$WASMER_VERSION', 'expected the pinned Wasmer release')
        has('npm install -g playwright@$PLAYWRIGHT_VERSION', 'expected the pinned Playwright install')
        has('npm install -g functionalscript@$FUNCTIONALSCRIPT_VERSION', 'expected the pinned FunctionalScript CLI')
    },
    ciParity: () => {
        for (const target of wasmTargets) {
            has(target, `expected the WASM target ${target}`)
        }
        for (const browser of browsers) {
            has(browser, `expected the browser ${browser}`)
        }
        // `rustup-init` takes one comma-separated list per flag, the same form
        // the workflow's `dtolnay/rust-toolchain` step uses.
        has(`--component ${rustComponents} `, 'expected the Rust components CI lints with')
        has('--target $rust_targets', 'expected the targets chosen per architecture')
        has(`rust_targets=${wasmTargets.join(',')}`, 'expected the WASM targets as one comma-separated list')
    },
    everyArchitecture: () => {
        // `arm64` covers the `ubuntu-26.04-arm` runners and Apple Silicon
        // workstations, `amd64` the Intel ones: one switch per downloaded
        // tool, plus the one selecting Intel-only packages.
        const switches = withRust.split('case "$arch" in').length - 1
        assertEq(switches, 7, 'expected an architecture switch per download, plus the package selection')
        assertEq(withRust.split('amd64)').length - 1, switches, 'expected every switch to handle amd64')
        assertEq(withRust.split('arm64)').length - 1, switches, 'expected every switch to handle arm64')
        has('unsupported architecture: $arch', 'expected unsupported architectures to fail the build')
    },
    // The Ubuntu Intel job cross-compiles to 32-bit, so an image meant to host
    // it needs the target and its system headers — on Intel only, where they
    // exist.
    i686: () => {
        has(`rust_targets=${[...wasmTargets, i686Linux.target].join(',')} ;; arm64)`, 'expected the i686 target on amd64 only')
        has(`extra_packages=${i686Linux.package} ;; arm64) extra_packages= `, 'expected the 32-bit headers on amd64 only')
        has('--no-install-recommends build-essential', 'expected the common packages to stay unconditional')
        has(' $extra_packages', 'expected the architecture-specific packages to be installed')
    },
    shell: () => {
        // `pipefail` keeps the checksum pipeline from passing on a failed
        // download, `-e` stops a `RUN` at its first failing command.
        has('SHELL ["/bin/bash", "-euo", "pipefail", "-c"]', 'expected a strict shell')
    },
    // A project with no `Cargo.toml` runs no `cargo` step, so its image gets no
    // toolchain and no WASM runner — they exist only for the crate's targets.
    withoutRust: () => {
        const plain = dockerfile(false)
        for (const absent of ['rustup', 'RUST_VERSION', 'wasmtime', 'wasmer', 'cargo', i686Linux.package, i686Linux.target]) {
            assert(!plain.includes(absent), `unexpected ${absent} in a Rust-free image`)
        }
        // Nothing is architecture-specific outside the downloads once the Rust
        // layers are gone, so the package list needs no switch of its own.
        assertEq(plain.split('case "$arch" in').length - 1, 3, 'expected a switch per download and no more')
        for (const present of ['NODE_VERSION', 'DENO_VERSION', 'BUN_VERSION', 'PLAYWRIGHT_VERSION', 'UBUNTU_SNAPSHOT']) {
            assert(plain.includes(present), `expected ${present} in a Rust-free image`)
        }
        assertEq(plain.split('curl -fsSLo').length - 1, 3, 'expected only Node, Deno and Bun downloaded')
        assertEq(plain.split('sha256sum -c -').length - 1, 3, 'expected every remaining download verified')
    },
    buildJobs: {
        // One native job per architecture: a single multi-platform build would
        // emulate the foreign half of a Rust toolchain and three browsers.
        perArchitecture: () => {
            const jobs = dockerJobs(true)
            assertEq(Object.keys(jobs).length, 2, 'expected one build job per architecture')
            assertEq(jobs['docker-intel']?.['runs-on'], images.ubuntu.intel, 'expected the Intel runner')
            assertEq(jobs['docker-arm']?.['runs-on'], images.ubuntu.arm, 'expected the ARM runner')
        },
        rustFreeSmokeTest: () => {
            for (const [id, job] of entries(dockerJobs(false))) {
                const smoke = (job?.steps ?? []).flatMap(s => s.run === undefined ? [] : [s.run]).find(r => r.startsWith('docker run'))
                assert(smoke !== undefined, `expected ${id} to run the image`)
                for (const tool of ['rustc', 'cargo', 'wasmtime', 'wasmer']) {
                    assert(!smoke.includes(tool), `unexpected ${tool} check in a Rust-free image`)
                }
                assert(smoke.includes('node --version'), `expected ${id} to still check Node`)
            }
        },
        buildsAndSmokeTests: () => {
            for (const [id, job] of entries(dockerJobs(true))) {
                const runs = (job?.steps ?? []).flatMap(step => step.run === undefined ? [] : [step.run])
                assert(runs.some(r => r === 'docker build -t functionalscript ./docker'), `expected ${id} to build the image`)
                // Checking out is what gives `docker build` its context.
                assert((job?.steps ?? []).some(step => step.uses?.startsWith('actions/checkout') === true), `expected ${id} to check out the repository`)
                const smoke = runs.find(r => r.startsWith('docker run'))
                assert(smoke !== undefined, `expected ${id} to run the image`)
                for (const check of [
                    'node --version',
                    'deno --version',
                    'bun --version',
                    'rustc --version',
                    'cargo --version',
                    'wasmtime --version',
                    'wasmer --version',
                    'playwright --version',
                    // `fjs` has no `--version`, and exits non-zero when given one.
                    'fjs help',
                ]) {
                    assert(smoke.includes(check), `expected ${id} to smoke test with \`${check}\``)
                }
            }
        },
    },
    layout: () => {
        has('WORKDIR /workspace', 'expected the mount point of the repository')
        has('CMD ["bash"]', 'expected an interactive default command')
        assertEq(instructions[0], `FROM ${dockerBase}`, 'expected FROM to be the first instruction')
        assertEq(lines[lines.length - 1], '', 'expected a trailing newline')
    },
}
