import { dockerfile } from './module.f.ts'
import { actions, bun, deno, dockerBase, dockerSnapshot, functionalscript, node, playwright, rustup, wasmer, wasmtime } from '../config/module.f.ts'
import { browsers } from '../playwright/module.f.ts'
import { wasmTargets } from '../rust/module.f.ts'
import { assert, assertEq } from '../../asserts/module.f.ts'

const has = (s: string, msg: string): void => assert(dockerfile.includes(s), msg)

const hasNot = (s: string, msg: string): void => assert(!dockerfile.includes(s), msg)

const lines: readonly string[] = dockerfile.split('\n')

const instructions: readonly string[] =
    lines.filter(line => line !== '' && !line.startsWith('#') && !line.startsWith(' '))

export const proof = {
    generatedHeader: () => {
        assert(dockerfile.startsWith('# Generated by `fjs ci`'), 'expected a generated-file header')
        has('fjs/ci/config/module.f.ts', 'expected a pointer to the version pins')
    },
    base: () => {
        has(`FROM ${dockerBase}`, 'expected the pinned base image')
    },
    pinnedVersions: () => {
        for (const [name, version] of [
            ['UBUNTU_SNAPSHOT', dockerSnapshot],
            ['NODE_VERSION', node.default],
            ['DENO_VERSION', deno],
            ['BUN_VERSION', bun],
            ['RUSTUP_VERSION', rustup],
            ['RUST_VERSION', actions['dtolnay/rust-toolchain']],
            ['WASMTIME_VERSION', wasmtime],
            ['WASMER_VERSION', wasmer],
            ['PLAYWRIGHT_VERSION', playwright],
            ['FUNCTIONALSCRIPT_VERSION', functionalscript],
        ] as const) {
            has(`ENV ${name}=${version}`, `expected ${name} pinned to ${version}`)
        }
    },
    aptSnapshot: () => {
        // Without this the base-image tag pins only the initial filesystem:
        // `apt-get update` would resolve whatever the archive holds that day.
        has('snapshot.ubuntu.com/ubuntu/$UBUNTU_SNAPSHOT', 'expected apt pinned to the archive snapshot')
        has('/etc/apt/sources.list.d/ubuntu.sources', 'expected the deb822 sources to be repointed')
        // The unpinned bootstrap transaction installs the TLS trust anchor the
        // snapshot service needs, and nothing else — every build prerequisite
        // is resolved after the pin.
        has('--no-install-recommends ca-certificates \\', 'expected the bootstrap to install only ca-certificates')
        assert(
            dockerfile.indexOf('snapshot.ubuntu.com') < dockerfile.indexOf('build-essential'),
            'expected the build prerequisites to resolve after the snapshot pin')
    },
    noFloatingVersions: () => {
        // A tool installed from a `latest` URL, a rolling image tag, or an
        // unpinned installer script would silently change what the image
        // contains between two builds of the same file.
        hasNot('latest', 'unexpected floating version')
        hasNot('archive.ubuntu.com', 'unexpected unpinned apt archive')
        hasNot('ports.ubuntu.com', 'unexpected unpinned apt archive')
        hasNot(`FROM ${dockerBase.split(':')[0]}\n`, 'unexpected untagged base image')
        hasNot('rustup.rs', 'unexpected unpinned rustup installer script')
        hasNot('deno.land/x/install', 'unexpected unpinned Deno installer script')
        hasNot('bun.sh/install', 'unexpected unpinned Bun installer script')
        hasNot('wasmtime.dev/install.sh', 'unexpected unpinned Wasmtime installer script')
        hasNot('get.wasmer.io', 'unexpected unpinned Wasmer installer script')
    },
    everyToolInstalled: () => {
        has('nodejs.org/dist/v$NODE_VERSION', 'expected the pinned Node.js archive')
        has('SHASUMS256.txt', 'expected the Node.js checksum verification')
        has('denoland/deno/releases/download/v$DENO_VERSION', 'expected the pinned Deno release')
        has('oven-sh/bun/releases/download/bun-v$BUN_VERSION', 'expected the pinned Bun release')
        has('rustup/archive/$RUSTUP_VERSION', 'expected the pinned rustup installer')
        has('--default-toolchain $RUST_VERSION', 'expected the pinned Rust toolchain')
        has('bytecodealliance/wasmtime/releases/download/v$WASMTIME_VERSION', 'expected the pinned Wasmtime release')
        has('wasmerio/wasmer/releases/download/v$WASMER_VERSION', 'expected the pinned Wasmer release')
        has('npm install -g playwright@$PLAYWRIGHT_VERSION', 'expected the pinned Playwright install')
        has('npm install -g functionalscript@$FUNCTIONALSCRIPT_VERSION', 'expected the pinned FunctionalScript CLI')
    },
    ciParity: () => {
        for (const target of wasmTargets) {
            has(target, `expected the WASM target ${target}`)
        }
        for (const browser of browsers) {
            has(browser, `expected the browser ${browser}`)
        }
        has('rustfmt clippy', 'expected the Rust components CI lints with')
    },
    everyArchitecture: () => {
        // `arm64` covers the `ubuntu-26.04-arm` runners and Apple Silicon
        // workstations, `amd64` the Intel ones.
        assertEq(dockerfile.split('case "$arch" in').length - 1, 6, 'expected one architecture switch per downloaded tool')
        assertEq(dockerfile.split('amd64)').length - 1, 6, 'expected amd64 support for every downloaded tool')
        assertEq(dockerfile.split('arm64)').length - 1, 6, 'expected arm64 support for every downloaded tool')
        has('unsupported architecture: $arch', 'expected unsupported architectures to fail the build')
    },
    shell: () => {
        // `pipefail` keeps the checksum pipeline from passing on a failed
        // download, `-e` stops a `RUN` at its first failing command.
        has('SHELL ["/bin/bash", "-euo", "pipefail", "-c"]', 'expected a strict shell')
    },
    layout: () => {
        has('WORKDIR /workspace', 'expected the mount point of the repository')
        has('CMD ["bash"]', 'expected an interactive default command')
        assertEq(instructions[0], `FROM ${dockerBase}`, 'expected FROM to be the first instruction')
        assertEq(lines[lines.length - 1], '', 'expected a trailing newline')
    },
}
