// Generated file.
module.exports = {
  types: {
    nullable: require("./types/nullable/module.f.cjs"),
    array: require("./types/array/module.f.cjs"),
    function: require("./types/function/module.f.cjs"),
    list: require("./types/list/module.f.cjs"),
    btree: require("./types/btree/module.f.cjs"),
    string: require("./types/string/module.f.cjs"),
    map: require("./types/map/module.f.cjs"),
    object: require("./types/object/module.f.cjs"),
    bigint: require("./types/bigint/module.f.cjs"),
    bigfloat: require("./types/bigfloat/module.f.cjs"),
    sorted_list: require("./types/sorted_list/module.f.cjs"),
    number: require("./types/number/module.f.cjs"),
    range: require("./types/range/module.f.cjs"),
    range_map: require("./types/range_map/module.f.cjs"),
    result: require("./types/result/module.f.cjs"),
    string_set: require("./types/string_set/module.f.cjs"),
    sorted_set: require("./types/sorted_set/module.f.cjs"),
    byte_set: require("./types/byte_set/module.f.cjs"),
    nibble_set: require("./types/nibble_set/module.f.cjs"),
  },
  com: require("./com/module.f.cjs"),
  text: require("./text/module.f.cjs"),
  json: require("./json/module.f.cjs"),
  js: {
    tokenizer: require("./js/tokenizer/module.f.cjs"),
  },
  commonjs: require("./commonjs/module.f.cjs"),
  dev: require("./dev/module.f.cjs"),
  djs: require("./djs/module.f.cjs"),
  fsc: require("./fsc/module.f.cjs"),
  fsm: require("./fsm/module.f.cjs"),
  html: require("./html/module.f.cjs"),
  nodejs: require("./nodejs/module.f.cjs"),
  prime_field: require("./prime_field/module.f.cjs"),
  secp: require("./secp/module.f.cjs"),
  sha2: require("./sha2/module.f.cjs"),
}
