/**
 * The expectation of one corpus fixture, as the text of a Rust module, for
 * the Stage 8 comparison (see
 * [callable-function-objects](../../../nanvm-lib/todo/callable-function-objects.md)).
 *
 * It is the FJS interpreter's value of the fixture's `default` export, which
 * `fjs/nanvm/corpus`'s proof ties to Node's, in two layers that fail
 * independently:
 *
 * - `module`, the value as a graph, printed by the compiler's Rust backend as
 *   the object `{ default: <value> }`. It keeps sharing, `bigint`,
 *   `undefined`, `NaN` and `-0`, and it shares the Rust literal emitter with
 *   the compiled fixture;
 * - `JSON`, the UTF-8 bytes of the compiler's own JSON text of the value,
 *   with `-0` written as `0`, or `None` when the value has no JSON form. It
 *   shares nothing with the Rust emitter, which is its use, and is spelled as
 *   numbers so that not even a string literal's escaping is shared.
 *
 * A fixture whose initialization throws is expected to throw: its `module`
 * returns an `Err`, whose value no one compares (an engine's thrown value is
 * its own), its `JSON` is `None`, and its `THROWS` is `true`. Every
 * expectation says `THROWS`, so that a compiled fixture which throws where a
 * value is expected, or the reverse, fails by that record and not by whatever
 * the two sides happen to share.
 *
 * This module is pure. `fjs/nanvm/harness` reads the fixtures and writes the
 * files.
 *
 * @module
 *
 * @import { Result } from '../../types/result/types.ts'
 * @import { EdagValue } from '../../edag/value/types.ts'
 * @import { SourceError } from '../../compiler/transpiler/types.ts'
 * @import { Unknown } from '../../media/datajs/types.ts'
 */

import { toRust } from '../../compiler/rust/module.f.mjs'
import { read } from '../../edag/value/property/module.f.mjs'
import { toData } from '../../edag/value/to_unknown/module.f.mjs'
import { tryJsonStringify } from '../../media/datajs/serializer/module.f.mjs'
import { stringToU8List } from '../../text/utf8/module.f.mjs'
import { toArray } from '../../types/list/module.f.mjs'
import { assertOk } from '../../asserts/module.f.mjs'
import { error, ok } from '../../types/result/module.f.mjs'
import { withoutNegativeZero } from '../corpus/module.f.mjs'

/** The first line of a generated expectation. @type {(fixture: string) => string} */
const header = fixture =>
    `// Expectation of \`nanvm-harness/fixtures/${fixture}\`, generated by \`fjs/nanvm/expected\`. Do not edit: change the fixture and regenerate.`

/** The `JSON` constant of a value with no JSON form. */
const none = '#[rustfmt::skip]\npub const JSON: Option<&[u8]> = None;'

/** The `THROWS` constant: whether the fixture is expected to throw. @type {(throws: boolean) => string} */
const throwsConstant = throws => `pub const THROWS: bool = ${throws};`

/** A byte as a Rust hexadecimal literal. @type {(byte: number) => string} */
const byteLiteral = byte => `0x${byte.toString(16).padStart(2, '0')}`

/**
 * The `JSON` constant: the UTF-8 bytes of the text, or `None`. The bytes are
 * spelled as numbers and not as a string literal on purpose: the Rust
 * string-literal emitter is the one that spells the compiled fixture's
 * strings, so a text written through it would share any escaping mistake with
 * what it checks, and `rustc` refuses some characters (a bidirectional
 * control, say) in a literal anyway. Here the only code between the text and
 * the Rust source is the UTF-8 encoder and a hexadecimal digit.
 *
 * @type {(json: string | null) => string}
 */
const jsonConstant = json => json === null
    ? none
    : `#[rustfmt::skip]\npub const JSON: Option<&[u8]> = Some(&[${toArray(stringToU8List(json)).map(byteLiteral).join(', ')}]);`

/** The compiler's JSON text of a value, or `null` when JSON cannot spell it. @type {(value: EdagValue) => string | null} */
const jsonText = value => {
    const data = toData(value)
    if (data[0] === 'error') { return null }
    const text = tryJsonStringify(/** @type {Unknown} */ (withoutNegativeZero(data[1])))
    return text[0] === 'ok' ? text[1] : null
}

/** A module that throws, for a fixture that does. */
const throwing = [
    'use nanvm_lib::vm::{Any, IVm, Nullish, ToAny};',
    '',
    '#[rustfmt::skip]',
    'pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {',
    '    Err(Nullish::Undefined.to_any())',
    '}',
].join('\n')

/** The graph module of a value, as `{ default: value }`. @type {(value: EdagValue) => Result<string, string>} */
const graph = value => toRust(['{}', [[':', 'default', value]]])

/** Replace the first line of a printed module with the expectation's header. @type {(fixture: string) => (text: string) => string} */
const withHeader = fixture => text => [header(fixture), ...text.split('\n').slice(1)].join('\n')

/**
 * The expectation of `fixture` from its interpretation: the module and
 * constant text, a throwing module for an initialization that threw, or the
 * reason there is none (the fixture could not be loaded at all, or its value
 * has no Rust spelling). A loading failure and a throw are told apart by the
 * `thrown` an initialization failure carries and a parse or loader failure
 * does not.
 *
 * @type {(fixture: string) => (interpreted: Result<EdagValue, SourceError>) => Result<string, string>}
 */
export const expectation = fixture => interpreted => {
    if (interpreted[0] === 'error') {
        const failure = interpreted[1]
        return 'thrown' in failure
            ? ok([header(fixture), '', throwing, '', none, throwsConstant(true), ''].join('\n'))
            : error(`${fixture}: ${failure.message}`)
    }
    // An export object always answers `default`, if only `undefined`.
    const value = assertOk(read(ok(interpreted[1]), 'default'))
    const printed = graph(value)
    return printed[0] === 'error'
        ? error(`${fixture}: ${printed[1]}`)
        : ok([withHeader(fixture)(printed[1]).trimEnd(), '', jsonConstant(jsonText(value)), throwsConstant(false), ''].join('\n'))
}
