/**
 * The expectation of one corpus fixture, as the text of a Rust module, for
 * the Stage 8 comparison (see
 * [callable-function-objects](../../../nanvm-lib/todo/callable-function-objects.md)).
 *
 * It is the FJS interpreter's value of the fixture's `default` export, which
 * `fjs/nanvm/corpus`'s proof ties to Node's, in two layers that fail
 * independently:
 *
 * - `module`, the value as a graph, printed by the compiler's Rust backend as
 *   the object `{ default: <value> }`. It keeps sharing, `bigint`,
 *   `undefined`, `NaN` and `-0`, and it shares the Rust literal emitter with
 *   the compiled fixture;
 * - `JSON`, the compiler's own JSON text of the value, with `-0` written as
 *   `0`, or `None` when the value has no JSON form. It shares nothing with the
 *   Rust emitter, which is its use.
 *
 * A fixture whose initialization throws is expected to throw: its `module`
 * returns an `Err`, whose value no one compares (an engine's thrown value is
 * its own), and its `JSON` is `None`.
 *
 * This module is pure. `fjs/nanvm/harness` reads the fixtures and writes the
 * files.
 *
 * @module
 *
 * @import { Result } from '../../types/result/types.ts'
 * @import { EdagValue } from '../../edag/value/types.ts'
 * @import { SourceError } from '../../compiler/transpiler/types.ts'
 * @import { Unknown } from '../../media/datajs/types.ts'
 */

import { toRust } from '../../compiler/rust/module.f.mjs'
import { read } from '../../edag/value/property/module.f.mjs'
import { toData } from '../../edag/value/to_unknown/module.f.mjs'
import { tryJsonStringify } from '../../media/datajs/serializer/module.f.mjs'
import { stringLiteral } from '../../media/rust/module.f.mjs'
import { assertOk } from '../../asserts/module.f.mjs'
import { error, ok, unwrap } from '../../types/result/module.f.mjs'
import { withoutNegativeZero } from '../corpus/module.f.mjs'

/** The first line of a generated expectation. @type {(fixture: string) => string} */
const header = fixture =>
    `// Expectation of \`nanvm-harness/fixtures/${fixture}\`, generated by \`fjs/nanvm/expected\`. Do not edit: change the fixture and regenerate.`

/** The `JSON` constant of a value with no JSON form. */
const none = '#[rustfmt::skip]\npub const JSON: Option<&str> = None;'

/**
 * The `JSON` constant: the text, or `None`. The text never holds a lone
 * surrogate, which JSON writes as an escape, so it always has a Rust spelling.
 *
 * @type {(json: string | null) => string}
 */
const jsonConstant = json => json === null
    ? none
    : `#[rustfmt::skip]\npub const JSON: Option<&str> = Some(${unwrap(stringLiteral(json))});`

/** The compiler's JSON text of a value, or `null` when JSON cannot spell it. @type {(value: EdagValue) => string | null} */
const jsonText = value => {
    const data = toData(value)
    if (data[0] === 'error') { return null }
    const text = tryJsonStringify(/** @type {Unknown} */ (withoutNegativeZero(data[1])))
    return text[0] === 'ok' ? text[1] : null
}

/** A module that throws, for a fixture that does. */
const throwing = [
    'use nanvm_lib::vm::{Any, IVm, Nullish, ToAny};',
    '',
    '#[rustfmt::skip]',
    'pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {',
    '    Err(Nullish::Undefined.to_any())',
    '}',
].join('\n')

/** The graph module of a value, as `{ default: value }`. @type {(value: EdagValue) => Result<string, string>} */
const graph = value => toRust(['{}', [[':', 'default', value]]])

/** Replace the first line of a printed module with the expectation's header. @type {(fixture: string) => (text: string) => string} */
const withHeader = fixture => text => [header(fixture), ...text.split('\n').slice(1)].join('\n')

/**
 * The expectation of `fixture` from its interpretation: the module and
 * constant text, a throwing module for an initialization that threw, or the
 * reason there is none (the fixture could not be loaded at all, or its value
 * has no Rust spelling). A loading failure and a throw are told apart by the
 * `thrown` an initialization failure carries and a parse or loader failure
 * does not.
 *
 * @type {(fixture: string) => (interpreted: Result<EdagValue, SourceError>) => Result<string, string>}
 */
export const expectation = fixture => interpreted => {
    if (interpreted[0] === 'error') {
        const failure = interpreted[1]
        return 'thrown' in failure
            ? ok([header(fixture), '', throwing, '', none, ''].join('\n'))
            : error(`${fixture}: ${failure.message}`)
    }
    // An export object always answers `default`, if only `undefined`.
    const value = assertOk(read(ok(interpreted[1]), 'default'))
    const printed = graph(value)
    return printed[0] === 'error'
        ? error(`${fixture}: ${printed[1]}`)
        : ok([withHeader(fixture)(printed[1]).trimEnd(), '', jsonConstant(jsonText(value)), ''].join('\n'))
}
