/**
 * Proofs for the expectation of a corpus fixture, on interpreted values built
 * directly: what the module and the JSON constant say for a value with and
 * without a JSON form, for a throwing initialization, and for the failures.
 *
 * @import { EdagValue } from '../../edag/value/types.ts'
 */

import { assert, assertEq, assertError, assertOk } from '../../asserts/module.f.mjs'
import { error, ok } from '../../types/result/module.f.mjs'
import { expectation } from './module.f.mjs'

/** The export object a module with this default makes. @type {(value: EdagValue) => EdagValue} */
const exportsOf = value => ['{}', [[':', 'default', value]]]

/** The expectation of a module whose default is `value`. @type {(value: EdagValue) => string} */
const of = value => assertOk(expectation('f.mjs')(ok(/** @type {any} */ (exportsOf(value)))))

export const proof = {
    // The first line names the fixture, the module returns the export object
    // `{ default: value }`, and the JSON constant is the value's text.
    data: () => {
        const text = of(['[]', [1, 'a']])
        const lines = text.split('\n')
        assertEq(lines[0], '// Expectation of `nanvm-harness/fixtures/f.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.')
        assert(text.includes('pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {'))
        assert(text.includes('Ok([(string_key("default"), c0)].to_object().to_any())'))
        // `[1,"a"]`
        assert(text.includes('#[rustfmt::skip]\npub const JSON: Option<&[u8]> = Some(&[0x5b, 0x31, 0x2c, 0x22, 0x61, 0x22, 0x5d]);'))
        assertEq(text.endsWith('\n'), true)
    },
    // A shared node is one binding cloned at each reference, so the graph
    // keeps the sharing the JSON text cannot.
    sharing: () => {
        const text = of(['[]', [['{}', [[':', 'x', 1]]]]])
        assert(text.includes('Some(&[0x5b, 0x7b, 0x22, 0x78, 0x22, 0x3a, 0x31, 0x7d, 0x5d])'))
        /** @type {EdagValue} */
        const shared = ['{}', [[':', 'x', 1]]]
        const twice = of(['[]', [shared, shared]])
        assert(twice.includes('[c0.clone(), c0.clone()]'))
        assert(twice.includes('Some(&[0x5b, 0x7b, 0x22, 0x78, 0x22, 0x3a, 0x31, 0x7d, 0x2c, 0x7b, 0x22, 0x78, 0x22, 0x3a, 0x31, 0x7d, 0x5d])'))
    },
    // `JSON.stringify` and `to_json` print `-0` as `0`; the graph keeps its bits.
    negativeZero: () => {
        const text = of(['[]', [-0]])
        assert(text.includes('Some(&[0x5b, 0x30, 0x5d])'))
        assert(text.includes('f64_any(0x8000000000000000)'))
    },
    // A value JSON cannot spell has a graph and no JSON text.
    noJsonForm: () => {
        for (const value of /** @type {readonly EdagValue[]} */ ([['undefined'], 1n, NaN, ['=>', 0, [], ['undefined']]])) {
            const text = of(value)
            assert(text.includes('pub const JSON: Option<&[u8]> = None;'), String(value))
        }
        assert(of(['undefined']).includes('Nullish::Undefined.to_any()'))
        assert(of(1n).includes('bigint_any(1)'))
    },
    // A lone surrogate is escaped in the JSON text and spelled in UTF-16 in the graph.
    loneSurrogate: () => {
        const text = of(['[]', ['\ud83d']])
        assert(text.includes('string_any_utf16(&[0xd83d])'))
        // `["\ud83d"]`, the escape as text
        assert(text.includes('Some(&[0x5b, 0x22, 0x5c, 0x75, 0x64, 0x38, 0x33, 0x64, 0x22, 0x5d])'))
    },
    // A character `rustc` refuses in a literal, or one an emitter could
    // mis-escape, is only bytes here: DEL and a bidirectional control.
    controlCharacters: () => {
        const text = of(['[]', ['\u007f\u202e']])
        assert(text.includes('Some(&[0x5b, 0x22, 0x7f, 0xe2, 0x80, 0xae, 0x22, 0x5d])'))
    },
    // An initialization that threw is expected to throw; its value is not compared.
    throws: () => {
        const text = assertOk(expectation('f.mjs')(error({ message: 'module initialization failed', metadata: null, path: 'f.mjs', thrown: ['undefined'] })))
        assert(text.includes('Err(Nullish::Undefined.to_any())'))
        assert(text.includes('#[rustfmt::skip]\npub const JSON: Option<&[u8]> = None;'))
        assertEq(text.split('\n')[0].startsWith('// Expectation of'), true)
    },
    // A parse or loader failure carries no `thrown`: the fixture was never run,
    // so it has no expectation and the reason is the failure's own.
    loaderFailure: () => {
        assertEq(assertError(expectation('f.mjs')(error({ message: 'unexpected token', metadata: null }))), 'f.mjs: unexpected token')
    },
    // A value the Rust backend has no spelling for: a function past its largest length.
    unspellable: () => {
        const message = assertError(expectation('f.mjs')(ok(/** @type {any} */ (exportsOf(['=>', 17, [], 1])))))
        assert(message.startsWith('f.mjs: '), message)
    },
}
