/**
 * Experimental generator for a target-specific Nix flake
 * (fjs/ci/todo/65z-ci-nix.md, Phase 1). Produces deterministic
 * `flake.nix`/`flake.lock` text from maintained `fjs/ci/config` values only;
 * it never invokes Nix, so `npm run ci-update` stays runnable without a
 * local Nix installation.
 *
 * This is a partial, single-target experiment: it covers only the
 * `playwright` job's host, and the generated flake is not wired into CI yet
 * (that is Phase 3) or validated by building it (Phase 2). The point of this
 * slice is the generation half of the pipeline — committed, deterministic
 * output driven entirely by maintained configuration.
 *
 * @module
 */
import { node, nixpkgsLock, playwright } from '../config/module.f.ts'

/** Host system for the generated Playwright flake: matches the `playwright`
 * job's `ubuntu-*-arm` runner image. */
export const playwrightSystem = 'aarch64-linux'

/** Directory the generated Playwright flake is written to. */
export const playwrightFlakeDir = 'nix/generated/playwright-linux-aarch64'

const nixpkgsUrl = `github:${nixpkgsLock.owner}/${nixpkgsLock.repo}/${nixpkgsLock.rev}`

export const playwrightFlakeNix = `\
# Generated by \`npm run ci-update\` (fjs/ci/nix/module.f.ts). Do not edit by
# hand: regenerate via \`npm run ci-update\` instead.
#
# Experimental Phase 1 output for fjs/ci/todo/65z-ci-nix.md. Describes the
# \`playwright\` CI job's host as a Nix flake; evaluating or building it
# requires Nix, but generating this file does not. Not yet used by CI
# (Phase 3) and not yet validated (Phase 2): exact Node/Playwright artifact
# fetches and hashes remain future work.
{
  description = "Playwright CI environment (generated, experimental)";

  inputs.nixpkgs.url = "${nixpkgsUrl}";

  outputs = { self, nixpkgs }:
    let
      system = "${playwrightSystem}";
      pkgs = import nixpkgs { inherit system; };
    in {
      devShells.\${system}.default = pkgs.mkShellNoCC {
        packages = [ pkgs.nodejs ];
        NODE_VERSION = "${node.default}";
        PLAYWRIGHT_VERSION = "${playwright}";
      };
    };
}
`

export const playwrightFlakeLock = JSON.stringify({
    nodes: {
        nixpkgs: {
            locked: {
                lastModified: nixpkgsLock.lastModified,
                narHash: nixpkgsLock.narHash,
                owner: nixpkgsLock.owner,
                repo: nixpkgsLock.repo,
                rev: nixpkgsLock.rev,
                type: 'github',
            },
            original: {
                owner: nixpkgsLock.owner,
                repo: nixpkgsLock.repo,
                rev: nixpkgsLock.rev,
                type: 'github',
            },
        },
        root: {
            inputs: {
                nixpkgs: 'nixpkgs',
            },
        },
    },
    root: 'root',
    version: 7,
}, null, '  ') + '\n'
