// Fixture source: `fjs/nanvm/values/module.f.mjs`; regenerate with `npm run gen`.
// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, IStaticFunction, Nullish, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x4008000000000000)].to_array().to_any();
    let c1: Any<A> = [(string_key("unused"), f64_any(0x4022000000000000))].to_object().to_any();
    let c2: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = (A::frame(self_)[0].clone() + args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()))?;
        Ok([c0, A::frame(self_)[1].clone(), A::frame(self_)[2].clone()].to_array().to_any())
    }, 1, [f64_any(0x4000000000000000), c0.clone(), c0.clone(), c1.clone()].to_array(), Some("($4)=>[$0+$4,$1,$2]")).to_any();
    let c3: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = (A::frame(self_)[0].clone() + args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()))?;
        Ok([c0, A::frame(self_)[1].clone(), A::frame(self_)[2].clone()].to_array().to_any())
    }, 1, [f64_any(0x4000000000000000), c0.clone(), c0.clone(), c1.clone()].to_array(), Some("($4)=>[$0+$4,$1,$2]")).to_any();
    let c4: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array().to_any();
        Ok(A::static_function(|self_, args| {
            let c0: Any<A> = A::frame(self_)[1].clone();
            let c1 = || Ok([A::frame(self_)[0].clone(), c0.clone(), c0.clone()].to_array().to_any());
            let c2 = || Err(c0.clone());
            Any::conditional(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), c1, c2)
        }, 1, [A::frame(self_)[0].clone(), c0].to_array(), Some("($2)=>$2?[$0,$1,$1]:(()=>{throw $1;})()")).to_any())
    }, 1, [c0.clone()].to_array(), Some("($1)=>{const $2=[$1];return ($3)=>$3?[$0,$2,$2]:(()=>{throw $2;})();}")).to_any();
    Ok([(string_key("shared"), c0.clone()), (string_key("alias"), c0.clone()), (string_key("call"), c2.clone()), (string_key("again"), c2.clone()), (string_key("other"), c3), (string_key("make"), c4)].to_object().to_any())
}
