/**
 * Writes the compiled `nanvm-harness` fixtures: every `.mjs` directly in
 * `nanvm-harness/fixtures/` compiled through the compiler's Rust output into
 * `nanvm-harness/gen.fixtures/<name>.rs`, named after its Rust module, and
 * `gen.fixtures/mod.rs` naming each — so the directory is the list of
 * fixtures, and a new one is one file. `src/lib.rs` reaches the whole set
 * through one `#[path]` to that `mod.rs`.
 *
 * The thin effectful shell beside [`../update`](../update/module.f.mjs),
 * invoked from `gen` so the CI drift check regenerates the files on every
 * pull request and fails when a committed copy is stale. The name rule and
 * the `mod.rs` text are pure exports; the walk, the compiles and the writes
 * are the one effect {@link generateFixtures} sequences.
 *
 * The names are sorted by Rust module name with `string.cmp`: `readdir`
 * answers in the file system's order, which differs between hosts, and a
 * `mod.rs` written in that order would fail the drift check with no source
 * change. The Rust name rather than the file name because `rustfmt` orders
 * `mod` lines by it, and `function_scope` follows `function` where
 * `function-scope.mjs` precedes `function.mjs`.
 *
 * @module
 *
 * @import { IoChannel, NodeProgram, Readdir } from '../../effects/node/types.ts'
 * @import { Effect } from '../../effects/types.ts'
 * @import { _CompileOp } from '../../compiler/types.ts'
 */

import { compileFile } from '../../compiler/module.f.mjs'
import { forEachStep, mapStep, pureOk, step } from '../../effects/module.f.mjs'
import { exitStep, mkdir, readdir, writeUtf8File } from '../../effects/node/module.f.mjs'
import { cmp } from '../../types/string/module.f.mjs'

/** Where the fixtures are: one `.mjs` module each, a helper one imports beside them. */
export const fixturesDirectory = 'nanvm-harness/fixtures'

/** Where the compiled fixtures go, a `gen.` name `gen:clean` empties. */
export const directory = 'nanvm-harness/gen.fixtures'

/** The module file naming every compiled fixture, which `src/lib.rs` includes by path. */
export const modulesPath = `${directory}/mod.rs`

const extension = '.mjs'

/**
 * The Rust module a fixture file compiles into: the name without its
 * extension, a `-` as `_` since a Rust identifier has no hyphen —
 * `function-scope.mjs` is `function_scope`. One place, for the thirty-odd
 * pairs the `gen` script used to spell by hand.
 *
 * @type {(file: string) => string}
 */
export const rustName = file => file.slice(0, -extension.length).replaceAll('-', '_')

/**
 * The fixtures: every `.mjs` file directly in {@link fixturesDirectory},
 * sorted by the Rust name each compiles into. A helper a fixture imports is
 * one of them — compiling what is in the directory is the simpler rule, and
 * costs one small `.rs`.
 *
 * @type {() => Effect<Readdir, readonly string[], IoChannel>}
 */
export const fixtures = () => mapStep(
    readdir(fixturesDirectory, {}),
    entries => entries
        .filter(({ name, isFile }) => isFile && name.endsWith(extension))
        .map(({ name }) => name)
        .toSorted((a, b) => cmp(rustName(a))(rustName(b))))

/**
 * The text of `mod.rs`: one `pub mod` per Rust module name, in the order
 * given, under the header every generated file carries.
 *
 * @type {(names: readonly string[]) => string}
 */
export const modules = names => [
    '// @generated by `fjs run ./fjs/nanvm/harness/module.f.mjs`. Do not edit: add or remove a fixture instead.',
    '',
    ...names.map(name => `pub mod ${name};`),
    '',
].join('\n')

/**
 * Compiles every fixture into its `.rs`, in order, stopping at the first the
 * compiler refuses, then writes `mod.rs` naming them all. The output
 * directory is created by the first compile — after `gen:clean` on a fresh
 * checkout nothing else does — and again here, so an empty fixture set still
 * leaves a `mod.rs`.
 *
 * @type {() => Effect<_CompileOp, void, IoChannel>}
 */
export const generateFixtures = () => step(fixtures(), names => {
    const compiled = forEachStep(
        pureOk(names),
        name => compileFile(`${fixturesDirectory}/${name}`, `${directory}/${rustName(name)}.rs`))
    const directoryReady = step(compiled, () => mkdir(directory, { recursive: true }))
    return step(directoryReady, () => writeUtf8File(modulesPath, modules(names.map(rustName))))
})

/**
 * The program `npm run gen` runs. It takes the options every `NodeProgram` is
 * given and reads none of them: the directories are fixed above, so there is
 * nothing on the command line to vary.
 *
 * @type {NodeProgram}
 */
export const main = _options => exitStep(generateFixtures())
