/**
 * Proofs for the harness fixture generator: a fixture directory in the
 * virtual filesystem, compiled, and the outputs read back.
 *
 * @import { Dir } from '../../effects/node/virtual/types.ts'
 */

import { assert, assertEq, assertOk } from '../../asserts/module.f.mjs'
import { exitCode, readUtf8File } from '../../effects/node/module.f.mjs'
import { step } from '../../effects/module.f.mjs'
import { defaultNodeProgramOptions, emptyState, virtual } from '../../effects/node/virtual/module.f.mjs'
import { utf8 } from '../../text/module.f.mjs'
import { directory, fixtures, generateFixtures, main, modules, modulesPath, rustName } from './module.f.mjs'

/**
 * Four fixtures and the things the walk must leave alone: a file that is not
 * a module, a subdirectory, and the file system's own order, which is not the
 * sorted one. `function-scope.mjs` and `function.mjs` sort one way as file
 * names and the other as Rust names, and `rustfmt` wants the latter.
 *
 * @type {Dir}
 */
const root = {
    'nanvm-harness': {
        'fixtures': {
            'rest-function.mjs': [utf8('export default 2;')],
            'README.md': [utf8('# fixtures')],
            'function-scope.mjs': [utf8('export default 4;')],
            'helpers': { 'nested.mjs': [utf8('export default 3;')] },
            'function.mjs': [utf8('export default 5;')],
            'at.mjs': [utf8('export default 1;')],
        },
    },
}

/** The fixtures above as Rust module names, in the order `mod.rs` lists them. @type {readonly string[]} */
const names = ['at', 'function', 'function_scope', 'rest_function']

/** @type {(dir: Dir, path: readonly string[]) => Dir} */
const into = (dir, path) => path.reduce((d, name) => {
    const next = d[name]
    assert(typeof next === 'object' && !(next instanceof Array), name)
    return next
}, dir)

export const proof = {
    rustName: () => {
        assertEq(rustName('function-scope.mjs'), 'function_scope')
        assertEq(rustName('named-imports-throws.mjs'), 'named_imports_throws')
        assertEq(rustName('at.mjs'), 'at')
    },
    // Files only, modules only, directly in the directory, and sorted
    // whatever order the listing came in.
    fixtures: () => {
        const [, result] = virtual({ ...emptyState, root })(fixtures())
        assertEq(assertOk(result).join(','), 'at.mjs,function.mjs,function-scope.mjs,rest-function.mjs')
    },
    modules: () => {
        assertEq(modules(['at', 'rest_function']), [
            '// @generated by `fjs run ./fjs/nanvm/harness/module.f.mjs`. Do not edit: add or remove a fixture instead.',
            '',
            'pub mod at;',
            'pub mod rest_function;',
            '',
        ].join('\n'))
        assertEq(modules([]).endsWith('\n\n'), true)
    },
    generateFixtures: () => {
        const [state, result] = virtual({ ...emptyState, root })(generateFixtures())
        assertOk(result)
        const written = into(state.root, directory.split('/'))
        assertEq(Object.keys(written).toSorted().join(','), 'at.rs,function.rs,function_scope.rs,mod.rs,rest_function.rs')
        const [, modRs] = virtual(state)(readUtf8File(modulesPath))
        assertEq(assertOk(modRs), modules(names))
        const [, atRs] = virtual(state)(readUtf8File(`${directory}/at.rs`))
        assert(assertOk(atRs).startsWith('// @generated by `fjs compile`.'))
    },
    // A fixture the compiler refuses stops the sequence before `mod.rs` is
    // written: a list naming a module that does not exist would not build.
    generateFixturesStopsAtARefusedFixture: () => {
        /** @type {Dir} */
        const broken = {
            'nanvm-harness': { 'fixtures': { 'a.mjs': [utf8('export default 1;')], 'b.mjs': [utf8('export default (')] } },
        }
        const [state, result] = virtual({ ...emptyState, root: broken })(generateFixtures())
        assertEq(result[0], 'error')
        const written = into(state.root, directory.split('/'))
        assertEq(Object.keys(written).join(','), 'a.rs')
    },
    // No fixtures at all still leaves a `mod.rs`, so `src/lib.rs` has a file
    // to include.
    generateFixturesWithNoFixtures: () => {
        /** @type {Dir} */
        const none = { 'nanvm-harness': { 'fixtures': {} } }
        const [state, result] = virtual({ ...emptyState, root: none })(step(generateFixtures(), () => readUtf8File(modulesPath)))
        assertEq(assertOk(result), modules([]))
        assertEq(Object.keys(into(state.root, directory.split('/'))).join(','), 'mod.rs')
    },
    main: () => {
        const [, code] = virtual({ ...emptyState, root })(main(defaultNodeProgramOptions))
        assertEq(exitCode(code), 0)
    },
    // The fixture directory missing is the failure `fjs run` reports: exit
    // `1`, the host's message on `stderr`.
    mainRefusesAMissingDirectory: () => {
        const [state, code] = virtual(emptyState)(main(defaultNodeProgramOptions))
        assertEq(exitCode(code), 1)
        assert(state.stderr !== '')
    },
}
