// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| { Any::member_access(args.clone().to_any(), string_any("length")) }, 0, Array::default()).to_any();
    Ok([(string_key("default"), [(Any::call(c0.clone(), Array::default().to_any()))?, (Any::call(c0.clone(), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any()))?].to_array().to_any())].to_object().to_any())
}
