// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, strict_eq, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IVm, Nullish, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any();
    let c1 = || Ok([f64_any(0x0000000000000000)].to_array().to_any());
    let c2: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c1)?;
    let c3 = || Ok([f64_any(0xbff0000000000000)].to_array().to_any());
    let c4: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c3)?;
    let c5 = || Ok([f64_any(0x4008000000000000)].to_array().to_any());
    let c6: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c5)?;
    let c7: Any<A> = (strict_eq(c6, Nullish::Undefined.to_any()))?;
    let c8 = || Ok([f64_any(0xc010000000000000)].to_array().to_any());
    let c9: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c8)?;
    let c10: Any<A> = (strict_eq(c9, Nullish::Undefined.to_any()))?;
    let c11 = || Ok([f64_any(0x3ffb333333333333)].to_array().to_any());
    let c12: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c11)?;
    let c13 = || Ok([string_any("1")].to_array().to_any());
    let c14: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c13)?;
    let c15: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(|| Ok(Array::default().to_any()))?;
    let c16: Any<A> = [c2, c4, c7, c10, c12, c14, c15].to_array().to_any();
    Ok([(string_key("default"), c16)].to_object().to_any())
}
