// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(true.to_any())
}
