// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x4024000000000000)].to_array().to_any();
    let c1: Any<A> = [f64_any(0x4034000000000000)].to_array().to_any();
    let c2: Any<A> = Any::call(A::static_function(|_self, args| {
        let c0: Any<A> = Any::dot(A::frame(_self).clone().to_any(), f64_any(0x0000000000000000)).end()?;
        let c1: Any<A> = [args.clone().to_any(), c0].to_array().to_any();
        Ok(A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(A::frame(_self).clone().to_any(), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = Any::dot(c0, f64_any(0x0000000000000000)).end()?;
            let c2: Any<A> = Any::dot(args.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            let c3: Any<A> = (c1 + c2)?;
            let c4: Any<A> = Any::dot(A::frame(_self).clone().to_any(), f64_any(0x3ff0000000000000)).end()?;
            c3 + c4
        }, 0, [args.clone().to_any().clone(), Any::dot(A::frame(_self).clone().to_any(), f64_any(0x0000000000000000)).end()?.clone()].to_array()).to_any())
    }, 0, [f64_any(0x4024000000000000).clone()].to_array()).to_any(), c1)?;
    let c3: Any<A> = [f64_any(0x4028000000000000)].to_array().to_any();
    let c4: Any<A> = Any::call(c2, c3)?;
    Ok([(string_key("default"), c4)].to_object().to_any())
}
