// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("g"), A::static_function(|_self, _args| { Ok([(string_key("h"), A::static_function(|_self, args| { Ok(args.clone().to_any()) }, 0, Array::default()).to_any())].to_object().to_any()) }, 0, Array::default()).to_any())].to_object().to_any();
    Ok([(string_key("default"), [Any::member_access(Any::member_access(c0.clone(), string_any("g")).and_then(|f| Any::call(f, [f64_any(0x3ff0000000000000)].to_array().to_any()))?, string_any("h")).and_then(|f| Any::call(f, [f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any()))?, Any::member_access(Any::member_access(Any::member_access(c0.clone(), string_any("g")).and_then(|f| Any::call(f, [f64_any(0x4010000000000000)].to_array().to_any()))?, string_any("h")).and_then(|f| Any::call(f, Array::default().to_any()))?, string_any("length"))?].to_array().to_any())].to_object().to_any())
}
