// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, Array, IVm, ToAny};

fn f0<A: IVm>(_args: &Array<A>) -> Result<Any<A>, Any<A>> {
    Ok((42f64).to_any())
}

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let _args: Array<A> = Array::default();
    f0(&_args)
}
