// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{bigint_any, f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, Nullish, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = Any::dot(Array::default().to_any(), string_any("length")).end()?;
    let c1 = || bigint_any(1) / bigint_any(0);
    let c2: Any<A> = (Any::logical_and(c0.clone(), c1))?;
    let c3: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c4: Any<A> = Any::dot(c3, string_any("length")).end()?;
    let c5: Any<A> = (Any::logical_and(c4.clone(), || Ok(f64_any(0x4000000000000000))))?;
    let c6: Any<A> = [Nullish::Null.to_any(), f64_any(0x3ff0000000000000)].to_array().to_any();
    let c7: Any<A> = Any::dot(c6, f64_any(0x0000000000000000)).end()?;
    let c8 = || bigint_any(1) / bigint_any(0);
    let c9: Any<A> = (Any::logical_and(c7.clone(), c8))?;
    let c10 = || bigint_any(1) / bigint_any(0);
    let c11: Any<A> = (Any::logical_or(c4.clone(), c10))?;
    let c12: Any<A> = (Any::logical_or(c0.clone(), || Ok(f64_any(0x4008000000000000))))?;
    let c13: Any<A> = [string_any(""), string_any("x")].to_array().to_any();
    let c14: Any<A> = Any::dot(c13, f64_any(0x0000000000000000)).end()?;
    let c15: Any<A> = (Any::logical_or(c14, || Ok(string_any("x"))))?;
    let c16: Any<A> = [f64_any(0x0000000000000000), Nullish::Null.to_any()].to_array().to_any();
    let c17: Any<A> = Any::dot(c16, f64_any(0x0000000000000000)).end()?;
    let c18 = || bigint_any(1) / bigint_any(0);
    let c19: Any<A> = (Any::nullish_coalescing(c17, c18))?;
    let c20: Any<A> = (Any::nullish_coalescing(c7.clone(), || Ok(f64_any(0x4010000000000000))))?;
    let c21: Any<A> = [Nullish::Undefined.to_any(), f64_any(0x3ff0000000000000)].to_array().to_any();
    let c22: Any<A> = Any::dot(c21, f64_any(0x0000000000000000)).end()?;
    let c23: Any<A> = (Any::nullish_coalescing(c22, || Ok(f64_any(0x4014000000000000))))?;
    let c24: Any<A> = [false.to_any(), Nullish::Null.to_any()].to_array().to_any();
    let c25: Any<A> = Any::dot(c24, f64_any(0x0000000000000000)).end()?;
    let c26: Any<A> = (Any::nullish_coalescing(c25, || Ok(f64_any(0x4018000000000000))))?;
    let c27 = || bigint_any(1) / bigint_any(0);
    let c28: Any<A> = (Any::conditional(c4.clone(), || Ok(f64_any(0x401c000000000000)), c27))?;
    let c29 = || bigint_any(1) / bigint_any(0);
    let c30: Any<A> = (Any::conditional(c0.clone(), c29, || Ok(f64_any(0x4020000000000000))))?;
    let c31: Any<A> = (Any::logical_and(c4.clone(), || Ok(f64_any(0x4000000000000000))))?;
    let c32: Any<A> = (Any::logical_or(c31, || Ok(f64_any(0x4008000000000000))))?;
    let c33: Any<A> = (Any::nullish_coalescing(c7.clone(), || Ok(c0.clone())))?;
    let c34: Any<A> = (Any::conditional(c33, || Ok(f64_any(0x4022000000000000)), || Ok(f64_any(0x4024000000000000))))?;
    let c35 = || Any::conditional(c4.clone(), || Ok(f64_any(0x4026000000000000)), || Ok(f64_any(0x4028000000000000)));
    let c36: Any<A> = (Any::conditional(c0.clone(), || Ok(f64_any(0x3ff0000000000000)), c35))?;
    let c37: Any<A> = A::static_function(|_self, args| {
        let c0: Any<A> = args.clone().to_any();
        let c1: Any<A> = Any::dot(c0.clone(), string_any("length")).end()?;
        let c2: Any<A> = (Any::conditional(c1, || Ok(c0.clone()), || Ok(c0.clone())))?;
        Any::dot(c2, f64_any(0x0000000000000000)).end()
    }, 0, Array::default()).to_any();
    let c38: Any<A> = [f64_any(0x402a000000000000)].to_array().to_any();
    let c39: Any<A> = Any::call(c37, c38)?;
    let c40: Any<A> = A::static_function(|_self, args| {
        let c0: Any<A> = Any::dot(Array::default().to_any(), string_any("length")).end()?;
        let c1 = || Ok(args.clone().to_any());
        let c2: Any<A> = (Any::logical_and(c0, c1))?;
        let c3: Any<A> = (Any::logical_or(c2, c1))?;
        Any::dot(c3, string_any("length")).end()
    }, 0, Array::default()).to_any();
    let c41: Any<A> = [f64_any(0x402c000000000000), f64_any(0x402e000000000000)].to_array().to_any();
    let c42: Any<A> = Any::call(c40, c41)?;
    let c43: Any<A> = [c2, c5, c9, c11, c12, c15, c19, c20, c23, c26, c28, c30, c32, c34, c36, c39, c42].to_array().to_any();
    Ok([(string_key("default"), c43)].to_object().to_any())
}
