// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x4014000000000000)].to_array().to_any();
    Ok([(string_key("a"), c0.clone()), (string_key("default"), c0.clone()), (string_key("z"), c0.clone())].to_object().to_any())
}
