// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    Ok([(string_key("default"), (Any::call((Any::call(A::static_function(|_self, _args| { Ok(A::static_function(|_self, args| { Ok(args.clone().to_any()) }, 0, Array::default()).to_any()) }, 0, Array::default()).to_any(), [f64_any(0x3ff0000000000000)].to_array().to_any()))?, [f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any()))?)].to_object().to_any())
}
