// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, String, ToAny, ToObject};

fn string_key<A: IVm>(v: &str) -> String<A> {
    v.into()
}

fn f64_any<A: IVm>(v: u64) -> Any<A> {
    f64::from_bits(v).to_any()
}

#[rustfmt::skip]
pub fn module<A: IVm>() -> Any<A> {
    [(string_key("default"), f64_any(0x4045000000000000))].to_object().to_any()
}
