// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("a"), f64_any(0x3ff0000000000000)), (string_key("b"), string_any("two"))].to_object().to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}
