// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, strict_eq, strict_ne, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok([(string_key("default"), [(f64_any(0x4018000000000000) + f64_any(0x3ff0000000000000))?, (f64_any(0x4018000000000000) - f64_any(0x3ff0000000000000))?, (f64_any(0x4018000000000000) * f64_any(0x4000000000000000))?, (f64_any(0x4018000000000000) / f64_any(0x4010000000000000))?, (f64_any(0x4018000000000000) % f64_any(0x4010000000000000))?, (Any::pow(f64_any(0x4018000000000000), f64_any(0x4000000000000000)))?, f64_any(0xc018000000000000), (Any::bitwise_not(f64_any(0x4018000000000000)))?, (strict_eq(f64_any(0x4018000000000000), f64_any(0x4018000000000000)))?, (strict_ne(f64_any(0x4018000000000000), f64_any(0x4018000000000000)))?, (Any::lt(f64_any(0x4018000000000000), f64_any(0x401c000000000000)))?, (Any::le(f64_any(0x4018000000000000), f64_any(0x4018000000000000)))?, (Any::gt(f64_any(0x4018000000000000), f64_any(0x401c000000000000)))?, (Any::ge(f64_any(0x4018000000000000), f64_any(0x4018000000000000)))?, (f64_any(0x4018000000000000) & f64_any(0x4008000000000000))?, (f64_any(0x4018000000000000) | f64_any(0x3ff0000000000000))?, (f64_any(0x4018000000000000) ^ f64_any(0x3ff0000000000000))?, (f64_any(0x4018000000000000) << f64_any(0x3ff0000000000000))?, (f64_any(0x4018000000000000) >> f64_any(0x3ff0000000000000))?, (Any::unsigned_right_shift(f64_any(0x4018000000000000), f64_any(0x3ff0000000000000)))?, (string_any("a") + string_any("b"))?, (f64_any(0x3ff0000000000000) + (f64_any(0x4000000000000000) * f64_any(0x4008000000000000))?)?].to_array().to_any())].to_object().to_any())
}
