// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let c0: Any<A> = args.clone().to_any();
        let c1: Any<A> = Any::dot(c0.clone(), f64_any(0x3ff0000000000000)).end()?;
        let c2: Any<A> = Any::dot(c0.clone(), f64_any(0x0000000000000000)).end()?;
        Ok([c1, c2].to_array().to_any())
    }, 2, Array::default()).to_any();
    let c1: Any<A> = [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any();
    let c2: Any<A> = Any::call(c0.clone(), c1)?;
    let c3: Any<A> = [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any();
    let c4: Any<A> = Any::call(c0.clone(), c3)?;
    let c5: Any<A> = A::static_function(|_self, args| { Any::dot(args.clone().to_any(), f64_any(0x0000000000000000)).end() }, 1, Array::default()).to_any();
    let c6: Any<A> = [f64_any(0x4010000000000000)].to_array().to_any();
    let c7: Any<A> = Any::call(c5.clone(), c6)?;
    let c8: Any<A> = A::static_function(|_self, args| { Any::dot(args.clone().to_any(), f64_any(0x0000000000000000)).end() }, 2, Array::default()).to_any();
    let c9: Any<A> = [f64_any(0x4014000000000000)].to_array().to_any();
    let c10: Any<A> = Any::call(c8.clone(), c9)?;
    let c11: Any<A> = Any::dot(c0.clone(), string_any("length")).end()?;
    let c12: Any<A> = Any::dot(c5.clone(), string_any("length")).end()?;
    let c13: Any<A> = Any::dot(c8.clone(), string_any("length")).end()?;
    let c14: Any<A> = A::static_function(|_self, args| { Any::dot(args.clone().to_any(), string_any("length")).end() }, 0, Array::default()).to_any();
    let c15: Any<A> = Any::dot(c14, string_any("length")).end()?;
    let c16: Any<A> = [c2, c4, c7, c10, c11, c12, c13, c15].to_array().to_any();
    Ok([(string_key("default"), c16)].to_object().to_any())
}
