// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("a"), f64_any(0x4045000000000000))].to_object().to_any();
    let c1: Any<A> = Any::dot(c0, string_any("a")).end()?;
    Ok([(string_key("default"), c1)].to_object().to_any())
}
