// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, String, ToAny, ToObject};

fn string_any<A: IVm>(v: &str) -> Any<A> {
    v.into()
}

fn string_key<A: IVm>(v: &str) -> String<A> {
    v.into()
}

#[rustfmt::skip]
pub fn module<A: IVm>() -> Any<A> {
    Any::member_access([(string_key("a"), (42f64).to_any())].to_object().to_any(), string_any("a")).unwrap()
}
