// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Any<A> {
    [(string_key("default"), Any::member_access([(string_key("a"), f64_any(0x4045000000000000))].to_object().to_any(), string_any("a")).unwrap())].to_object().to_any()
}
