// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, Array, IVm};

fn f0<A: IVm>(args: &Array<A>) -> Result<Any<A>, Any<A>> {
    Ok(args.clone())
}

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let args: Array<A> = Array::default();
    f0(&args)
}
