runs:
  using: "composite"
  steps:
    # setup
    - uses: oven-sh/setup-bun@v1
    # checkout
    - run: bun test --timeout 10000
      shell: bash
    - run: bun ./dev/tf/module.ts
      shell: bash
