/**
 * The proof of the compiler's `.rs` output, split off `./proof.f.mjs` when
 * that file outgrew what the website's build accepts in one file — 128 KiB,
 * which it passed at `5db504c` — along the seam its own sections drew. It
 * reads the compiler as that proof does, through the helper it exports.
 *
 * No `@module`: a proof's documentation reaches no reader of the published
 * API, which is the case that rule names outright.
 */

import { maxLengthBytes } from '../types/bit_vec/module.f.mjs'
import { exitCode } from '../effects/node/module.f.mjs'
import { compile } from './module.f.mjs'
import { virtual, emptyState, nodeProgramOptions } from '../effects/node/virtual/module.f.mjs'
import { utf8, utf8ToString } from '../text/module.f.mjs'
import { assert, assertEq, assertStructurallySame } from '../asserts/module.f.mjs'
import { compileSource } from './proof.f.mjs'

export const proof = {
    // The `.rs` output: the linked EDAG printed as a generated Rust module
    // against the `nanvm-lib` API, by `fjs/compiler/rust/module.f.mjs`'s shared
    // printer — see `fjs/edag/rust/module.f.mjs`.
    rustOutput: {
        // Property access on an object literal, the same source the EDAG
        // and value outputs above compile, to a `pub fn module<A: IVm>()`.
        graph: () => {
            assertEq(
                compileSource('const a = { b: 1 }; export default a.b;')('output.rs'),
                `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("b"), f64_any(0x3ff0000000000000))].to_object().to_any();
    let c1: Any<A> = Any::dot(c0, string_any("b")).end()?;
    Ok([(string_key("default"), c1)].to_object().to_any())
}
`)
        },
        // Indexing an array literal — refused until `nanvm-lib` could read
        // an array — now prints like any other property access.
        indexingAnArrayLiteral: () => {
            assertEq(
                compileSource('const a = [1]; export default a[0];')('output.rs'),
                `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c1: Any<A> = Any::dot(c0, f64_any(0x0000000000000000)).end()?;
    Ok([(string_key("default"), c1)].to_object().to_any())
}
`)
        },
        // An output past one `Vec`, 128 KiB, is written whole, in several
        // chunks, where it once ended the compile with a bare `assertion failed`.
        largeOutput: () => {
            const source = `export default [${Array.from({ length: 5000 }, (_, i) => i).join(', ')}];`
            const root = { 'input.f.js': [utf8(source)] }
            const [state, code] = virtual({ ...emptyState, root })(compile(nodeProgramOptions(['input.f.js', 'output.rs'])))
            assertEq(exitCode(code), 0, state.stderr)
            const file = state.root['output.rs']
            assert(Array.isArray(file), file)
            assert(file.length > 1, file.length)
            const text = file.map(utf8ToString).join('')
            assert(text.length > Number(maxLengthBytes), text.length)
            assert(text.endsWith('}\n'), text.slice(-20))
        },
        // A property read on a nullish base compiles: the `.rs` output is a
        // program, and the read throws when it runs, as JavaScript throws —
        // the compiler predicts nothing of a program it writes, where the
        // data outputs evaluate the module and report the throw as theirs.
        nullishBase: () => {
            assert(compileSource('const a = null; export default a.x;')('output.rs')
                .includes('Any::dot(Nullish::Null.to_any(), string_any("x")).end()?'))
        },
        // A bigint outside `i64` is written as its sign and `u64` words,
        // which a literal's own text cannot be.
        wideBigint: () => {
            assert(compileSource('export default 9223372036854775808n;')('output.rs')
                .includes('bigint_any_words(false, &[0x8000000000000000])'))
        },
        // Every eager operator prints as a temporary, its `let` followed
        // by `?`: `pub fn module` answers the `Result` a throw lands in, so
        // the temporary is an `Any<A>`, referenced by name in the export
        // object. A negated *literal* never reaches the printer as a node —
        // the lowering folds it into the number — and prints as it always
        // did.
        operators: () => {
            /** The lines of the module's body. @type {(source: string) => readonly string[]} */
            const body = source => compileSource(source)('output.rs').split('\n').filter(line => line.startsWith('    '))
            /** @type {(source: string, value: string) => void} */
            const expect = (source, value) => assertStructurallySame(body(source), [
                `    let c0: Any<A> = ${value};`,
                '    Ok([(string_key("default"), c0)].to_object().to_any())',
            ])
            const one = 'f64_any(0x3ff0000000000000)'
            const two = 'f64_any(0x4000000000000000)'
            expect('export default 1 + 2;', `(${one} + ${two})?`)
            expect('export default 1 - 2;', `(${one} - ${two})?`)
            expect('export default 1 * 2;', `(${one} * ${two})?`)
            expect('export default 1 / 2;', `(${one} / ${two})?`)
            expect('export default 1 % 2;', `(${one} % ${two})?`)
            expect('export default 1 ** 2;', `(Any::pow(${one}, ${two}))?`)
            expect('export default 1 === 2;', `(strict_eq(${one}, ${two}))?`)
            expect('export default 1 !== 2;', `(strict_ne(${one}, ${two}))?`)
            expect('export default 1 < 2;', `(Any::lt(${one}, ${two}))?`)
            expect('export default 1 <= 2;', `(Any::le(${one}, ${two}))?`)
            expect('export default 1 > 2;', `(Any::gt(${one}, ${two}))?`)
            expect('export default 1 >= 2;', `(Any::ge(${one}, ${two}))?`)
            expect('export default 1 & 2;', `(${one} & ${two})?`)
            expect('export default 1 | 2;', `(${one} | ${two})?`)
            expect('export default 1 ^ 2;', `(${one} ^ ${two})?`)
            expect('export default 1 << 2;', `(${one} << ${two})?`)
            expect('export default 1 >> 2;', `(${one} >> ${two})?`)
            expect('export default 1 >>> 2;', `(Any::unsigned_right_shift(${one}, ${two}))?`)
            expect('export default ~1;', `(Any::bitwise_not(${one}))?`)
            expect('export default -"a";', '(-(string_any("a")))?')
            // an operand with operands of its own is a temporary before the
            // operation, referenced by name: a literal array, an inner
            // operation
            assertStructurallySame(body('export default -[1];'), [
                `    let c0: Any<A> = [${one}].to_array().to_any();`,
                '    let c1: Any<A> = (-(c0))?;',
                '    Ok([(string_key("default"), c1)].to_object().to_any())',
            ])
            assertStructurallySame(body('export default 1 + 2 * 1;'), [
                `    let c0: Any<A> = (${two} * ${one})?;`,
                `    let c1: Any<A> = (${one} + c0)?;`,
                '    Ok([(string_key("default"), c1)].to_object().to_any())',
            ])
            // `===` and `!==` import their helpers, as every literal does its own
            assertEq(
                compileSource('export default 1 === 2;')('output.rs').split('\n')[2],
                'use nanvm_lib::vm::unstable::{f64_any, strict_eq, string_key};')
            // the folded negations print as the leaves they lower to
            expect(
                'export default [-1, -1n, - -1, -Infinity, -0];',
                '[f64_any(0xbff0000000000000), bigint_any(-1), f64_any(0x3ff0000000000000), f64_any(0xfff0000000000000), f64_any(0x8000000000000000)].to_array().to_any()')
        },
        // A lazy operator's conditionally established operand prints as
        // the thunk `nanvm-lib` takes — `|| Ok(…)` around a value, an
        // operation's own line bound to a closure — so the `1n / 0n` a
        // `&&` never reaches, or the arm a `?:` does not select, is never
        // run: `nanvm-harness/fixtures/lazy.mjs` runs each against the VM.
        lazyOperators: () => {
            /** The lines of the module's body. @type {(source: string) => readonly string[]} */
            const body = source => compileSource(source)('output.rs').split('\n').filter(line => line.startsWith('    '))
            const one = 'f64_any(0x3ff0000000000000)'
            const two = 'f64_any(0x4000000000000000)'
            assertStructurallySame(body('export default 1 && 2;'), [
                `    let c0: Any<A> = (Any::logical_and(${one}, || Ok(${two})))?;`,
                '    Ok([(string_key("default"), c0)].to_object().to_any())',
            ])
            assertStructurallySame(body('export default false || 1n / 0n;'), [
                '    let c0 = || bigint_any(1) / bigint_any(0);',
                '    let c1: Any<A> = (Any::logical_or(false.to_any(), c0))?;',
                '    Ok([(string_key("default"), c1)].to_object().to_any())',
            ])
            assertStructurallySame(body('export default null ?? 1;'), [
                `    let c0: Any<A> = (Any::nullish_coalescing(Nullish::Null.to_any(), || Ok(${one})))?;`,
                '    Ok([(string_key("default"), c0)].to_object().to_any())',
            ])
            assertStructurallySame(body('export default true ? 1 : 2;'), [
                `    let c0: Any<A> = (Any::conditional(true.to_any(), || Ok(${one}), || Ok(${two})))?;`,
                '    Ok([(string_key("default"), c0)].to_object().to_any())',
            ])
            // a `const` reached only lazily is anchored — a `let` before
            // the root, as JavaScript establishes a `const` at its
            // declaration — and each thunk clones it
            assertStructurallySame(body('const c = [1]; export default [false && c, true && c];'), [
                `    let c0: Any<A> = [${one}].to_array().to_any();`,
                '    let c1: Any<A> = (Any::logical_and(false.to_any(), || Ok(c0.clone())))?;',
                '    let c2: Any<A> = (Any::logical_and(true.to_any(), || Ok(c0.clone())))?;',
                '    let c3: Any<A> = [c1, c2].to_array().to_any();',
                '    Ok([(string_key("default"), c3)].to_object().to_any())',
            ])
            // a function's arguments reached only lazily are no `const`
            // to anchor and need none: the parameter is bound already, so
            // the body binds it once and each thunk clones it
            assertStructurallySame(body('export default (...a) => true ? a : a;'), [
                '    let c0: Any<A> = A::static_function(|_self, args| {',
                '        let rest = args.clone().into_iter().to_array();',
                '        let c0 = || Ok(rest.clone().to_any());',
                '        Any::conditional(true.to_any(), c0, c0)',
                '    }, 0, Array::default(), Some("(...$0)=>true?$0:$0")).to_any();',
                '    Ok([(string_key("default"), c0)].to_object().to_any())',
            ])
            assertStructurallySame(body('export default (...a) => true ? [a] : [a, a];'), [
                '    let c0: Any<A> = A::static_function(|_self, args| {',
                '        let rest = args.clone().into_iter().to_array();',
                '        let c0: Any<A> = rest.clone().to_any();',
                '        let c1 = || Ok([c0.clone()].to_array().to_any());',
                '        let c2 = || Ok([c0.clone(), c0.clone()].to_array().to_any());',
                '        Any::conditional(true.to_any(), c1, c2)',
                '    }, 0, Array::default(), Some("(...$0)=>true?[$0]:[$0,$0]")).to_any();',
                '    Ok([(string_key("default"), c0)].to_object().to_any())',
            ])
        },
        // A shared operation is established once, in its `let`, with the
        // same `?`; each reference clones the value it produced, where a
        // value referenced once — the array — is moved.
        // A `const` inside an arm — a call inlined by the lowering — is a
        // shared node the arm alone reaches, bound in the arm's own block
        // and so established exactly when the arm is taken. Through the
        // whole of `fjs compile`, as the review of the design asked, so
        // that the shape's Rust is pinned by the compiler and not by the
        // corpus.
        inlinedCall: () => {
            assert(compileSource('const f = () => [1]; export default (...a) => a[0] ? (() => { const x = f(); return [x, x]; })() : 4;')('output.rs').includes([
                '        let c1 = || {',
                '            let c2: Any<A> = Any::call(A::frame(self_)[0].clone(), Array::default().to_any())?;',
                '            Ok([c2.clone(), c2.clone()].to_array().to_any())',
                '        };',
                '        Any::conditional(c0, c1, || Ok(f64_any(0x4010000000000000)))',
            ].join('\n')))
            // and one at an eager position, its anchor floated to the
            // scope's root, prints as an anchored `const` does
            assert(compileSource('export default [(() => { const x = null.x; return 1; })()];')('output.rs').includes([
                '    let _: Any<A> = Any::dot(Nullish::Null.to_any(), string_any("x")).end()?;',
                '    let c0: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();',
            ].join('\n')))
        },
        sharedOperation: () => {
            assertStructurallySame(
                compileSource('const a = 1 + 2; export default [a, a];')('output.rs').split('\n').filter(line => line.startsWith('    ')),
                [
                    '    let c0: Any<A> = (f64_any(0x3ff0000000000000) + f64_any(0x4000000000000000))?;',
                    '    let c1: Any<A> = [c0.clone(), c0.clone()].to_array().to_any();',
                    '    Ok([(string_key("default"), c1)].to_object().to_any())',
                ])
        },
    },
}
