inputs:
  node-version:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm ci
      shell: bash
    - run: npm test
      shell: bash
    - run: npm run fst
      shell: bash
    - run: npx tsgo # check types using TypeScript native-preview
      shell: bash
    - run: npm run index
      shell: bash
    - run: npm pack
      shell: bash
