const $m0 = [0];
const $s0 = [0];
const $s1 = [0];
const $s2 = [0];
const $s3 = {};
const $s4 = [0];
const $s5 = [1];
const $s6 = [0];
const $s7 = {};
const $s8 = [0];
const $s9 = {"d": 0, "c": 1};
const $s10 = {"a": 0};
const $s11 = {["__proto__"]: 1};
const $f0 = [null, 0];
const $f1 = [undefined, 0];
const $f2 = [NaN, 0];
const $f3 = [Infinity, 0];
const $f4 = [-Infinity, 0];
const $f5 = [-0, 0];
const $f6 = [false, 0];
const $f7 = [true, 0];
const $f8 = ["", 0];
const $f9 = ["a", 0];
const $f10 = [1n, 0];
const $f11 = [-1n, 0];
const $f12 = [0n, 0];
const $f13 = [-1, 0];
const $f14 = [[], 0];
const $f15 = [{}, 0];
const $g0 = {"a": null, "b": 0};
const $g1 = {"a": undefined, "b": 0};
const $g2 = {"a": NaN, "b": 0};
const $g3 = {"a": Infinity, "b": 0};
const $g4 = {"a": -Infinity, "b": 0};
const $g5 = {"a": -0, "b": 0};
const $g6 = {"a": false, "b": 0};
const $g7 = {"a": true, "b": 0};
const $g8 = {"a": "", "b": 0};
const $g9 = {"a": "a", "b": 0};
const $g10 = {"a": 1n, "b": 0};
const $g11 = {"a": -1n, "b": 0};
const $g12 = {"a": 0n, "b": 0};
const $g13 = {"a": -1, "b": 0};
const $g14 = {"a": [], "b": 0};
const $g15 = {"a": {}, "b": 0};
const $s12 = {"\"": "\"", "\\": "\\", "\b": "\b", "\t": "\t", "\n": "\n", "\f": "\f", "\r": "\r", "\u0000": "\u0000", "\u001f": "\u001f"};
export default [
    {"id": "null", "class": "leaf/null", "document": "export default null;", "graph": null},
    {"id": "true", "class": "leaf/boolean/true", "document": "export default true;", "graph": true},
    {"id": "false", "class": "leaf/boolean/false", "document": "export default false;", "graph": false},
    {"id": "undefined", "class": "leaf/undefined", "document": "export default undefined;", "graph": undefined},
    {"id": "nan", "class": "leaf/nan", "document": "export default NaN;", "graph": NaN},
    {"id": "infinity", "class": "infinity/plus", "document": "export default Infinity;", "graph": Infinity},
    {"id": "neg-infinity", "class": "infinity/minus", "document": "export default -Infinity;", "graph": -Infinity},
    {"id": "number-0", "class": "number/int/zero", "document": "export default 0;", "graph": 0},
    {"id": "number-neg-0", "class": "number/int/zero/neg", "document": "export default -0;", "graph": -0},
    {"id": "number-9", "class": "number/int/digit9", "document": "export default 9;", "graph": 9},
    {"id": "number-neg-9", "class": "number/int/digit9/neg", "document": "export default -9;", "graph": -9},
    {"id": "number-109", "class": "number/int/digits", "document": "export default 109;", "graph": 109},
    {"id": "number-neg-109", "class": "number/int/digits/neg", "document": "export default -109;", "graph": -109},
    {"id": "number-1.09", "class": "number/frac", "document": "export default 1.09;", "graph": 1.09},
    {"id": "number-neg-1.09", "class": "number/frac/neg", "document": "export default -1.09;", "graph": -1.09},
    {"id": "number-1.0", "class": "number/frac/one-digit", "document": "export default 1.0;", "graph": 1},
    {"id": "number-neg-1.0", "class": "number/frac/one-digit/neg", "document": "export default -1.0;", "graph": -1},
    {"id": "number-1.9", "class": "number/frac/one-digit/high", "document": "export default 1.9;", "graph": 1.9},
    {"id": "number-neg-1.9", "class": "number/frac/one-digit/high/neg", "document": "export default -1.9;", "graph": -1.9},
    {"id": "number-1.90", "class": "number/frac/high-first", "document": "export default 1.90;", "graph": 1.9},
    {"id": "number-neg-1.90", "class": "number/frac/high-first/neg", "document": "export default -1.90;", "graph": -1.9},
    {"id": "number-1e0", "class": "number/exp/one-digit/low", "document": "export default 1e0;", "graph": 1},
    {"id": "number-neg-1e0", "class": "number/exp/one-digit/low/neg", "document": "export default -1e0;", "graph": -1},
    {"id": "number-1e9", "class": "number/exp/one-digit/high", "document": "export default 1e9;", "graph": 1e9},
    {"id": "number-neg-1e9", "class": "number/exp/one-digit/high/neg", "document": "export default -1e9;", "graph": -1e9},
    {"id": "number-1e90", "class": "number/exp/high-first", "document": "export default 1e90;", "graph": 1e90},
    {"id": "number-neg-1e90", "class": "number/exp/high-first/neg", "document": "export default -1e90;", "graph": -1e90},
    {"id": "number-1e09", "class": "number/exp/e", "document": "export default 1e09;", "graph": 1e9},
    {"id": "number-neg-1e09", "class": "number/exp/e/neg", "document": "export default -1e09;", "graph": -1e9},
    {"id": "number-1E2", "class": "number/exp/E", "document": "export default 1E2;", "graph": 100},
    {"id": "number-neg-1E2", "class": "number/exp/E/neg", "document": "export default -1E2;", "graph": -100},
    {"id": "number-1e+2", "class": "number/exp/plus", "document": "export default 1e+2;", "graph": 100},
    {"id": "number-neg-1e+2", "class": "number/exp/plus/neg", "document": "export default -1e+2;", "graph": -100},
    {"id": "number-1e-2", "class": "number/exp/minus", "document": "export default 1e-2;", "graph": 0.01},
    {"id": "number-neg-1e-2", "class": "number/exp/minus/neg", "document": "export default -1e-2;", "graph": -0.01},
    {"id": "number-1.09e-2", "class": "number/frac-exp", "document": "export default 1.09e-2;", "graph": 0.0109},
    {"id": "number-neg-1.09e-2", "class": "number/frac-exp/neg", "document": "export default -1.09e-2;", "graph": -0.0109},
    {"id": "number-0.0", "class": "number/zero/frac", "document": "export default 0.0;", "graph": 0},
    {"id": "number-neg-0.0", "class": "number/zero/frac/neg", "document": "export default -0.0;", "graph": -0},
    {"id": "number-0e0", "class": "number/zero/exp", "document": "export default 0e0;", "graph": 0},
    {"id": "number-neg-0e0", "class": "number/zero/exp/neg", "document": "export default -0e0;", "graph": -0},
    {"id": "number-rounding", "class": "number/binary64/rounding", "document": "export default 9007199254740993;", "graph": 9007199254740992},
    {"id": "number-neg-rounding", "class": "number/binary64/rounding/neg", "document": "export default -9007199254740993;", "graph": -9007199254740992},
    {"id": "number-subnormal", "class": "number/binary64/subnormal", "document": "export default 5e-324;", "graph": 5e-324},
    {"id": "number-neg-subnormal", "class": "number/binary64/subnormal/neg", "document": "export default -5e-324;", "graph": -5e-324},
    {"id": "number-underflow", "class": "number/binary64/underflow", "document": "export default 1e-999;", "graph": 0},
    {"id": "number-neg-underflow", "class": "number/binary64/underflow/neg", "document": "export default -1e-999;", "graph": -0},
    {"id": "number-overflow", "class": "number/binary64/overflow", "document": "export default 1e999;", "graph": Infinity},
    {"id": "number-neg-overflow", "class": "number/binary64/overflow/neg", "document": "export default -1e999;", "graph": -Infinity},
    {"id": "number-max", "class": "number/binary64/max", "document": "export default 1.7976931348623157e308;", "graph": 1.7976931348623157e308},
    {"id": "number-neg-max", "class": "number/binary64/max/neg", "document": "export default -1.7976931348623157e308;", "graph": -1.7976931348623157e308},
    {"id": "bigint-0", "class": "bigint/zero", "document": "export default 0n;", "graph": 0n},
    {"id": "bigint-neg-0", "class": "bigint/zero/neg", "document": "export default -0n;", "graph": 0n},
    {"id": "bigint-9", "class": "bigint/digit9", "document": "export default 9n;", "graph": 9n},
    {"id": "bigint-neg-9", "class": "bigint/digit9/neg", "document": "export default -9n;", "graph": -9n},
    {"id": "bigint-109", "class": "bigint/digits", "document": "export default 109n;", "graph": 109n},
    {"id": "bigint-neg-109", "class": "bigint/digits/neg", "document": "export default -109n;", "graph": -109n},
    {"id": "bigint-2p53", "class": "bigint/past-2p53", "document": "export default 9007199254740993n;", "graph": 9007199254740993n},
    {"id": "bigint-neg-2p53", "class": "bigint/past-2p53/neg", "document": "export default -9007199254740993n;", "graph": -9007199254740993n},
    {"id": "bigint-2p64", "class": "bigint/past-2p64", "document": "export default 18446744073709551617n;", "graph": 18446744073709551617n},
    {"id": "bigint-neg-2p64", "class": "bigint/past-2p64/neg", "document": "export default -18446744073709551617n;", "graph": -18446744073709551617n},
    {"id": "bigint-2p128", "class": "bigint/past-2p128", "document": "export default 340282366920938463463374607431768211457n;", "graph": 340282366920938463463374607431768211457n},
    {"id": "bigint-neg-2p128", "class": "bigint/past-2p128/neg", "document": "export default -340282366920938463463374607431768211457n;", "graph": -340282366920938463463374607431768211457n},
    {"id": "string-empty", "class": "string/empty", "document": "export default \"\";", "graph": ""},
    {"id": "key-empty", "class": "key/string/empty", "document": "export default {\"\":0};", "graph": {"": 0}},
    {"id": "string-escape-quote", "class": "string/escape/quote", "document": "export default \"\\\"\";", "graph": "\""},
    {"id": "key-escape-quote", "class": "key/string/escape/quote", "document": "export default {\"\\\"\":0};", "graph": {"\"": 0}},
    {"id": "string-escape-backslash", "class": "string/escape/backslash", "document": "export default \"\\\\\";", "graph": "\\"},
    {"id": "key-escape-backslash", "class": "key/string/escape/backslash", "document": "export default {\"\\\\\":0};", "graph": {"\\": 0}},
    {"id": "string-escape-slash", "class": "string/escape/slash", "document": "export default \"\\/\";", "graph": "/"},
    {"id": "key-escape-slash", "class": "key/string/escape/slash", "document": "export default {\"\\/\":0};", "graph": {"/": 0}},
    {"id": "string-escape-b", "class": "string/escape/b", "document": "export default \"\\b\";", "graph": "\b"},
    {"id": "key-escape-b", "class": "key/string/escape/b", "document": "export default {\"\\b\":0};", "graph": {"\b": 0}},
    {"id": "string-escape-f", "class": "string/escape/f", "document": "export default \"\\f\";", "graph": "\f"},
    {"id": "key-escape-f", "class": "key/string/escape/f", "document": "export default {\"\\f\":0};", "graph": {"\f": 0}},
    {"id": "string-escape-n", "class": "string/escape/n", "document": "export default \"\\n\";", "graph": "\n"},
    {"id": "key-escape-n", "class": "key/string/escape/n", "document": "export default {\"\\n\":0};", "graph": {"\n": 0}},
    {"id": "string-escape-r", "class": "string/escape/r", "document": "export default \"\\r\";", "graph": "\r"},
    {"id": "key-escape-r", "class": "key/string/escape/r", "document": "export default {\"\\r\":0};", "graph": {"\r": 0}},
    {"id": "string-escape-t", "class": "string/escape/t", "document": "export default \"\\t\";", "graph": "\t"},
    {"id": "key-escape-t", "class": "key/string/escape/t", "document": "export default {\"\\t\":0};", "graph": {"\t": 0}},
    {"id": "string-escape-u-09af", "class": "string/escape/u/09af", "document": "export default \"\\u09af\";", "graph": "\u09af"},
    {"id": "key-escape-u-09af", "class": "key/string/escape/u/09af", "document": "export default {\"\\u09af\":0};", "graph": {"\u09af": 0}},
    {"id": "string-escape-u-9afA", "class": "string/escape/u/9afA", "document": "export default \"\\u9afA\";", "graph": "\u9afa"},
    {"id": "key-escape-u-9afA", "class": "key/string/escape/u/9afA", "document": "export default {\"\\u9afA\":0};", "graph": {"\u9afa": 0}},
    {"id": "string-escape-u-afAF", "class": "string/escape/u/afAF", "document": "export default \"\\uafAF\";", "graph": "\uafaf"},
    {"id": "key-escape-u-afAF", "class": "key/string/escape/u/afAF", "document": "export default {\"\\uafAF\":0};", "graph": {"\uafaf": 0}},
    {"id": "string-escape-u-fAF0", "class": "string/escape/u/fAF0", "document": "export default \"\\ufAF0\";", "graph": "\ufaf0"},
    {"id": "key-escape-u-fAF0", "class": "key/string/escape/u/fAF0", "document": "export default {\"\\ufAF0\":0};", "graph": {"\ufaf0": 0}},
    {"id": "string-escape-u-AF09", "class": "string/escape/u/AF09", "document": "export default \"\\uAF09\";", "graph": "\uaf09"},
    {"id": "key-escape-u-AF09", "class": "key/string/escape/u/AF09", "document": "export default {\"\\uAF09\":0};", "graph": {"\uaf09": 0}},
    {"id": "string-escape-u-F09a", "class": "string/escape/u/F09a", "document": "export default \"\\uF09a\";", "graph": "\uf09a"},
    {"id": "key-escape-u-F09a", "class": "key/string/escape/u/F09a", "document": "export default {\"\\uF09a\":0};", "graph": {"\uf09a": 0}},
    {"id": "string-raw-slash", "class": "string/raw/slash", "document": "export default \"/\";", "graph": "/"},
    {"id": "key-raw-slash", "class": "key/string/raw/slash", "document": "export default {\"/\":0};", "graph": {"/": 0}},
    {"id": "string-raw-latin", "class": "string/raw/bmp", "document": "export default \"\u00e9\";", "graph": "\u00e9"},
    {"id": "key-raw-latin", "class": "key/string/raw/bmp", "document": "export default {\"\u00e9\":0};", "graph": {"\u00e9": 0}},
    {"id": "string-raw-cjk", "class": "string/raw/bmp", "document": "export default \"\u4e2d\";", "graph": "\u4e2d"},
    {"id": "key-raw-cjk", "class": "key/string/raw/bmp", "document": "export default {\"\u4e2d\":0};", "graph": {"\u4e2d": 0}},
    {"id": "string-raw-astral", "class": "string/raw/astral", "document": "export default \"\ud83d\ude00\";", "graph": "\ud83d\ude00"},
    {"id": "key-raw-astral", "class": "key/string/raw/astral", "document": "export default {\"\ud83d\ude00\":0};", "graph": {"\ud83d\ude00": 0}},
    {"id": "string-raw-0020", "class": "string/raw/range/0020-0021/low", "document": "export default \" \";", "graph": " "},
    {"id": "key-raw-0020", "class": "key/string/raw/range/0020-0021/low", "document": "export default {\" \":0};", "graph": {" ": 0}},
    {"id": "string-raw-0021", "class": "string/raw/range/0020-0021/high", "document": "export default \"!\";", "graph": "!"},
    {"id": "key-raw-0021", "class": "key/string/raw/range/0020-0021/high", "document": "export default {\"!\":0};", "graph": {"!": 0}},
    {"id": "string-raw-0023", "class": "string/raw/range/0023-005b/low", "document": "export default \"#\";", "graph": "#"},
    {"id": "key-raw-0023", "class": "key/string/raw/range/0023-005b/low", "document": "export default {\"#\":0};", "graph": {"#": 0}},
    {"id": "string-raw-005b", "class": "string/raw/range/0023-005b/high", "document": "export default \"[\";", "graph": "["},
    {"id": "key-raw-005b", "class": "key/string/raw/range/0023-005b/high", "document": "export default {\"[\":0};", "graph": {"[": 0}},
    {"id": "string-raw-005d", "class": "string/raw/range/005d-10ffff/low", "document": "export default \"]\";", "graph": "]"},
    {"id": "key-raw-005d", "class": "key/string/raw/range/005d-10ffff/low", "document": "export default {\"]\":0};", "graph": {"]": 0}},
    {"id": "string-raw-10ffff", "class": "string/raw/range/005d-10ffff/high", "document": "export default \"\udbff\udfff\";", "graph": "\udbff\udfff"},
    {"id": "key-raw-10ffff", "class": "key/string/raw/range/005d-10ffff/high", "document": "export default {\"\udbff\udfff\":0};", "graph": {"\udbff\udfff": 0}},
    {"id": "string-raw-ws-like-2028", "class": "string/raw/ws-like/2028", "document": "export default \"\u2028\";", "graph": "\u2028"},
    {"id": "key-raw-ws-like-2028", "class": "key/string/raw/ws-like/2028", "document": "export default {\"\u2028\":0};", "graph": {"\u2028": 0}},
    {"id": "string-raw-ws-like-2029", "class": "string/raw/ws-like/2029", "document": "export default \"\u2029\";", "graph": "\u2029"},
    {"id": "key-raw-ws-like-2029", "class": "key/string/raw/ws-like/2029", "document": "export default {\"\u2029\":0};", "graph": {"\u2029": 0}},
    {"id": "string-raw-ws-like-feff", "class": "string/raw/ws-like/feff", "document": "export default \"\ufeff\";", "graph": "\ufeff"},
    {"id": "key-raw-ws-like-feff", "class": "key/string/raw/ws-like/feff", "document": "export default {\"\ufeff\":0};", "graph": {"\ufeff": 0}},
    {"id": "string-raw-ws-like-00a0", "class": "string/raw/ws-like/00a0", "document": "export default \"\u00a0\";", "graph": "\u00a0"},
    {"id": "key-raw-ws-like-00a0", "class": "key/string/raw/ws-like/00a0", "document": "export default {\"\u00a0\":0};", "graph": {"\u00a0": 0}},
    {"id": "string-raw-ws-like-1680", "class": "string/raw/ws-like/1680", "document": "export default \"\u1680\";", "graph": "\u1680"},
    {"id": "key-raw-ws-like-1680", "class": "key/string/raw/ws-like/1680", "document": "export default {\"\u1680\":0};", "graph": {"\u1680": 0}},
    {"id": "string-raw-ws-like-2000", "class": "string/raw/ws-like/2000", "document": "export default \"\u2000\";", "graph": "\u2000"},
    {"id": "key-raw-ws-like-2000", "class": "key/string/raw/ws-like/2000", "document": "export default {\"\u2000\":0};", "graph": {"\u2000": 0}},
    {"id": "string-raw-ws-like-2001", "class": "string/raw/ws-like/2001", "document": "export default \"\u2001\";", "graph": "\u2001"},
    {"id": "key-raw-ws-like-2001", "class": "key/string/raw/ws-like/2001", "document": "export default {\"\u2001\":0};", "graph": {"\u2001": 0}},
    {"id": "string-raw-ws-like-2002", "class": "string/raw/ws-like/2002", "document": "export default \"\u2002\";", "graph": "\u2002"},
    {"id": "key-raw-ws-like-2002", "class": "key/string/raw/ws-like/2002", "document": "export default {\"\u2002\":0};", "graph": {"\u2002": 0}},
    {"id": "string-raw-ws-like-2003", "class": "string/raw/ws-like/2003", "document": "export default \"\u2003\";", "graph": "\u2003"},
    {"id": "key-raw-ws-like-2003", "class": "key/string/raw/ws-like/2003", "document": "export default {\"\u2003\":0};", "graph": {"\u2003": 0}},
    {"id": "string-raw-ws-like-2004", "class": "string/raw/ws-like/2004", "document": "export default \"\u2004\";", "graph": "\u2004"},
    {"id": "key-raw-ws-like-2004", "class": "key/string/raw/ws-like/2004", "document": "export default {\"\u2004\":0};", "graph": {"\u2004": 0}},
    {"id": "string-raw-ws-like-2005", "class": "string/raw/ws-like/2005", "document": "export default \"\u2005\";", "graph": "\u2005"},
    {"id": "key-raw-ws-like-2005", "class": "key/string/raw/ws-like/2005", "document": "export default {\"\u2005\":0};", "graph": {"\u2005": 0}},
    {"id": "string-raw-ws-like-2006", "class": "string/raw/ws-like/2006", "document": "export default \"\u2006\";", "graph": "\u2006"},
    {"id": "key-raw-ws-like-2006", "class": "key/string/raw/ws-like/2006", "document": "export default {\"\u2006\":0};", "graph": {"\u2006": 0}},
    {"id": "string-raw-ws-like-2007", "class": "string/raw/ws-like/2007", "document": "export default \"\u2007\";", "graph": "\u2007"},
    {"id": "key-raw-ws-like-2007", "class": "key/string/raw/ws-like/2007", "document": "export default {\"\u2007\":0};", "graph": {"\u2007": 0}},
    {"id": "string-raw-ws-like-2008", "class": "string/raw/ws-like/2008", "document": "export default \"\u2008\";", "graph": "\u2008"},
    {"id": "key-raw-ws-like-2008", "class": "key/string/raw/ws-like/2008", "document": "export default {\"\u2008\":0};", "graph": {"\u2008": 0}},
    {"id": "string-raw-ws-like-2009", "class": "string/raw/ws-like/2009", "document": "export default \"\u2009\";", "graph": "\u2009"},
    {"id": "key-raw-ws-like-2009", "class": "key/string/raw/ws-like/2009", "document": "export default {\"\u2009\":0};", "graph": {"\u2009": 0}},
    {"id": "string-raw-ws-like-200a", "class": "string/raw/ws-like/200a", "document": "export default \"\u200a\";", "graph": "\u200a"},
    {"id": "key-raw-ws-like-200a", "class": "key/string/raw/ws-like/200a", "document": "export default {\"\u200a\":0};", "graph": {"\u200a": 0}},
    {"id": "string-raw-ws-like-202f", "class": "string/raw/ws-like/202f", "document": "export default \"\u202f\";", "graph": "\u202f"},
    {"id": "key-raw-ws-like-202f", "class": "key/string/raw/ws-like/202f", "document": "export default {\"\u202f\":0};", "graph": {"\u202f": 0}},
    {"id": "string-raw-ws-like-205f", "class": "string/raw/ws-like/205f", "document": "export default \"\u205f\";", "graph": "\u205f"},
    {"id": "key-raw-ws-like-205f", "class": "key/string/raw/ws-like/205f", "document": "export default {\"\u205f\":0};", "graph": {"\u205f": 0}},
    {"id": "string-raw-ws-like-3000", "class": "string/raw/ws-like/3000", "document": "export default \"\u3000\";", "graph": "\u3000"},
    {"id": "key-raw-ws-like-3000", "class": "key/string/raw/ws-like/3000", "document": "export default {\"\u3000\":0};", "graph": {"\u3000": 0}},
    {"id": "string-surrogate-lone-d800", "class": "string/surrogate/lone/d800", "document": "export default \"\\ud800\";", "graph": "\ud800"},
    {"id": "key-surrogate-lone-d800", "class": "key/string/surrogate/lone/d800", "document": "export default {\"\\ud800\":0};", "graph": {"\ud800": 0}},
    {"id": "string-surrogate-lone-dbff", "class": "string/surrogate/lone/dbff", "document": "export default \"\\udbff\";", "graph": "\udbff"},
    {"id": "key-surrogate-lone-dbff", "class": "key/string/surrogate/lone/dbff", "document": "export default {\"\\udbff\":0};", "graph": {"\udbff": 0}},
    {"id": "string-surrogate-lone-dc00", "class": "string/surrogate/lone/dc00", "document": "export default \"\\udc00\";", "graph": "\udc00"},
    {"id": "key-surrogate-lone-dc00", "class": "key/string/surrogate/lone/dc00", "document": "export default {\"\\udc00\":0};", "graph": {"\udc00": 0}},
    {"id": "string-surrogate-lone-dfff", "class": "string/surrogate/lone/dfff", "document": "export default \"\\udfff\";", "graph": "\udfff"},
    {"id": "key-surrogate-lone-dfff", "class": "key/string/surrogate/lone/dfff", "document": "export default {\"\\udfff\":0};", "graph": {"\udfff": 0}},
    {"id": "string-surrogate-lone-raw-d800", "class": "string/surrogate/lone/raw/d800", "document": "export default \"\ud800\";", "graph": "\ud800"},
    {"id": "key-surrogate-lone-raw-d800", "class": "key/string/surrogate/lone/raw/d800", "document": "export default {\"\ud800\":0};", "graph": {"\ud800": 0}},
    {"id": "string-surrogate-lone-raw-dbff", "class": "string/surrogate/lone/raw/dbff", "document": "export default \"\udbff\";", "graph": "\udbff"},
    {"id": "key-surrogate-lone-raw-dbff", "class": "key/string/surrogate/lone/raw/dbff", "document": "export default {\"\udbff\":0};", "graph": {"\udbff": 0}},
    {"id": "string-surrogate-lone-raw-dc00", "class": "string/surrogate/lone/raw/dc00", "document": "export default \"\udc00\";", "graph": "\udc00"},
    {"id": "key-surrogate-lone-raw-dc00", "class": "key/string/surrogate/lone/raw/dc00", "document": "export default {\"\udc00\":0};", "graph": {"\udc00": 0}},
    {"id": "string-surrogate-lone-raw-dfff", "class": "string/surrogate/lone/raw/dfff", "document": "export default \"\udfff\";", "graph": "\udfff"},
    {"id": "key-surrogate-lone-raw-dfff", "class": "key/string/surrogate/lone/raw/dfff", "document": "export default {\"\udfff\":0};", "graph": {"\udfff": 0}},
    {"id": "string-surrogate-pair-interior", "class": "string/surrogate/pair/interior", "document": "export default \"\\ud83d\\ude00\";", "graph": "\ud83d\ude00"},
    {"id": "key-surrogate-pair-interior", "class": "key/string/surrogate/pair/interior", "document": "export default {\"\\ud83d\\ude00\":0};", "graph": {"\ud83d\ude00": 0}},
    {"id": "string-surrogate-pair-low-corner", "class": "string/surrogate/pair/low-corner", "document": "export default \"\\ud800\\udc00\";", "graph": "\ud800\udc00"},
    {"id": "key-surrogate-pair-low-corner", "class": "key/string/surrogate/pair/low-corner", "document": "export default {\"\\ud800\\udc00\":0};", "graph": {"\ud800\udc00": 0}},
    {"id": "string-surrogate-pair-high-corner", "class": "string/surrogate/pair/high-corner", "document": "export default \"\\udbff\\udfff\";", "graph": "\udbff\udfff"},
    {"id": "key-surrogate-pair-high-corner", "class": "key/string/surrogate/pair/high-corner", "document": "export default {\"\\udbff\\udfff\":0};", "graph": {"\udbff\udfff": 0}},
    {"id": "string-surrogate-pair-mixed", "class": "string/surrogate/pair/mixed", "document": "export default \"\\ud800\\udfff\";", "graph": "\ud800\udfff"},
    {"id": "key-surrogate-pair-mixed", "class": "key/string/surrogate/pair/mixed", "document": "export default {\"\\ud800\\udfff\":0};", "graph": {"\ud800\udfff": 0}},
    {"id": "string-surrogate-adjacent-hh-d800", "class": "string/surrogate/adjacent/hh-d800", "document": "export default \"\\ud800\\ud800\";", "graph": "\ud800\ud800"},
    {"id": "key-surrogate-adjacent-hh-d800", "class": "key/string/surrogate/adjacent/hh-d800", "document": "export default {\"\\ud800\\ud800\":0};", "graph": {"\ud800\ud800": 0}},
    {"id": "string-surrogate-adjacent-lh-dc00-d800", "class": "string/surrogate/adjacent/lh-dc00-d800", "document": "export default \"\\udc00\\ud800\";", "graph": "\udc00\ud800"},
    {"id": "key-surrogate-adjacent-lh-dc00-d800", "class": "key/string/surrogate/adjacent/lh-dc00-d800", "document": "export default {\"\\udc00\\ud800\":0};", "graph": {"\udc00\ud800": 0}},
    {"id": "string-surrogate-adjacent-ll-dc00", "class": "string/surrogate/adjacent/ll-dc00", "document": "export default \"\\udc00\\udc00\";", "graph": "\udc00\udc00"},
    {"id": "key-surrogate-adjacent-ll-dc00", "class": "key/string/surrogate/adjacent/ll-dc00", "document": "export default {\"\\udc00\\udc00\":0};", "graph": {"\udc00\udc00": 0}},
    {"id": "string-surrogate-adjacent-hh-dbff", "class": "string/surrogate/adjacent/hh-dbff", "document": "export default \"\\udbff\\udbff\";", "graph": "\udbff\udbff"},
    {"id": "key-surrogate-adjacent-hh-dbff", "class": "key/string/surrogate/adjacent/hh-dbff", "document": "export default {\"\\udbff\\udbff\":0};", "graph": {"\udbff\udbff": 0}},
    {"id": "string-surrogate-adjacent-lh-dfff-dbff", "class": "string/surrogate/adjacent/lh-dfff-dbff", "document": "export default \"\\udfff\\udbff\";", "graph": "\udfff\udbff"},
    {"id": "key-surrogate-adjacent-lh-dfff-dbff", "class": "key/string/surrogate/adjacent/lh-dfff-dbff", "document": "export default {\"\\udfff\\udbff\":0};", "graph": {"\udfff\udbff": 0}},
    {"id": "string-surrogate-adjacent-ll-dfff", "class": "string/surrogate/adjacent/ll-dfff", "document": "export default \"\\udfff\\udfff\";", "graph": "\udfff\udfff"},
    {"id": "key-surrogate-adjacent-ll-dfff", "class": "key/string/surrogate/adjacent/ll-dfff", "document": "export default {\"\\udfff\\udfff\":0};", "graph": {"\udfff\udfff": 0}},
    {"id": "string-surrogate-adjacent-hh-d800-dbff", "class": "string/surrogate/adjacent/hh-d800-dbff", "document": "export default \"\\ud800\\udbff\";", "graph": "\ud800\udbff"},
    {"id": "key-surrogate-adjacent-hh-d800-dbff", "class": "key/string/surrogate/adjacent/hh-d800-dbff", "document": "export default {\"\\ud800\\udbff\":0};", "graph": {"\ud800\udbff": 0}},
    {"id": "array-empty", "class": "array/empty", "document": "export default [];", "graph": []},
    {"id": "array-one", "class": "array/one", "document": "export default [1];", "graph": [1]},
    {"id": "array-two", "class": "array/two", "document": "export default [1,2];", "graph": [1, 2]},
    {"id": "array-three", "class": "array/three", "document": "export default [1,2,3];", "graph": [1, 2, 3]},
    {"id": "array-nested-array", "class": "array/nested/array", "document": "export default [[1]];", "graph": [[1]]},
    {"id": "array-nested-object", "class": "array/nested/object", "document": "export default [{\"a\":1}];", "graph": [{"a": 1}]},
    {"id": "array-nested-empty", "class": "array/nested/empty", "document": "export default [[],{}];", "graph": [[], {}]},
    {"id": "array-elements-every-value", "class": "array/elements/every-value", "document": "const $0=1;export default [null,true,false,undefined,NaN,Infinity,-Infinity,0,-0,9,-9,1.5,1e2,1n,-1n,\"\",\"a\",\"\u2028\",\"\\ud800\",\"\\u0000\",\"\\ud800\\udc00\",[],{},$0];", "graph": [null, true, false, undefined, NaN, Infinity, -Infinity, 0, -0, 9, -9, 1.5, 100, 1n, -1n, "", "a", "\u2028", "\ud800", "\u0000", "\ud800\udc00", [], {}, 1]},
    {"id": "array-elements-negative-first", "class": "array/elements/negative-first", "document": "export default [-1,-1n,-Infinity];", "graph": [-1, -1n, -Infinity]},
    {"id": "array-nested-deep", "class": "array/nested/deep", "document": "export default [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]];", "graph": [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]},
    {"id": "object-empty", "class": "object/empty", "document": "export default {};", "graph": {}},
    {"id": "object-one", "class": "object/one", "document": "export default {\"a\":1};", "graph": {"a": 1}},
    {"id": "object-two", "class": "object/two", "document": "export default {\"a\":1,\"b\":2};", "graph": {"a": 1, "b": 2}},
    {"id": "object-three", "class": "object/three", "document": "export default {\"a\":1,\"b\":2,\"c\":3};", "graph": {"a": 1, "b": 2, "c": 3}},
    {"id": "object-nested-object", "class": "object/nested/object", "document": "export default {\"a\":{\"b\":1}};", "graph": {"a": {"b": 1}}},
    {"id": "object-nested-array", "class": "object/nested/array", "document": "export default {\"a\":[1]};", "graph": {"a": [1]}},
    {"id": "object-nested-empty", "class": "object/nested/empty", "document": "export default {\"a\":{},\"b\":[]};", "graph": {"a": {}, "b": []}},
    {"id": "object-members-every-value", "class": "object/members/every-value", "document": "const $0=1;export default {\"a\":null,\"b\":true,\"c\":false,\"d\":undefined,\"e\":NaN,\"f\":Infinity,\"g\":-Infinity,\"h\":0,\"i\":-0,\"j\":9,\"k\":-9,\"l\":1.5,\"m\":1e2,\"n\":1n,\"o\":-1n,\"p\":\"\",\"q\":\"a\",\"r\":[],\"s\":{},\"t\":$0,\"u\":\"\u2028\",\"v\":\"\\ud800\",\"w\":\"\\u0000\",\"x\":\"\\ud800\\udc00\"};", "graph": {"a": null, "b": true, "c": false, "d": undefined, "e": NaN, "f": Infinity, "g": -Infinity, "h": 0, "i": -0, "j": 9, "k": -9, "l": 1.5, "m": 100, "n": 1n, "o": -1n, "p": "", "q": "a", "r": [], "s": {}, "t": 1, "u": "\u2028", "v": "\ud800", "w": "\u0000", "x": "\ud800\udc00"}},
    {"id": "object-nested-deep", "class": "object/nested/deep", "document": "export default {\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":{\"a\":1}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}};", "graph": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": {"a": 1}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}},
    {"id": "mixed-nested", "class": "array/object/nested/mixed", "document": "export default [{\"a\":[{\"b\":[]}]},[{\"c\":{}}]];", "graph": [{"a": [{"b": []}]}, [{"c": {}}]]},
    {"id": "key-proto", "class": "key/proto", "document": "export default {[\"__proto__\"]:1};", "graph": {["__proto__"]: 1}},
    {"id": "key-proto-among", "class": "key/proto/among", "document": "export default {\"a\":1,[\"__proto__\"]:2,\"b\":3};", "graph": {"a": 1, ["__proto__"]: 2, "b": 3}},
    {"id": "key-proto-nested", "class": "key/proto/nested", "document": "export default [{[\"__proto__\"]:{[\"__proto__\"]:1}}];", "graph": [{["__proto__"]: {["__proto__"]: 1}}]},
    {"id": "key-proto-value-object", "class": "key/proto/value/object", "document": "export default {[\"__proto__\"]:{\"a\":1}};", "graph": {["__proto__"]: {"a": 1}}},
    {"id": "key-proto-value-null", "class": "key/proto/value/null", "document": "export default {[\"__proto__\"]:null};", "graph": {["__proto__"]: null}},
    {"id": "key-proto-shared", "class": "key/proto/value/shared", "document": "const $0=[0];export default {[\"__proto__\"]:$0,\"a\":$0};", "graph": {["__proto__"]: $s0, "a": $s0}},
    {"id": "object-duplicate-plain", "class": "object/duplicate/plain", "document": "export default {\"a\":1,\"b\":2,\"a\":3};", "graph": {"a": 3, "b": 2}},
    {"id": "object-duplicate-first", "class": "object/duplicate/adjacent", "document": "export default {\"a\":1,\"a\":2};", "graph": {"a": 2}},
    {"id": "object-duplicate-three", "class": "object/duplicate/three", "document": "export default {\"a\":1,\"b\":2,\"a\":3,\"c\":4,\"a\":5};", "graph": {"a": 5, "b": 2, "c": 4}},
    {"id": "object-duplicate-escaped", "class": "object/duplicate/escaped", "document": "export default {\"a\":1,\"\\u0061\":2};", "graph": {"a": 2}},
    {"id": "object-duplicate-escaped-first", "class": "object/duplicate/escaped-first", "document": "export default {\"\\u0061\":1,\"b\":2,\"a\":3};", "graph": {"a": 3, "b": 2}},
    {"id": "object-duplicate-proto", "class": "object/duplicate/proto", "document": "export default {[\"__proto__\"]:1,\"a\":2,[\"__proto__\"]:3};", "graph": {["__proto__"]: 3, "a": 2}},
    {"id": "object-duplicate-index", "class": "object/duplicate/index", "document": "export default {\"1\":0,\"0\":1,\"1\":2};", "graph": {"0": 1, "1": 2}},
    {"id": "object-duplicate-nested", "class": "object/duplicate/nested", "document": "export default {\"a\":{\"b\":1,\"b\":2},\"c\":[{\"d\":1,\"d\":2}]};", "graph": {"a": {"b": 2}, "c": [{"d": 2}]}},
    {"id": "object-duplicate-both-levels", "class": "object/duplicate/both-levels", "document": "export default {\"a\":{\"b\":1},\"a\":{\"c\":1,\"c\":2}};", "graph": {"a": {"c": 2}}},
    {"id": "object-key-order-index-first", "class": "object/key-order/index-first", "document": "export default {\"2\":0,\"1\":0};", "graph": {"1": 0, "2": 0}},
    {"id": "object-key-order-index-before-name", "class": "object/key-order/index-before-name", "document": "export default {\"z\":0,\"1\":1};", "graph": {"1": 1, "z": 0}},
    {"id": "object-key-order-boundaries", "class": "object/key-order/boundaries", "document": "export default {\"z\":0,\"4294967295\":0,\"4294967294\":0,\"2147483648\":0,\"1\":0,\"01\":0,\"1.0\":0,\"0\":0};", "graph": {"0": 0, "1": 0, "2147483648": 0, "4294967294": 0, "z": 0, "4294967295": 0, "01": 0, "1.0": 0}},
    {"id": "object-key-order-non-index-negative", "class": "object/key-order/non-index/negative", "document": "export default {\"-1\":0,\"1\":1};", "graph": {"1": 1, "-1": 0}},
    {"id": "object-key-order-non-index-negative-zero", "class": "object/key-order/non-index/negative-zero", "document": "export default {\"-0\":0,\"0\":1};", "graph": {"0": 1, "-0": 0}},
    {"id": "object-key-order-non-index-plus", "class": "object/key-order/non-index/plus", "document": "export default {\"+1\":0,\"1\":1};", "graph": {"1": 1, "+1": 0}},
    {"id": "object-key-order-non-index-space", "class": "object/key-order/non-index/space", "document": "export default {\" 1\":0,\"1\":1};", "graph": {"1": 1, " 1": 0}},
    {"id": "object-key-order-non-index-hex", "class": "object/key-order/non-index/hex", "document": "export default {\"0x1\":0,\"1\":1};", "graph": {"1": 1, "0x1": 0}},
    {"id": "object-key-order-non-index-exp", "class": "object/key-order/non-index/exp", "document": "export default {\"1e0\":0,\"1\":1};", "graph": {"1": 1, "1e0": 0}},
    {"id": "object-key-order-non-index-above", "class": "object/key-order/non-index/above", "document": "export default {\"4294967296\":0,\"4294967294\":1};", "graph": {"4294967294": 1, "4294967296": 0}},
    {"id": "object-key-order-names-first-occurrence", "class": "object/key-order/names/first-occurrence", "document": "export default {\"b\":0,\"a\":1,\"c\":2};", "graph": {"b": 0, "a": 1, "c": 2}},
    {"id": "object-key-order-escaped-index", "class": "object/key-order/escaped-index", "document": "export default {\"z\":0,\"\\u0031\":1};", "graph": {"1": 1, "z": 0}},
    {"id": "const-one", "class": "const/one", "document": "const $0=1;export default $0;", "graph": 1},
    {"id": "const-two", "class": "const/two", "document": "const $0=1;const $1=2;export default [$0,$1];", "graph": [1, 2]},
    {"id": "const-unreferenced", "class": "const/unreferenced", "document": "const $0=1;export default 2;", "graph": 2},
    {"id": "const-unreferenced-among", "class": "const/unreferenced/among", "document": "const $0=1;const $1=2;const $2=3;export default [$0,$2];", "graph": [1, 3]},
    {"id": "const-reference-element", "class": "const/reference/element", "document": "const $0=1;export default [$0];", "graph": [1]},
    {"id": "const-reference-member", "class": "const/reference/member", "document": "const $0=1;export default {\"a\":$0};", "graph": {"a": 1}},
    {"id": "const-reference-chain", "class": "const/reference/chain", "document": "const $0=1;const $1=$0;export default $1;", "graph": 1},
    {"id": "const-reference-chain-shared", "class": "const/reference/chain/shared", "document": "const $0=[0];const $1=$0;export default [$0,$1];", "graph": [$s1, $s1]},
    {"id": "const-value-every", "class": "const/value/every-alternative", "document": "const $a=null;const $b=true;const $c=false;const $d=undefined;const $e=NaN;const $f=Infinity;const $g=-Infinity;const $h=-0;const $i=1n;const $j=\"a\";const $k=[];const $l={};export default [$a,$b,$c,$d,$e,$f,$g,$h,$i,$j,$k,$l];", "graph": [null, true, false, undefined, NaN, Infinity, -Infinity, -0, 1n, "a", [], {}]},
    {"id": "const-shared-twice", "class": "const/shared/twice", "document": "const $0=[0];export default [$0,$0];", "graph": [$s2, $s2]},
    {"id": "const-shared-object", "class": "const/shared/object", "document": "const $0={};export default {\"a\":$0,\"b\":$0};", "graph": {"a": $s3, "b": $s3}},
    {"id": "const-shared-nested", "class": "const/shared/nested", "document": "const $0=[0];const $1=[$0];export default [$0,$1];", "graph": [$s4, [$s4]]},
    {"id": "const-shared-three-paths", "class": "const/shared/three-paths", "document": "const $0=[1];const $1={\"a\":$0};export default [$0,$1,{\"b\":[$0]}];", "graph": [$s5, {"a": $s5}, {"b": [$s5]}]},
    {"id": "const-shared-two-nodes", "class": "const/shared/two-nodes", "document": "const $0=[0];const $1={};export default [$0,$1,$0,$1];", "graph": [$s6, $s7, $s6, $s7]},
    {"id": "const-shared-leaf", "class": "const/shared/leaf", "document": "const $0=\"a\";export default [$0,$0];", "graph": ["a", "a"]},
    {"id": "array-unshared", "class": "array/unshared", "document": "export default [[],[]];", "graph": [[], []]},
    {"id": "object-unshared", "class": "object/unshared", "document": "export default [{},{}];", "graph": [{}, {}]},
    {"id": "array-unshared-equal", "class": "array/unshared/equal", "document": "export default [[1],[1]];", "graph": [[1], [1]]},
    {"id": "const-unshared-twins", "class": "const/unshared/twins", "document": "const $0=[];const $1=[];export default [$0,$1];", "graph": [[], []]},
    {"id": "id-empty-tail", "class": "id/tail/empty", "document": "const $=1;export default $;", "graph": 1},
    {"id": "id-tail-dollar", "class": "id/tail/dollar", "document": "const $$=1;export default $$;", "graph": 1},
    {"id": "id-tail-endpoints", "class": "id/tail/endpoints", "document": "const $azAZ09_$=1;export default $azAZ09_$;", "graph": 1},
    {"id": "id-tail-digit-first", "class": "id/tail/digit-first", "document": "const $0=1;export default $0;", "graph": 1},
    {"id": "id-tail-one-a", "class": "id/tail/one/a", "document": "const $a=1;export default $a;", "graph": 1},
    {"id": "id-tail-one-z", "class": "id/tail/one/z", "document": "const $z=1;export default $z;", "graph": 1},
    {"id": "id-tail-one-A", "class": "id/tail/one/A", "document": "const $A=1;export default $A;", "graph": 1},
    {"id": "id-tail-one-Z", "class": "id/tail/one/Z", "document": "const $Z=1;export default $Z;", "graph": 1},
    {"id": "id-tail-one-9", "class": "id/tail/one/9", "document": "const $9=1;export default $9;", "graph": 1},
    {"id": "id-tail-one-underscore", "class": "id/tail/one/underscore", "document": "const $_=1;export default $_;", "graph": 1},
    {"id": "id-tail-long", "class": "id/tail/long", "document": "const $aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=1;export default $aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;", "graph": 1},
    {"id": "id-tail-reserved-class", "class": "id/tail/reserved/class", "document": "const $class=1;export default $class;", "graph": 1},
    {"id": "id-tail-reserved-await", "class": "id/tail/reserved/await", "document": "const $await=1;export default $await;", "graph": 1},
    {"id": "id-tail-reserved-eval", "class": "id/tail/reserved/eval", "document": "const $eval=1;export default $eval;", "graph": 1},
    {"id": "id-tail-reserved-let", "class": "id/tail/reserved/let", "document": "const $let=1;export default $let;", "graph": 1},
    {"id": "id-tail-reserved-yield", "class": "id/tail/reserved/yield", "document": "const $yield=1;export default $yield;", "graph": 1},
    {"id": "id-tail-reserved-enum", "class": "id/tail/reserved/enum", "document": "const $enum=1;export default $enum;", "graph": 1},
    {"id": "id-tail-reserved-arguments", "class": "id/tail/reserved/arguments", "document": "const $arguments=1;export default $arguments;", "graph": 1},
    {"id": "id-tail-reserved-import", "class": "id/tail/reserved/import", "document": "const $import=1;export default $import;", "graph": 1},
    {"id": "id-tail-reserved-static", "class": "id/tail/reserved/static", "document": "const $static=1;export default $static;", "graph": 1},
    {"id": "id-tail-reserved-var", "class": "id/tail/reserved/var", "document": "const $var=1;export default $var;", "graph": 1},
    {"id": "id-tail-reserved-function", "class": "id/tail/reserved/function", "document": "const $function=1;export default $function;", "graph": 1},
    {"id": "id-tail-reserved-new", "class": "id/tail/reserved/new", "document": "const $new=1;export default $new;", "graph": 1},
    {"id": "id-tail-reserved-this", "class": "id/tail/reserved/this", "document": "const $this=1;export default $this;", "graph": 1},
    {"id": "id-tail-reserved-delete", "class": "id/tail/reserved/delete", "document": "const $delete=1;export default $delete;", "graph": 1},
    {"id": "id-tail-reserved-typeof", "class": "id/tail/reserved/typeof", "document": "const $typeof=1;export default $typeof;", "graph": 1},
    {"id": "id-tail-reserved-in", "class": "id/tail/reserved/in", "document": "const $in=1;export default $in;", "graph": 1},
    {"id": "id-tail-reserved-if", "class": "id/tail/reserved/if", "document": "const $if=1;export default $if;", "graph": 1},
    {"id": "id-tail-reserved-with", "class": "id/tail/reserved/with", "document": "const $with=1;export default $with;", "graph": 1},
    {"id": "id-tail-value-word-undefined", "class": "id/tail/value-word/undefined", "document": "const $undefined=1;export default $undefined;", "graph": 1},
    {"id": "id-tail-value-word-NaN", "class": "id/tail/value-word/NaN", "document": "const $NaN=1;export default $NaN;", "graph": 1},
    {"id": "id-tail-value-word-Infinity", "class": "id/tail/value-word/Infinity", "document": "const $Infinity=1;export default $Infinity;", "graph": 1},
    {"id": "id-tail-value-word-null", "class": "id/tail/value-word/null", "document": "const $null=1;export default $null;", "graph": 1},
    {"id": "id-tail-value-word-true", "class": "id/tail/value-word/true", "document": "const $true=1;export default $true;", "graph": 1},
    {"id": "id-tail-value-word-false", "class": "id/tail/value-word/false", "document": "const $false=1;export default $false;", "graph": 1},
    {"id": "id-tail-keyword-const", "class": "id/tail/keyword/const", "document": "const $const=1;export default $const;", "graph": 1},
    {"id": "id-tail-keyword-export", "class": "id/tail/keyword/export", "document": "const $export=1;export default $export;", "graph": 1},
    {"id": "id-tail-keyword-default", "class": "id/tail/keyword/default", "document": "const $default=1;export default $default;", "graph": 1},
    {"id": "id-tail-contextual-async", "class": "id/tail/contextual/async", "document": "const $async=1;export default $async;", "graph": 1},
    {"id": "id-tail-contextual-as", "class": "id/tail/contextual/as", "document": "const $as=1;export default $as;", "graph": 1},
    {"id": "id-tail-contextual-from", "class": "id/tail/contextual/from", "document": "const $from=1;export default $from;", "graph": 1},
    {"id": "id-tail-contextual-get", "class": "id/tail/contextual/get", "document": "const $get=1;export default $get;", "graph": 1},
    {"id": "id-tail-contextual-of", "class": "id/tail/contextual/of", "document": "const $of=1;export default $of;", "graph": 1},
    {"id": "id-tail-contextual-set", "class": "id/tail/contextual/set", "document": "const $set=1;export default $set;", "graph": 1},
    {"id": "id-distinct-case", "class": "id/distinct/case", "document": "const $a=1;const $A=2;export default [$a,$A];", "graph": [1, 2]},
    {"id": "id-distinct-length", "class": "id/distinct/length", "document": "const $0=1;const $00=2;export default [$0,$00];", "graph": [1, 2]},
    {"id": "id-distinct-prefix", "class": "id/distinct/prefix", "document": "const $a=1;const $ab=2;export default [$ab,$a];", "graph": [2, 1]},
    {"id": "id-distinct-dollar", "class": "id/distinct/dollar", "document": "const $=1;const $$=2;export default [$$,$];", "graph": [2, 1]},
    {"id": "ws-space-required", "class": "ws/space/required", "document": "const $0=1;export default $0;", "graph": 1},
    {"id": "ws-space-everywhere", "class": "ws/space/everywhere", "document": " const $0 = [ 1 , { \"a\" : 2 } ] ; export default $0 ; ", "graph": [1, {"a": 2}]},
    {"id": "ws-space-run", "class": "ws/space/run", "document": "const  $0=1;export  default  $0;", "graph": 1},
    {"id": "ws-tab-required", "class": "ws/tab/required", "document": "const\t$0=1;export\tdefault\t$0;", "graph": 1},
    {"id": "ws-tab-everywhere", "class": "ws/tab/everywhere", "document": "\tconst\t$0\t=\t[\t1\t,\t{\t\"a\"\t:\t2\t}\t]\t;\texport\tdefault\t$0\t;\t", "graph": [1, {"a": 2}]},
    {"id": "ws-tab-run", "class": "ws/tab/run", "document": "const\t\t$0=1;export\t\tdefault\t\t$0;", "graph": 1},
    {"id": "ws-lf-required", "class": "ws/lf/required", "document": "const\n$0=1;export\ndefault\n$0;", "graph": 1},
    {"id": "ws-lf-everywhere", "class": "ws/lf/everywhere", "document": "\nconst\n$0\n=\n[\n1\n,\n{\n\"a\"\n:\n2\n}\n]\n;\nexport\ndefault\n$0\n;\n", "graph": [1, {"a": 2}]},
    {"id": "ws-lf-run", "class": "ws/lf/run", "document": "const\n\n$0=1;export\n\ndefault\n\n$0;", "graph": 1},
    {"id": "ws-cr-required", "class": "ws/cr/required", "document": "const\r$0=1;export\rdefault\r$0;", "graph": 1},
    {"id": "ws-cr-everywhere", "class": "ws/cr/everywhere", "document": "\rconst\r$0\r=\r[\r1\r,\r{\r\"a\"\r:\r2\r}\r]\r;\rexport\rdefault\r$0\r;\r", "graph": [1, {"a": 2}]},
    {"id": "ws-cr-run", "class": "ws/cr/run", "document": "const\r\r$0=1;export\r\rdefault\r\r$0;", "graph": 1},
    {"id": "ws-run-all-four", "class": "ws/run/all-four", "document": "const \t\n\r$0= \t\n\r[ \t\n\r1 \t\n\r] \t\n\r;export \t\n\rdefault \t\n\r$0 \t\n\r;", "graph": [1]},
    {"id": "ws-run-all-four-reversed", "class": "ws/run/all-four/reversed", "document": "const\r\n\t $0=\r\n\t 1;export\r\n\t default\r\n\t $0;", "graph": 1},
    {"id": "ws-crlf", "class": "ws/crlf", "document": "const $0=1;\r\nexport default $0;\r\n", "graph": 1},
    {"id": "ws-none-optional", "class": "ws/none-optional", "document": "const $0=[1,{\"a\":2}];export default $0;", "graph": [1, {"a": 2}]},
    {"id": "ws-around-colon", "class": "ws/around-colon", "document": "export default {\"a\" : 1};", "graph": {"a": 1}},
    {"id": "ws-around-comma", "class": "ws/around-comma", "document": "export default [1 , 2];", "graph": [1, 2]},
    {"id": "ws-before-semicolon", "class": "ws/before-semicolon", "document": "const $0=1 ;export default $0 ;", "graph": 1},
    {"id": "ws-inside-empty", "class": "ws/inside-empty", "document": "export default [ [ ] , { } ];", "graph": [[], {}]},
    {"id": "document-shortest", "class": "document/shortest", "document": "export default 1;", "graph": 1},
    {"id": "document-trailing-lf", "class": "document/trailing/lf", "document": "export default 1;\n", "graph": 1},
    {"id": "document-trailing-crlf", "class": "document/trailing/crlf", "document": "export default 1;\r\n", "graph": 1},
    {"id": "document-trailing-spaces", "class": "document/trailing/spaces", "document": "export default 1;  ", "graph": 1},
    {"id": "document-trailing-run", "class": "document/trailing/run", "document": "export default 1; \t\r\n", "graph": 1},
    {"id": "document-leading-lf", "class": "document/leading/lf", "document": "\nexport default 1;", "graph": 1},
    {"id": "document-leading-run", "class": "document/leading/run", "document": " \t\r\nexport default 1;", "graph": 1},
    {"id": "document-both-edges", "class": "document/both-edges", "document": "\n export default 1; ", "graph": 1},
    {"id": "document-spelling-one-line", "class": "document/spelling/one-line", "document": "const $0=[0];export default [$0,$0];", "graph": [$s8, $s8]},
    {"id": "document-spelling-readable", "class": "document/spelling/readable", "document": "const $0 = [0];\nexport default [\n    $0,\n    $0\n];\n", "graph": [$s8, $s8]},
    {"id": "document-many-consts", "class": "document/consts/many", "document": "const $0=0;const $1=1;const $2=2;const $3=3;const $4=4;const $5=5;const $6=6;const $7=7;const $8=8;const $9=9;const $10=10;const $11=11;const $12=12;const $13=13;const $14=14;const $15=15;const $16=16;const $17=17;const $18=18;const $19=19;const $20=20;const $21=21;const $22=22;const $23=23;const $24=24;const $25=25;const $26=26;const $27=27;const $28=28;const $29=29;const $30=30;const $31=31;const $32=32;const $33=33;const $34=34;const $35=35;const $36=36;const $37=37;const $38=38;const $39=39;const $40=40;const $41=41;const $42=42;const $43=43;const $44=44;const $45=45;const $46=46;const $47=47;const $48=48;const $49=49;const $50=50;const $51=51;const $52=52;const $53=53;const $54=54;const $55=55;const $56=56;const $57=57;const $58=58;const $59=59;const $60=60;const $61=61;const $62=62;const $63=63;const $64=64;const $65=65;const $66=66;const $67=67;const $68=68;const $69=69;const $70=70;const $71=71;const $72=72;const $73=73;const $74=74;const $75=75;const $76=76;const $77=77;const $78=78;const $79=79;const $80=80;const $81=81;const $82=82;const $83=83;const $84=84;const $85=85;const $86=86;const $87=87;const $88=88;const $89=89;const $90=90;const $91=91;const $92=92;const $93=93;const $94=94;const $95=95;const $96=96;const $97=97;const $98=98;const $99=99;export default [$0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$60,$61,$62,$63,$64,$65,$66,$67,$68,$69,$70,$71,$72,$73,$74,$75,$76,$77,$78,$79,$80,$81,$82,$83,$84,$85,$86,$87,$88,$89,$90,$91,$92,$93,$94,$95,$96,$97,$98,$99];", "graph": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]},
    {"id": "document-const-chain-long", "class": "document/consts/chain", "document": "const $0=[];const $1={\"a\":$0};const $2=[$1];const $3={\"a\":$2};const $4=[$3];const $5={\"a\":$4};const $6=[$5];const $7={\"a\":$6};const $8=[$7];const $9={\"a\":$8};const $10=[$9];const $11={\"a\":$10};const $12=[$11];const $13={\"a\":$12};const $14=[$13];const $15={\"a\":$14};const $16=[$15];const $17={\"a\":$16};const $18=[$17];const $19={\"a\":$18};const $20=[$19];const $21={\"a\":$20};const $22=[$21];const $23={\"a\":$22};const $24=[$23];const $25={\"a\":$24};const $26=[$25];const $27={\"a\":$26};const $28=[$27];const $29={\"a\":$28};const $30=[$29];const $31={\"a\":$30};const $32=[$31];const $33={\"a\":$32};const $34=[$33];const $35={\"a\":$34};const $36=[$35];const $37={\"a\":$36};const $38=[$37];const $39={\"a\":$38};const $40=[$39];const $41={\"a\":$40};const $42=[$41];const $43={\"a\":$42};const $44=[$43];const $45={\"a\":$44};const $46=[$45];const $47={\"a\":$46};const $48=[$47];const $49={\"a\":$48};const $50=[$49];const $51={\"a\":$50};const $52=[$51];const $53={\"a\":$52};const $54=[$53];const $55={\"a\":$54};const $56=[$55];const $57={\"a\":$56};const $58=[$57];const $59={\"a\":$58};const $60=[$59];const $61={\"a\":$60};const $62=[$61];const $63={\"a\":$62};const $64=[$63];const $65={\"a\":$64};const $66=[$65];const $67={\"a\":$66};const $68=[$67];const $69={\"a\":$68};const $70=[$69];const $71={\"a\":$70};const $72=[$71];const $73={\"a\":$72};const $74=[$73];const $75={\"a\":$74};const $76=[$75];const $77={\"a\":$76};const $78=[$77];const $79={\"a\":$78};const $80=[$79];const $81={\"a\":$80};const $82=[$81];const $83={\"a\":$82};const $84=[$83];const $85={\"a\":$84};const $86=[$85];const $87={\"a\":$86};const $88=[$87];const $89={\"a\":$88};const $90=[$89];const $91={\"a\":$90};const $92=[$91];const $93={\"a\":$92};const $94=[$93];const $95={\"a\":$94};const $96=[$95];const $97={\"a\":$96};const $98=[$97];const $99={\"a\":$98};export default $99;", "graph": {"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": [{"a": []}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}},
    {"id": "string-escape-u00-0000", "class": "string/escape/u00/0000", "document": "export default \"\\u0000\";", "graph": "\u0000"},
    {"id": "string-escape-u00-001f", "class": "string/escape/u00/001f", "document": "export default \"\\u001f\";", "graph": "\u001f"},
    {"id": "key-escape-u00-0000", "class": "key/string/escape/u00/0000", "document": "export default {\"\\u0000\":0};", "graph": {"\u0000": 0}},
    {"id": "key-escape-u00-001f", "class": "key/string/escape/u00/001f", "document": "export default {\"\\u001f\":0};", "graph": {"\u001f": 0}},
    {"id": "const-shared-mixed", "class": "const/shared/mixed", "document": "const $0=[0];export default [[$0],{\"x\":$0}];", "graph": [[$m0], {"x": $m0}]},
    {"id": "object-unshared-equal", "class": "object/unshared/equal", "document": "export default [{\"a\":0},{\"a\":0}];", "graph": [{"a": 0}, {"a": 0}]},
    {"id": "array-unshared-object-parent", "class": "array/unshared", "document": "export default {\"x\":[],\"y\":[]};", "graph": {"x": [], "y": []}},
    {"id": "array-unshared-equal-object-parent", "class": "array/unshared/equal", "document": "export default {\"x\":[1],\"y\":[1]};", "graph": {"x": [1], "y": [1]}},
    {"id": "object-unshared-object-parent", "class": "object/unshared", "document": "export default {\"x\":{},\"y\":{}};", "graph": {"x": {}, "y": {}}},
    {"id": "object-unshared-equal-object-parent", "class": "object/unshared/equal", "document": "export default {\"x\":{\"a\":0},\"y\":{\"a\":0}};", "graph": {"x": {"a": 0}, "y": {"a": 0}}},
    {"id": "object-members-negative-first-zero", "class": "object/members/negative-first", "document": "export default {\"a\":-0,\"b\":1};", "graph": {"a": -0, "b": 1}},
    {"id": "object-members-negative-first-number", "class": "object/members/negative-first", "document": "export default {\"a\":-1,\"b\":1};", "graph": {"a": -1, "b": 1}},
    {"id": "object-members-negative-first-bigint", "class": "object/members/negative-first", "document": "export default {\"a\":-1n,\"b\":1};", "graph": {"a": -1n, "b": 1}},
    {"id": "object-members-negative-first-infinity", "class": "object/members/negative-first", "document": "export default {\"a\":-Infinity,\"b\":1};", "graph": {"a": -Infinity, "b": 1}},
    {"id": "key-raw-ws-like-2028-after-first", "class": "key/string/raw/ws-like/2028", "document": "export default {\"a\":0,\"\u2028\":0};", "graph": {"a": 0, "\u2028": 0}},
    {"id": "byte-valid-widths", "class": "byte/valid/widths", "document": ["hex", "65 78 70 6f 72 74 20 64 65 66 61 75 6c 74 20 22 61 c3 a9 e2 82 ac f0 90 80 80 22 3b"], "graph": "a\u00e9\u20ac\ud800\udc00"},
    {"id": "string-escape-quote-every-slot", "class": "string/escape/quote", "document": "export default [\"\\\"\",0,\"\\\"\"];", "graph": ["\"", 0, "\""]},
    {"id": "key-escape-quote-every-slot", "class": "key/string/escape/quote", "document": "export default [{\"\\\"\":\"\\\"\",\"a\":1},{\"a\":0,\"\\\"\":\"\\\"\"}];", "graph": [{"\"": "\"", "a": 1}, {"a": 0, "\"": "\""}]},
    {"id": "string-escape-backslash-every-slot", "class": "string/escape/backslash", "document": "export default [\"\\\\\",0,\"\\\\\"];", "graph": ["\\", 0, "\\"]},
    {"id": "key-escape-backslash-every-slot", "class": "key/string/escape/backslash", "document": "export default [{\"\\\\\":\"\\\\\",\"a\":1},{\"a\":0,\"\\\\\":\"\\\\\"}];", "graph": [{"\\": "\\", "a": 1}, {"a": 0, "\\": "\\"}]},
    {"id": "string-escape-slash-every-slot", "class": "string/escape/slash", "document": "export default [\"\\/\",0,\"\\/\"];", "graph": ["/", 0, "/"]},
    {"id": "key-escape-slash-every-slot", "class": "key/string/escape/slash", "document": "export default [{\"\\/\":\"\\/\",\"a\":1},{\"a\":0,\"\\/\":\"\\/\"}];", "graph": [{"/": "/", "a": 1}, {"a": 0, "/": "/"}]},
    {"id": "string-escape-b-every-slot", "class": "string/escape/b", "document": "export default [\"\\b\",0,\"\\b\"];", "graph": ["\b", 0, "\b"]},
    {"id": "key-escape-b-every-slot", "class": "key/string/escape/b", "document": "export default [{\"\\b\":\"\\b\",\"a\":1},{\"a\":0,\"\\b\":\"\\b\"}];", "graph": [{"\b": "\b", "a": 1}, {"a": 0, "\b": "\b"}]},
    {"id": "string-escape-f-every-slot", "class": "string/escape/f", "document": "export default [\"\\f\",0,\"\\f\"];", "graph": ["\f", 0, "\f"]},
    {"id": "key-escape-f-every-slot", "class": "key/string/escape/f", "document": "export default [{\"\\f\":\"\\f\",\"a\":1},{\"a\":0,\"\\f\":\"\\f\"}];", "graph": [{"\f": "\f", "a": 1}, {"a": 0, "\f": "\f"}]},
    {"id": "string-escape-n-every-slot", "class": "string/escape/n", "document": "export default [\"\\n\",0,\"\\n\"];", "graph": ["\n", 0, "\n"]},
    {"id": "key-escape-n-every-slot", "class": "key/string/escape/n", "document": "export default [{\"\\n\":\"\\n\",\"a\":1},{\"a\":0,\"\\n\":\"\\n\"}];", "graph": [{"\n": "\n", "a": 1}, {"a": 0, "\n": "\n"}]},
    {"id": "string-escape-r-every-slot", "class": "string/escape/r", "document": "export default [\"\\r\",0,\"\\r\"];", "graph": ["\r", 0, "\r"]},
    {"id": "key-escape-r-every-slot", "class": "key/string/escape/r", "document": "export default [{\"\\r\":\"\\r\",\"a\":1},{\"a\":0,\"\\r\":\"\\r\"}];", "graph": [{"\r": "\r", "a": 1}, {"a": 0, "\r": "\r"}]},
    {"id": "string-escape-t-every-slot", "class": "string/escape/t", "document": "export default [\"\\t\",0,\"\\t\"];", "graph": ["\t", 0, "\t"]},
    {"id": "key-escape-t-every-slot", "class": "key/string/escape/t", "document": "export default [{\"\\t\":\"\\t\",\"a\":1},{\"a\":0,\"\\t\":\"\\t\"}];", "graph": [{"\t": "\t", "a": 1}, {"a": 0, "\t": "\t"}]},
    {"id": "string-escape-u-09af-every-slot", "class": "string/escape/u/09af", "document": "export default [\"\\u09af\",0,\"\\u09af\"];", "graph": ["\u09af", 0, "\u09af"]},
    {"id": "key-escape-u-09af-every-slot", "class": "key/string/escape/u/09af", "document": "export default [{\"\\u09af\":\"\\u09af\",\"a\":1},{\"a\":0,\"\\u09af\":\"\\u09af\"}];", "graph": [{"\u09af": "\u09af", "a": 1}, {"a": 0, "\u09af": "\u09af"}]},
    {"id": "string-escape-u-9afA-every-slot", "class": "string/escape/u/9afA", "document": "export default [\"\\u9afA\",0,\"\\u9afA\"];", "graph": ["\u9afa", 0, "\u9afa"]},
    {"id": "key-escape-u-9afA-every-slot", "class": "key/string/escape/u/9afA", "document": "export default [{\"\\u9afA\":\"\\u9afA\",\"a\":1},{\"a\":0,\"\\u9afA\":\"\\u9afA\"}];", "graph": [{"\u9afa": "\u9afa", "a": 1}, {"a": 0, "\u9afa": "\u9afa"}]},
    {"id": "string-escape-u-afAF-every-slot", "class": "string/escape/u/afAF", "document": "export default [\"\\uafAF\",0,\"\\uafAF\"];", "graph": ["\uafaf", 0, "\uafaf"]},
    {"id": "key-escape-u-afAF-every-slot", "class": "key/string/escape/u/afAF", "document": "export default [{\"\\uafAF\":\"\\uafAF\",\"a\":1},{\"a\":0,\"\\uafAF\":\"\\uafAF\"}];", "graph": [{"\uafaf": "\uafaf", "a": 1}, {"a": 0, "\uafaf": "\uafaf"}]},
    {"id": "string-escape-u-fAF0-every-slot", "class": "string/escape/u/fAF0", "document": "export default [\"\\ufAF0\",0,\"\\ufAF0\"];", "graph": ["\ufaf0", 0, "\ufaf0"]},
    {"id": "key-escape-u-fAF0-every-slot", "class": "key/string/escape/u/fAF0", "document": "export default [{\"\\ufAF0\":\"\\ufAF0\",\"a\":1},{\"a\":0,\"\\ufAF0\":\"\\ufAF0\"}];", "graph": [{"\ufaf0": "\ufaf0", "a": 1}, {"a": 0, "\ufaf0": "\ufaf0"}]},
    {"id": "string-escape-u-AF09-every-slot", "class": "string/escape/u/AF09", "document": "export default [\"\\uAF09\",0,\"\\uAF09\"];", "graph": ["\uaf09", 0, "\uaf09"]},
    {"id": "key-escape-u-AF09-every-slot", "class": "key/string/escape/u/AF09", "document": "export default [{\"\\uAF09\":\"\\uAF09\",\"a\":1},{\"a\":0,\"\\uAF09\":\"\\uAF09\"}];", "graph": [{"\uaf09": "\uaf09", "a": 1}, {"a": 0, "\uaf09": "\uaf09"}]},
    {"id": "string-escape-u-F09a-every-slot", "class": "string/escape/u/F09a", "document": "export default [\"\\uF09a\",0,\"\\uF09a\"];", "graph": ["\uf09a", 0, "\uf09a"]},
    {"id": "key-escape-u-F09a-every-slot", "class": "key/string/escape/u/F09a", "document": "export default [{\"\\uF09a\":\"\\uF09a\",\"a\":1},{\"a\":0,\"\\uF09a\":\"\\uF09a\"}];", "graph": [{"\uf09a": "\uf09a", "a": 1}, {"a": 0, "\uf09a": "\uf09a"}]},
    {"id": "string-escape-u00-0000-every-slot", "class": "string/escape/u00/0000", "document": "export default [\"\\u0000\",0,\"\\u0000\"];", "graph": ["\u0000", 0, "\u0000"]},
    {"id": "key-escape-u00-0000-every-slot", "class": "key/string/escape/u00/0000", "document": "export default [{\"\\u0000\":\"\\u0000\",\"a\":1},{\"a\":0,\"\\u0000\":\"\\u0000\"}];", "graph": [{"\u0000": "\u0000", "a": 1}, {"a": 0, "\u0000": "\u0000"}]},
    {"id": "string-escape-u00-001f-every-slot", "class": "string/escape/u00/001f", "document": "export default [\"\\u001f\",0,\"\\u001f\"];", "graph": ["\u001f", 0, "\u001f"]},
    {"id": "key-escape-u00-001f-every-slot", "class": "key/string/escape/u00/001f", "document": "export default [{\"\\u001f\":\"\\u001f\",\"a\":1},{\"a\":0,\"\\u001f\":\"\\u001f\"}];", "graph": [{"\u001f": "\u001f", "a": 1}, {"a": 0, "\u001f": "\u001f"}]},
    {"id": "array-elements-every-value-first", "class": "array/elements/every-value-first", "document": "export default [[null,0],[true,0],[false,0],[undefined,0],[NaN,0],[Infinity,0],[-Infinity,0],[0,0],[-0,0],[9,0],[-9,0],[1.5,0],[1e2,0],[1n,0],[-1n,0],[0n,0],[\"\",0],[\"a\",0],[\"\u2028\",0],[\"\\ud800\",0],[\"\\u0000\",0],[\"\\ud800\\udc00\",0],[[],0],[{},0]];", "graph": [[null, 0], [true, 0], [false, 0], [undefined, 0], [NaN, 0], [Infinity, 0], [-Infinity, 0], [0, 0], [-0, 0], [9, 0], [-9, 0], [1.5, 0], [100, 0], [1n, 0], [-1n, 0], [0n, 0], ["", 0], ["a", 0], ["\u2028", 0], ["\ud800", 0], ["\u0000", 0], ["\ud800\udc00", 0], [[], 0], [{}, 0]]},
    {"id": "object-members-every-value-first", "class": "object/members/every-value-first", "document": "export default [{\"a\":null,\"b\":0},{\"a\":true,\"b\":0},{\"a\":false,\"b\":0},{\"a\":undefined,\"b\":0},{\"a\":NaN,\"b\":0},{\"a\":Infinity,\"b\":0},{\"a\":-Infinity,\"b\":0},{\"a\":0,\"b\":0},{\"a\":-0,\"b\":0},{\"a\":9,\"b\":0},{\"a\":-9,\"b\":0},{\"a\":1.5,\"b\":0},{\"a\":1e2,\"b\":0},{\"a\":1n,\"b\":0},{\"a\":-1n,\"b\":0},{\"a\":0n,\"b\":0},{\"a\":\"\",\"b\":0},{\"a\":\"a\",\"b\":0},{\"a\":\"\u2028\",\"b\":0},{\"a\":\"\\ud800\",\"b\":0},{\"a\":\"\\u0000\",\"b\":0},{\"a\":\"\\ud800\\udc00\",\"b\":0},{\"a\":[],\"b\":0},{\"a\":{},\"b\":0}];", "graph": [{"a": null, "b": 0}, {"a": true, "b": 0}, {"a": false, "b": 0}, {"a": undefined, "b": 0}, {"a": NaN, "b": 0}, {"a": Infinity, "b": 0}, {"a": -Infinity, "b": 0}, {"a": 0, "b": 0}, {"a": -0, "b": 0}, {"a": 9, "b": 0}, {"a": -9, "b": 0}, {"a": 1.5, "b": 0}, {"a": 100, "b": 0}, {"a": 1n, "b": 0}, {"a": -1n, "b": 0}, {"a": 0n, "b": 0}, {"a": "", "b": 0}, {"a": "a", "b": 0}, {"a": "\u2028", "b": 0}, {"a": "\ud800", "b": 0}, {"a": "\u0000", "b": 0}, {"a": "\ud800\udc00", "b": 0}, {"a": [], "b": 0}, {"a": {}, "b": 0}]},
    {"id": "object-key-order-nested", "class": "object/key-order/nested", "document": "const $0={\"d\":0,\"c\":1};export default [{\"b\":0,\"a\":1},{\"x\":{\"b\":0,\"a\":1}},$0,$0];", "graph": [{"b": 0, "a": 1}, {"x": {"b": 0, "a": 1}}, $s9, $s9]},
    {"id": "object-keys-every-string", "class": "object/keys/every-string", "document": "export default [{\"\u2028\":0,\"\\ud800\":1,\"\\u0000\":2,\"\\ud800\\udc00\":3,\"a\":4}];", "graph": [{"\u2028": 0, "\ud800": 1, "\u0000": 2, "\ud800\udc00": 3, "a": 4}]},
    {"id": "const-shared-object-parent", "class": "const/shared/object", "document": "const $0={\"a\":0};export default {\"x\":$0,\"y\":$0};", "graph": {"x": $s10, "y": $s10}},
    {"id": "const-shared-object-proto-key", "class": "const/shared/object", "document": "const $0={[\"__proto__\"]:1};export default [$0,$0];", "graph": [$s11, $s11]},
    {"id": "const-shared-object-escaped-keys", "class": "const/shared/object", "document": "const $0={\"\\\"\":\"\\\"\",\"\\\\\":\"\\\\\",\"\\b\":\"\\b\",\"\\t\":\"\\t\",\"\\n\":\"\\n\",\"\\f\":\"\\f\",\"\\r\":\"\\r\",\"\\u0000\":\"\\u0000\",\"\\u001f\":\"\\u001f\"};export default [$0,$0];", "graph": [$s12, $s12]},
    {"id": "const-body-first-slot-array", "class": "const/shared/twice", "document": "const $0=[null,0];const $1=[undefined,0];const $2=[NaN,0];const $3=[Infinity,0];const $4=[-Infinity,0];const $5=[-0,0];const $6=[false,0];const $7=[true,0];const $8=[\"\",0];const $9=[\"a\",0];const $10=[1n,0];const $11=[-1n,0];const $12=[0n,0];const $13=[-1,0];const $14=[[],0];const $15=[{},0];export default [$0,$0,$1,$1,$2,$2,$3,$3,$4,$4,$5,$5,$6,$6,$7,$7,$8,$8,$9,$9,$10,$10,$11,$11,$12,$12,$13,$13,$14,$14,$15,$15];", "graph": [$f0, $f0, $f1, $f1, $f2, $f2, $f3, $f3, $f4, $f4, $f5, $f5, $f6, $f6, $f7, $f7, $f8, $f8, $f9, $f9, $f10, $f10, $f11, $f11, $f12, $f12, $f13, $f13, $f14, $f14, $f15, $f15]},
    {"id": "const-body-first-slot-object", "class": "const/shared/object", "document": "const $0={\"a\":null,\"b\":0};const $1={\"a\":undefined,\"b\":0};const $2={\"a\":NaN,\"b\":0};const $3={\"a\":Infinity,\"b\":0};const $4={\"a\":-Infinity,\"b\":0};const $5={\"a\":-0,\"b\":0};const $6={\"a\":false,\"b\":0};const $7={\"a\":true,\"b\":0};const $8={\"a\":\"\",\"b\":0};const $9={\"a\":\"a\",\"b\":0};const $10={\"a\":1n,\"b\":0};const $11={\"a\":-1n,\"b\":0};const $12={\"a\":0n,\"b\":0};const $13={\"a\":-1,\"b\":0};const $14={\"a\":[],\"b\":0};const $15={\"a\":{},\"b\":0};export default [$0,$0,$1,$1,$2,$2,$3,$3,$4,$4,$5,$5,$6,$6,$7,$7,$8,$8,$9,$9,$10,$10,$11,$11,$12,$12,$13,$13,$14,$14,$15,$15];", "graph": [$g0, $g0, $g1, $g1, $g2, $g2, $g3, $g3, $g4, $g4, $g5, $g5, $g6, $g6, $g7, $g7, $g8, $g8, $g9, $g9, $g10, $g10, $g11, $g11, $g12, $g12, $g13, $g13, $g14, $g14, $g15, $g15]}
];
