export default [
    {"id": "null", "class": "leaf/null", "document": "export default null;", "graph": null},
    {"id": "true", "class": "leaf/boolean/true", "document": "export default true;", "graph": true},
    {"id": "false", "class": "leaf/boolean/false", "document": "export default false;", "graph": false},
    {"id": "undefined", "class": "leaf/undefined", "document": "export default undefined;", "graph": undefined},
    {"id": "nan", "class": "leaf/nan", "document": "export default NaN;", "graph": NaN},
    {"id": "infinity", "class": "infinity/plus", "document": "export default Infinity;", "graph": Infinity},
    {"id": "neg-infinity", "class": "infinity/minus", "document": "export default -Infinity;", "graph": -Infinity},
    {"id": "number-0", "class": "number/int/zero", "document": "export default 0;", "graph": 0},
    {"id": "number-neg-0", "class": "number/int/zero/neg", "document": "export default -0;", "graph": -0},
    {"id": "number-9", "class": "number/int/digit9", "document": "export default 9;", "graph": 9},
    {"id": "number-neg-9", "class": "number/int/digit9/neg", "document": "export default -9;", "graph": -9},
    {"id": "number-109", "class": "number/int/digits", "document": "export default 109;", "graph": 109},
    {"id": "number-neg-109", "class": "number/int/digits/neg", "document": "export default -109;", "graph": -109},
    {"id": "number-1.09", "class": "number/frac", "document": "export default 1.09;", "graph": 1.09},
    {"id": "number-neg-1.09", "class": "number/frac/neg", "document": "export default -1.09;", "graph": -1.09},
    {"id": "number-1.0", "class": "number/frac/one-digit", "document": "export default 1.0;", "graph": 1},
    {"id": "number-neg-1.0", "class": "number/frac/one-digit/neg", "document": "export default -1.0;", "graph": -1},
    {"id": "number-1e09", "class": "number/exp/e", "document": "export default 1e09;", "graph": 1e9},
    {"id": "number-neg-1e09", "class": "number/exp/e/neg", "document": "export default -1e09;", "graph": -1e9},
    {"id": "number-1E2", "class": "number/exp/E", "document": "export default 1E2;", "graph": 100},
    {"id": "number-neg-1E2", "class": "number/exp/E/neg", "document": "export default -1E2;", "graph": -100},
    {"id": "number-1e+2", "class": "number/exp/plus", "document": "export default 1e+2;", "graph": 100},
    {"id": "number-neg-1e+2", "class": "number/exp/plus/neg", "document": "export default -1e+2;", "graph": -100},
    {"id": "number-1e-2", "class": "number/exp/minus", "document": "export default 1e-2;", "graph": 0.01},
    {"id": "number-neg-1e-2", "class": "number/exp/minus/neg", "document": "export default -1e-2;", "graph": -0.01},
    {"id": "number-1.09e-2", "class": "number/frac-exp", "document": "export default 1.09e-2;", "graph": 0.0109},
    {"id": "number-neg-1.09e-2", "class": "number/frac-exp/neg", "document": "export default -1.09e-2;", "graph": -0.0109},
    {"id": "number-0.0", "class": "number/zero/frac", "document": "export default 0.0;", "graph": 0},
    {"id": "number-neg-0.0", "class": "number/zero/frac/neg", "document": "export default -0.0;", "graph": -0},
    {"id": "number-0e0", "class": "number/zero/exp", "document": "export default 0e0;", "graph": 0},
    {"id": "number-neg-0e0", "class": "number/zero/exp/neg", "document": "export default -0e0;", "graph": -0},
    {"id": "number-rounding", "class": "number/binary64/rounding", "document": "export default 1000000000000000128;", "graph": 1000000000000000100},
    {"id": "number-neg-rounding", "class": "number/binary64/rounding/neg", "document": "export default -1000000000000000128;", "graph": -1000000000000000100},
    {"id": "number-subnormal", "class": "number/binary64/subnormal", "document": "export default 5e-324;", "graph": 5e-324},
    {"id": "number-neg-subnormal", "class": "number/binary64/subnormal/neg", "document": "export default -5e-324;", "graph": -5e-324},
    {"id": "number-underflow", "class": "number/binary64/underflow", "document": "export default 1e-999;", "graph": 0},
    {"id": "number-neg-underflow", "class": "number/binary64/underflow/neg", "document": "export default -1e-999;", "graph": -0},
    {"id": "number-overflow", "class": "number/binary64/overflow", "document": "export default 1e999;", "graph": Infinity},
    {"id": "number-neg-overflow", "class": "number/binary64/overflow/neg", "document": "export default -1e999;", "graph": -Infinity},
    {"id": "number-max", "class": "number/binary64/max", "document": "export default 1.7976931348623157e308;", "graph": 1.7976931348623157e308},
    {"id": "number-neg-max", "class": "number/binary64/max/neg", "document": "export default -1.7976931348623157e308;", "graph": -1.7976931348623157e308},
    {"id": "bigint-0", "class": "bigint/zero", "document": "export default 0n;", "graph": 0n},
    {"id": "bigint-neg-0", "class": "bigint/zero/neg", "document": "export default -0n;", "graph": 0n},
    {"id": "bigint-9", "class": "bigint/digit9", "document": "export default 9n;", "graph": 9n},
    {"id": "bigint-neg-9", "class": "bigint/digit9/neg", "document": "export default -9n;", "graph": -9n},
    {"id": "bigint-109", "class": "bigint/digits", "document": "export default 109n;", "graph": 109n},
    {"id": "bigint-neg-109", "class": "bigint/digits/neg", "document": "export default -109n;", "graph": -109n},
    {"id": "bigint-2p53", "class": "bigint/past-2p53", "document": "export default 9007199254740993n;", "graph": 9007199254740993n},
    {"id": "bigint-neg-2p53", "class": "bigint/past-2p53/neg", "document": "export default -9007199254740993n;", "graph": -9007199254740993n},
    {"id": "bigint-2p64", "class": "bigint/past-2p64", "document": "export default 18446744073709551617n;", "graph": 18446744073709551617n},
    {"id": "bigint-neg-2p64", "class": "bigint/past-2p64/neg", "document": "export default -18446744073709551617n;", "graph": -18446744073709551617n},
    {"id": "bigint-2p128", "class": "bigint/past-2p128", "document": "export default 340282366920938463463374607431768211457n;", "graph": 340282366920938463463374607431768211457n},
    {"id": "bigint-neg-2p128", "class": "bigint/past-2p128/neg", "document": "export default -340282366920938463463374607431768211457n;", "graph": -340282366920938463463374607431768211457n},
    {"id": "string-empty", "class": "string/empty", "document": "export default \"\";", "graph": ""},
    {"id": "key-empty", "class": "key/string/empty", "document": "export default {\"\":0};", "graph": {"": 0}},
    {"id": "string-escape-quote", "class": "string/escape/quote", "document": "export default \"\\\"\";", "graph": "\""},
    {"id": "key-escape-quote", "class": "key/string/escape/quote", "document": "export default {\"\\\"\":0};", "graph": {"\"": 0}},
    {"id": "string-escape-backslash", "class": "string/escape/backslash", "document": "export default \"\\\\\";", "graph": "\\"},
    {"id": "key-escape-backslash", "class": "key/string/escape/backslash", "document": "export default {\"\\\\\":0};", "graph": {"\\": 0}},
    {"id": "string-escape-slash", "class": "string/escape/slash", "document": "export default \"\\/\";", "graph": "/"},
    {"id": "key-escape-slash", "class": "key/string/escape/slash", "document": "export default {\"\\/\":0};", "graph": {"/": 0}},
    {"id": "string-escape-b", "class": "string/escape/b", "document": "export default \"\\b\";", "graph": "\b"},
    {"id": "key-escape-b", "class": "key/string/escape/b", "document": "export default {\"\\b\":0};", "graph": {"\b": 0}},
    {"id": "string-escape-f", "class": "string/escape/f", "document": "export default \"\\f\";", "graph": "\f"},
    {"id": "key-escape-f", "class": "key/string/escape/f", "document": "export default {\"\\f\":0};", "graph": {"\f": 0}},
    {"id": "string-escape-n", "class": "string/escape/n", "document": "export default \"\\n\";", "graph": "\n"},
    {"id": "key-escape-n", "class": "key/string/escape/n", "document": "export default {\"\\n\":0};", "graph": {"\n": 0}},
    {"id": "string-escape-r", "class": "string/escape/r", "document": "export default \"\\r\";", "graph": "\r"},
    {"id": "key-escape-r", "class": "key/string/escape/r", "document": "export default {\"\\r\":0};", "graph": {"\r": 0}},
    {"id": "string-escape-t", "class": "string/escape/t", "document": "export default \"\\t\";", "graph": "\t"},
    {"id": "key-escape-t", "class": "key/string/escape/t", "document": "export default {\"\\t\":0};", "graph": {"\t": 0}},
    {"id": "string-escape-u-09af", "class": "string/escape/u/09af", "document": "export default \"\\u09af\";", "graph": "\u09af"},
    {"id": "key-escape-u-09af", "class": "key/string/escape/u/09af", "document": "export default {\"\\u09af\":0};", "graph": {"\u09af": 0}},
    {"id": "string-escape-u-9afA", "class": "string/escape/u/9afA", "document": "export default \"\\u9afA\";", "graph": "\u9afa"},
    {"id": "key-escape-u-9afA", "class": "key/string/escape/u/9afA", "document": "export default {\"\\u9afA\":0};", "graph": {"\u9afa": 0}},
    {"id": "string-escape-u-afAF", "class": "string/escape/u/afAF", "document": "export default \"\\uafAF\";", "graph": "\uafaf"},
    {"id": "key-escape-u-afAF", "class": "key/string/escape/u/afAF", "document": "export default {\"\\uafAF\":0};", "graph": {"\uafaf": 0}},
    {"id": "string-escape-u-fAF0", "class": "string/escape/u/fAF0", "document": "export default \"\\ufAF0\";", "graph": "\ufaf0"},
    {"id": "key-escape-u-fAF0", "class": "key/string/escape/u/fAF0", "document": "export default {\"\\ufAF0\":0};", "graph": {"\ufaf0": 0}},
    {"id": "string-escape-u-AF09", "class": "string/escape/u/AF09", "document": "export default \"\\uAF09\";", "graph": "\uaf09"},
    {"id": "key-escape-u-AF09", "class": "key/string/escape/u/AF09", "document": "export default {\"\\uAF09\":0};", "graph": {"\uaf09": 0}},
    {"id": "string-escape-u-F09a", "class": "string/escape/u/F09a", "document": "export default \"\\uF09a\";", "graph": "\uf09a"},
    {"id": "key-escape-u-F09a", "class": "key/string/escape/u/F09a", "document": "export default {\"\\uF09a\":0};", "graph": {"\uf09a": 0}},
    {"id": "string-raw-slash", "class": "string/raw/slash", "document": "export default \"/\";", "graph": "/"},
    {"id": "key-raw-slash", "class": "key/string/raw/slash", "document": "export default {\"/\":0};", "graph": {"/": 0}},
    {"id": "string-raw-latin", "class": "string/raw/bmp", "document": "export default \"\u00e9\";", "graph": "\u00e9"},
    {"id": "key-raw-latin", "class": "key/string/raw/bmp", "document": "export default {\"\u00e9\":0};", "graph": {"\u00e9": 0}},
    {"id": "string-raw-cjk", "class": "string/raw/bmp", "document": "export default \"\u4e2d\";", "graph": "\u4e2d"},
    {"id": "key-raw-cjk", "class": "key/string/raw/bmp", "document": "export default {\"\u4e2d\":0};", "graph": {"\u4e2d": 0}},
    {"id": "string-raw-astral", "class": "string/raw/astral", "document": "export default \"\ud83d\ude00\";", "graph": "\ud83d\ude00"},
    {"id": "key-raw-astral", "class": "key/string/raw/astral", "document": "export default {\"\ud83d\ude00\":0};", "graph": {"\ud83d\ude00": 0}},
    {"id": "string-raw-ws-like-2028", "class": "string/raw/ws-like/2028", "document": "export default \"\u2028\";", "graph": "\u2028"},
    {"id": "key-raw-ws-like-2028", "class": "key/string/raw/ws-like/2028", "document": "export default {\"\u2028\":0};", "graph": {"\u2028": 0}},
    {"id": "string-raw-ws-like-2029", "class": "string/raw/ws-like/2029", "document": "export default \"\u2029\";", "graph": "\u2029"},
    {"id": "key-raw-ws-like-2029", "class": "key/string/raw/ws-like/2029", "document": "export default {\"\u2029\":0};", "graph": {"\u2029": 0}},
    {"id": "string-raw-ws-like-feff", "class": "string/raw/ws-like/feff", "document": "export default \"\ufeff\";", "graph": "\ufeff"},
    {"id": "key-raw-ws-like-feff", "class": "key/string/raw/ws-like/feff", "document": "export default {\"\ufeff\":0};", "graph": {"\ufeff": 0}},
    {"id": "string-raw-ws-like-00a0", "class": "string/raw/ws-like/00a0", "document": "export default \"\u00a0\";", "graph": "\u00a0"},
    {"id": "key-raw-ws-like-00a0", "class": "key/string/raw/ws-like/00a0", "document": "export default {\"\u00a0\":0};", "graph": {"\u00a0": 0}},
    {"id": "string-raw-ws-like-1680", "class": "string/raw/ws-like/1680", "document": "export default \"\u1680\";", "graph": "\u1680"},
    {"id": "key-raw-ws-like-1680", "class": "key/string/raw/ws-like/1680", "document": "export default {\"\u1680\":0};", "graph": {"\u1680": 0}},
    {"id": "string-raw-ws-like-2000", "class": "string/raw/ws-like/2000", "document": "export default \"\u2000\";", "graph": "\u2000"},
    {"id": "key-raw-ws-like-2000", "class": "key/string/raw/ws-like/2000", "document": "export default {\"\u2000\":0};", "graph": {"\u2000": 0}},
    {"id": "string-raw-ws-like-2001", "class": "string/raw/ws-like/2001", "document": "export default \"\u2001\";", "graph": "\u2001"},
    {"id": "key-raw-ws-like-2001", "class": "key/string/raw/ws-like/2001", "document": "export default {\"\u2001\":0};", "graph": {"\u2001": 0}},
    {"id": "string-raw-ws-like-2002", "class": "string/raw/ws-like/2002", "document": "export default \"\u2002\";", "graph": "\u2002"},
    {"id": "key-raw-ws-like-2002", "class": "key/string/raw/ws-like/2002", "document": "export default {\"\u2002\":0};", "graph": {"\u2002": 0}},
    {"id": "string-raw-ws-like-2003", "class": "string/raw/ws-like/2003", "document": "export default \"\u2003\";", "graph": "\u2003"},
    {"id": "key-raw-ws-like-2003", "class": "key/string/raw/ws-like/2003", "document": "export default {\"\u2003\":0};", "graph": {"\u2003": 0}},
    {"id": "string-raw-ws-like-2004", "class": "string/raw/ws-like/2004", "document": "export default \"\u2004\";", "graph": "\u2004"},
    {"id": "key-raw-ws-like-2004", "class": "key/string/raw/ws-like/2004", "document": "export default {\"\u2004\":0};", "graph": {"\u2004": 0}},
    {"id": "string-raw-ws-like-2005", "class": "string/raw/ws-like/2005", "document": "export default \"\u2005\";", "graph": "\u2005"},
    {"id": "key-raw-ws-like-2005", "class": "key/string/raw/ws-like/2005", "document": "export default {\"\u2005\":0};", "graph": {"\u2005": 0}},
    {"id": "string-raw-ws-like-2006", "class": "string/raw/ws-like/2006", "document": "export default \"\u2006\";", "graph": "\u2006"},
    {"id": "key-raw-ws-like-2006", "class": "key/string/raw/ws-like/2006", "document": "export default {\"\u2006\":0};", "graph": {"\u2006": 0}},
    {"id": "string-raw-ws-like-2007", "class": "string/raw/ws-like/2007", "document": "export default \"\u2007\";", "graph": "\u2007"},
    {"id": "key-raw-ws-like-2007", "class": "key/string/raw/ws-like/2007", "document": "export default {\"\u2007\":0};", "graph": {"\u2007": 0}},
    {"id": "string-raw-ws-like-2008", "class": "string/raw/ws-like/2008", "document": "export default \"\u2008\";", "graph": "\u2008"},
    {"id": "key-raw-ws-like-2008", "class": "key/string/raw/ws-like/2008", "document": "export default {\"\u2008\":0};", "graph": {"\u2008": 0}},
    {"id": "string-raw-ws-like-2009", "class": "string/raw/ws-like/2009", "document": "export default \"\u2009\";", "graph": "\u2009"},
    {"id": "key-raw-ws-like-2009", "class": "key/string/raw/ws-like/2009", "document": "export default {\"\u2009\":0};", "graph": {"\u2009": 0}},
    {"id": "string-raw-ws-like-200a", "class": "string/raw/ws-like/200a", "document": "export default \"\u200a\";", "graph": "\u200a"},
    {"id": "key-raw-ws-like-200a", "class": "key/string/raw/ws-like/200a", "document": "export default {\"\u200a\":0};", "graph": {"\u200a": 0}},
    {"id": "string-raw-ws-like-202f", "class": "string/raw/ws-like/202f", "document": "export default \"\u202f\";", "graph": "\u202f"},
    {"id": "key-raw-ws-like-202f", "class": "key/string/raw/ws-like/202f", "document": "export default {\"\u202f\":0};", "graph": {"\u202f": 0}},
    {"id": "string-raw-ws-like-205f", "class": "string/raw/ws-like/205f", "document": "export default \"\u205f\";", "graph": "\u205f"},
    {"id": "key-raw-ws-like-205f", "class": "key/string/raw/ws-like/205f", "document": "export default {\"\u205f\":0};", "graph": {"\u205f": 0}},
    {"id": "string-raw-ws-like-3000", "class": "string/raw/ws-like/3000", "document": "export default \"\u3000\";", "graph": "\u3000"},
    {"id": "key-raw-ws-like-3000", "class": "key/string/raw/ws-like/3000", "document": "export default {\"\u3000\":0};", "graph": {"\u3000": 0}},
    {"id": "string-surrogate-lone-d800", "class": "string/surrogate/lone/d800", "document": "export default \"\\ud800\";", "graph": "\ud800"},
    {"id": "key-surrogate-lone-d800", "class": "key/string/surrogate/lone/d800", "document": "export default {\"\\ud800\":0};", "graph": {"\ud800": 0}},
    {"id": "string-surrogate-lone-dbff", "class": "string/surrogate/lone/dbff", "document": "export default \"\\udbff\";", "graph": "\udbff"},
    {"id": "key-surrogate-lone-dbff", "class": "key/string/surrogate/lone/dbff", "document": "export default {\"\\udbff\":0};", "graph": {"\udbff": 0}},
    {"id": "string-surrogate-lone-dc00", "class": "string/surrogate/lone/dc00", "document": "export default \"\\udc00\";", "graph": "\udc00"},
    {"id": "key-surrogate-lone-dc00", "class": "key/string/surrogate/lone/dc00", "document": "export default {\"\\udc00\":0};", "graph": {"\udc00": 0}},
    {"id": "string-surrogate-lone-dfff", "class": "string/surrogate/lone/dfff", "document": "export default \"\\udfff\";", "graph": "\udfff"},
    {"id": "key-surrogate-lone-dfff", "class": "key/string/surrogate/lone/dfff", "document": "export default {\"\\udfff\":0};", "graph": {"\udfff": 0}},
    {"id": "string-surrogate-pair-interior", "class": "string/surrogate/pair/interior", "document": "export default \"\\ud83d\\ude00\";", "graph": "\ud83d\ude00"},
    {"id": "key-surrogate-pair-interior", "class": "key/string/surrogate/pair/interior", "document": "export default {\"\\ud83d\\ude00\":0};", "graph": {"\ud83d\ude00": 0}},
    {"id": "string-surrogate-pair-low-corner", "class": "string/surrogate/pair/low-corner", "document": "export default \"\\ud800\\udc00\";", "graph": "\ud800\udc00"},
    {"id": "key-surrogate-pair-low-corner", "class": "key/string/surrogate/pair/low-corner", "document": "export default {\"\\ud800\\udc00\":0};", "graph": {"\ud800\udc00": 0}},
    {"id": "string-surrogate-pair-high-corner", "class": "string/surrogate/pair/high-corner", "document": "export default \"\\udbff\\udfff\";", "graph": "\udbff\udfff"},
    {"id": "key-surrogate-pair-high-corner", "class": "key/string/surrogate/pair/high-corner", "document": "export default {\"\\udbff\\udfff\":0};", "graph": {"\udbff\udfff": 0}},
    {"id": "string-surrogate-pair-mixed", "class": "string/surrogate/pair/mixed", "document": "export default \"\\ud800\\udfff\";", "graph": "\ud800\udfff"},
    {"id": "key-surrogate-pair-mixed", "class": "key/string/surrogate/pair/mixed", "document": "export default {\"\\ud800\\udfff\":0};", "graph": {"\ud800\udfff": 0}},
    {"id": "string-surrogate-adjacent-hh-d800", "class": "string/surrogate/adjacent/hh-d800", "document": "export default \"\\ud800\\ud800\";", "graph": "\ud800\ud800"},
    {"id": "key-surrogate-adjacent-hh-d800", "class": "key/string/surrogate/adjacent/hh-d800", "document": "export default {\"\\ud800\\ud800\":0};", "graph": {"\ud800\ud800": 0}},
    {"id": "string-surrogate-adjacent-lh-dc00-d800", "class": "string/surrogate/adjacent/lh-dc00-d800", "document": "export default \"\\udc00\\ud800\";", "graph": "\udc00\ud800"},
    {"id": "key-surrogate-adjacent-lh-dc00-d800", "class": "key/string/surrogate/adjacent/lh-dc00-d800", "document": "export default {\"\\udc00\\ud800\":0};", "graph": {"\udc00\ud800": 0}},
    {"id": "string-surrogate-adjacent-ll-dc00", "class": "string/surrogate/adjacent/ll-dc00", "document": "export default \"\\udc00\\udc00\";", "graph": "\udc00\udc00"},
    {"id": "key-surrogate-adjacent-ll-dc00", "class": "key/string/surrogate/adjacent/ll-dc00", "document": "export default {\"\\udc00\\udc00\":0};", "graph": {"\udc00\udc00": 0}},
    {"id": "string-surrogate-adjacent-hh-dbff", "class": "string/surrogate/adjacent/hh-dbff", "document": "export default \"\\udbff\\udbff\";", "graph": "\udbff\udbff"},
    {"id": "key-surrogate-adjacent-hh-dbff", "class": "key/string/surrogate/adjacent/hh-dbff", "document": "export default {\"\\udbff\\udbff\":0};", "graph": {"\udbff\udbff": 0}},
    {"id": "string-surrogate-adjacent-lh-dfff-dbff", "class": "string/surrogate/adjacent/lh-dfff-dbff", "document": "export default \"\\udfff\\udbff\";", "graph": "\udfff\udbff"},
    {"id": "key-surrogate-adjacent-lh-dfff-dbff", "class": "key/string/surrogate/adjacent/lh-dfff-dbff", "document": "export default {\"\\udfff\\udbff\":0};", "graph": {"\udfff\udbff": 0}},
    {"id": "string-surrogate-adjacent-ll-dfff", "class": "string/surrogate/adjacent/ll-dfff", "document": "export default \"\\udfff\\udfff\";", "graph": "\udfff\udfff"},
    {"id": "key-surrogate-adjacent-ll-dfff", "class": "key/string/surrogate/adjacent/ll-dfff", "document": "export default {\"\\udfff\\udfff\":0};", "graph": {"\udfff\udfff": 0}},
    {"id": "string-surrogate-adjacent-hh-d800-dbff", "class": "string/surrogate/adjacent/hh-d800-dbff", "document": "export default \"\\ud800\\udbff\";", "graph": "\ud800\udbff"},
    {"id": "key-surrogate-adjacent-hh-d800-dbff", "class": "key/string/surrogate/adjacent/hh-d800-dbff", "document": "export default {\"\\ud800\\udbff\":0};", "graph": {"\ud800\udbff": 0}}
];
