const $s0 = [0];
const $s1 = {"a": 0};
const $s2 = [0];
const $s3 = [0];
const $s4 = {"a": 0};
export default [
    {"id": "ser-null", "class": "leaf/null", "input": null},
    {"id": "ser-true", "class": "leaf/boolean/true", "input": true},
    {"id": "ser-false", "class": "leaf/boolean/false", "input": false},
    {"id": "ser-undefined", "class": "leaf/undefined", "input": undefined},
    {"id": "ser-nan", "class": "leaf/nan", "input": NaN},
    {"id": "ser-infinity", "class": "infinity/plus", "input": Infinity},
    {"id": "ser-neg-infinity", "class": "infinity/minus", "input": -Infinity},
    {"id": "ser-number-0", "class": "number/int/zero", "input": 0},
    {"id": "ser-number-neg-0", "class": "number/int/zero/neg", "input": -0},
    {"id": "ser-number-1.5", "class": "number/frac", "input": 1.5},
    {"id": "ser-number-neg-1.5", "class": "number/frac/neg", "input": -1.5},
    {"id": "ser-number-subnormal", "class": "number/binary64/subnormal", "input": 5e-324},
    {"id": "ser-number-neg-subnormal", "class": "number/binary64/subnormal/neg", "input": -5e-324},
    {"id": "ser-number-max", "class": "number/binary64/max", "input": 1.7976931348623157e308},
    {"id": "ser-number-neg-max", "class": "number/binary64/max/neg", "input": -1.7976931348623157e308},
    {"id": "ser-bigint-0", "class": "bigint/zero", "input": 0n},
    {"id": "ser-bigint-109", "class": "bigint/digits", "input": 109n},
    {"id": "ser-bigint-neg-109", "class": "bigint/digits/neg", "input": -109n},
    {"id": "ser-bigint-2p53", "class": "bigint/past-2p53", "input": 9007199254740993n},
    {"id": "ser-bigint-neg-2p53", "class": "bigint/past-2p53/neg", "input": -9007199254740993n},
    {"id": "ser-bigint-2p64", "class": "bigint/past-2p64", "input": 18446744073709551617n},
    {"id": "ser-bigint-neg-2p64", "class": "bigint/past-2p64/neg", "input": -18446744073709551617n},
    {"id": "ser-bigint-2p128", "class": "bigint/past-2p128", "input": 340282366920938463463374607431768211457n},
    {"id": "ser-bigint-neg-2p128", "class": "bigint/past-2p128/neg", "input": -340282366920938463463374607431768211457n},
    {"id": "ser-array-empty", "class": "array/empty", "input": []},
    {"id": "ser-array-one", "class": "array/one", "input": [1]},
    {"id": "ser-array-three", "class": "array/three", "input": [1, 2, 3]},
    {"id": "ser-object-empty", "class": "object/empty", "input": {}},
    {"id": "ser-object-one", "class": "object/one", "input": {"a": 1}},
    {"id": "ser-object-three", "class": "object/three", "input": {"a": 1, "b": 2, "c": 3}},
    {"id": "ser-array-nested-array", "class": "array/nested/array", "input": [[1]]},
    {"id": "ser-array-nested-object", "class": "array/nested/object", "input": [{"a": 1}]},
    {"id": "ser-object-nested-object", "class": "object/nested/object", "input": {"a": {"b": 1}}},
    {"id": "ser-object-nested-array", "class": "object/nested/array", "input": {"a": [1]}},
    {"id": "ser-array-elements-every-value", "class": "array/elements/every-value", "input": [null, true, false, undefined, NaN, Infinity, -Infinity, 0, -0, 1.5, -1.5, 109n, -109n, "", "a", [], {}]},
    {"id": "ser-object-members-every-value", "class": "object/members/every-value", "input": {"a": null, "b": true, "c": false, "d": undefined, "e": NaN, "f": Infinity, "g": -Infinity, "h": 0, "i": -0, "j": 1.5, "k": -1.5, "l": 109n, "m": -109n, "n": "", "o": "a", "p": [], "q": {}}},
    {"id": "ser-object-key-order-names-first-occurrence", "class": "object/key-order/names/first-occurrence", "input": {"b": 1, "a": 2, "c": 3}},
    {"id": "ser-object-key-order-index-before-name", "class": "object/key-order/index-before-name", "input": {"10": 1, "2": 2, "z": 3, "a": 4}},
    {"id": "ser-key-proto", "class": "key/proto", "input": {["__proto__"]: 1}},
    {"id": "ser-key-proto-among", "class": "key/proto/among", "input": {"a": 1, ["__proto__"]: 2, "b": 3}},
    {"id": "ser-string-escape-quote", "class": "string/escape/quote", "input": "\""},
    {"id": "ser-key-escape-quote", "class": "key/string/escape/quote", "input": {"\"": 0}},
    {"id": "ser-string-escape-backslash", "class": "string/escape/backslash", "input": "\\"},
    {"id": "ser-key-escape-backslash", "class": "key/string/escape/backslash", "input": {"\\": 0}},
    {"id": "ser-string-escape-u00-0000", "class": "string/escape/u00/0000", "input": "\u0000"},
    {"id": "ser-key-escape-u00-0000", "class": "key/string/escape/u00/0000", "input": {"\u0000": 0}},
    {"id": "ser-string-escape-u00-001f", "class": "string/escape/u00/001f", "input": "\u001f"},
    {"id": "ser-key-escape-u00-001f", "class": "key/string/escape/u00/001f", "input": {"\u001f": 0}},
    {"id": "ser-string-escape-b", "class": "string/escape/b", "input": "\b"},
    {"id": "ser-key-escape-b", "class": "key/string/escape/b", "input": {"\b": 0}},
    {"id": "ser-string-escape-t", "class": "string/escape/t", "input": "\t"},
    {"id": "ser-key-escape-t", "class": "key/string/escape/t", "input": {"\t": 0}},
    {"id": "ser-string-escape-n", "class": "string/escape/n", "input": "\n"},
    {"id": "ser-key-escape-n", "class": "key/string/escape/n", "input": {"\n": 0}},
    {"id": "ser-string-escape-f", "class": "string/escape/f", "input": "\f"},
    {"id": "ser-key-escape-f", "class": "key/string/escape/f", "input": {"\f": 0}},
    {"id": "ser-string-escape-r", "class": "string/escape/r", "input": "\r"},
    {"id": "ser-key-escape-r", "class": "key/string/escape/r", "input": {"\r": 0}},
    {"id": "ser-string-surrogate-lone-d800", "class": "string/surrogate/lone/d800", "input": "\ud800"},
    {"id": "ser-key-surrogate-lone-d800", "class": "key/string/surrogate/lone/d800", "input": {"\ud800": 0}},
    {"id": "ser-string-surrogate-lone-dbff", "class": "string/surrogate/lone/dbff", "input": "\udbff"},
    {"id": "ser-key-surrogate-lone-dbff", "class": "key/string/surrogate/lone/dbff", "input": {"\udbff": 0}},
    {"id": "ser-string-surrogate-lone-dc00", "class": "string/surrogate/lone/dc00", "input": "\udc00"},
    {"id": "ser-key-surrogate-lone-dc00", "class": "key/string/surrogate/lone/dc00", "input": {"\udc00": 0}},
    {"id": "ser-string-surrogate-lone-dfff", "class": "string/surrogate/lone/dfff", "input": "\udfff"},
    {"id": "ser-key-surrogate-lone-dfff", "class": "key/string/surrogate/lone/dfff", "input": {"\udfff": 0}},
    {"id": "ser-string-surrogate-pair-interior", "class": "string/surrogate/pair/interior", "input": "😀"},
    {"id": "ser-key-surrogate-pair-interior", "class": "key/string/surrogate/pair/interior", "input": {"😀": 0}},
    {"id": "ser-string-raw-latin", "class": "string/raw/bmp", "input": "é"},
    {"id": "ser-key-raw-latin", "class": "key/string/raw/bmp", "input": {"é": 0}},
    {"id": "ser-string-raw-0020", "class": "string/raw/range/0020-0021/low", "input": " "},
    {"id": "ser-key-raw-0020", "class": "key/string/raw/range/0020-0021/low", "input": {" ": 0}},
    {"id": "ser-string-raw-0800", "class": "string/raw/bmp", "input": "ࠀ"},
    {"id": "ser-key-raw-0800", "class": "key/string/raw/bmp", "input": {"ࠀ": 0}},
    {"id": "ser-string-raw-10000", "class": "string/raw/astral", "input": "𐀀"},
    {"id": "ser-key-raw-10000", "class": "key/string/raw/astral", "input": {"𐀀": 0}},
    {"id": "ser-string-raw-10ffff", "class": "string/raw/range/005d-10ffff/high", "input": "􏿿"},
    {"id": "ser-key-raw-10ffff", "class": "key/string/raw/range/005d-10ffff/high", "input": {"􏿿": 0}},
    {"id": "ser-string-raw-ws-like-00a0", "class": "string/raw/ws-like/00a0", "input": " "},
    {"id": "ser-key-raw-ws-like-00a0", "class": "key/string/raw/ws-like/00a0", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-1680", "class": "string/raw/ws-like/1680", "input": " "},
    {"id": "ser-key-raw-ws-like-1680", "class": "key/string/raw/ws-like/1680", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2000", "class": "string/raw/ws-like/2000", "input": " "},
    {"id": "ser-key-raw-ws-like-2000", "class": "key/string/raw/ws-like/2000", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2001", "class": "string/raw/ws-like/2001", "input": " "},
    {"id": "ser-key-raw-ws-like-2001", "class": "key/string/raw/ws-like/2001", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2002", "class": "string/raw/ws-like/2002", "input": " "},
    {"id": "ser-key-raw-ws-like-2002", "class": "key/string/raw/ws-like/2002", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2003", "class": "string/raw/ws-like/2003", "input": " "},
    {"id": "ser-key-raw-ws-like-2003", "class": "key/string/raw/ws-like/2003", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2004", "class": "string/raw/ws-like/2004", "input": " "},
    {"id": "ser-key-raw-ws-like-2004", "class": "key/string/raw/ws-like/2004", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2005", "class": "string/raw/ws-like/2005", "input": " "},
    {"id": "ser-key-raw-ws-like-2005", "class": "key/string/raw/ws-like/2005", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2006", "class": "string/raw/ws-like/2006", "input": " "},
    {"id": "ser-key-raw-ws-like-2006", "class": "key/string/raw/ws-like/2006", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2007", "class": "string/raw/ws-like/2007", "input": " "},
    {"id": "ser-key-raw-ws-like-2007", "class": "key/string/raw/ws-like/2007", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2008", "class": "string/raw/ws-like/2008", "input": " "},
    {"id": "ser-key-raw-ws-like-2008", "class": "key/string/raw/ws-like/2008", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2009", "class": "string/raw/ws-like/2009", "input": " "},
    {"id": "ser-key-raw-ws-like-2009", "class": "key/string/raw/ws-like/2009", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-200a", "class": "string/raw/ws-like/200a", "input": " "},
    {"id": "ser-key-raw-ws-like-200a", "class": "key/string/raw/ws-like/200a", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2028", "class": "string/raw/ws-like/2028", "input": " "},
    {"id": "ser-key-raw-ws-like-2028", "class": "key/string/raw/ws-like/2028", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-2029", "class": "string/raw/ws-like/2029", "input": " "},
    {"id": "ser-key-raw-ws-like-2029", "class": "key/string/raw/ws-like/2029", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-202f", "class": "string/raw/ws-like/202f", "input": " "},
    {"id": "ser-key-raw-ws-like-202f", "class": "key/string/raw/ws-like/202f", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-205f", "class": "string/raw/ws-like/205f", "input": " "},
    {"id": "ser-key-raw-ws-like-205f", "class": "key/string/raw/ws-like/205f", "input": {" ": 0}},
    {"id": "ser-string-raw-ws-like-3000", "class": "string/raw/ws-like/3000", "input": "　"},
    {"id": "ser-key-raw-ws-like-3000", "class": "key/string/raw/ws-like/3000", "input": {"　": 0}},
    {"id": "ser-string-raw-ws-like-feff", "class": "string/raw/ws-like/feff", "input": "﻿"},
    {"id": "ser-key-raw-ws-like-feff", "class": "key/string/raw/ws-like/feff", "input": {"﻿": 0}},
    {"id": "ser-string-empty", "class": "string/empty", "input": ""},
    {"id": "ser-key-empty", "class": "key/string/empty", "input": {"": 0}},
    {"id": "ser-sharing-array", "class": "const/shared/twice", "input": [$s0, $s0]},
    {"id": "ser-sharing-object", "class": "const/shared/object", "input": {"x": $s1, "y": $s1}},
    {"id": "ser-sharing-mixed", "class": "const/shared/mixed", "input": [[$s2], {"x": $s2}]},
    {"id": "ser-string-raw-slash", "class": "string/raw/slash", "input": "/"},
    {"id": "ser-key-raw-slash", "class": "key/string/raw/slash", "input": {"/": 0}},
    {"id": "ser-string-raw-0023", "class": "string/raw/range/0023-005b/low", "input": "#"},
    {"id": "ser-key-raw-0023", "class": "key/string/raw/range/0023-005b/low", "input": {"#": 0}},
    {"id": "ser-string-raw-005b", "class": "string/raw/range/0023-005b/high", "input": "["},
    {"id": "ser-key-raw-005b", "class": "key/string/raw/range/0023-005b/high", "input": {"[": 0}},
    {"id": "ser-string-surrogate-adjacent-hh-d800", "class": "string/surrogate/adjacent/hh-d800", "input": "\ud800\ud800"},
    {"id": "ser-key-surrogate-adjacent-hh-d800", "class": "key/string/surrogate/adjacent/hh-d800", "input": {"\ud800\ud800": 0}},
    {"id": "ser-string-surrogate-adjacent-lh-dc00-d800", "class": "string/surrogate/adjacent/lh-dc00-d800", "input": "\udc00\ud800"},
    {"id": "ser-key-surrogate-adjacent-lh-dc00-d800", "class": "key/string/surrogate/adjacent/lh-dc00-d800", "input": {"\udc00\ud800": 0}},
    {"id": "ser-string-surrogate-adjacent-ll-dc00", "class": "string/surrogate/adjacent/ll-dc00", "input": "\udc00\udc00"},
    {"id": "ser-key-surrogate-adjacent-ll-dc00", "class": "key/string/surrogate/adjacent/ll-dc00", "input": {"\udc00\udc00": 0}},
    {"id": "ser-string-surrogate-adjacent-hh-dbff", "class": "string/surrogate/adjacent/hh-dbff", "input": "\udbff\udbff"},
    {"id": "ser-key-surrogate-adjacent-hh-dbff", "class": "key/string/surrogate/adjacent/hh-dbff", "input": {"\udbff\udbff": 0}},
    {"id": "ser-string-surrogate-adjacent-lh-dfff-dbff", "class": "string/surrogate/adjacent/lh-dfff-dbff", "input": "\udfff\udbff"},
    {"id": "ser-key-surrogate-adjacent-lh-dfff-dbff", "class": "key/string/surrogate/adjacent/lh-dfff-dbff", "input": {"\udfff\udbff": 0}},
    {"id": "ser-string-surrogate-adjacent-ll-dfff", "class": "string/surrogate/adjacent/ll-dfff", "input": "\udfff\udfff"},
    {"id": "ser-key-surrogate-adjacent-ll-dfff", "class": "key/string/surrogate/adjacent/ll-dfff", "input": {"\udfff\udfff": 0}},
    {"id": "ser-string-surrogate-adjacent-hh-d800-dbff", "class": "string/surrogate/adjacent/hh-d800-dbff", "input": "\ud800\udbff"},
    {"id": "ser-key-surrogate-adjacent-hh-d800-dbff", "class": "key/string/surrogate/adjacent/hh-d800-dbff", "input": {"\ud800\udbff": 0}},
    {"id": "ser-shared-two-nodes", "class": "const/shared/two-nodes", "input": [$s3, $s4, $s3, $s4]},
    {"id": "ser-key-proto-nested", "class": "key/proto/nested", "input": [{["__proto__"]: {["__proto__"]: 1}}]},
    {"id": "ser-string-raw-007f", "class": "string/raw/bmp", "input": "\u007f"},
    {"id": "ser-key-raw-007f", "class": "key/string/raw/bmp", "input": {"\u007f": 0}},
    {"id": "ser-string-raw-0080", "class": "string/raw/bmp", "input": "\u0080"},
    {"id": "ser-key-raw-0080", "class": "key/string/raw/bmp", "input": {"\u0080": 0}},
    {"id": "ser-string-raw-07ff", "class": "string/raw/bmp", "input": "\u07ff"},
    {"id": "ser-key-raw-07ff", "class": "key/string/raw/bmp", "input": {"\u07ff": 0}},
    {"id": "ser-string-raw-d7ff", "class": "string/raw/bmp", "input": "\ud7ff"},
    {"id": "ser-key-raw-d7ff", "class": "key/string/raw/bmp", "input": {"\ud7ff": 0}},
    {"id": "ser-string-raw-e000", "class": "string/raw/bmp", "input": "\ue000"},
    {"id": "ser-key-raw-e000", "class": "key/string/raw/bmp", "input": {"\ue000": 0}},
    {"id": "ser-string-raw-ffff", "class": "string/raw/bmp", "input": "\uffff"},
    {"id": "ser-key-raw-ffff", "class": "key/string/raw/bmp", "input": {"\uffff": 0}}
];
