import { assert, assertEq } from '../../asserts/module.f.mjs'
import { nodeCommands } from '../../effects/node/module.f.mjs'
import { directory, generate, path } from './module.f.mjs'

export const proof = {
    generate: () => {
        const rust = generate()
        assert(rust.startsWith('// @generated by `npm run gen` from `fjs/nanvm/commands/module.f.mjs`.\n'), rust)
        assert(rust.includes('pub const COMMANDS: &[&str] = &[\n    "access",\n'), rust)
        assert(rust.endsWith('    "writeFile",\n];\n'), rust)
        // Every command of the set is printed once, and nothing else is.
        assertEq(rust.split('\n    "').length - 1, nodeCommands.length)
        assert(nodeCommands.every(command => rust.includes(`\n    "${command}",\n`)), rust)
        assertEq(path, `${directory}/gen.commands.rs`)
        assertEq(directory, 'nanvm-effects-node/src')
    },
}
