runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v2
      with:
        deno-version: 2
    - run: deno install
      shell: bash
    - run: deno task test
      shell: bash
    - run: deno task fst
      shell: bash
    - run: deno publish --dry-run
      shell: bash
