/**
 * Proofs for the Rust printer.
 *
 * The interesting assertion is `generate`'s on a tiny synthetic corpus: it
 * pins the exact text of every construct the printer can emit, so a change in
 * layout is a visible diff here and not only in the generated file.
 *
 * @import { Data, Value } from '../types.ts'
 */

import { assert, assertEq } from '../../asserts/module.f.mjs'
import { casesOf, data, functionValue, groupKey, lambdaExp, ref, throws, valueExp } from '../module.f.mjs'
import { directory, generate, nodeExpr, path, rustName } from './module.f.mjs'

/** A value as the printer meets it: its lowering, printed. @type {(v: Value) => string} */
const valueExpr = v => nodeExpr(valueExp(v))

/**
 * One case of every shape the printer can emit: a shared value and a
 * reference to it, a skipped case, a throwing case, an `Op12` group at unary
 * arity, the ternary operation, and a commutative binary operator.
 *
 * @type {Data}
 */
const sample = {
    shared: { emptyArray: [] },
    groups: [
        {
            op: '===',
            commutative: true,
            cases: [
                {
                    name: 'itself',
                    args: [ref('emptyArray'), ref('emptyArray')],
                    expected: true,
                },
                { name: 'skipped', args: [null, null], expected: true, rust: 'not yet' },
            ],
        },
        { op: '+', arity: 1, cases: [{ name: 'bigint', args: [0n], expected: throws }] },
        { op: '?:', cases: [{ name: 'pick', args: [true, 1, 2], expected: 1 }] },
        {
            op: '*',
            commutative: true,
            cases: [{ name: 'oneByTwo', args: [1, 2], expected: 2 }],
        },
    ],
}

const expected = `// @generated by \`npm run gen\` from \`fjs/nanvm/module.f.mjs\`.
// Do not edit: change the shared operator test data and regenerate.

use super::harness::*;

#[rustfmt::skip]
fn eq<A: IVm>() {
    let empty_array: Any<A> = Array::default().to_any();
    check::<A>("itself", strict_eq(empty_array.clone(), empty_array.clone()), true.to_any());
    check::<A>("itselfSwapped", strict_eq(empty_array.clone(), empty_array.clone()), true.to_any());
    // TODO: not yet: check::<A>("skipped", strict_eq(Nullish::Null.to_any(), Nullish::Null.to_any()), true.to_any());
    // TODO: not yet: check::<A>("skippedSwapped", strict_eq(Nullish::Null.to_any(), Nullish::Null.to_any()), true.to_any());
}

#[rustfmt::skip]
fn unary_plus<A: IVm>() {
    check_throws::<A>("bigint", Any::unary_plus(bigint_any(0)));
}

#[rustfmt::skip]
fn conditional<A: IVm>() {
    check::<A>("pick", Any::conditional(true.to_any(), (1f64).to_any(), (2f64).to_any()), (1f64).to_any());
}

#[rustfmt::skip]
fn mul<A: IVm>() {
    check::<A>("oneByTwo", (1f64).to_any() * (2f64).to_any(), (2f64).to_any());
    check::<A>("oneByTwoSwapped", (2f64).to_any() * (1f64).to_any(), (2f64).to_any());
}

pub fn all<A: IVm>() {
    eq::<A>();
    unary_plus::<A>();
    conditional::<A>();
    mul::<A>();
}
`

export const proof = {
    path: () => {
        assertEq(directory, 'nanvm-lib/tests/test')
        assertEq(path, 'nanvm-lib/tests/test/generated.rs')
    },
    valueExpr: () => {
        assertEq(valueExpr(null), 'Nullish::Null.to_any()')
        assertEq(valueExpr(undefined), 'Nullish::Undefined.to_any()')
        assertEq(valueExpr(true), 'true.to_any()')
        assertEq(valueExpr(false), 'false.to_any()')
        assertEq(valueExpr(-0.3), '(-0.3f64).to_any()')
        assertEq(valueExpr('a'), 'string_any("a")')
        assertEq(valueExpr(-1n), 'bigint_any(-1)')
        assertEq(valueExpr([]), 'Array::default().to_any()')
        assertEq(valueExpr([null]), '[Nullish::Null.to_any()].to_array().to_any()')
        assertEq(valueExpr({}), 'Object::default().to_any()')
        assertEq(
            valueExpr({ k: null }),
            '[(string_key("k"), Nullish::Null.to_any())].to_object().to_any()')
        assertEq(valueExpr(functionValue), 'function_any()')
        // Nested, a function is the same node inside its container's.
        assertEq(valueExpr([functionValue]), '[function_any()].to_array().to_any()')
    },
    /**
     * The operation nodes, printed straight from the EDAG rather than through
     * a case: this is the whole of what the printer knows about operations,
     * and the ids are the canonical ones.
     */
    nodeExpr: () => {
        assertEq(nodeExpr(['-', 1]), '-((1f64).to_any())')
        assertEq(nodeExpr(['+', 1]), 'Any::unary_plus((1f64).to_any())')
        assertEq(nodeExpr(['typeof', 1]), 'Any::typeof_((1f64).to_any())')
        assertEq(
            nodeExpr(['?:', true, 1, 2]),
            'Any::conditional(true.to_any(), (1f64).to_any(), (2f64).to_any())')
        // The one `=>` with a spelling: the corpus's function value, printed
        // as the harness's stand-in, and atomic as an operand.
        assertEq(nodeExpr(lambdaExp()), 'function_any()')
        assertEq(nodeExpr(['-', lambdaExp()]), '-(function_any())')
        assertEq(
            nodeExpr(['String', 'a']),
            'string_any("a").to_string().map(|v| v.to_any())')
        assertEq(nodeExpr(['*', 1, 2]), '(1f64).to_any() * (2f64).to_any()')
        assertEq(nodeExpr(['-', 1, 2]), '(1f64).to_any() - (2f64).to_any()')
        assertEq(nodeExpr(['+', 1, 2]), '(1f64).to_any() + (2f64).to_any()')
        assertEq(nodeExpr(['undefined']), 'Nullish::Undefined.to_any()')
    },
    /**
     * An operation nested as an operand keeps its parentheses.
     *
     * Rust parses `a * b * c` to the left and binds a method call tighter
     * than `*`, so without them the printed statement would be a different
     * program from the node — `1e308 * (1e-308 * 1e-308)` underflows to zero
     * where the flattened reading does not.
     *
     * Grouping is all this claims. The printed text is not yet *compilable*
     * Rust for a nested operation: every `nanvm-lib` operator returns
     * `Result<Any<A>, Any<A>>`, which `check` takes at the top of a statement,
     * so an inner operation hands the outer one a `Result` where it needs an
     * `Any`. Propagating that is the nested-emission strategy owed by
     * [corpus-as-conformance-vectors](../todo/corpus-as-conformance-vectors.md).
     * No corpus case needs it yet — a case is one operation over lowered
     * values, so `generated.rs` nests nothing — but `nodeExpr` is exported and
     * takes an arbitrary `Exp`, so a caller can reach it today, and the
     * lazy-operator groups will nest.
     *
     * Unary `-` parenthesizes in its own template, so a composed operand
     * there is doubly wrapped — redundant, and correct either way.
     */
    nestedOperation: () => {
        assertEq(
            nodeExpr(['*', 1, ['*', 2, 3]]),
            '(1f64).to_any() * ((2f64).to_any() * (3f64).to_any())')
        assertEq(
            nodeExpr(['String', ['*', 1, 2]]),
            '((1f64).to_any() * (2f64).to_any()).to_string().map(|v| v.to_any())')
        assertEq(
            nodeExpr(['-', ['*', 1, 2]]),
            '-(((1f64).to_any() * (2f64).to_any()))')
        // An array, an object and `['undefined']` are atomic renderings, so
        // they are operands as written.
        assertEq(nodeExpr(['-', ['undefined']]), '-(Nullish::Undefined.to_any())')
        assertEq(nodeExpr(['-', ['[]', []]]), '-(Array::default().to_any())')
        assertEq(nodeExpr(['-', ['{}', []]]), '-(Object::default().to_any())')
    },
    /**
     * A Rust name is this printer's, and never derived from a punctuation id.
     * It is keyed by group, so the two arities of `-` are two names.
     */
    rustName: () => {
        assertEq(rustName['*'], 'mul')
        assertEq(rustName['-/2'], 'sub')
        assertEq(rustName['+/2'], 'add')
        assertEq(rustName['-/1'], 'neg')
        assertEq(rustName.String, 'string_coercion')
        assertEq(rustName['+/1'], 'unary_plus')
    },
    generate: () => {
        assertEq(generate(sample), expected)
    },
    /**
     * A shared value referencing an earlier one clones that binding.
     *
     * Printed without the bindings established before it, the initializer
     * would construct a second object and the Rust heap graph would not be
     * the graph the nodes describe — with `base` left unread besides.
     */
    nestedSharing: () => {
        const rust = generate({
            shared: { base: [], wrapper: [ref('base')] },
            groups: [{
                op: '===',
                cases: [{
                    name: 'w',
                    args: [ref('wrapper'), ref('wrapper')],
                    expected: true,
                }],
            }],
        })
        assert(
            rust.includes('let wrapper: Any<A> = [base.clone()].to_array().to_any();'),
            rust)
    },
    generateData: () => {
        // The real corpus, which is what `gen` writes. Only its shape is
        // asserted here: its contents are checked by `cargo test`.
        const result = generate(data)
        assert(result.endsWith('}\n'), result)
        assert(result.includes('pub fn all<A: IVm>() {'), result)
        for (const g of data.groups) {
            const n = rustName[groupKey(g)]
            assert(result.includes(`fn ${n}<A: IVm>() {`), n)
            assert(result.includes(`${n}::<A>();`), n)
            // Every case reaches the output, commented out or not.
            for (const c of casesOf(g)) { assert(result.includes(`"${c.name}"`), c.name) }
        }
    },
    throw: {
        /**
         * An operation the printer has no `nanvm-lib` spelling for. The
         * generated file would otherwise carry a statement that does not
         * compile, or worse, one that does and means something else. `!==`
         * is such an id: the schema has it and the corpus has no group for
         * it, so nothing maps it.
         */
        unknownOperation: () => nodeExpr(['!==', 1, 2]),
        /**
         * A lambda other than `() => undefined`: no closure prints, so each
         * way of not being the smallest one is refused — a frame that is a
         * primitive, one that is a node but not an array literal, one that is
         * not empty, a body that is not a node, and a body that is not the
         * `undefined` node.
         */
        lambdaFramePrimitive: () => nodeExpr(['=>', 1, 2]),
        lambdaFrameNotArray: () => nodeExpr(['=>', ['undefined'], ['undefined']]),
        lambdaFrameNotEmpty: () => nodeExpr(['=>', ['[]', [1]], ['undefined']]),
        lambdaBodyPrimitive: () => nodeExpr(['=>', ['[]', []], 5]),
        lambdaBodyNotUndefined: () => nodeExpr(['=>', ['[]', []], ['args']]),
        /** An object key the corpus cannot produce and Rust cannot spell. */
        computedKey: () => nodeExpr(['{}', [[':', ['undefined'], 1]]]),
        /**
         * An object spread. `Properties` is `Property | Spread`, so this is a
         * valid `Exp`; read as a property it printed the spread's operand as
         * the key and a bare `undefined` as the value.
         */
        objectSpread: () => nodeExpr(['{}', [['...', 'x']]]),
    },
}
