/**
 * Proofs for the Rust printer.
 *
 * The interesting assertion is `generate`'s on a tiny synthetic corpus: it
 * pins the exact text of every construct the printer can emit, so a change in
 * layout is a visible diff here and not only in the generated file.
 *
 * @import { Data } from '../types.ts'
 */

import { assert, assertEq } from '../../asserts/module.f.mjs'
import { casesOf, data, functionValue, opId, ref, throws } from '../module.f.mjs'
import { directory, generate, nodeExpr, path, rustName, valueExpr } from './module.f.mjs'

/**
 * One case of every shape the printer can emit: a shared value and a
 * reference to it, a skipped case, a throwing case, a group with no canonical
 * EDAG id, and a commutative binary operator.
 *
 * @type {Data}
 */
const sample = {
    eq: {
        shared: { emptyArray: [] },
        cases: [
            { name: 'itself', a: ref('emptyArray'), b: ref('emptyArray'), eq: true },
            { name: 'skipped', a: null, b: null, eq: true, rust: 'not yet' },
        ],
    },
    groups: [
        { nanvmOp: 'unaryPlus', cases: [{ name: 'bigint', args: [0n], expected: throws }] },
        {
            op: '*',
            commutative: true,
            cases: [{ name: 'oneByTwo', args: [1, 2], expected: 2 }],
        },
    ],
}

const expected = `// @generated by \`npm run ci-update\` from \`fjs/nanvm/module.f.mjs\`.
// Do not edit: change the shared operator test data and regenerate.

use super::harness::*;

#[rustfmt::skip]
fn eq<A: IVm>() {
    let empty_array: Any<A> = Array::default().to_any();
    check_eq::<A>("itself", empty_array.clone(), empty_array.clone(), true);
    // TODO: not yet
    // check_eq::<A>("skipped", Nullish::Null.to_any(), Nullish::Null.to_any(), true);
}

#[rustfmt::skip]
fn unary_plus<A: IVm>() {
    check_throws::<A>("bigint", Any::unary_plus(bigint_any(0)));
}

#[rustfmt::skip]
fn mul<A: IVm>() {
    check::<A>("oneByTwo", (1f64).to_any() * (2f64).to_any(), (2f64).to_any());
    check::<A>("oneByTwoSwapped", (2f64).to_any() * (1f64).to_any(), (2f64).to_any());
}

pub fn all<A: IVm>() {
    eq::<A>();
    unary_plus::<A>();
    mul::<A>();
}
`

export const proof = {
    path: () => {
        assertEq(directory, 'nanvm-lib/tests/test')
        assertEq(path, 'nanvm-lib/tests/test/generated.rs')
    },
    valueExpr: () => {
        assertEq(valueExpr(null), 'Nullish::Null.to_any()')
        assertEq(valueExpr(undefined), 'Nullish::Undefined.to_any()')
        assertEq(valueExpr(true), 'true.to_any()')
        assertEq(valueExpr(false), 'false.to_any()')
        assertEq(valueExpr(-0.3), '(-0.3f64).to_any()')
        assertEq(valueExpr('a'), 'string_any("a")')
        assertEq(valueExpr(-1n), 'bigint_any(-1)')
        assertEq(valueExpr([]), 'Array::default().to_any()')
        assertEq(valueExpr([null]), '[Nullish::Null.to_any()].to_array().to_any()')
        assertEq(valueExpr({}), 'Object::default().to_any()')
        assertEq(
            valueExpr({ k: null }),
            '[(string_key("k"), Nullish::Null.to_any())].to_object().to_any()')
        assertEq(valueExpr(functionValue), 'function_any()')
    },
    /**
     * The operation nodes, printed straight from the EDAG rather than through
     * a case: this is the whole of what the printer knows about operations,
     * and the ids are the canonical ones.
     */
    nodeExpr: () => {
        assertEq(nodeExpr(['neg', 1]), '-((1f64).to_any())')
        assertEq(
            nodeExpr(['String', 'a']),
            'string_any("a").to_string().map(|v| v.to_any())')
        assertEq(nodeExpr(['*', 1, 2]), '(1f64).to_any() * (2f64).to_any()')
        assertEq(nodeExpr(['undefined']), 'Nullish::Undefined.to_any()')
    },
    /** A Rust name is this printer's, and never derived from a punctuation id. */
    rustName: () => {
        assertEq(rustName['*'], 'mul')
        assertEq(rustName.neg, 'neg')
        assertEq(rustName.String, 'string_coercion')
        assertEq(rustName.unaryPlus, 'unary_plus')
    },
    generate: () => {
        assertEq(generate(sample), expected)
    },
    generateData: () => {
        // The real corpus, which is what `ci-update` writes. Only its shape is
        // asserted here: its contents are checked by `cargo test`.
        const result = generate(data)
        assert(result.endsWith('}\n'), result)
        assert(result.includes('pub fn all<A: IVm>() {'), result)
        for (const g of data.groups) {
            const n = rustName[opId(g)]
            assert(result.includes(`fn ${n}<A: IVm>() {`), n)
            assert(result.includes(`${n}::<A>();`), n)
            // Every case reaches the output, commented out or not.
            for (const c of casesOf(g)) { assert(result.includes(`"${c.name}"`), c.name) }
        }
    },
    throw: {
        /** `throws` is an outcome, so it has no expression to print. */
        throwsIsNotAnExp: () => valueExpr(throws),
        /**
         * An operation the printer has no `nanvm-lib` spelling for. The
         * generated file would otherwise carry a statement that does not
         * compile, or worse, one that does and means something else.
         */
        unknownOperation: () => nodeExpr(['+', 1, 2]),
        /** An object key the corpus cannot produce and Rust cannot spell. */
        computedKey: () => nodeExpr(['{}', [[':', ['undefined'], 1]]]),
    },
}
