// Expectation of `nanvm-harness/fixtures/at.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x4024000000000000), f64_any(0x403e000000000000), true.to_any(), true.to_any(), f64_any(0x4034000000000000), f64_any(0x4034000000000000), f64_any(0x4024000000000000)].to_array().to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&str> = Some("[10,30,true,true,20,20,10]");
