// Expectation of `nanvm-harness/fixtures/boolean.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::string_key;
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok([(string_key("default"), true.to_any())].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&[u8]> = Some(&[0x74, 0x72, 0x75, 0x65]);
