// Expectation of `nanvm-harness/fixtures/entry.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x3ff0000000000000), f64_any(0x4008000000000000), true.to_any(), f64_any(0x4020000000000000), f64_any(0x4020000000000000), true.to_any(), true.to_any(), string_any("a"), true.to_any(), true.to_any(), f64_any(0x4000000000000000), string_any("function"), f64_any(0x4022000000000000), f64_any(0x4014000000000000), true.to_any(), true.to_any()].to_array().to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&str> = Some("[1,3,true,8,8,true,true,\"a\",true,true,2,\"function\",9,5,true,true]");
