// Expectation of `nanvm-harness/fixtures/escapes.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [string_any("\u{0}"), string_any("\u{1f}"), string_any("\u{7f}"), string_any("\u{202e}"), string_any("\u{2069}")].to_array().to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&[u8]> = Some(&[0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x30, 0x22, 0x2c, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x31, 0x66, 0x22, 0x2c, 0x22, 0x7f, 0x22, 0x2c, 0x22, 0xe2, 0x80, 0xae, 0x22, 0x2c, 0x22, 0xe2, 0x81, 0xa9, 0x22, 0x5d]);
