// Expectation of `nanvm-harness/fixtures/lazy.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, Nullish, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x0000000000000000), f64_any(0x4000000000000000), Nullish::Null.to_any(), f64_any(0x3ff0000000000000), f64_any(0x4008000000000000), string_any("x"), f64_any(0x0000000000000000), f64_any(0x4010000000000000), f64_any(0x4014000000000000), false.to_any(), f64_any(0x401c000000000000), f64_any(0x4020000000000000), f64_any(0x4000000000000000), f64_any(0x4024000000000000), f64_any(0x4026000000000000), f64_any(0x402a000000000000), f64_any(0x4000000000000000)].to_array().to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&str> = Some("[0,2,null,1,3,\"x\",0,4,5,false,7,8,2,10,11,13,2]");
