// @generated by `fjs run ./fjs/nanvm/harness/module.f.mjs`. Do not edit: add or remove a fixture instead.

pub mod arity;
pub mod array;
pub mod at;
pub mod bigint;
pub mod boolean;
pub mod call;
pub mod calls;
pub mod closure;
pub mod closure_identity;
pub mod closure_throws;
pub mod effect;
pub mod entry;
pub mod escapes;
pub mod exports;
pub mod function_scope;
pub mod lazy;
pub mod length;
pub mod method;
pub mod missing;
pub mod named;
pub mod named_imports;
pub mod named_imports_math;
pub mod named_imports_throws;
pub mod nested;
pub mod not_a_function;
pub mod nullish;
pub mod number;
pub mod object;
pub mod object_spread;
pub mod operators;
pub mod optional;
pub mod parameters;
pub mod property;
pub mod recursion;
pub mod rest;
pub mod sharing;
pub mod spread;
pub mod string;
pub mod throw;
pub mod throws;
pub mod to_string;

use nanvm_lib::naive::Naive;

/// Every corpus fixture with its expectation.
#[rustfmt::skip]
pub const CASES: &[crate::Case] = &[
    crate::Case { name: "arity", fixture: crate::fixtures::arity::module::<Naive>, expected: arity::module::<Naive>, json: arity::JSON, throws: arity::THROWS },
    crate::Case { name: "array", fixture: crate::fixtures::array::module::<Naive>, expected: array::module::<Naive>, json: array::JSON, throws: array::THROWS },
    crate::Case { name: "at", fixture: crate::fixtures::at::module::<Naive>, expected: at::module::<Naive>, json: at::JSON, throws: at::THROWS },
    crate::Case { name: "bigint", fixture: crate::fixtures::bigint::module::<Naive>, expected: bigint::module::<Naive>, json: bigint::JSON, throws: bigint::THROWS },
    crate::Case { name: "boolean", fixture: crate::fixtures::boolean::module::<Naive>, expected: boolean::module::<Naive>, json: boolean::JSON, throws: boolean::THROWS },
    crate::Case { name: "call", fixture: crate::fixtures::call::module::<Naive>, expected: call::module::<Naive>, json: call::JSON, throws: call::THROWS },
    crate::Case { name: "calls", fixture: crate::fixtures::calls::module::<Naive>, expected: calls::module::<Naive>, json: calls::JSON, throws: calls::THROWS },
    crate::Case { name: "closure", fixture: crate::fixtures::closure::module::<Naive>, expected: closure::module::<Naive>, json: closure::JSON, throws: closure::THROWS },
    crate::Case { name: "closure_identity", fixture: crate::fixtures::closure_identity::module::<Naive>, expected: closure_identity::module::<Naive>, json: closure_identity::JSON, throws: closure_identity::THROWS },
    crate::Case { name: "closure_throws", fixture: crate::fixtures::closure_throws::module::<Naive>, expected: closure_throws::module::<Naive>, json: closure_throws::JSON, throws: closure_throws::THROWS },
    crate::Case { name: "effect", fixture: crate::fixtures::effect::module::<Naive>, expected: effect::module::<Naive>, json: effect::JSON, throws: effect::THROWS },
    crate::Case { name: "entry", fixture: crate::fixtures::entry::module::<Naive>, expected: entry::module::<Naive>, json: entry::JSON, throws: entry::THROWS },
    crate::Case { name: "escapes", fixture: crate::fixtures::escapes::module::<Naive>, expected: escapes::module::<Naive>, json: escapes::JSON, throws: escapes::THROWS },
    crate::Case { name: "exports", fixture: crate::fixtures::exports::module::<Naive>, expected: exports::module::<Naive>, json: exports::JSON, throws: exports::THROWS },
    crate::Case { name: "function_scope", fixture: crate::fixtures::function_scope::module::<Naive>, expected: function_scope::module::<Naive>, json: function_scope::JSON, throws: function_scope::THROWS },
    crate::Case { name: "lazy", fixture: crate::fixtures::lazy::module::<Naive>, expected: lazy::module::<Naive>, json: lazy::JSON, throws: lazy::THROWS },
    crate::Case { name: "length", fixture: crate::fixtures::length::module::<Naive>, expected: length::module::<Naive>, json: length::JSON, throws: length::THROWS },
    crate::Case { name: "method", fixture: crate::fixtures::method::module::<Naive>, expected: method::module::<Naive>, json: method::JSON, throws: method::THROWS },
    crate::Case { name: "missing", fixture: crate::fixtures::missing::module::<Naive>, expected: missing::module::<Naive>, json: missing::JSON, throws: missing::THROWS },
    crate::Case { name: "named", fixture: crate::fixtures::named::module::<Naive>, expected: named::module::<Naive>, json: named::JSON, throws: named::THROWS },
    crate::Case { name: "named_imports", fixture: crate::fixtures::named_imports::module::<Naive>, expected: named_imports::module::<Naive>, json: named_imports::JSON, throws: named_imports::THROWS },
    crate::Case { name: "named_imports_math", fixture: crate::fixtures::named_imports_math::module::<Naive>, expected: named_imports_math::module::<Naive>, json: named_imports_math::JSON, throws: named_imports_math::THROWS },
    crate::Case { name: "named_imports_throws", fixture: crate::fixtures::named_imports_throws::module::<Naive>, expected: named_imports_throws::module::<Naive>, json: named_imports_throws::JSON, throws: named_imports_throws::THROWS },
    crate::Case { name: "nested", fixture: crate::fixtures::nested::module::<Naive>, expected: nested::module::<Naive>, json: nested::JSON, throws: nested::THROWS },
    crate::Case { name: "not_a_function", fixture: crate::fixtures::not_a_function::module::<Naive>, expected: not_a_function::module::<Naive>, json: not_a_function::JSON, throws: not_a_function::THROWS },
    crate::Case { name: "nullish", fixture: crate::fixtures::nullish::module::<Naive>, expected: nullish::module::<Naive>, json: nullish::JSON, throws: nullish::THROWS },
    crate::Case { name: "number", fixture: crate::fixtures::number::module::<Naive>, expected: number::module::<Naive>, json: number::JSON, throws: number::THROWS },
    crate::Case { name: "object", fixture: crate::fixtures::object::module::<Naive>, expected: object::module::<Naive>, json: object::JSON, throws: object::THROWS },
    crate::Case { name: "object_spread", fixture: crate::fixtures::object_spread::module::<Naive>, expected: object_spread::module::<Naive>, json: object_spread::JSON, throws: object_spread::THROWS },
    crate::Case { name: "operators", fixture: crate::fixtures::operators::module::<Naive>, expected: operators::module::<Naive>, json: operators::JSON, throws: operators::THROWS },
    crate::Case { name: "optional", fixture: crate::fixtures::optional::module::<Naive>, expected: optional::module::<Naive>, json: optional::JSON, throws: optional::THROWS },
    crate::Case { name: "parameters", fixture: crate::fixtures::parameters::module::<Naive>, expected: parameters::module::<Naive>, json: parameters::JSON, throws: parameters::THROWS },
    crate::Case { name: "property", fixture: crate::fixtures::property::module::<Naive>, expected: property::module::<Naive>, json: property::JSON, throws: property::THROWS },
    crate::Case { name: "recursion", fixture: crate::fixtures::recursion::module::<Naive>, expected: recursion::module::<Naive>, json: recursion::JSON, throws: recursion::THROWS },
    crate::Case { name: "rest", fixture: crate::fixtures::rest::module::<Naive>, expected: rest::module::<Naive>, json: rest::JSON, throws: rest::THROWS },
    crate::Case { name: "sharing", fixture: crate::fixtures::sharing::module::<Naive>, expected: sharing::module::<Naive>, json: sharing::JSON, throws: sharing::THROWS },
    crate::Case { name: "spread", fixture: crate::fixtures::spread::module::<Naive>, expected: spread::module::<Naive>, json: spread::JSON, throws: spread::THROWS },
    crate::Case { name: "string", fixture: crate::fixtures::string::module::<Naive>, expected: string::module::<Naive>, json: string::JSON, throws: string::THROWS },
    crate::Case { name: "throw", fixture: crate::fixtures::throw::module::<Naive>, expected: throw::module::<Naive>, json: throw::JSON, throws: throw::THROWS },
    crate::Case { name: "throws", fixture: crate::fixtures::throws::module::<Naive>, expected: throws::module::<Naive>, json: throws::JSON, throws: throws::THROWS },
    crate::Case { name: "to_string", fixture: crate::fixtures::to_string::module::<Naive>, expected: to_string::module::<Naive>, json: to_string::JSON, throws: to_string::THROWS },
];
