// Expectation of `nanvm-harness/fixtures/sharing.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{f64_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("x"), f64_any(0x3ff0000000000000))].to_object().to_any();
    let c1: Any<A> = [c0.clone(), c0.clone()].to_array().to_any();
    Ok([(string_key("default"), c1)].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&[u8]> = Some(&[0x5b, 0x7b, 0x22, 0x78, 0x22, 0x3a, 0x31, 0x7d, 0x2c, 0x7b, 0x22, 0x78, 0x22, 0x3a, 0x31, 0x7d, 0x5d]);
