// Expectation of `nanvm-harness/fixtures/string.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok([(string_key("default"), string_any("hello"))].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&str> = Some("\"hello\"");
