// Expectation of `nanvm-harness/fixtures/to-string.mjs`, generated by `fjs/nanvm/expected`. Do not edit: change the fixture and regenerate.

use nanvm_lib::vm::unstable::{string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [string_any("1.5"), string_any("true"), string_any("ab"), string_any("5"), string_any("1,b"), string_any("[object Object]"), string_any("own")].to_array().to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}

#[rustfmt::skip]
pub const JSON: Option<&str> = Some("[\"1.5\",\"true\",\"ab\",\"5\",\"1,b\",\"[object Object]\",\"own\"]");
