// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullBitAndSix", Nullish::Null.to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("nullBitAndSixSwapped", f64_any(0x4018000000000000) & Nullish::Null.to_any(), f64_any(0x0000000000000000));
    check::<A>("undefinedBitAndSix", Nullish::Undefined.to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("undefinedBitAndSixSwapped", f64_any(0x4018000000000000) & Nullish::Undefined.to_any(), f64_any(0x0000000000000000));
    check::<A>("trueBitAndSix", true.to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("trueBitAndSixSwapped", f64_any(0x4018000000000000) & true.to_any(), f64_any(0x0000000000000000));
    check::<A>("falseBitAndSix", false.to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("falseBitAndSixSwapped", f64_any(0x4018000000000000) & false.to_any(), f64_any(0x0000000000000000));
    check::<A>("stringTenBitAndSix", string_any("10") & f64_any(0x4018000000000000), f64_any(0x4000000000000000));
    check::<A>("stringTenBitAndSixSwapped", f64_any(0x4018000000000000) & string_any("10"), f64_any(0x4000000000000000));
    check::<A>("stringLetterBitAndSix", string_any("a") & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("stringLetterBitAndSixSwapped", f64_any(0x4018000000000000) & string_any("a"), f64_any(0x0000000000000000));
    check::<A>("emptyArrayBitAndSix", Array::default().to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("emptyArrayBitAndSixSwapped", f64_any(0x4018000000000000) & Array::default().to_any(), f64_any(0x0000000000000000));
    check::<A>("arrayTenBitAndSix", [f64_any(0x4024000000000000)].to_array().to_any() & f64_any(0x4018000000000000), f64_any(0x4000000000000000));
    check::<A>("arrayTenBitAndSixSwapped", f64_any(0x4018000000000000) & [f64_any(0x4024000000000000)].to_array().to_any(), f64_any(0x4000000000000000));
    check::<A>("arrayStringTenBitAndSix", [string_any("10")].to_array().to_any() & f64_any(0x4018000000000000), f64_any(0x4000000000000000));
    check::<A>("arrayStringTenBitAndSixSwapped", f64_any(0x4018000000000000) & [string_any("10")].to_array().to_any(), f64_any(0x4000000000000000));
    check::<A>("arrayPairBitAndSix", [f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("arrayPairBitAndSixSwapped", f64_any(0x4018000000000000) & [f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any(), f64_any(0x0000000000000000));
    check::<A>("emptyObjectBitAndSix", Object::default().to_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("emptyObjectBitAndSixSwapped", f64_any(0x4018000000000000) & Object::default().to_any(), f64_any(0x0000000000000000));
    check::<A>("functionBitAndSix", function_any() & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("functionBitAndSixSwapped", f64_any(0x4018000000000000) & function_any(), f64_any(0x0000000000000000));
    check::<A>("truncatesTowardZero", f64_any(0x400f333333333333) & f64_any(0x4018000000000000), f64_any(0x4000000000000000));
    check::<A>("truncatesTowardZeroSwapped", f64_any(0x4018000000000000) & f64_any(0x400f333333333333), f64_any(0x4000000000000000));
    check::<A>("negativeTruncatesTowardZero", f64_any(0xc00f333333333333) & f64_any(0x4018000000000000), f64_any(0x4010000000000000));
    check::<A>("negativeTruncatesTowardZeroSwapped", f64_any(0x4018000000000000) & f64_any(0xc00f333333333333), f64_any(0x4010000000000000));
    check::<A>("nanBitAndSix", f64_any(0x7ff8000000000000) & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("nanBitAndSixSwapped", f64_any(0x4018000000000000) & f64_any(0x7ff8000000000000), f64_any(0x0000000000000000));
    check::<A>("infinityBitAndSix", f64_any(0x7ff0000000000000) & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("infinityBitAndSixSwapped", f64_any(0x4018000000000000) & f64_any(0x7ff0000000000000), f64_any(0x0000000000000000));
    check::<A>("negativeInfinityBitAndSix", f64_any(0xfff0000000000000) & f64_any(0x4018000000000000), f64_any(0x0000000000000000));
    check::<A>("negativeInfinityBitAndSixSwapped", f64_any(0x4018000000000000) & f64_any(0xfff0000000000000), f64_any(0x0000000000000000));
    check::<A>("wrapsAt32Bits", f64_any(0x41f0000000500000) & f64_any(0x4018000000000000), f64_any(0x4010000000000000));
    check::<A>("wrapsAt32BitsSwapped", f64_any(0x4018000000000000) & f64_any(0x41f0000000500000), f64_any(0x4010000000000000));
    check::<A>("negativeOneBitAndSix", f64_any(0xbff0000000000000) & f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("negativeOneBitAndSixSwapped", f64_any(0x4018000000000000) & f64_any(0xbff0000000000000), f64_any(0x4018000000000000));
    check::<A>("bigTwelveBitAndTen", bigint_any(12) & bigint_any(10), bigint_any(8));
    check::<A>("bigTwelveBitAndTenSwapped", bigint_any(10) & bigint_any(12), bigint_any(8));
    check::<A>("bigNegativeOneBitAndNegativeOne", bigint_any(-1) & bigint_any(-1), bigint_any(-1));
    check::<A>("bigNegativeOneBitAndNegativeOneSwapped", bigint_any(-1) & bigint_any(-1), bigint_any(-1));
    check::<A>("bigNegativeTwoBitAndNegativeThree", bigint_any(-2) & bigint_any(-3), bigint_any(-4));
    check::<A>("bigNegativeTwoBitAndNegativeThreeSwapped", bigint_any(-3) & bigint_any(-2), bigint_any(-4));
    check::<A>("bigFiveBitAndNegativeOne", bigint_any(5) & bigint_any(-1), bigint_any(5));
    check::<A>("bigFiveBitAndNegativeOneSwapped", bigint_any(-1) & bigint_any(5), bigint_any(5));
    check::<A>("bigZeroBitAndZero", bigint_any(0) & bigint_any(0), bigint_any(0));
    check::<A>("bigZeroBitAndZeroSwapped", bigint_any(0) & bigint_any(0), bigint_any(0));
    check::<A>("bigPositiveBitAndZero", bigint_any(12345) & bigint_any(0), bigint_any(0));
    check::<A>("bigPositiveBitAndZeroSwapped", bigint_any(0) & bigint_any(12345), bigint_any(0));
    check::<A>("bigNegativeBitAndZero", bigint_any(-12345) & bigint_any(0), bigint_any(0));
    check::<A>("bigNegativeBitAndZeroSwapped", bigint_any(0) & bigint_any(-12345), bigint_any(0));
    check::<A>("bigLargeMagnitude", bigint_any(-4611686018427387904) & bigint_any(-1), bigint_any(-4611686018427387904));
    check::<A>("bigLargeMagnitudeSwapped", bigint_any(-1) & bigint_any(-4611686018427387904), bigint_any(-4611686018427387904));
    check_throws::<A>("numberBitAndBigint", f64_any(0x3ff0000000000000) & bigint_any(1));
    check_throws::<A>("numberBitAndBigintSwapped", bigint_any(1) & f64_any(0x3ff0000000000000));
}
