// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullBitXorSix", Nullish::Null.to_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("nullBitXorSixSwapped", f64_any(0x4018000000000000) ^ Nullish::Null.to_any(), f64_any(0x4018000000000000));
    check::<A>("undefinedBitXorSix", Nullish::Undefined.to_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("undefinedBitXorSixSwapped", f64_any(0x4018000000000000) ^ Nullish::Undefined.to_any(), f64_any(0x4018000000000000));
    check::<A>("trueBitXorSix", true.to_any() ^ f64_any(0x4018000000000000), f64_any(0x401c000000000000));
    check::<A>("trueBitXorSixSwapped", f64_any(0x4018000000000000) ^ true.to_any(), f64_any(0x401c000000000000));
    check::<A>("falseBitXorSix", false.to_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("falseBitXorSixSwapped", f64_any(0x4018000000000000) ^ false.to_any(), f64_any(0x4018000000000000));
    check::<A>("stringTenBitXorSix", string_any("10") ^ f64_any(0x4018000000000000), f64_any(0x4028000000000000));
    check::<A>("stringTenBitXorSixSwapped", f64_any(0x4018000000000000) ^ string_any("10"), f64_any(0x4028000000000000));
    check::<A>("stringLetterBitXorSix", string_any("a") ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("stringLetterBitXorSixSwapped", f64_any(0x4018000000000000) ^ string_any("a"), f64_any(0x4018000000000000));
    check::<A>("emptyArrayBitXorSix", Array::default().to_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("emptyArrayBitXorSixSwapped", f64_any(0x4018000000000000) ^ Array::default().to_any(), f64_any(0x4018000000000000));
    check::<A>("arrayTenBitXorSix", [f64_any(0x4024000000000000)].to_array().to_any() ^ f64_any(0x4018000000000000), f64_any(0x4028000000000000));
    check::<A>("arrayTenBitXorSixSwapped", f64_any(0x4018000000000000) ^ [f64_any(0x4024000000000000)].to_array().to_any(), f64_any(0x4028000000000000));
    check::<A>("arrayStringTenBitXorSix", [string_any("10")].to_array().to_any() ^ f64_any(0x4018000000000000), f64_any(0x4028000000000000));
    check::<A>("arrayStringTenBitXorSixSwapped", f64_any(0x4018000000000000) ^ [string_any("10")].to_array().to_any(), f64_any(0x4028000000000000));
    check::<A>("arrayPairBitXorSix", [f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("arrayPairBitXorSixSwapped", f64_any(0x4018000000000000) ^ [f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any(), f64_any(0x4018000000000000));
    check::<A>("emptyObjectBitXorSix", Object::default().to_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("emptyObjectBitXorSixSwapped", f64_any(0x4018000000000000) ^ Object::default().to_any(), f64_any(0x4018000000000000));
    check::<A>("functionBitXorSix", function_any() ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("functionBitXorSixSwapped", f64_any(0x4018000000000000) ^ function_any(), f64_any(0x4018000000000000));
    check::<A>("truncatesTowardZero", f64_any(0x400f333333333333) ^ f64_any(0x4018000000000000), f64_any(0x4014000000000000));
    check::<A>("truncatesTowardZeroSwapped", f64_any(0x4018000000000000) ^ f64_any(0x400f333333333333), f64_any(0x4014000000000000));
    check::<A>("negativeTruncatesTowardZero", f64_any(0xc00f333333333333) ^ f64_any(0x4018000000000000), f64_any(0xc014000000000000));
    check::<A>("negativeTruncatesTowardZeroSwapped", f64_any(0x4018000000000000) ^ f64_any(0xc00f333333333333), f64_any(0xc014000000000000));
    check::<A>("nanBitXorSix", f64_any(0x7ff8000000000000) ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("nanBitXorSixSwapped", f64_any(0x4018000000000000) ^ f64_any(0x7ff8000000000000), f64_any(0x4018000000000000));
    check::<A>("infinityBitXorSix", f64_any(0x7ff0000000000000) ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("infinityBitXorSixSwapped", f64_any(0x4018000000000000) ^ f64_any(0x7ff0000000000000), f64_any(0x4018000000000000));
    check::<A>("negativeInfinityBitXorSix", f64_any(0xfff0000000000000) ^ f64_any(0x4018000000000000), f64_any(0x4018000000000000));
    check::<A>("negativeInfinityBitXorSixSwapped", f64_any(0x4018000000000000) ^ f64_any(0xfff0000000000000), f64_any(0x4018000000000000));
    check::<A>("wrapsAt32Bits", f64_any(0x41f0000000500000) ^ f64_any(0x4018000000000000), f64_any(0x4008000000000000));
    check::<A>("wrapsAt32BitsSwapped", f64_any(0x4018000000000000) ^ f64_any(0x41f0000000500000), f64_any(0x4008000000000000));
    check::<A>("negativeOneBitXorSix", f64_any(0xbff0000000000000) ^ f64_any(0x4018000000000000), f64_any(0xc01c000000000000));
    check::<A>("negativeOneBitXorSixSwapped", f64_any(0x4018000000000000) ^ f64_any(0xbff0000000000000), f64_any(0xc01c000000000000));
    check::<A>("bigTwelveBitXorTen", bigint_any(12) ^ bigint_any(10), bigint_any(6));
    check::<A>("bigTwelveBitXorTenSwapped", bigint_any(10) ^ bigint_any(12), bigint_any(6));
    check::<A>("bigNegativeOneBitXorNegativeOne", bigint_any(-1) ^ bigint_any(-1), bigint_any(0));
    check::<A>("bigNegativeOneBitXorNegativeOneSwapped", bigint_any(-1) ^ bigint_any(-1), bigint_any(0));
    check::<A>("bigNegativeTwoBitXorNegativeThree", bigint_any(-2) ^ bigint_any(-3), bigint_any(3));
    check::<A>("bigNegativeTwoBitXorNegativeThreeSwapped", bigint_any(-3) ^ bigint_any(-2), bigint_any(3));
    check::<A>("bigFiveBitXorNegativeOne", bigint_any(5) ^ bigint_any(-1), bigint_any(-6));
    check::<A>("bigFiveBitXorNegativeOneSwapped", bigint_any(-1) ^ bigint_any(5), bigint_any(-6));
    check::<A>("bigZeroBitXorZero", bigint_any(0) ^ bigint_any(0), bigint_any(0));
    check::<A>("bigZeroBitXorZeroSwapped", bigint_any(0) ^ bigint_any(0), bigint_any(0));
    check::<A>("bigPositiveBitXorZero", bigint_any(12345) ^ bigint_any(0), bigint_any(12345));
    check::<A>("bigPositiveBitXorZeroSwapped", bigint_any(0) ^ bigint_any(12345), bigint_any(12345));
    check::<A>("bigNegativeBitXorZero", bigint_any(-12345) ^ bigint_any(0), bigint_any(-12345));
    check::<A>("bigNegativeBitXorZeroSwapped", bigint_any(0) ^ bigint_any(-12345), bigint_any(-12345));
    check::<A>("bigLargeMagnitude", bigint_any(-4611686018427387904) ^ bigint_any(-1), bigint_any(4611686018427387903));
    check::<A>("bigLargeMagnitudeSwapped", bigint_any(-1) ^ bigint_any(-4611686018427387904), bigint_any(4611686018427387903));
    check_throws::<A>("numberBitXorBigint", f64_any(0x3ff0000000000000) ^ bigint_any(1));
    check_throws::<A>("numberBitXorBigintSwapped", bigint_any(1) ^ f64_any(0x3ff0000000000000));
}
