// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullDividedByFour", Nullish::Null.to_any() / f64_any(0x4010000000000000), f64_any(0x0000000000000000));
    check::<A>("undefinedDividedByFour", Nullish::Undefined.to_any() / f64_any(0x4010000000000000), f64_any(0x7ff8000000000000));
    check::<A>("trueDividedByFour", true.to_any() / f64_any(0x4010000000000000), f64_any(0x3fd0000000000000));
    check::<A>("falseDividedByFour", false.to_any() / f64_any(0x4010000000000000), f64_any(0x0000000000000000));
    check::<A>("stringTenDividedByFour", string_any("10") / f64_any(0x4010000000000000), f64_any(0x4004000000000000));
    check::<A>("stringLetterDividedByFour", string_any("a") / f64_any(0x4010000000000000), f64_any(0x7ff8000000000000));
    check::<A>("emptyArrayDividedByFour", Array::default().to_any() / f64_any(0x4010000000000000), f64_any(0x0000000000000000));
    check::<A>("arrayTenDividedByFour", [f64_any(0x4024000000000000)].to_array().to_any() / f64_any(0x4010000000000000), f64_any(0x4004000000000000));
    check::<A>("arrayStringTenDividedByFour", [string_any("10")].to_array().to_any() / f64_any(0x4010000000000000), f64_any(0x4004000000000000));
    check::<A>("arrayPairDividedByFour", [f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any() / f64_any(0x4010000000000000), f64_any(0x7ff8000000000000));
    check::<A>("emptyObjectDividedByFour", Object::default().to_any() / f64_any(0x4010000000000000), f64_any(0x7ff8000000000000));
    check::<A>("functionDividedByFour", function_any() / f64_any(0x4010000000000000), f64_any(0x7ff8000000000000));
    check::<A>("zeroDividedByOne", f64_any(0x0000000000000000) / f64_any(0x3ff0000000000000), f64_any(0x0000000000000000));
    check::<A>("negativeZeroDividedByOne", f64_any(0x8000000000000000) / f64_any(0x3ff0000000000000), f64_any(0x8000000000000000));
    check::<A>("tenDividedByFour", f64_any(0x4024000000000000) / f64_any(0x4010000000000000), f64_any(0x4004000000000000));
    check::<A>("negativeTenDividedByFour", f64_any(0xc024000000000000) / f64_any(0x4010000000000000), f64_any(0xc004000000000000));
    check::<A>("tenDividedByNegativeFour", f64_any(0x4024000000000000) / f64_any(0xc010000000000000), f64_any(0xc004000000000000));
    check::<A>("negativeTenDividedByNegativeFour", f64_any(0xc024000000000000) / f64_any(0xc010000000000000), f64_any(0x4004000000000000));
    check::<A>("fiveDividedByZero", f64_any(0x4014000000000000) / f64_any(0x0000000000000000), f64_any(0x7ff0000000000000));
    check::<A>("negativeFiveDividedByZero", f64_any(0xc014000000000000) / f64_any(0x0000000000000000), f64_any(0xfff0000000000000));
    check::<A>("fiveDividedByNegativeZero", f64_any(0x4014000000000000) / f64_any(0x8000000000000000), f64_any(0xfff0000000000000));
    check::<A>("negativeFiveDividedByNegativeZero", f64_any(0xc014000000000000) / f64_any(0x8000000000000000), f64_any(0x7ff0000000000000));
    check::<A>("zeroDividedByZero", f64_any(0x0000000000000000) / f64_any(0x0000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("negativeZeroDividedByZero", f64_any(0x8000000000000000) / f64_any(0x0000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("zeroDividedByNegativeZero", f64_any(0x0000000000000000) / f64_any(0x8000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("negativeZeroDividedByNegativeZero", f64_any(0x8000000000000000) / f64_any(0x8000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("infinityDividedByFive", f64_any(0x7ff0000000000000) / f64_any(0x4014000000000000), f64_any(0x7ff0000000000000));
    check::<A>("infinityDividedByNegativeFive", f64_any(0x7ff0000000000000) / f64_any(0xc014000000000000), f64_any(0xfff0000000000000));
    check::<A>("negativeInfinityDividedByFive", f64_any(0xfff0000000000000) / f64_any(0x4014000000000000), f64_any(0xfff0000000000000));
    check::<A>("fiveDividedByInfinity", f64_any(0x4014000000000000) / f64_any(0x7ff0000000000000), f64_any(0x0000000000000000));
    check::<A>("negativeFiveDividedByInfinity", f64_any(0xc014000000000000) / f64_any(0x7ff0000000000000), f64_any(0x8000000000000000));
    check::<A>("fiveDividedByNegativeInfinity", f64_any(0x4014000000000000) / f64_any(0xfff0000000000000), f64_any(0x8000000000000000));
    check::<A>("infinityDividedByInfinity", f64_any(0x7ff0000000000000) / f64_any(0x7ff0000000000000), f64_any(0x7ff8000000000000));
    check::<A>("infinityDividedByNegativeInfinity", f64_any(0x7ff0000000000000) / f64_any(0xfff0000000000000), f64_any(0x7ff8000000000000));
    check::<A>("nanDividedByOne", f64_any(0x7ff8000000000000) / f64_any(0x3ff0000000000000), f64_any(0x7ff8000000000000));
    check::<A>("oneDividedByNan", f64_any(0x3ff0000000000000) / f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000));
    check::<A>("sevenDividedByTwo", f64_any(0x401c000000000000) / f64_any(0x4000000000000000), f64_any(0x400c000000000000));
    check::<A>("oneDividedByThree", f64_any(0x3ff0000000000000) / f64_any(0x4008000000000000), f64_any(0x3fd5555555555555));
    check::<A>("bigTenDividedByThree", bigint_any(10) / bigint_any(3), bigint_any(3));
    check::<A>("bigNegativeTenDividedByThree", bigint_any(-10) / bigint_any(3), bigint_any(-3));
    check::<A>("bigTenDividedByNegativeThree", bigint_any(10) / bigint_any(-3), bigint_any(-3));
    check::<A>("bigNegativeTenDividedByNegativeThree", bigint_any(-10) / bigint_any(-3), bigint_any(3));
    check::<A>("bigSevenDividedByTwo", bigint_any(7) / bigint_any(2), bigint_any(3));
    check::<A>("bigNegativeSevenDividedByTwo", bigint_any(-7) / bigint_any(2), bigint_any(-3));
    check::<A>("bigZeroDividedByFive", bigint_any(0) / bigint_any(5), bigint_any(0));
    check_throws::<A>("bigTenDividedByZero", bigint_any(10) / bigint_any(0));
    check_throws::<A>("numberDividedByBigint", f64_any(0x3ff0000000000000) / bigint_any(1));
    check_throws::<A>("bigintDividedByNumber", bigint_any(1) / f64_any(0x3ff0000000000000));
}
