// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    let empty_array: Any<A> = Array::default().to_any();
    let string_array: Any<A> = [string_any("0")].to_array().to_any();
    let object: Any<A> = [(string_key("0"), string_any("0"))].to_object().to_any();
    check::<A>("nullByNull", strict_eq(Nullish::Null.to_any(), Nullish::Null.to_any()), true.to_any());
    check::<A>("nullByNullSwapped", strict_eq(Nullish::Null.to_any(), Nullish::Null.to_any()), true.to_any());
    check::<A>("undefinedByUndefined", strict_eq(Nullish::Undefined.to_any(), Nullish::Undefined.to_any()), true.to_any());
    check::<A>("undefinedByUndefinedSwapped", strict_eq(Nullish::Undefined.to_any(), Nullish::Undefined.to_any()), true.to_any());
    check::<A>("nullByUndefined", strict_eq(Nullish::Null.to_any(), Nullish::Undefined.to_any()), false.to_any());
    check::<A>("nullByUndefinedSwapped", strict_eq(Nullish::Undefined.to_any(), Nullish::Null.to_any()), false.to_any());
    check::<A>("trueByTrue", strict_eq(true.to_any(), true.to_any()), true.to_any());
    check::<A>("trueByTrueSwapped", strict_eq(true.to_any(), true.to_any()), true.to_any());
    check::<A>("falseByFalse", strict_eq(false.to_any(), false.to_any()), true.to_any());
    check::<A>("falseByFalseSwapped", strict_eq(false.to_any(), false.to_any()), true.to_any());
    check::<A>("trueByFalse", strict_eq(true.to_any(), false.to_any()), false.to_any());
    check::<A>("trueByFalseSwapped", strict_eq(false.to_any(), true.to_any()), false.to_any());
    check::<A>("falseByUndefined", strict_eq(false.to_any(), Nullish::Undefined.to_any()), false.to_any());
    check::<A>("falseByUndefinedSwapped", strict_eq(Nullish::Undefined.to_any(), false.to_any()), false.to_any());
    check::<A>("falseByNull", strict_eq(false.to_any(), Nullish::Null.to_any()), false.to_any());
    check::<A>("falseByNullSwapped", strict_eq(Nullish::Null.to_any(), false.to_any()), false.to_any());
    check::<A>("numberBySameNumber", strict_eq(f64_any(0x4002666666666666), f64_any(0x4002666666666666)), true.to_any());
    check::<A>("numberBySameNumberSwapped", strict_eq(f64_any(0x4002666666666666), f64_any(0x4002666666666666)), true.to_any());
    check::<A>("numberByOtherNumber", strict_eq(f64_any(0x4002666666666666), f64_any(0xc01599999999999a)), false.to_any());
    check::<A>("numberByOtherNumberSwapped", strict_eq(f64_any(0xc01599999999999a), f64_any(0x4002666666666666)), false.to_any());
    check::<A>("nanByNan", strict_eq(f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanByNanSwapped", strict_eq(f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("zeroByNegativeZero", strict_eq(f64_any(0x0000000000000000), f64_any(0x8000000000000000)), true.to_any());
    check::<A>("zeroByNegativeZeroSwapped", strict_eq(f64_any(0x8000000000000000), f64_any(0x0000000000000000)), true.to_any());
    check::<A>("infinityByInfinity", strict_eq(f64_any(0x7ff0000000000000), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("infinityByInfinitySwapped", strict_eq(f64_any(0x7ff0000000000000), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("negativeInfinityByNegativeInfinity", strict_eq(f64_any(0xfff0000000000000), f64_any(0xfff0000000000000)), true.to_any());
    check::<A>("negativeInfinityByNegativeInfinitySwapped", strict_eq(f64_any(0xfff0000000000000), f64_any(0xfff0000000000000)), true.to_any());
    check::<A>("infinityByNegativeInfinity", strict_eq(f64_any(0x7ff0000000000000), f64_any(0xfff0000000000000)), false.to_any());
    check::<A>("infinityByNegativeInfinitySwapped", strict_eq(f64_any(0xfff0000000000000), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("undefinedByNan", strict_eq(Nullish::Undefined.to_any(), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("undefinedByNanSwapped", strict_eq(f64_any(0x7ff8000000000000), Nullish::Undefined.to_any()), false.to_any());
    check::<A>("undefinedByZero", strict_eq(Nullish::Undefined.to_any(), f64_any(0x0000000000000000)), false.to_any());
    check::<A>("undefinedByZeroSwapped", strict_eq(f64_any(0x0000000000000000), Nullish::Undefined.to_any()), false.to_any());
    check::<A>("stringBySameString", strict_eq(string_any("hello"), string_any("hello")), true.to_any());
    check::<A>("stringBySameStringSwapped", strict_eq(string_any("hello"), string_any("hello")), true.to_any());
    check::<A>("stringByOtherString", strict_eq(string_any("hello"), string_any("world")), false.to_any());
    check::<A>("stringByOtherStringSwapped", strict_eq(string_any("world"), string_any("hello")), false.to_any());
    check::<A>("zeroByStringZero", strict_eq(f64_any(0x0000000000000000), string_any("0")), false.to_any());
    check::<A>("zeroByStringZeroSwapped", strict_eq(string_any("0"), f64_any(0x0000000000000000)), false.to_any());
    check::<A>("bigintBySameBigint", strict_eq(bigint_any(12), bigint_any(12)), true.to_any());
    check::<A>("bigintBySameBigintSwapped", strict_eq(bigint_any(12), bigint_any(12)), true.to_any());
    check::<A>("bigintByNegatedBigint", strict_eq(bigint_any(12), bigint_any(-12)), false.to_any());
    check::<A>("bigintByNegatedBigintSwapped", strict_eq(bigint_any(-12), bigint_any(12)), false.to_any());
    check::<A>("bigintByOtherBigint", strict_eq(bigint_any(12), bigint_any(13)), false.to_any());
    check::<A>("bigintByOtherBigintSwapped", strict_eq(bigint_any(13), bigint_any(12)), false.to_any());
    check::<A>("twelveByStringTwelve", strict_eq(bigint_any(12), string_any("12")), false.to_any());
    check::<A>("twelveByStringTwelveSwapped", strict_eq(string_any("12"), bigint_any(12)), false.to_any());
    check::<A>("arrayByItself", strict_eq(empty_array.clone(), empty_array.clone()), true.to_any());
    check::<A>("arrayByItselfSwapped", strict_eq(empty_array.clone(), empty_array.clone()), true.to_any());
    check::<A>("arrayByEqualArray", strict_eq(Array::default().to_any(), Array::default().to_any()), false.to_any());
    check::<A>("arrayByEqualArraySwapped", strict_eq(Array::default().to_any(), Array::default().to_any()), false.to_any());
    check::<A>("stringArrayByItself", strict_eq(string_array.clone(), string_array.clone()), true.to_any());
    check::<A>("stringArrayByItselfSwapped", strict_eq(string_array.clone(), string_array.clone()), true.to_any());
    check::<A>("objectByItself", strict_eq(object.clone(), object.clone()), true.to_any());
    check::<A>("objectByItselfSwapped", strict_eq(object.clone(), object.clone()), true.to_any());
    check::<A>("objectByEqualObject", strict_eq(object.clone(), [(string_key("0"), string_any("0"))].to_object().to_any()), false.to_any());
    check::<A>("objectByEqualObjectSwapped", strict_eq([(string_key("0"), string_any("0"))].to_object().to_any(), object.clone()), false.to_any());
}
