// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullGreaterOrEqualFive", Any::ge(Nullish::Null.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("undefinedGreaterOrEqualFive", Any::ge(Nullish::Undefined.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("trueGreaterOrEqualFive", Any::ge(true.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("falseGreaterOrEqualFive", Any::ge(false.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("stringThreeGreaterOrEqualFive", Any::ge(string_any("3"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("stringLetterGreaterOrEqualFive", Any::ge(string_any("a"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("emptyArrayGreaterOrEqualFive", Any::ge(Array::default().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("arrayThreeGreaterOrEqualFive", Any::ge([f64_any(0x4008000000000000)].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("arrayStringThreeGreaterOrEqualFive", Any::ge([string_any("3")].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("arrayPairGreaterOrEqualFive", Any::ge([f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("emptyObjectGreaterOrEqualFive", Any::ge(Object::default().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("functionGreaterOrEqualFive", Any::ge(function_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("threeGreaterOrEqualFive", Any::ge(f64_any(0x4008000000000000), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("fiveGreaterOrEqualThree", Any::ge(f64_any(0x4014000000000000), f64_any(0x4008000000000000)), true.to_any());
    check::<A>("fiveGreaterOrEqualFive", Any::ge(f64_any(0x4014000000000000), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("zeroGreaterOrEqualNegativeZero", Any::ge(f64_any(0x0000000000000000), f64_any(0x8000000000000000)), true.to_any());
    check::<A>("negativeZeroGreaterOrEqualZero", Any::ge(f64_any(0x8000000000000000), f64_any(0x0000000000000000)), true.to_any());
    check::<A>("nanGreaterOrEqualOne", Any::ge(f64_any(0x7ff8000000000000), f64_any(0x3ff0000000000000)), false.to_any());
    check::<A>("oneGreaterOrEqualNan", Any::ge(f64_any(0x3ff0000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanGreaterOrEqualNan", Any::ge(f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("infinityGreaterOrEqualOne", Any::ge(f64_any(0x7ff0000000000000), f64_any(0x3ff0000000000000)), true.to_any());
    check::<A>("oneGreaterOrEqualInfinity", Any::ge(f64_any(0x3ff0000000000000), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("negativeInfinityGreaterOrEqualInfinity", Any::ge(f64_any(0xfff0000000000000), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("infinityGreaterOrEqualInfinity", Any::ge(f64_any(0x7ff0000000000000), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("stringTenGreaterOrEqualStringNine", Any::ge(string_any("10"), string_any("9")), false.to_any());
    check::<A>("stringNineGreaterOrEqualStringTen", Any::ge(string_any("9"), string_any("10")), true.to_any());
    check::<A>("stringAGreaterOrEqualStringB", Any::ge(string_any("a"), string_any("b")), false.to_any());
    check::<A>("emptyStringGreaterOrEqualStringA", Any::ge(string_any(""), string_any("a")), false.to_any());
    check::<A>("stringAbGreaterOrEqualStringAbc", Any::ge(string_any("ab"), string_any("abc")), false.to_any());
    check::<A>("stringAbcGreaterOrEqualStringAb", Any::ge(string_any("abc"), string_any("ab")), true.to_any());
    check::<A>("stringUppercaseBGreaterOrEqualStringA", Any::ge(string_any("B"), string_any("a")), false.to_any());
    check::<A>("stringTenGreaterOrEqualNine", Any::ge(string_any("10"), f64_any(0x4022000000000000)), true.to_any());
    check::<A>("nineGreaterOrEqualStringTen", Any::ge(f64_any(0x4022000000000000), string_any("10")), false.to_any());
    check::<A>("stringAbcGreaterOrEqualFive", Any::ge(string_any("abc"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("fiveGreaterOrEqualStringAbc", Any::ge(f64_any(0x4014000000000000), string_any("abc")), false.to_any());
    check::<A>("negativeFiveBigGreaterOrEqualThreeBig", Any::ge(bigint_any(-5), bigint_any(3)), false.to_any());
    check::<A>("threeBigGreaterOrEqualThreeBig", Any::ge(bigint_any(3), bigint_any(3)), true.to_any());
    check::<A>("threeBigGreaterOrEqualNegativeFiveBig", Any::ge(bigint_any(3), bigint_any(-5)), true.to_any());
    check::<A>("fiveBigGreaterOrEqualFiveHalf", Any::ge(bigint_any(5), f64_any(0x4016000000000000)), false.to_any());
    check::<A>("fiveBigGreaterOrEqualFive", Any::ge(bigint_any(5), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("fiveGreaterOrEqualFiveBig", Any::ge(f64_any(0x4014000000000000), bigint_any(5)), true.to_any());
    check::<A>("fiveBigGreaterOrEqualNan", Any::ge(bigint_any(5), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanGreaterOrEqualFiveBig", Any::ge(f64_any(0x7ff8000000000000), bigint_any(5)), false.to_any());
    check::<A>("fiveBigGreaterOrEqualInfinity", Any::ge(bigint_any(5), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("negativeInfinityGreaterOrEqualFiveBig", Any::ge(f64_any(0xfff0000000000000), bigint_any(5)), false.to_any());
    check::<A>("infinityGreaterOrEqualFiveBig", Any::ge(f64_any(0x7ff0000000000000), bigint_any(5)), true.to_any());
    check::<A>("stringTenGreaterOrEqualTwentyBig", Any::ge(string_any("10"), bigint_any(20)), false.to_any());
    check::<A>("twentyBigGreaterOrEqualStringThirty", Any::ge(bigint_any(20), string_any("30")), false.to_any());
    check::<A>("stringAbcGreaterOrEqualTwentyBig", Any::ge(string_any("abc"), bigint_any(20)), false.to_any());
    check::<A>("twentyBigGreaterOrEqualStringAbc", Any::ge(bigint_any(20), string_any("abc")), false.to_any());
}
