// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullGreaterThanFive", Any::gt(Nullish::Null.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("undefinedGreaterThanFive", Any::gt(Nullish::Undefined.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("trueGreaterThanFive", Any::gt(true.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("falseGreaterThanFive", Any::gt(false.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("stringThreeGreaterThanFive", Any::gt(string_any("3"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("stringLetterGreaterThanFive", Any::gt(string_any("a"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("emptyArrayGreaterThanFive", Any::gt(Array::default().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("arrayThreeGreaterThanFive", Any::gt([f64_any(0x4008000000000000)].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("arrayStringThreeGreaterThanFive", Any::gt([string_any("3")].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("arrayPairGreaterThanFive", Any::gt([f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("emptyObjectGreaterThanFive", Any::gt(Object::default().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("functionGreaterThanFive", Any::gt(function_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("threeGreaterThanFive", Any::gt(f64_any(0x4008000000000000), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("fiveGreaterThanThree", Any::gt(f64_any(0x4014000000000000), f64_any(0x4008000000000000)), true.to_any());
    check::<A>("fiveGreaterThanFive", Any::gt(f64_any(0x4014000000000000), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("zeroGreaterThanNegativeZero", Any::gt(f64_any(0x0000000000000000), f64_any(0x8000000000000000)), false.to_any());
    check::<A>("negativeZeroGreaterThanZero", Any::gt(f64_any(0x8000000000000000), f64_any(0x0000000000000000)), false.to_any());
    check::<A>("nanGreaterThanOne", Any::gt(f64_any(0x7ff8000000000000), f64_any(0x3ff0000000000000)), false.to_any());
    check::<A>("oneGreaterThanNan", Any::gt(f64_any(0x3ff0000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanGreaterThanNan", Any::gt(f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("infinityGreaterThanOne", Any::gt(f64_any(0x7ff0000000000000), f64_any(0x3ff0000000000000)), true.to_any());
    check::<A>("oneGreaterThanInfinity", Any::gt(f64_any(0x3ff0000000000000), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("negativeInfinityGreaterThanInfinity", Any::gt(f64_any(0xfff0000000000000), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("infinityGreaterThanInfinity", Any::gt(f64_any(0x7ff0000000000000), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("stringTenGreaterThanStringNine", Any::gt(string_any("10"), string_any("9")), false.to_any());
    check::<A>("stringNineGreaterThanStringTen", Any::gt(string_any("9"), string_any("10")), true.to_any());
    check::<A>("stringAGreaterThanStringB", Any::gt(string_any("a"), string_any("b")), false.to_any());
    check::<A>("emptyStringGreaterThanStringA", Any::gt(string_any(""), string_any("a")), false.to_any());
    check::<A>("stringAbGreaterThanStringAbc", Any::gt(string_any("ab"), string_any("abc")), false.to_any());
    check::<A>("stringAbcGreaterThanStringAb", Any::gt(string_any("abc"), string_any("ab")), true.to_any());
    check::<A>("stringUppercaseBGreaterThanStringA", Any::gt(string_any("B"), string_any("a")), false.to_any());
    check::<A>("stringTenGreaterThanNine", Any::gt(string_any("10"), f64_any(0x4022000000000000)), true.to_any());
    check::<A>("nineGreaterThanStringTen", Any::gt(f64_any(0x4022000000000000), string_any("10")), false.to_any());
    check::<A>("stringAbcGreaterThanFive", Any::gt(string_any("abc"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("fiveGreaterThanStringAbc", Any::gt(f64_any(0x4014000000000000), string_any("abc")), false.to_any());
    check::<A>("negativeFiveBigGreaterThanThreeBig", Any::gt(bigint_any(-5), bigint_any(3)), false.to_any());
    check::<A>("threeBigGreaterThanThreeBig", Any::gt(bigint_any(3), bigint_any(3)), false.to_any());
    check::<A>("threeBigGreaterThanNegativeFiveBig", Any::gt(bigint_any(3), bigint_any(-5)), true.to_any());
    check::<A>("fiveBigGreaterThanFiveHalf", Any::gt(bigint_any(5), f64_any(0x4016000000000000)), false.to_any());
    check::<A>("fiveBigGreaterThanFive", Any::gt(bigint_any(5), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("fiveGreaterThanFiveBig", Any::gt(f64_any(0x4014000000000000), bigint_any(5)), false.to_any());
    check::<A>("fiveBigGreaterThanNan", Any::gt(bigint_any(5), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanGreaterThanFiveBig", Any::gt(f64_any(0x7ff8000000000000), bigint_any(5)), false.to_any());
    check::<A>("fiveBigGreaterThanInfinity", Any::gt(bigint_any(5), f64_any(0x7ff0000000000000)), false.to_any());
    check::<A>("negativeInfinityGreaterThanFiveBig", Any::gt(f64_any(0xfff0000000000000), bigint_any(5)), false.to_any());
    check::<A>("infinityGreaterThanFiveBig", Any::gt(f64_any(0x7ff0000000000000), bigint_any(5)), true.to_any());
    check::<A>("stringTenGreaterThanTwentyBig", Any::gt(string_any("10"), bigint_any(20)), false.to_any());
    check::<A>("twentyBigGreaterThanStringThirty", Any::gt(bigint_any(20), string_any("30")), false.to_any());
    check::<A>("stringAbcGreaterThanTwentyBig", Any::gt(string_any("abc"), bigint_any(20)), false.to_any());
    check::<A>("twentyBigGreaterThanStringAbc", Any::gt(bigint_any(20), string_any("abc")), false.to_any());
}
