// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("emptyArray", Any::instanceof_(Array::default().to_any(), Constructor::Array), true.to_any());
    check::<A>("array", Any::instanceof_([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), Constructor::Array), true.to_any());
    check::<A>("nestedArray", Any::instanceof_([Array::default().to_any()].to_array().to_any(), Constructor::Array), true.to_any());
    check::<A>("undefined", Any::instanceof_(Nullish::Undefined.to_any(), Constructor::Array), false.to_any());
    check::<A>("null", Any::instanceof_(Nullish::Null.to_any(), Constructor::Array), false.to_any());
    check::<A>("booleanTrue", Any::instanceof_(true.to_any(), Constructor::Array), false.to_any());
    check::<A>("number", Any::instanceof_(f64_any(0x4002666666666666), Constructor::Array), false.to_any());
    check::<A>("string", Any::instanceof_(string_any("a"), Constructor::Array), false.to_any());
    check::<A>("bigint", Any::instanceof_(bigint_any(5), Constructor::Array), false.to_any());
    check::<A>("emptyObject", Any::instanceof_(Object::default().to_any(), Constructor::Array), false.to_any());
    check::<A>("object", Any::instanceof_([(string_key("a"), f64_any(0x3ff0000000000000))].to_object().to_any(), Constructor::Array), false.to_any());
    check::<A>("arrayLikeObject", Any::instanceof_([(string_key("length"), f64_any(0x0000000000000000))].to_object().to_any(), Constructor::Array), false.to_any());
    check::<A>("function", Any::instanceof_(function_any(), Constructor::Array), false.to_any());
}
