// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullLessOrEqualFive", Any::le(Nullish::Null.to_any(), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("undefinedLessOrEqualFive", Any::le(Nullish::Undefined.to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("trueLessOrEqualFive", Any::le(true.to_any(), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("falseLessOrEqualFive", Any::le(false.to_any(), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("stringThreeLessOrEqualFive", Any::le(string_any("3"), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("stringLetterLessOrEqualFive", Any::le(string_any("a"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("emptyArrayLessOrEqualFive", Any::le(Array::default().to_any(), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("arrayThreeLessOrEqualFive", Any::le([f64_any(0x4008000000000000)].to_array().to_any(), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("arrayStringThreeLessOrEqualFive", Any::le([string_any("3")].to_array().to_any(), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("arrayPairLessOrEqualFive", Any::le([f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("emptyObjectLessOrEqualFive", Any::le(Object::default().to_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("functionLessOrEqualFive", Any::le(function_any(), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("threeLessOrEqualFive", Any::le(f64_any(0x4008000000000000), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("fiveLessOrEqualThree", Any::le(f64_any(0x4014000000000000), f64_any(0x4008000000000000)), false.to_any());
    check::<A>("fiveLessOrEqualFive", Any::le(f64_any(0x4014000000000000), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("zeroLessOrEqualNegativeZero", Any::le(f64_any(0x0000000000000000), f64_any(0x8000000000000000)), true.to_any());
    check::<A>("negativeZeroLessOrEqualZero", Any::le(f64_any(0x8000000000000000), f64_any(0x0000000000000000)), true.to_any());
    check::<A>("nanLessOrEqualOne", Any::le(f64_any(0x7ff8000000000000), f64_any(0x3ff0000000000000)), false.to_any());
    check::<A>("oneLessOrEqualNan", Any::le(f64_any(0x3ff0000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanLessOrEqualNan", Any::le(f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("infinityLessOrEqualOne", Any::le(f64_any(0x7ff0000000000000), f64_any(0x3ff0000000000000)), false.to_any());
    check::<A>("oneLessOrEqualInfinity", Any::le(f64_any(0x3ff0000000000000), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("negativeInfinityLessOrEqualInfinity", Any::le(f64_any(0xfff0000000000000), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("infinityLessOrEqualInfinity", Any::le(f64_any(0x7ff0000000000000), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("stringTenLessOrEqualStringNine", Any::le(string_any("10"), string_any("9")), true.to_any());
    check::<A>("stringNineLessOrEqualStringTen", Any::le(string_any("9"), string_any("10")), false.to_any());
    check::<A>("stringALessOrEqualStringB", Any::le(string_any("a"), string_any("b")), true.to_any());
    check::<A>("emptyStringLessOrEqualStringA", Any::le(string_any(""), string_any("a")), true.to_any());
    check::<A>("stringAbLessOrEqualStringAbc", Any::le(string_any("ab"), string_any("abc")), true.to_any());
    check::<A>("stringAbcLessOrEqualStringAb", Any::le(string_any("abc"), string_any("ab")), false.to_any());
    check::<A>("stringUppercaseBLessOrEqualStringA", Any::le(string_any("B"), string_any("a")), true.to_any());
    check::<A>("stringTenLessOrEqualNine", Any::le(string_any("10"), f64_any(0x4022000000000000)), false.to_any());
    check::<A>("nineLessOrEqualStringTen", Any::le(f64_any(0x4022000000000000), string_any("10")), true.to_any());
    check::<A>("stringAbcLessOrEqualFive", Any::le(string_any("abc"), f64_any(0x4014000000000000)), false.to_any());
    check::<A>("fiveLessOrEqualStringAbc", Any::le(f64_any(0x4014000000000000), string_any("abc")), false.to_any());
    check::<A>("negativeFiveBigLessOrEqualThreeBig", Any::le(bigint_any(-5), bigint_any(3)), true.to_any());
    check::<A>("threeBigLessOrEqualThreeBig", Any::le(bigint_any(3), bigint_any(3)), true.to_any());
    check::<A>("threeBigLessOrEqualNegativeFiveBig", Any::le(bigint_any(3), bigint_any(-5)), false.to_any());
    check::<A>("fiveBigLessOrEqualFiveHalf", Any::le(bigint_any(5), f64_any(0x4016000000000000)), true.to_any());
    check::<A>("fiveBigLessOrEqualFive", Any::le(bigint_any(5), f64_any(0x4014000000000000)), true.to_any());
    check::<A>("fiveLessOrEqualFiveBig", Any::le(f64_any(0x4014000000000000), bigint_any(5)), true.to_any());
    check::<A>("fiveBigLessOrEqualNan", Any::le(bigint_any(5), f64_any(0x7ff8000000000000)), false.to_any());
    check::<A>("nanLessOrEqualFiveBig", Any::le(f64_any(0x7ff8000000000000), bigint_any(5)), false.to_any());
    check::<A>("fiveBigLessOrEqualInfinity", Any::le(bigint_any(5), f64_any(0x7ff0000000000000)), true.to_any());
    check::<A>("negativeInfinityLessOrEqualFiveBig", Any::le(f64_any(0xfff0000000000000), bigint_any(5)), true.to_any());
    check::<A>("infinityLessOrEqualFiveBig", Any::le(f64_any(0x7ff0000000000000), bigint_any(5)), false.to_any());
    check::<A>("stringTenLessOrEqualTwentyBig", Any::le(string_any("10"), bigint_any(20)), true.to_any());
    check::<A>("twentyBigLessOrEqualStringThirty", Any::le(bigint_any(20), string_any("30")), true.to_any());
    check::<A>("stringAbcLessOrEqualTwentyBig", Any::le(string_any("abc"), bigint_any(20)), false.to_any());
    check::<A>("twentyBigLessOrEqualStringAbc", Any::le(bigint_any(20), string_any("abc")), false.to_any());
}
