// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("suffix", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("bc")].to_array().to_any())), true.to_any());
    check::<A>("notSuffix", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("ab")].to_array().to_any())), false.to_any());
    check::<A>("at", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("ab"), f64_any(0x4000000000000000)].to_array().to_any())), true.to_any());
    check::<A>("undefinedEnd", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("c"), Nullish::Undefined.to_any()].to_array().to_any())), true.to_any());
    check::<A>("empty", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("")].to_array().to_any())), true.to_any());
    check::<A>("longer", Any::dot(string_any("bc"), string_any("endsWith")).end_call(|| Ok([string_any("abc")].to_array().to_any())), false.to_any());
    check::<A>("pastTheEnd", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("c"), f64_any(0x4022000000000000)].to_array().to_any())), true.to_any());
    check::<A>("negative", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any(""), f64_any(0xbff0000000000000)].to_array().to_any())), true.to_any());
    check::<A>("zero", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("a"), f64_any(0x0000000000000000)].to_array().to_any())), false.to_any());
    check_throws::<A>("bigintEnd", Any::dot(string_any("abc"), string_any("endsWith")).end_call(|| Ok([string_any("a"), bigint_any(1)].to_array().to_any())));
}
