// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("first", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), f64_any(0x0000000000000000));
    check::<A>("notFound", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x4010000000000000)].to_array().to_any())), f64_any(0xbff0000000000000));
    check::<A>("nan", Any::dot([f64_any(0x7ff8000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x7ff8000000000000)].to_array().to_any())), f64_any(0xbff0000000000000));
    check::<A>("negativeZero", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x0000000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x8000000000000000)].to_array().to_any())), f64_any(0x3ff0000000000000));
    check::<A>("noCoercion", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([string_any("1")].to_array().to_any())), f64_any(0xbff0000000000000));
    check::<A>("noArgument", Any::dot([f64_any(0x3ff0000000000000), Nullish::Undefined.to_any()].to_array().to_any(), string_any("indexOf")).end_call(|| Ok(Array::default().to_any())), f64_any(0x3ff0000000000000));
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("indexOf")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), f64_any(0xbff0000000000000));
    check::<A>("from", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0x3ff0000000000000)].to_array().to_any())), f64_any(0x4000000000000000));
    check::<A>("fromTheEnd", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0xbff0000000000000)].to_array().to_any())), f64_any(0x4000000000000000));
    check::<A>("fromBeforeTheStart", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0xc022000000000000)].to_array().to_any())), f64_any(0x0000000000000000));
    check::<A>("fromPastTheEnd", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0x4008000000000000)].to_array().to_any())), f64_any(0xbff0000000000000));
    check::<A>("fromNegativeInfinity", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0xfff0000000000000)].to_array().to_any())), f64_any(0x0000000000000000));
    check::<A>("emptyBigintFrom", Any::dot(Array::default().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), bigint_any(1)].to_array().to_any())), f64_any(0xbff0000000000000));
    check_throws::<A>("bigintFrom", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000), bigint_any(1)].to_array().to_any())));
    check_throws::<A>("object", Any::dot(Object::default().to_any(), string_any("indexOf")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())));
}
