// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("first", Any::dot(string_any("abc"), string_any("charCodeAt")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), f64_any(0x4058400000000000));
    check::<A>("noArgument", Any::dot(string_any("abc"), string_any("charCodeAt")).end_call(|| Ok(Array::default().to_any())), f64_any(0x4058400000000000));
    check::<A>("negative", Any::dot(string_any("abc"), string_any("charCodeAt")).end_call(|| Ok([f64_any(0xbff0000000000000)].to_array().to_any())), f64_any(0x7ff8000000000000));
    check::<A>("pastTheEnd", Any::dot(string_any("abc"), string_any("charCodeAt")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), f64_any(0x7ff8000000000000));
    check::<A>("highSurrogate", Any::dot(string_any("😀"), string_any("charCodeAt")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), f64_any(0x40eb07a000000000));
    check::<A>("lowSurrogate", Any::dot(string_any("😀"), string_any("charCodeAt")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), f64_any(0x40ebc00000000000));
    check_throws::<A>("bigint", Any::dot(string_any("abc"), string_any("charCodeAt")).end_call(|| Ok([bigint_any(0)].to_array().to_any())));
}
