// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("first", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0x0000000000000000), f64_any(0x4022000000000000)].to_array().to_any())), [f64_any(0x4022000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any());
    check::<A>("fromTheEnd", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0xbff0000000000000), f64_any(0x4022000000000000)].to_array().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4022000000000000)].to_array().to_any());
    check::<A>("truncated", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0x3ff8000000000000), f64_any(0x4022000000000000)].to_array().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4022000000000000), f64_any(0x4008000000000000)].to_array().to_any());
    check::<A>("string", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([string_any("2"), f64_any(0x4022000000000000)].to_array().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4022000000000000)].to_array().to_any());
    check::<A>("noValue", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), [Nullish::Undefined.to_any(), f64_any(0x4000000000000000)].to_array().to_any());
    check::<A>("noArgument", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok(Array::default().to_any())), [Nullish::Undefined.to_any(), f64_any(0x4000000000000000)].to_array().to_any());
    check_throws::<A>("pastTheEnd", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0x4008000000000000), f64_any(0x4022000000000000)].to_array().to_any())));
    check_throws::<A>("beforeTheStart", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0xc010000000000000), f64_any(0x4022000000000000)].to_array().to_any())));
    check_throws::<A>("empty", Any::dot(Array::default().to_any(), string_any("with")).end_call(|| Ok([f64_any(0x0000000000000000), f64_any(0x4022000000000000)].to_array().to_any())));
    check_throws::<A>("infinity", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([f64_any(0x7ff0000000000000), f64_any(0x4022000000000000)].to_array().to_any())));
    check_throws::<A>("bigint", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("with")).end_call(|| Ok([bigint_any(0), f64_any(0x4022000000000000)].to_array().to_any())));
}
