// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("half", Any::dot(f64_any(0x3fe0000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("1"));
    check::<A>("twoAndAHalf", Any::dot(f64_any(0x4004000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("3"));
    check::<A>("tie", Any::dot(f64_any(0x3ff4000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), string_any("1.3"));
    check::<A>("belowTheDecimal", Any::dot(f64_any(0x3ff0147ae147ae14), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("1.00"));
    check::<A>("belowTheTie", Any::dot(f64_any(0x3ff7333333333333), string_any("toFixed")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), string_any("1.4"));
    check::<A>("negative", Any::dot(f64_any(0xbff8000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("-2"));
    check::<A>("negativeTie", Any::dot(f64_any(0xc004000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("-3"));
    check::<A>("negativeToZero", Any::dot(f64_any(0xbfb999999999999a), string_any("toFixed")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("-0"));
    check::<A>("negativeZero", Any::dot(f64_any(0x8000000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("0.00"));
    check::<A>("smallNegative", Any::dot(f64_any(0xbe7ad7f29abcaf48), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("-0.00"));
    check::<A>("noArgument", Any::dot(f64_any(0x3ff8000000000000), string_any("toFixed")).end_call(|| Ok(Array::default().to_any())), string_any("2"));
    check::<A>("exact", Any::dot(f64_any(0x3fb999999999999a), string_any("toFixed")).end_call(|| Ok([f64_any(0x4039000000000000)].to_array().to_any())), string_any("0.1000000000000000055511151"));
    check::<A>("large", Any::dot(f64_any(0x4415af1d78b58c40), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("100000000000000000000.00"));
    check::<A>("tooLarge", Any::dot(f64_any(0x444b1ae4d6e2ef50), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("1e+21"));
    check::<A>("tiny", Any::dot(f64_any(0x3e7ad7f29abcaf48), string_any("toFixed")).end_call(|| Ok([f64_any(0x4024000000000000)].to_array().to_any())), string_any("0.0000001000"));
    check::<A>("nan", Any::dot(f64_any(0x7ff8000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("NaN"));
    check::<A>("infinity", Any::dot(f64_any(0x7ff0000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("Infinity"));
    check::<A>("hundred", Any::dot(f64_any(0x3ff0000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x4059000000000000)].to_array().to_any())), string_any("1.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"));
    check_throws::<A>("tooManyDigits", Any::dot(f64_any(0x3ff0000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x4059400000000000)].to_array().to_any())));
    check_throws::<A>("negativeDigits", Any::dot(f64_any(0x3ff0000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0xbff0000000000000)].to_array().to_any())));
    check_throws::<A>("infinityTooManyDigits", Any::dot(f64_any(0x7ff0000000000000), string_any("toFixed")).end_call(|| Ok([f64_any(0x4059400000000000)].to_array().to_any())));
    check_throws::<A>("bigint", Any::dot(f64_any(0x3ff0000000000000), string_any("toFixed")).end_call(|| Ok([bigint_any(1)].to_array().to_any())));
}
