// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("ascii", Any::dot(string_any("abc"), string_any("toWellFormed")).end_call(|| Ok(Array::default().to_any())), string_any("abc"));
    check::<A>("pair", Any::dot(string_any("a😀b"), string_any("toWellFormed")).end_call(|| Ok(Array::default().to_any())), string_any("a😀b"));
    check::<A>("lone", Any::dot(string_any_utf16(&[0x0061, 0xd800, 0x0062, 0xdc00]), string_any("toWellFormed")).end_call(|| Ok(Array::default().to_any())), string_any("a�b�"));
    check::<A>("reversedPair", Any::dot(string_any_utf16(&[0xde00, 0xd83d]), string_any("toWellFormed")).end_call(|| Ok(Array::default().to_any())), string_any("��"));
    check::<A>("empty", Any::dot(string_any(""), string_any("toWellFormed")).end_call(|| Ok(Array::default().to_any())), string_any(""));
}
