// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("asStrings", Any::dot([f64_any(0x4024000000000000), f64_any(0x4022000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| Ok(Array::default().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4024000000000000), f64_any(0x4022000000000000)].to_array().to_any());
    check::<A>("undefinedComparator", Any::dot([f64_any(0x4008000000000000), f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any());
    check::<A>("undefinedLast", Any::dot([f64_any(0x4008000000000000), Nullish::Undefined.to_any(), f64_any(0x3ff0000000000000), Nullish::Null.to_any()].to_array().to_any(), string_any("toSorted")).end_call(|| Ok(Array::default().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4008000000000000), Nullish::Null.to_any(), Nullish::Undefined.to_any()].to_array().to_any());
    check::<A>("mixed", Any::dot([true.to_any(), string_any("a"), f64_any(0x4024000000000000), bigint_any(2), string_any("B")].to_array().to_any(), string_any("toSorted")).end_call(|| Ok(Array::default().to_any())), [f64_any(0x4024000000000000), bigint_any(2), string_any("B"), string_any("a"), true.to_any()].to_array().to_any());
    check::<A>("nested", Any::dot([[f64_any(0x4000000000000000)].to_array().to_any(), [f64_any(0x3ff0000000000000), f64_any(0x4014000000000000)].to_array().to_any(), [f64_any(0x3ff0000000000000)].to_array().to_any()].to_array().to_any(), string_any("toSorted")).end_call(|| Ok(Array::default().to_any())), [[f64_any(0x3ff0000000000000)].to_array().to_any(), [f64_any(0x3ff0000000000000), f64_any(0x4014000000000000)].to_array().to_any(), [f64_any(0x4000000000000000)].to_array().to_any()].to_array().to_any());
    check::<A>("ascending", Any::dot([f64_any(0x4024000000000000), f64_any(0x4022000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x3ff0000000000000)).end()?;
            c0 - c1
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), [f64_any(0x3ff0000000000000), f64_any(0x4022000000000000), f64_any(0x4024000000000000)].to_array().to_any());
    check::<A>("descending", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4024000000000000), f64_any(0x4022000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x3ff0000000000000)).end()?;
            let c1: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            c0 - c1
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), [f64_any(0x4024000000000000), f64_any(0x4022000000000000), f64_any(0x3ff0000000000000)].to_array().to_any());
    check::<A>("undefinedNeverCompared", Any::dot([f64_any(0x4000000000000000), Nullish::Undefined.to_any(), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x3ff0000000000000)).end()?;
            c0 - c1
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), Nullish::Undefined.to_any()].to_array().to_any());
    check::<A>("nanAnswerIsEqual", Any::dot([f64_any(0x4008000000000000), f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            Any::dot(c0, string_any("x")).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), [f64_any(0x4008000000000000), f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any());
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("toSorted")).end_call(|| Ok(Array::default().to_any())), Array::default().to_any());
    check::<A>("one", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x3ff0000000000000)).end()?;
            c0 - c1
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), [f64_any(0x3ff0000000000000)].to_array().to_any());
    check_throws::<A>("nullComparator", Any::dot([f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| Ok([Nullish::Null.to_any()].to_array().to_any())));
    check_throws::<A>("numberComparator", Any::dot([f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toSorted")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())));
    check_throws::<A>("emptyNotAFunction", Any::dot(Array::default().to_any(), string_any("toSorted")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())));
    check_throws::<A>("bigintAnswer", Any::dot([bigint_any(2), bigint_any(1)].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }));
    check_throws::<A>("throwingComparator", Any::dot([Nullish::Null.to_any(), Nullish::Null.to_any()].to_array().to_any(), string_any("toSorted")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            Any::dot(c0, string_any("x")).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }));
    check_throws::<A>("object", Any::dot(Object::default().to_any(), string_any("toSorted")).end_call(|| Ok(Array::default().to_any())));
}
