// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("noArgument", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("concat")).end_call(|| Ok(Array::default().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any());
    check::<A>("array", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("concat")).end_call(|| {
        let c0: Any<A> = [f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any();
        Ok([c0].to_array().to_any())
    }), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any());
    check::<A>("value", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("concat")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any());
    check::<A>("several", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("concat")).end_call(|| {
        let c0: Any<A> = [f64_any(0x4008000000000000)].to_array().to_any();
        Ok([f64_any(0x4000000000000000), c0, Array::default().to_any(), f64_any(0x4010000000000000)].to_array().to_any())
    }), [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000), f64_any(0x4010000000000000)].to_array().to_any());
    check::<A>("oneLevel", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("concat")).end_call(|| {
        let c0: Any<A> = [f64_any(0x4000000000000000)].to_array().to_any();
        let c1: Any<A> = [c0].to_array().to_any();
        Ok([c1].to_array().to_any())
    }), [f64_any(0x3ff0000000000000), [f64_any(0x4000000000000000)].to_array().to_any()].to_array().to_any());
    check::<A>("object", Any::dot(Array::default().to_any(), string_any("concat")).end_call(|| {
        let c0: Any<A> = [(string_key("a"), f64_any(0x3ff0000000000000))].to_object().to_any();
        Ok([c0].to_array().to_any())
    }), [[(string_key("a"), f64_any(0x3ff0000000000000))].to_object().to_any()].to_array().to_any());
    check::<A>("nullish", Any::dot(Array::default().to_any(), string_any("concat")).end_call(|| Ok([Nullish::Null.to_any(), Nullish::Undefined.to_any()].to_array().to_any())), [Nullish::Null.to_any(), Nullish::Undefined.to_any()].to_array().to_any());
    check::<A>("string", Any::dot(Array::default().to_any(), string_any("concat")).end_call(|| Ok([string_any("ab")].to_array().to_any())), [string_any("ab")].to_array().to_any());
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("concat")).end_call(|| Ok(Array::default().to_any())), Array::default().to_any());
}
