// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("found", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), true.to_any());
    check::<A>("notFound", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x4010000000000000)].to_array().to_any())), false.to_any());
    check::<A>("nan", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x7ff8000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x7ff8000000000000)].to_array().to_any())), true.to_any());
    check::<A>("negativeZero", Any::dot([f64_any(0x0000000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x8000000000000000)].to_array().to_any())), true.to_any());
    check::<A>("noCoercion", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([string_any("1")].to_array().to_any())), false.to_any());
    check::<A>("nullIsNotUndefined", Any::dot([Nullish::Null.to_any()].to_array().to_any(), string_any("includes")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), false.to_any());
    check::<A>("noArgument", Any::dot([Nullish::Undefined.to_any()].to_array().to_any(), string_any("includes")).end_call(|| Ok(Array::default().to_any())), true.to_any());
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("includes")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), false.to_any());
    check::<A>("from", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0x3ff0000000000000)].to_array().to_any())), false.to_any());
    check::<A>("fromTheEnd", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x4008000000000000), f64_any(0xbff0000000000000)].to_array().to_any())), true.to_any());
    check::<A>("fromBeforeTheStart", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0xc022000000000000)].to_array().to_any())), true.to_any());
    check::<A>("fromPastTheEnd", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x4008000000000000), f64_any(0x4008000000000000)].to_array().to_any())), false.to_any());
    check::<A>("fromInfinity", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0x7ff0000000000000)].to_array().to_any())), false.to_any());
    check::<A>("fromString", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000), string_any("1")].to_array().to_any())), false.to_any());
    check::<A>("emptyBigintFrom", Any::dot(Array::default().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000), bigint_any(1)].to_array().to_any())), false.to_any());
    check_throws::<A>("bigintFrom", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000), bigint_any(1)].to_array().to_any())));
    check_throws::<A>("object", Any::dot(Object::default().to_any(), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())));
    check::<A>("stringFound", Any::dot(string_any("abc"), string_any("includes")).end_call(|| Ok([string_any("bc")].to_array().to_any())), true.to_any());
    check::<A>("stringNotFound", Any::dot(string_any("abc"), string_any("includes")).end_call(|| Ok([string_any("cb")].to_array().to_any())), false.to_any());
    check::<A>("stringEmpty", Any::dot(string_any("abc"), string_any("includes")).end_call(|| Ok([string_any("")].to_array().to_any())), true.to_any());
    check::<A>("stringFrom", Any::dot(string_any("abc"), string_any("includes")).end_call(|| Ok([string_any("a"), f64_any(0x3ff0000000000000)].to_array().to_any())), false.to_any());
    check::<A>("stringFromNegative", Any::dot(string_any("abc"), string_any("includes")).end_call(|| Ok([string_any("a"), f64_any(0xc014000000000000)].to_array().to_any())), true.to_any());
    check::<A>("stringNoArgument", Any::dot(string_any("undefined"), string_any("includes")).end_call(|| Ok(Array::default().to_any())), true.to_any());
    check::<A>("stringNumber", Any::dot(string_any("a1b"), string_any("includes")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), true.to_any());
    check::<A>("stringObject", Any::dot(string_any("[object Object]"), string_any("includes")).end_call(|| Ok([Object::default().to_any()].to_array().to_any())), true.to_any());
    check_throws::<A>("stringBigintFrom", Any::dot(string_any("abc"), string_any("includes")).end_call(|| Ok([string_any("a"), bigint_any(0)].to_array().to_any())));
}
