// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("all", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), true.to_any());
    check::<A>("one", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x0000000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), false.to_any());
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), true.to_any());
    check::<A>("stops", Any::dot([Object::default().to_any(), Nullish::Null.to_any()].to_array().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            Any::dot(c0, string_any("x")).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }), false.to_any());
    check_throws::<A>("reachesThrow", Any::dot([[(string_key("x"), f64_any(0x3ff0000000000000))].to_object().to_any(), Nullish::Null.to_any()].to_array().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            Any::dot(c0, string_any("x")).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }));
    check_throws::<A>("everyNotAFunction", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("every")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())));
    check_throws::<A>("everyEmptyNotAFunction", Any::dot(Array::default().to_any(), string_any("every")).end_call(|| Ok([Nullish::Null.to_any()].to_array().to_any())));
    check_throws::<A>("everyNoCallback", Any::dot(Array::default().to_any(), string_any("every")).end_call(|| Ok(Array::default().to_any())));
    check::<A>("everyThisArg", Any::dot([[(string_key("x"), f64_any(0x3ff0000000000000))].to_object().to_any()].to_array().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            Any::dot(c0, string_any("x")).end()
        }, 0, Array::default()).to_any();
        let c1: Any<A> = [(string_key("x"), f64_any(0x0000000000000000))].to_object().to_any();
        Ok([c0, c1].to_array().to_any())
    }), true.to_any());
    check_throws::<A>("everyObject", Any::dot(Object::default().to_any(), string_any("every")).end_call(|| {
        let c0: Any<A> = A::static_function(|_self, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            Any::dot(c0, string_any("x")).end()
        }, 0, Array::default()).to_any();
        Ok([c0].to_array().to_any())
    }));
}
