// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("twice", Any::dot(string_any("ab"), string_any("repeat")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("abab"));
    check::<A>("truncated", Any::dot(string_any("ab"), string_any("repeat")).end_call(|| Ok([f64_any(0x4007333333333333)].to_array().to_any())), string_any("abab"));
    check::<A>("zero", Any::dot(string_any("ab"), string_any("repeat")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any(""));
    check::<A>("noArgument", Any::dot(string_any("ab"), string_any("repeat")).end_call(|| Ok(Array::default().to_any())), string_any(""));
    check::<A>("string", Any::dot(string_any("a"), string_any("repeat")).end_call(|| Ok([string_any("3")].to_array().to_any())), string_any("aaa"));
    check::<A>("emptyMany", Any::dot(string_any(""), string_any("repeat")).end_call(|| Ok([f64_any(0x408f400000000000)].to_array().to_any())), string_any(""));
    check_throws::<A>("negative", Any::dot(string_any("a"), string_any("repeat")).end_call(|| Ok([f64_any(0xbff0000000000000)].to_array().to_any())));
    check_throws::<A>("infinity", Any::dot(string_any("a"), string_any("repeat")).end_call(|| Ok([f64_any(0x7ff0000000000000)].to_array().to_any())));
    check_throws::<A>("emptyInfinity", Any::dot(string_any(""), string_any("repeat")).end_call(|| Ok([f64_any(0x7ff0000000000000)].to_array().to_any())));
    check_throws::<A>("bigint", Any::dot(string_any("a"), string_any("repeat")).end_call(|| Ok([bigint_any(1)].to_array().to_any())));
}
