// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("plain", Any::dot(f64_any(0x405edd2f1a9fbe77), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4010000000000000)].to_array().to_any())), string_any("123.5"));
    check::<A>("small", Any::dot(f64_any(0x3f201f31f46ed246), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("0.00012"));
    check::<A>("exponent", Any::dot(f64_any(0x40fe240000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("1.2e+5"));
    check::<A>("noArgument", Any::dot(f64_any(0x3ff8000000000000), string_any("toPrecision")).end_call(|| Ok(Array::default().to_any())), string_any("1.5"));
    check::<A>("zero", Any::dot(f64_any(0x0000000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), string_any("0.00"));
    check::<A>("negativeZero", Any::dot(f64_any(0x8000000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("0.0"));
    check::<A>("tiny", Any::dot(f64_any(0x3e7ad7f29abcaf48), string_any("toPrecision")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), string_any("1e-7"));
    check::<A>("smallestPlain", Any::dot(f64_any(0x3eb0c6f7a0b5ed8d), string_any("toPrecision")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), string_any("0.000001"));
    check::<A>("roundsUp", Any::dot(f64_any(0x4058ff5c28f5c28f), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), string_any("100"));
    check::<A>("tie", Any::dot(f64_any(0x4004000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), string_any("3"));
    check::<A>("tieExponent", Any::dot(f64_any(0x4039000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), string_any("3e+1"));
    check::<A>("large", Any::dot(f64_any(0x444b1ae4d6e2ef50), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), string_any("1.00e+21"));
    check::<A>("largest", Any::dot(f64_any(0x7fefffffffffffff), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), string_any("1.8e+308"));
    check::<A>("exact", Any::dot(f64_any(0x405ec00000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), string_any("123"));
    check::<A>("nanZero", Any::dot(f64_any(0x7ff8000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("NaN"));
    check::<A>("stringPrecision", Any::dot(f64_any(0x3ff0000000000000), string_any("toPrecision")).end_call(|| Ok([string_any("2.9")].to_array().to_any())), string_any("1.0"));
    check_throws::<A>("bigintOnInfinity", Any::dot(f64_any(0x7ff0000000000000), string_any("toPrecision")).end_call(|| Ok([bigint_any(1)].to_array().to_any())));
    check_throws::<A>("zeroPrecision", Any::dot(f64_any(0x3ff0000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())));
    check_throws::<A>("tooMany", Any::dot(f64_any(0x3ff0000000000000), string_any("toPrecision")).end_call(|| Ok([f64_any(0x4059400000000000)].to_array().to_any())));
    check_throws::<A>("bigint", Any::dot(f64_any(0x3ff0000000000000), string_any("toPrecision")).end_call(|| Ok([bigint_any(1)].to_array().to_any())));
}
