// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("number", Any::dot(f64_any(0x3ff8000000000000), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("1.5"));
    check::<A>("negativeZero", Any::dot(f64_any(0x8000000000000000), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("0"));
    check::<A>("boolean", Any::dot(true.to_any(), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("true"));
    check::<A>("string", Any::dot(string_any("ab"), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("ab"));
    check::<A>("bigint", Any::dot(bigint_any(5), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("5"));
    check::<A>("array", Any::dot([f64_any(0x3ff0000000000000), string_any("b"), Nullish::Null.to_any(), Nullish::Undefined.to_any(), [f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any()].to_array().to_any(), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("1,b,,,2,3"));
    check::<A>("object", Any::dot(Object::default().to_any(), string_any("toString")).end_call(|| Ok(Array::default().to_any())), string_any("[object Object]"));
    check::<A>("radixTen", Any::dot(f64_any(0x406fe00000000000), string_any("toString")).end_call(|| Ok([f64_any(0x4024000000000000)].to_array().to_any())), string_any("255"));
    check::<A>("radixUndefined", Any::dot(f64_any(0x406fe00000000000), string_any("toString")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), string_any("255"));
    // TODO: a radix other than ten is refused: check::<A>("radix", Any::dot(f64_any(0x406fe00000000000), string_any("toString")).end_call(|| Ok([f64_any(0x4030000000000000)].to_array().to_any())), string_any("ff"));
    // TODO: a radix other than ten is refused: check::<A>("bigintRadix", Any::dot(bigint_any(255), string_any("toString")).end_call(|| Ok([f64_any(0x4030000000000000)].to_array().to_any())), string_any("ff"));
    check::<A>("argumentIgnored", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("toString")).end_call(|| Ok([f64_any(0x4030000000000000)].to_array().to_any())), string_any("1"));
    check_throws::<A>("null", Any::dot(Nullish::Null.to_any(), string_any("toString")).end_call(|| Ok(Array::default().to_any())));
    check_throws::<A>("undefined", Any::dot(Nullish::Undefined.to_any(), string_any("toString")).end_call(|| Ok(Array::default().to_any())));
}
