// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("reversed", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("toReversed")).end_call(|| Ok(Array::default().to_any())), [f64_any(0x4008000000000000), f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any());
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("toReversed")).end_call(|| Ok(Array::default().to_any())), Array::default().to_any());
    check::<A>("argumentIgnored", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("toReversed")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), [f64_any(0x4000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any());
    check::<A>("nested", Any::dot([[f64_any(0x3ff0000000000000)].to_array().to_any(), f64_any(0x4000000000000000)].to_array().to_any(), string_any("toReversed")).end_call(|| Ok(Array::default().to_any())), [f64_any(0x4000000000000000), [f64_any(0x3ff0000000000000)].to_array().to_any()].to_array().to_any());
}
