// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("noArgument", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000), f64_any(0x4008000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok(Array::default().to_any())), string_any("1,2,3"));
    check::<A>("undefinedSeparator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), string_any("1,2"));
    check::<A>("separator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([string_any("-")].to_array().to_any())), string_any("1-2"));
    check::<A>("emptySeparator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([string_any("")].to_array().to_any())), string_any("12"));
    check::<A>("nullSeparator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([Nullish::Null.to_any()].to_array().to_any())), string_any("1null2"));
    check::<A>("numberSeparator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("102"));
    check::<A>("arraySeparator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| {
        let c0: Any<A> = [f64_any(0x4008000000000000), f64_any(0x4010000000000000)].to_array().to_any();
        Ok([c0].to_array().to_any())
    }), string_any("13,42"));
    check::<A>("nullish", Any::dot([Nullish::Null.to_any(), Nullish::Undefined.to_any(), f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([string_any(";")].to_array().to_any())), string_any(";;1"));
    check::<A>("nested", Any::dot([f64_any(0x3ff0000000000000), [f64_any(0x4000000000000000), [f64_any(0x4008000000000000), Nullish::Null.to_any()].to_array().to_any()].to_array().to_any()].to_array().to_any(), string_any("join")).end_call(|| Ok([string_any(";")].to_array().to_any())), string_any("1;2,3,"));
    check::<A>("values", Any::dot([true.to_any(), bigint_any(5), string_any("a"), Object::default().to_any(), f64_any(0x8000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok(Array::default().to_any())), string_any("true,5,a,[object Object],0"));
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("join")).end_call(|| Ok([string_any("-")].to_array().to_any())), string_any(""));
    check::<A>("one", Any::dot([f64_any(0x3ff0000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([string_any("-")].to_array().to_any())), string_any("1"));
    check::<A>("bigintSeparator", Any::dot([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("join")).end_call(|| Ok([bigint_any(0)].to_array().to_any())), string_any("102"));
}
