// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("first", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), f64_any(0x4024000000000000));
    check::<A>("last", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x4000000000000000)].to_array().to_any())), f64_any(0x403e000000000000));
    check::<A>("fromTheEnd", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0xbff0000000000000)].to_array().to_any())), f64_any(0x403e000000000000));
    check::<A>("firstFromTheEnd", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0xc008000000000000)].to_array().to_any())), f64_any(0x4024000000000000));
    check::<A>("pastTheEnd", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("beforeTheStart", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0xc010000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("infinity", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x7ff0000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("negativeInfinity", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0xfff0000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("empty", Any::dot(Array::default().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("truncated", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x3ffb333333333333)].to_array().to_any())), f64_any(0x4034000000000000));
    check::<A>("negativeFraction", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0xbfe0000000000000)].to_array().to_any())), f64_any(0x4024000000000000));
    check::<A>("string", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([string_any("1")].to_array().to_any())), f64_any(0x4034000000000000));
    check::<A>("undefinedIndex", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([Nullish::Undefined.to_any()].to_array().to_any())), f64_any(0x4024000000000000));
    check::<A>("nanIndex", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x7ff8000000000000)].to_array().to_any())), f64_any(0x4024000000000000));
    check::<A>("noArgument", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok(Array::default().to_any())), f64_any(0x4024000000000000));
    check::<A>("extraArgument", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any())), f64_any(0x4034000000000000));
    check::<A>("nested", Any::dot([[f64_any(0x3ff0000000000000)].to_array().to_any(), [f64_any(0x4000000000000000)].to_array().to_any()].to_array().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x3ff0000000000000)].to_array().to_any())), [f64_any(0x4000000000000000)].to_array().to_any());
    check_throws::<A>("bigint", Any::dot([f64_any(0x4024000000000000), f64_any(0x4034000000000000), f64_any(0x403e000000000000)].to_array().to_any(), string_any("at")).end_call(|| Ok([bigint_any(1)].to_array().to_any())));
    check_throws::<A>("object", Any::dot(Object::default().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())));
    check_throws::<A>("number", Any::dot(f64_any(0x3ff0000000000000), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())));
    check::<A>("ownProperty", Any::dot([(string_key("at"), function_any())].to_object().to_any(), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("stringFirst", Any::dot(string_any("abc"), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any("a"));
    check::<A>("stringFromTheEnd", Any::dot(string_any("abc"), string_any("at")).end_call(|| Ok([f64_any(0xbff0000000000000)].to_array().to_any())), string_any("c"));
    check::<A>("stringPastTheEnd", Any::dot(string_any("abc"), string_any("at")).end_call(|| Ok([f64_any(0x4008000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("stringBeforeTheStart", Any::dot(string_any("abc"), string_any("at")).end_call(|| Ok([f64_any(0xc010000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("stringNoArgument", Any::dot(string_any("abc"), string_any("at")).end_call(|| Ok(Array::default().to_any())), string_any("a"));
    check::<A>("stringEmpty", Any::dot(string_any(""), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), Nullish::Undefined.to_any());
    check::<A>("stringCodeUnit", Any::dot(string_any("😀"), string_any("at")).end_call(|| Ok([f64_any(0x0000000000000000)].to_array().to_any())), string_any_utf16(&[0xd83d]));
    check_throws::<A>("stringBigint", Any::dot(string_any("abc"), string_any("at")).end_call(|| Ok([bigint_any(0)].to_array().to_any())));
}
