// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("null", !(Nullish::Null.to_any()), true.to_any());
    check::<A>("undefined", !(Nullish::Undefined.to_any()), true.to_any());
    check::<A>("booleanFalse", !(false.to_any()), true.to_any());
    check::<A>("booleanTrue", !(true.to_any()), false.to_any());
    check::<A>("numberZero", !(f64_any(0x0000000000000000)), true.to_any());
    check::<A>("numberNegativeZero", !(f64_any(0x8000000000000000)), true.to_any());
    check::<A>("numberNan", !(f64_any(0x7ff8000000000000)), true.to_any());
    check::<A>("numberPositive", !(f64_any(0x4002666666666666)), false.to_any());
    check::<A>("numberNegative", !(f64_any(0xc002666666666666)), false.to_any());
    check::<A>("stringEmpty", !(string_any("")), true.to_any());
    check::<A>("stringNonEmpty", !(string_any("a")), false.to_any());
    check::<A>("bigintZero", !(bigint_any(0)), true.to_any());
    check::<A>("bigintPositive", !(bigint_any(5)), false.to_any());
    check::<A>("bigintNegative", !(bigint_any(-5)), false.to_any());
    check::<A>("emptyArray", !(Array::default().to_any()), false.to_any());
    check::<A>("emptyObject", !(Object::default().to_any()), false.to_any());
    check::<A>("function", !(function_any()), false.to_any());
}
