// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullCoalesceOne", Any::nullish_coalescing(Nullish::Null.to_any(), || Ok(f64_any(0x3ff0000000000000))), f64_any(0x3ff0000000000000));
    check::<A>("undefinedCoalesceOne", Any::nullish_coalescing(Nullish::Undefined.to_any(), || Ok(f64_any(0x3ff0000000000000))), f64_any(0x3ff0000000000000));
    check::<A>("zeroCoalesceOne", Any::nullish_coalescing(f64_any(0x0000000000000000), || Ok(f64_any(0x3ff0000000000000))), f64_any(0x0000000000000000));
    check::<A>("falseCoalesceOne", Any::nullish_coalescing(false.to_any(), || Ok(f64_any(0x3ff0000000000000))), false.to_any());
    check::<A>("nanCoalesceOne", Any::nullish_coalescing(f64_any(0x7ff8000000000000), || Ok(f64_any(0x3ff0000000000000))), f64_any(0x7ff8000000000000));
    check::<A>("emptyStringCoalesceOne", Any::nullish_coalescing(string_any(""), || Ok(f64_any(0x3ff0000000000000))), string_any(""));
    check::<A>("bigZeroCoalesceOne", Any::nullish_coalescing(bigint_any(0), || Ok(f64_any(0x3ff0000000000000))), bigint_any(0));
    check::<A>("oneCoalesceTwo", Any::nullish_coalescing(f64_any(0x3ff0000000000000), || Ok(f64_any(0x4000000000000000))), f64_any(0x3ff0000000000000));
    check::<A>("oneCoalesceNull", Any::nullish_coalescing(f64_any(0x3ff0000000000000), || Ok(Nullish::Null.to_any())), f64_any(0x3ff0000000000000));
    check::<A>("oneCoalesceEmptyArray", Any::nullish_coalescing(f64_any(0x3ff0000000000000), || Ok(Array::default().to_any())), f64_any(0x3ff0000000000000));
    check::<A>("oneCoalesceEmptyObject", Any::nullish_coalescing(f64_any(0x3ff0000000000000), || Ok(Object::default().to_any())), f64_any(0x3ff0000000000000));
    check::<A>("oneCoalesceFunction", Any::nullish_coalescing(f64_any(0x3ff0000000000000), || Ok(function_any())), f64_any(0x3ff0000000000000));
    check::<A>("oneCoalesceUnreached", Any::nullish_coalescing(f64_any(0x3ff0000000000000), || bigint_any(1) / bigint_any(0)), f64_any(0x3ff0000000000000));
    check::<A>("zeroCoalesceUnreached", Any::nullish_coalescing(f64_any(0x0000000000000000), || bigint_any(1) / bigint_any(0)), f64_any(0x0000000000000000));
    check::<A>("falseCoalesceUnreached", Any::nullish_coalescing(false.to_any(), || bigint_any(1) / bigint_any(0)), false.to_any());
    check::<A>("emptyStringCoalesceUnreached", Any::nullish_coalescing(string_any(""), || bigint_any(1) / bigint_any(0)), string_any(""));
}
