// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("null", Any::number(Nullish::Null.to_any()), f64_any(0x0000000000000000));
    check::<A>("undefined", Any::number(Nullish::Undefined.to_any()), f64_any(0x7ff8000000000000));
    check::<A>("booleanFalse", Any::number(false.to_any()), f64_any(0x0000000000000000));
    check::<A>("booleanTrue", Any::number(true.to_any()), f64_any(0x3ff0000000000000));
    check::<A>("numberZero", Any::number(f64_any(0x0000000000000000)), f64_any(0x0000000000000000));
    check::<A>("numberPositive", Any::number(f64_any(0x4002666666666666)), f64_any(0x4002666666666666));
    check::<A>("numberNegative", Any::number(f64_any(0xc002666666666666)), f64_any(0xc002666666666666));
    check::<A>("numberLarge", Any::number(f64_any(0xc06de00000000000)), f64_any(0xc06de00000000000));
    check::<A>("numberInfinity", Any::number(f64_any(0x7ff0000000000000)), f64_any(0x7ff0000000000000));
    check::<A>("numberNegativeInfinity", Any::number(f64_any(0xfff0000000000000)), f64_any(0xfff0000000000000));
    check::<A>("numberNan", Any::number(f64_any(0x7ff8000000000000)), f64_any(0x7ff8000000000000));
    check::<A>("stringEmpty", Any::number(string_any("")), f64_any(0x0000000000000000));
    check::<A>("stringZero", Any::number(string_any("0")), f64_any(0x0000000000000000));
    check::<A>("stringNumber", Any::number(string_any("2.3")), f64_any(0x4002666666666666));
    check::<A>("stringExponent", Any::number(string_any("2.3e2")), f64_any(0x406cc00000000000));
    check::<A>("stringNotANumber", Any::number(string_any("a")), f64_any(0x7ff8000000000000));
    check::<A>("arrayEmpty", Any::number(Array::default().to_any()), f64_any(0x0000000000000000));
    check::<A>("arrayNumber", Any::number([f64_any(0x4002666666666666)].to_array().to_any()), f64_any(0x4002666666666666));
    check::<A>("arrayNegativeNumber", Any::number([f64_any(0xbfd3333333333333)].to_array().to_any()), f64_any(0xbfd3333333333333));
    check::<A>("arrayString", Any::number([string_any("-2.3")].to_array().to_any()), f64_any(0xc002666666666666));
    check::<A>("arrayPositiveString", Any::number([string_any("0.3")].to_array().to_any()), f64_any(0x3fd3333333333333));
    check::<A>("arrayNull", Any::number([Nullish::Null.to_any()].to_array().to_any()), f64_any(0x0000000000000000));
    check::<A>("arrayPair", Any::number([Nullish::Null.to_any(), Nullish::Null.to_any()].to_array().to_any()), f64_any(0x7ff8000000000000));
    check::<A>("objectEmpty", Any::number(Object::default().to_any()), f64_any(0x7ff8000000000000));
    check::<A>("objectOwnValueOf", Any::number([(string_key("valueOf"), function_any())].to_object().to_any()), f64_any(0x7ff8000000000000));
    check::<A>("objectOwnValueOfNumber", Any::number([(string_key("valueOf"), A::static_function(|_self, _args| { Ok(f64_any(0x4002666666666666)) }, 0, Array::default(), Some("()=>2.3")).to_any())].to_object().to_any()), f64_any(0x4002666666666666));
    check::<A>("objectOwnToString", Any::number([(string_key("toString"), A::static_function(|_self, _args| { Ok(string_any("2.3")) }, 0, Array::default(), Some("()=>\"2.3\"")).to_any())].to_object().to_any()), f64_any(0x4002666666666666));
    check::<A>("objectOwnBoth", Any::number([(string_key("valueOf"), A::static_function(|_self, _args| { Ok(f64_any(0x3ff0000000000000)) }, 0, Array::default(), Some("()=>1")).to_any()), (string_key("toString"), A::static_function(|_self, _args| { Ok(string_any("2")) }, 0, Array::default(), Some("()=>\"2\"")).to_any())].to_object().to_any()), f64_any(0x3ff0000000000000));
    check::<A>("objectOwnValueOfNotAFunction", Any::number([(string_key("valueOf"), string_any("x"))].to_object().to_any()), f64_any(0x7ff8000000000000));
    check::<A>("objectOwnValueOfNotPrimitive", Any::number([(string_key("valueOf"), A::static_function(|_self, _args| { Ok(Object::default().to_any()) }, 0, Array::default(), Some("()=>{return {};}")).to_any()), (string_key("toString"), A::static_function(|_self, _args| { Ok(string_any("2")) }, 0, Array::default(), Some("()=>\"2\"")).to_any())].to_object().to_any()), f64_any(0x4000000000000000));
    check_throws::<A>("objectOwnNoPrimitive", Any::number([(string_key("toString"), A::static_function(|_self, _args| { Ok(Array::default().to_any()) }, 0, Array::default(), Some("()=>[]")).to_any())].to_object().to_any()));
    check_throws::<A>("objectOwnValueOfThrows", Any::number([(string_key("valueOf"), A::static_function(|_self, _args| { bigint_any(1) / bigint_any(0) }, 0, Array::default(), Some("()=>1n/0n")).to_any()), (string_key("toString"), A::static_function(|_self, _args| { Ok(string_any("2")) }, 0, Array::default(), Some("()=>\"2\"")).to_any())].to_object().to_any()));
    check::<A>("function", Any::number(function_any()), f64_any(0x7ff8000000000000));
    check::<A>("bigintZero", Any::number(bigint_any(0)), f64_any(0x0000000000000000));
    check::<A>("bigintPositive", Any::number(bigint_any(1)), f64_any(0x3ff0000000000000));
    check::<A>("bigintNegative", Any::number(bigint_any(-1)), f64_any(0xbff0000000000000));
    check::<A>("bigintTieDown", Any::number(bigint_any(9007199254740993)), f64_any(0x4340000000000000));
    check::<A>("bigintTieUp", Any::number(bigint_any(9007199254740995)), f64_any(0x4340000000000002));
    check::<A>("bigintWideTieDown", Any::number(bigint_any_words(false, &[0x0000000000000800, 0x0000000000000001])), f64_any(0x43f0000000000000));
    check::<A>("bigintWideTieUp", Any::number(bigint_any_words(false, &[0x0000000000001800, 0x0000000000000001])), f64_any(0x43f0000000000002));
    check::<A>("bigintWideSticky", Any::number(bigint_any_words(false, &[0x0000000000000801, 0x0000000000000001])), f64_any(0x43f0000000000001));
    check::<A>("bigintSeveralWords", Any::number(bigint_any_words(false, &[0xc373e0ee4e3f0ad2, 0x000000018ee90ff6])), f64_any(0x45f8ee90ff6c373e));
    check::<A>("bigintLargestFinite", Any::number(bigint_any_words(false, &[0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xfffffffffffff800])), f64_any(0x7fefffffffffffff));
    check::<A>("bigintBelowOverflowTie", Any::number(bigint_any_words(false, &[0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xfffffffffffffbff])), f64_any(0x7fefffffffffffff));
    check::<A>("bigintOverflowTie", Any::number(bigint_any_words(false, &[0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xfffffffffffffc00])), f64_any(0x7ff0000000000000));
    check::<A>("bigintNegativeOverflowTie", Any::number(bigint_any_words(true, &[0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xfffffffffffffc00])), f64_any(0xfff0000000000000));
    check::<A>("bigintBeyondRange", Any::number(bigint_any_words(false, &[0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000001])), f64_any(0x7ff0000000000000));
    check::<A>("bigintNegativeBeyondRange", Any::number(bigint_any_words(true, &[0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000001])), f64_any(0xfff0000000000000));
    check::<A>("bigintObject", Any::number([(string_key("valueOf"), A::static_function(|_self, _args| { Ok(bigint_any(7)) }, 0, Array::default(), Some("()=>7n")).to_any())].to_object().to_any()), f64_any(0x401c000000000000));
}
