// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("presentProperty", Any::own_property([(string_key("a"), f64_any(0x401c000000000000))].to_object().to_any(), string_any("a")), f64_any(0x401c000000000000));
    check::<A>("missingProperty", Any::own_property([(string_key("a"), f64_any(0x401c000000000000))].to_object().to_any(), string_any("b")), Nullish::Undefined.to_any());
    check::<A>("emptyObject", Any::own_property(Object::default().to_any(), string_any("a")), Nullish::Undefined.to_any());
    check::<A>("inheritedNameIsAbsent", Any::own_property(Object::default().to_any(), string_any("toString")), Nullish::Undefined.to_any());
    check::<A>("valuePreservesBooleanType", Any::own_property([(string_key("a"), true.to_any())].to_object().to_any(), string_any("a")), true.to_any());
    check::<A>("valuePreservesBigintType", Any::own_property([(string_key("a"), bigint_any(5))].to_object().to_any(), string_any("a")), bigint_any(5));
    check::<A>("valuePreservesStringType", Any::own_property([(string_key("a"), string_any("x"))].to_object().to_any(), string_any("a")), string_any("x"));
    check::<A>("valuePreservesNullType", Any::own_property([(string_key("a"), Nullish::Null.to_any())].to_object().to_any(), string_any("a")), Nullish::Null.to_any());
    check::<A>("multiplePropertiesDistinguished", Any::own_property([(string_key("a"), f64_any(0x3ff0000000000000)), (string_key("b"), f64_any(0x4000000000000000))].to_object().to_any(), string_any("b")), f64_any(0x4000000000000000));
    check::<A>("numericStringKey", Any::own_property([(string_key("1"), f64_any(0x4045000000000000))].to_object().to_any(), string_any("1")), f64_any(0x4045000000000000));
    check::<A>("nonObjectNumberReceiver", Any::own_property(f64_any(0x4014000000000000), string_any("a")), Nullish::Undefined.to_any());
    check::<A>("nonObjectStringReceiver", Any::own_property(string_any("hi"), string_any("a")), Nullish::Undefined.to_any());
    check::<A>("nonObjectBooleanReceiver", Any::own_property(true.to_any(), string_any("a")), Nullish::Undefined.to_any());
    check::<A>("nonObjectBigintReceiver", Any::own_property(bigint_any(5), string_any("a")), Nullish::Undefined.to_any());
    check::<A>("nonObjectArrayReceiver", Any::own_property([f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any(), string_any("a")), Nullish::Undefined.to_any());
    check::<A>("nonObjectFunctionReceiver", Any::own_property(function_any(), string_any("a")), Nullish::Undefined.to_any());
    check_throws::<A>("nullReceiverThrows", Any::own_property(Nullish::Null.to_any(), string_any("a")));
    check_throws::<A>("undefinedReceiverThrows", Any::own_property(Nullish::Undefined.to_any(), string_any("a")));
    check_throws::<A>("nonStringKeyThrows", Any::own_property([(string_key("1"), f64_any(0x4045000000000000))].to_object().to_any(), f64_any(0x3ff0000000000000)));
}
