// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("nullModThree", Nullish::Null.to_any() % f64_any(0x4008000000000000), f64_any(0x0000000000000000));
    check::<A>("undefinedModThree", Nullish::Undefined.to_any() % f64_any(0x4008000000000000), f64_any(0x7ff8000000000000));
    check::<A>("trueModThree", true.to_any() % f64_any(0x4008000000000000), f64_any(0x3ff0000000000000));
    check::<A>("falseModThree", false.to_any() % f64_any(0x4008000000000000), f64_any(0x0000000000000000));
    check::<A>("stringTenModThree", string_any("10") % f64_any(0x4008000000000000), f64_any(0x3ff0000000000000));
    check::<A>("stringLetterModThree", string_any("a") % f64_any(0x4008000000000000), f64_any(0x7ff8000000000000));
    check::<A>("emptyArrayModThree", Array::default().to_any() % f64_any(0x4008000000000000), f64_any(0x0000000000000000));
    check::<A>("arrayTenModThree", [f64_any(0x4024000000000000)].to_array().to_any() % f64_any(0x4008000000000000), f64_any(0x3ff0000000000000));
    check::<A>("arrayStringTenModThree", [string_any("10")].to_array().to_any() % f64_any(0x4008000000000000), f64_any(0x3ff0000000000000));
    check::<A>("arrayPairModThree", [f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any() % f64_any(0x4008000000000000), f64_any(0x7ff8000000000000));
    check::<A>("emptyObjectModThree", Object::default().to_any() % f64_any(0x4008000000000000), f64_any(0x7ff8000000000000));
    check::<A>("functionModThree", function_any() % f64_any(0x4008000000000000), f64_any(0x7ff8000000000000));
    check::<A>("zeroModOne", f64_any(0x0000000000000000) % f64_any(0x3ff0000000000000), f64_any(0x0000000000000000));
    check::<A>("negativeZeroModOne", f64_any(0x8000000000000000) % f64_any(0x3ff0000000000000), f64_any(0x8000000000000000));
    check::<A>("oneModOne", f64_any(0x3ff0000000000000) % f64_any(0x3ff0000000000000), f64_any(0x0000000000000000));
    check::<A>("tenModThree", f64_any(0x4024000000000000) % f64_any(0x4008000000000000), f64_any(0x3ff0000000000000));
    check::<A>("negativeTenModThree", f64_any(0xc024000000000000) % f64_any(0x4008000000000000), f64_any(0xbff0000000000000));
    check::<A>("tenModNegativeThree", f64_any(0x4024000000000000) % f64_any(0xc008000000000000), f64_any(0x3ff0000000000000));
    check::<A>("negativeTenModNegativeThree", f64_any(0xc024000000000000) % f64_any(0xc008000000000000), f64_any(0xbff0000000000000));
    check::<A>("fiveModZero", f64_any(0x4014000000000000) % f64_any(0x0000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("zeroModZero", f64_any(0x0000000000000000) % f64_any(0x0000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("negativeZeroModZero", f64_any(0x8000000000000000) % f64_any(0x0000000000000000), f64_any(0x7ff8000000000000));
    check::<A>("fiveModInfinity", f64_any(0x4014000000000000) % f64_any(0x7ff0000000000000), f64_any(0x4014000000000000));
    check::<A>("negativeFiveModInfinity", f64_any(0xc014000000000000) % f64_any(0x7ff0000000000000), f64_any(0xc014000000000000));
    check::<A>("infinityModFive", f64_any(0x7ff0000000000000) % f64_any(0x4014000000000000), f64_any(0x7ff8000000000000));
    check::<A>("infinityModInfinity", f64_any(0x7ff0000000000000) % f64_any(0x7ff0000000000000), f64_any(0x7ff8000000000000));
    check::<A>("nanModOne", f64_any(0x7ff8000000000000) % f64_any(0x3ff0000000000000), f64_any(0x7ff8000000000000));
    check::<A>("oneModNan", f64_any(0x3ff0000000000000) % f64_any(0x7ff8000000000000), f64_any(0x7ff8000000000000));
    check::<A>("fractionModTwo", f64_any(0x4016000000000000) % f64_any(0x4000000000000000), f64_any(0x3ff8000000000000));
    check::<A>("negativeFractionModTwo", f64_any(0xc016000000000000) % f64_any(0x4000000000000000), f64_any(0xbff8000000000000));
    check::<A>("bigTenModThree", bigint_any(10) % bigint_any(3), bigint_any(1));
    check::<A>("bigNegativeTenModThree", bigint_any(-10) % bigint_any(3), bigint_any(-1));
    check::<A>("bigTenModNegativeThree", bigint_any(10) % bigint_any(-3), bigint_any(1));
    check::<A>("bigNegativeTenModNegativeThree", bigint_any(-10) % bigint_any(-3), bigint_any(-1));
    check::<A>("bigZeroModOne", bigint_any(0) % bigint_any(1), bigint_any(0));
    check_throws::<A>("bigTenModZero", bigint_any(10) % bigint_any(0));
    check_throws::<A>("numberModBigint", f64_any(0x3ff0000000000000) % bigint_any(1));
    check_throws::<A>("bigintModNumber", bigint_any(1) % f64_any(0x3ff0000000000000));
}
