// @generated by `npm run gen` from `fjs/nanvm/module.f.mjs`.
// Do not edit: change the shared test data and regenerate.

use crate::harness::*;

#[rustfmt::skip]
pub fn run<A: IStaticFunction>() {
    check::<A>("null", Any::unary_plus(Nullish::Null.to_any()), f64_any(0x0000000000000000));
    check::<A>("undefined", Any::unary_plus(Nullish::Undefined.to_any()), f64_any(0x7ff8000000000000));
    check::<A>("booleanFalse", Any::unary_plus(false.to_any()), f64_any(0x0000000000000000));
    check::<A>("booleanTrue", Any::unary_plus(true.to_any()), f64_any(0x3ff0000000000000));
    check::<A>("numberZero", Any::unary_plus(f64_any(0x0000000000000000)), f64_any(0x0000000000000000));
    check::<A>("numberPositive", Any::unary_plus(f64_any(0x4002666666666666)), f64_any(0x4002666666666666));
    check::<A>("numberNegative", Any::unary_plus(f64_any(0xc002666666666666)), f64_any(0xc002666666666666));
    check::<A>("numberLarge", Any::unary_plus(f64_any(0xc06de00000000000)), f64_any(0xc06de00000000000));
    check::<A>("numberInfinity", Any::unary_plus(f64_any(0x7ff0000000000000)), f64_any(0x7ff0000000000000));
    check::<A>("numberNegativeInfinity", Any::unary_plus(f64_any(0xfff0000000000000)), f64_any(0xfff0000000000000));
    check::<A>("numberNan", Any::unary_plus(f64_any(0x7ff8000000000000)), f64_any(0x7ff8000000000000));
    check::<A>("stringEmpty", Any::unary_plus(string_any("")), f64_any(0x0000000000000000));
    check::<A>("stringZero", Any::unary_plus(string_any("0")), f64_any(0x0000000000000000));
    check::<A>("stringNumber", Any::unary_plus(string_any("2.3")), f64_any(0x4002666666666666));
    check::<A>("stringExponent", Any::unary_plus(string_any("2.3e2")), f64_any(0x406cc00000000000));
    check::<A>("stringNotANumber", Any::unary_plus(string_any("a")), f64_any(0x7ff8000000000000));
    check::<A>("arrayEmpty", Any::unary_plus(Array::default().to_any()), f64_any(0x0000000000000000));
    check::<A>("arrayNumber", Any::unary_plus([f64_any(0x4002666666666666)].to_array().to_any()), f64_any(0x4002666666666666));
    check::<A>("arrayNegativeNumber", Any::unary_plus([f64_any(0xbfd3333333333333)].to_array().to_any()), f64_any(0xbfd3333333333333));
    check::<A>("arrayString", Any::unary_plus([string_any("-2.3")].to_array().to_any()), f64_any(0xc002666666666666));
    check::<A>("arrayPositiveString", Any::unary_plus([string_any("0.3")].to_array().to_any()), f64_any(0x3fd3333333333333));
    check::<A>("arrayNull", Any::unary_plus([Nullish::Null.to_any()].to_array().to_any()), f64_any(0x0000000000000000));
    check::<A>("arrayPair", Any::unary_plus([Nullish::Null.to_any(), Nullish::Null.to_any()].to_array().to_any()), f64_any(0x7ff8000000000000));
    check::<A>("objectEmpty", Any::unary_plus(Object::default().to_any()), f64_any(0x7ff8000000000000));
    check::<A>("function", Any::unary_plus(function_any()), f64_any(0x7ff8000000000000));
    check_throws::<A>("bigint", Any::unary_plus(bigint_any(0)));
}
