const $s0 = [0];
const $s1 = {"a": 0};
const $s2 = [0];
export default [
    {"id": "graph-sharing-array", "class": "const/shared/twice", "input": [$s0, $s0], "denotes": ["const $0=[0];export default [$0,$0];", "const $0=[0];const $1=[$0,$0];export default $1;", "const $9 = [ 0 ] ;\nconst $x = [ $9 , $9 ] ;\nexport default $x ;\n"], "denotesNot": ["export default [[0],[0]];", "const $0=[0];const $1=[0];export default [$0,$1];", "const $0=[0];export default [$0,[0]];"]},
    {"id": "graph-sharing-object", "class": "const/shared/object", "input": {"x": $s1, "y": $s1}, "denotes": ["const $0={\"a\":0};export default {\"x\":$0,\"y\":$0};", "const $0={\"a\":0};const $1={\"x\":$0,\"y\":$0};export default $1;", "const $9 = { \"a\" : 0 } ;\nconst $x = { \"x\" : $9 , \"y\" : $9 } ;\nexport default $x ;\n"], "denotesNot": ["export default {\"x\":{\"a\":0},\"y\":{\"a\":0}};", "const $0={\"a\":0};const $1={\"a\":0};export default {\"x\":$0,\"y\":$1};", "const $0={\"a\":0};export default {\"x\":$0,\"y\":{\"a\":0}};"]},
    {"id": "graph-sharing-mixed", "class": "const/shared/mixed", "input": [[$s2], {"x": $s2}], "denotes": ["const $0=[0];export default [[$0],{\"x\":$0}];", "const $0=[0];const $1=[$0];const $2={\"x\":$0};export default [$1,$2];", "const $9 = [ 0 ] ;\nexport default [ [ $9 ] , { \"x\" : $9 } ] ;\n"], "denotesNot": ["export default [[[0]],{\"x\":[0]}];", "const $0=[0];const $1=[0];export default [[$0],{\"x\":$1}];", "const $0=[0];export default [[$0],{\"x\":[0]}];"]},
    {"id": "graph-unshared-array-empty", "class": "array/unshared", "input": [[], []], "denotes": ["export default [[],[]];", "const $0=[];const $1=[];export default [$0,$1];", "const $0=[];export default [$0,[]];"], "denotesNot": ["const $0=[];export default [$0,$0];", "const $0=[];const $1=[$0,$0];export default $1;"]},
    {"id": "graph-unshared-array-non-empty", "class": "array/unshared/equal", "input": [[1], [1]], "denotes": ["export default [[1],[1]];", "const $0=[1];const $1=[1];export default [$0,$1];", "const $0=[1];export default [$0,[1]];"], "denotesNot": ["const $0=[1];export default [$0,$0];", "const $0=[1];const $1=[$0,$0];export default $1;"]},
    {"id": "graph-unshared-object-empty", "class": "object/unshared", "input": [{}, {}], "denotes": ["export default [{},{}];", "const $0={};const $1={};export default [$0,$1];", "const $0={};export default [$0,{}];"], "denotesNot": ["const $0={};export default [$0,$0];", "const $0={};const $1=[$0,$0];export default $1;"]},
    {"id": "graph-unshared-object-non-empty", "class": "object/unshared/equal", "input": [{"a": 1}, {"a": 1}], "denotes": ["export default [{\"a\":1},{\"a\":1}];", "const $0={\"a\":1};const $1={\"a\":1};export default [$0,$1];", "const $0={\"a\":1};export default [$0,{\"a\":1}];"], "denotesNot": ["const $0={\"a\":1};export default [$0,$0];", "const $0={\"a\":1};const $1=[$0,$0];export default $1;"]},
    {"id": "graph-unshared-object-parent-empty", "class": "object/unshared", "input": {"x": {}, "y": {}}, "denotes": ["export default {\"x\":{},\"y\":{}};", "const $0={};const $1={};export default {\"x\":$0,\"y\":$1};"], "denotesNot": ["const $0={};export default {\"x\":$0,\"y\":$0};", "const $0={};const $1={\"x\":$0,\"y\":$0};export default $1;"]},
    {"id": "graph-unshared-object-parent", "class": "object/unshared/equal", "input": {"x": {"a": 1}, "y": {"a": 1}}, "denotes": ["export default {\"x\":{\"a\":1},\"y\":{\"a\":1}};", "const $0={\"a\":1};const $1={\"a\":1};export default {\"x\":$0,\"y\":$1};"], "denotesNot": ["const $0={\"a\":1};export default {\"x\":$0,\"y\":$0};", "const $0={\"a\":1};const $1={\"x\":$0,\"y\":$0};export default $1;"]}
];
