/**
 * Proofs for the completeness table.
 */

import { assert, assertEq } from '../../asserts/module.f.mjs'
import { allowedCalls, prohibitedCalls, prototypeNames } from '../../js/prototype/module.f.mjs'
import { directory, generate, path, pending, rows, types } from './module.f.mjs'

/** @type {(pairs: readonly (readonly[string, string])[]) => readonly string[]} */
const keys = pairs => pairs.map(([t, n]) => `${t}.${n}`)

export const proof = {
    /**
     * The three rows partition every pair of a type and a name its
     * prototype has, `length` alone aside, which is on neither call list.
     */
    partition: () => {
        const r = rows(pending)
        const all = [...keys(r.answered), ...keys(r.pending), ...keys(r.prohibited)]
        assertEq(new Set(all).size, all.length)
        const expected = types.flatMap(([t, names]) =>
            names.filter(n => n !== 'length').map(n => `${t}.${n}`))
        assertEq(all.toSorted().join(), expected.toSorted().join())
    },
    /** What the VM answers today: `toString` on all seven types, and `Array`'s own. */
    answered: () => {
        const array = [
            'at', 'concat', 'every', 'filter', 'find', 'findIndex', 'findLast', 'findLastIndex',
            'flat', 'flatMap', 'includes', 'indexOf', 'join', 'lastIndexOf', 'map', 'reduce',
            'reduceRight', 'slice', 'some', 'toReversed', 'toSorted', 'toSpliced', 'toString',
            'with',
        ]
        assertEq(
            keys(rows(pending).answered).join(),
            ['object', 'array', 'string', 'number', 'boolean', 'bigint', 'function']
                .flatMap(t => t === 'array' ? array.map(n => `${t}.${n}`) : [`${t}.toString`])
                .join())
    },
    /** A row holds names of its list only. */
    rows: () => {
        const r = rows(pending)
        /** @type {readonly string[]} */
        const allowed = allowedCalls
        /** @type {readonly string[]} */
        const prohibited = prohibitedCalls
        assert(r.answered.every(([, n]) => allowed.includes(n)))
        assert(r.pending.every(([, n]) => allowed.includes(n)))
        assert(r.prohibited.every(([, n]) => prohibited.includes(n)))
        assert(keys(r.prohibited).includes('array.push'))
        // A known name on another type's prototype only, allowed or not.
        assert(keys(r.absent).includes('array.charAt'))
        assert(keys(r.absent).includes('number.map'))
        assert(keys(r.absent).includes('array.bind'))
        // `length`, a property, on every type, whether its prototype has it or not.
        assert(types.every(([t]) => keys(r.absent).includes(`${t}.length`)))
        // Every known pair is in exactly one row.
        const onPrototype = [...keys(r.answered), ...keys(r.pending), ...keys(r.prohibited)]
        assert(r.absent.every(([t, n]) => !onPrototype.includes(`${t}.${n}`)))
        assertEq(onPrototype.length + r.absent.length, types.length * prototypeNames.length)
        // Every name any prototype has is some type's.
        /** @type {readonly string[]} */
        const names = types.flatMap(([, n]) => n)
        assert(prototypeNames.every(n => names.includes(n)))
        // An empty pending list answers every allowed pair.
        assertEq(rows({}).pending.length, 0)
        assertEq(rows({}).answered.length, r.answered.length + r.pending.length)
    },
    generate: () => {
        const rust = generate()
        assert(rust.startsWith('// @generated by `npm run gen` from `fjs/nanvm/methods/module.f.mjs`.\n'), rust)
        assert(rust.includes('pub const ANSWERED: &[(&str, &str)] = &[\n    ("object", "toString"),\n'), rust)
        assert(rust.includes('    ("array", "at"),\n'), rust)
        const [type, name] = rows(pending).pending[0]
        assert(rust.includes(`pub const PENDING: &[(&str, &str)] = &[\n    ("${type}", "${name}"),\n`), rust)
        assert(rust.includes('pub const PROHIBITED: &[(&str, &str)] = &[\n    ("object", "__defineGetter__"),\n'), rust)
        assert(rust.includes('pub const ABSENT: &[(&str, &str)] = &[\n'), rust)
        assert(rust.includes('    ("array", "charAt"),\n'), rust)
        assert(rust.endsWith('];\n'), rust)
        assertEq(path, `${directory}/gen.methods.rs`)
        assertEq(directory, 'nanvm-lib/src/vm/lambda')
    },
    throw: {
        /** A name the type's prototype lacks, `push` being a mutator's. */
        notAllowed: () => rows({ array: ['push'] }),
        /** A name of another type's prototype. */
        wrongType: () => rows({ number: ['map'] }),
        /** A type there is no prototype of. */
        unknownType: () => rows({ symbol: ['toString'] }),
        /** The same pair twice. */
        duplicate: () => rows({ array: ['map', 'map'] }),
    },
}
