// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, Nullish, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
        let c1: Any<A> = Any::dot(c0, string_any("x")).end()?;
        Ok(A::static_function(|self_, _args| { Ok(A::frame(self_)[0].clone()) }, 0, [c1].to_array(), Some("()=>$0")).to_any())
    }, 0, Array::default(), Some("(...$0)=>{const $1=$0[0].x;return ()=>$1;}")).to_any();
    let c1: Any<A> = Any::call(c0, [Nullish::Undefined.to_any()].to_array().to_any())?;
    Ok([(string_key("default"), c1)].to_object().to_any())
}
