// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, strict_eq, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, _args| { Ok(f64_any(0x3ff0000000000000)) }, 0, Array::default(), Some("()=>1")).to_any();
    let c1: Any<A> = Any::dot(c0.clone(), string_any("toString")).end_call(|| Ok(Array::default().to_any()))?;
    let c2: Any<A> = (c0.clone() + string_any("!"))?;
    let c3: Any<A> = [c0.clone(), f64_any(0x4000000000000000)].to_array().to_any();
    let c4 = || Ok([string_any("|")].to_array().to_any());
    let c5: Any<A> = Any::dot(c3, string_any("join")).end_call(c4)?;
    let c6: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        Ok(A::static_function(|self_, args| {
            let rest = args.clone().into_iter().to_array();
            let c0: Any<A> = Any::dot(A::frame(self_)[0].clone(), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
            c0 + c1
        }, 0, [rest.clone().to_any()].to_array(), Some("(...$a)=>$0[0]+$a[0]")).to_any())
    }, 0, Array::default(), Some("(...$a)=>(...$b)=>$a[0]+$b[0]")).to_any();
    let c7: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c8: Any<A> = Any::call(c6.clone(), c7)?;
    let c9: Any<A> = Any::dot(c8, string_any("toString")).end_call(|| Ok(Array::default().to_any()))?;
    let c10: Any<A> = Any::dot(c6.clone(), string_any("toString")).end_call(|| Ok(Array::default().to_any()))?;
    let c11: Any<A> = (strict_eq(c0.clone(), c0.clone()))?;
    let c12: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c13: Any<A> = Any::call(c6.clone(), c12)?;
    let c14: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c15: Any<A> = Any::call(c6.clone(), c14)?;
    let c16: Any<A> = (strict_eq(c13, c15))?;
    let c17: Any<A> = [c1, c2, c5, c9, c10, c11, c16].to_array().to_any();
    let c18: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c19: Any<A> = Any::call(c6.clone(), c18)?;
    Ok([(string_key("default"), c17), (string_key("inc"), c19)].to_object().to_any())
}
