// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{string_any, string_key};
use nanvm_lib::vm::{Any, IVm, Nullish, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("a"), Nullish::Null.to_any())].to_object().to_any();
    let c1: Any<A> = Any::dot(c0, string_any("a")).end()?;
    let c2: Any<A> = Any::dot(c1, string_any("x")).end()?;
    Ok([(string_key("default"), c2)].to_object().to_any())
}
