// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, Array, IStaticFunction, Object, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("b"), f64_any(0x3ff0000000000000))].to_object().to_any();
    let c1: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()
    }, 0, Array::default(), Some("(...$0)=>$0[0]")).to_any();
    let c2: Any<A> = [(string_key("a"), c0), (string_key("f"), c1)].to_object().to_any();
    let c3: Any<A> = Any::option_dot(c2.clone(), || Ok(string_any("a"))).dot(|| Ok(string_any("b"))).end()?;
    let c4: Any<A> = Object::default().to_any();
    let c5: Any<A> = Any::dot(c4.clone(), string_any("a")).end()?;
    let c6: Any<A> = Any::option_dot(c5, || Ok(string_any("b"))).end()?;
    let c7: Any<A> = (Any::nullish_coalescing(c6, || Ok(f64_any(0x0000000000000000))))?;
    let c8: Any<A> = Any::option_dot(c4.clone(), || Ok(string_any("a"))).end()?;
    let c9: Any<A> = Any::option_dot(c8, || Ok(string_any("b"))).end()?;
    let c10: Any<A> = (Any::nullish_coalescing(c9, || Ok(f64_any(0x0000000000000000))))?;
    let c11 = || Ok([f64_any(0x4000000000000000)].to_array().to_any());
    let c12: Any<A> = Any::dot(c2.clone(), string_any("f")).option_call(c11).end()?;
    let c13 = || Ok([f64_any(0x4008000000000000)].to_array().to_any());
    let c14: Any<A> = Any::dot(c4.clone(), string_any("f")).option_call(c13).end()?;
    let c15: Any<A> = (Any::nullish_coalescing(c14, || Ok(f64_any(0x0000000000000000))))?;
    let c16: Any<A> = Any::option_dot(c2.clone(), || Ok(string_any("a"))).end()?;
    let c17: Any<A> = Any::dot(c16, string_any("b")).end()?;
    let c18: Any<A> = [c3, c7, c10, c12, c15, c17].to_array().to_any();
    Ok([(string_key("default"), c18)].to_object().to_any())
}
