// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{
    bigint_any, f64_any, spread_array, spread_item, strict_eq, string_any, string_key, value_item,
};
use nanvm_lib::vm::{Any, Array, IStaticFunction, Nullish, Object, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let c0: Any<A> = Any::dot(args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x0000000000000000)).end()?;
        let c1: Any<A> = (strict_eq(c0, string_any("ok")))?;
        let c2 = || {
            let c3: Any<A> = Any::dot(args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
            let c4: Any<A> = Any::call(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), [c3].to_array().to_any())?;
            Ok([string_any("ok"), c4].to_array().to_any())
        };
        let c5 = || {
            let c6: Any<A> = Any::dot(args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
            let c7: Any<A> = Any::dot(c6, f64_any(0x0000000000000000)).end()?;
            let c8: Any<A> = (strict_eq(c7, string_any("ioError")))?;
            let c9 = || {
                let c10: Any<A> = Any::dot(args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
                let c11: Any<A> = Any::dot(c10, f64_any(0x3ff0000000000000)).end()?;
                let c12: Any<A> = Any::dot(c11, string_any("code")).end()?;
                let c13: Any<A> = (Any::nullish_coalescing(c12, || Ok(Nullish::Null.to_any())))?;
                Ok([string_any("error"), c13].to_array().to_any())
            };
            let c14 = || {
                let c15: Any<A> = Any::dot(args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
                Ok([string_any("error"), c15].to_array().to_any())
            };
            Any::conditional(c8, c9, c14)
        };
        Any::conditional(c1, c2, c5)
    }, 2, Array::default(), Some("($0,$1)=>$1[0]===\"ok\"?[\"ok\",$0($1[1])]:$1[1][0]===\"ioError\"?[\"error\",$1[1][1].code??null]:[\"error\",$1[1]]")).to_any();
    let c1: Any<A> = A::static_function(|self_, args| { Ok(A::static_function(|self_, args| { Ok(A::static_function(|self_, args| {
        let c0: Any<A> = A::static_function(|self_, args| {
            let c0: Any<A> = Any::call(A::frame(self_)[2].clone(), [A::frame(self_)[3].clone(), args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array().to_any())?;
            let c1: Any<A> = spread_array([spread_item(A::frame(self_)[1].clone()), value_item(c0)])?;
            Any::call(A::frame(self_)[0].clone(), [c1].to_array().to_any())
        }, 1, [A::frame(self_)[2].clone(), args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), A::frame(self_)[3].clone(), A::frame(self_)[4].clone()].to_array(), Some("($4)=>$0([...$1,$2($3,$4)])")).to_any();
        Ok([(string_key("command"), A::frame(self_)[0].clone()), (string_key("payload"), A::frame(self_)[1].clone()), (string_key("continuation"), c0)].to_object().to_any())
    }, 1, [A::frame(self_)[0].clone(), A::frame(self_)[1].clone(), args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), A::frame(self_)[2].clone(), A::frame(self_)[3].clone()].to_array(), Some("($5)=>{return {\"command\":$0,\"payload\":$1,\"continuation\":($6)=>$2([...$5,$3($4,$6)])};}")).to_any()) }, 1, [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any()), A::frame(self_)[0].clone(), args.clone().into_iter().nth(2).unwrap_or_else(|| Nullish::Undefined.to_any())].to_array(), Some("($4)=>($5)=>{return {\"command\":$0,\"payload\":$1,\"continuation\":($6)=>$4([...$5,$2($3,$6)])};}")).to_any()) }, 3, [c0].to_array(), Some("($1,$2,$3)=>($4)=>($5)=>{return {\"command\":$1,\"payload\":$2,\"continuation\":($6)=>$4([...$5,$0($3,$6)])};}")).to_any();
    let c2: Any<A> = A::static_function(|_self, _args| { Ok(Nullish::Null.to_any()) }, 1, Array::default(), Some("($0)=>null")).to_any();
    let c3: Any<A> = A::static_function(|_self, args| Any::entry(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), args.clone().into_iter().nth(1).unwrap_or_else(|| Nullish::Undefined.to_any())), 2, Array::default(), Some("($0,$1)=>{const $2=Object.getOwnPropertyDescriptor($0,$1);return $2?.enumerable?$2.value:undefined;}")).to_any();
    let c4: Any<A> = [(string_key("entry"), c3)].to_object().to_any();
    let c5: Any<A> = Any::dot(c4, string_any("entry")).end()?;
    let c6: Any<A> = [(string_key("entry"), c5)].to_object().to_any();
    let c7: Any<A> = Any::dot(c6, string_any("entry")).end()?;
    let c8: Any<A> = A::static_function(|_self, args| { Ok(A::static_function(|self_, _args| { Ok([string_any("ok"), A::frame(self_)[0].clone()].to_array().to_any()) }, 0, [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array(), Some("()=>[\"ok\",$0]")).to_any()) }, 1, Array::default(), Some("($0)=>()=>[\"ok\",$0]")).to_any();
    let c9: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/b"))?;
        let c2: Any<A> = [c1, Nullish::Undefined.to_any()].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c6: Any<A> = [c5, Nullish::Undefined.to_any()].to_array().to_any();
        let c7: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c6, c3.clone()].to_array().to_any())?;
        let c8: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/z"))?;
        let c9: Any<A> = [c8, bigint_any(-59497)].to_array().to_any();
        let c10: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c9, c3.clone()].to_array().to_any())?;
        let c11: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a/f"))?;
        let c12: Any<A> = [c11, bigint_any(-59497)].to_array().to_any();
        let c13: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c12, c3.clone()].to_array().to_any())?;
        let c14: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), Object::default().to_any()].to_array().to_any();
        let c15: Any<A> = A::frame(self_)[2].clone();
        let c16: Any<A> = A::static_function(|self_, args| {
            let c0: Any<A> = A::frame(self_)[0].clone();
            let c1: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x0000000000000000)).end()?;
            let c2: Any<A> = Any::call(c0.clone(), [c1, string_any("name")].to_array().to_any())?;
            let c3: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
            let c4: Any<A> = Any::call(c0.clone(), [c3, string_any("name")].to_array().to_any())?;
            let c5: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x4000000000000000)).end()?;
            let c6: Any<A> = Any::call(c0.clone(), [c5, string_any("name")].to_array().to_any())?;
            Ok([c2, c4, c6].to_array().to_any())
        }, 1, [c15.clone()].to_array(), Some("($1)=>[$0($1[0],\"name\"),$0($1[1],\"name\"),$0($1[2],\"name\")]")).to_any();
        let c17: Any<A> = Any::call(c0.clone(), [string_any("readdir"), c14, c16].to_array().to_any())?;
        let c18: Any<A> = [(string_key("recursive"), true.to_any())].to_object().to_any();
        let c19: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), c18].to_array().to_any();
        let c20: Any<A> = A::static_function(|self_, args| {
            let c0: Any<A> = A::frame(self_)[0].clone();
            let c1: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x0000000000000000)).end()?;
            let c2: Any<A> = Any::call(c0.clone(), [c1, string_any("name")].to_array().to_any())?;
            let c3: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
            let c4: Any<A> = Any::call(c0.clone(), [c3, string_any("name")].to_array().to_any())?;
            let c5: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x4000000000000000)).end()?;
            let c6: Any<A> = Any::call(c0.clone(), [c5, string_any("name")].to_array().to_any())?;
            let c7: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x4008000000000000)).end()?;
            let c8: Any<A> = Any::call(c0.clone(), [c7, string_any("name")].to_array().to_any())?;
            Ok([c2, c4, c6, c8].to_array().to_any())
        }, 1, [c15.clone()].to_array(), Some("($1)=>[$0($1[0],\"name\"),$0($1[1],\"name\"),$0($1[2],\"name\"),$0($1[3],\"name\")]")).to_any();
        let c21: Any<A> = Any::call(c0.clone(), [string_any("readdir"), c19, c20].to_array().to_any())?;
        let c22: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none"))?;
        let c23: Any<A> = [c22, Object::default().to_any()].to_array().to_any();
        let c24: Any<A> = Any::call(c0.clone(), [string_any("readdir"), c23, c3.clone()].to_array().to_any())?;
        let c25: Any<A> = Any::call(c24, [A::frame(self_)[3].clone()].to_array().to_any())?;
        let c26: Any<A> = Any::call(c21, [c25].to_array().to_any())?;
        let c27: Any<A> = Any::call(c17, [c26].to_array().to_any())?;
        let c28: Any<A> = Any::call(c13, [c27].to_array().to_any())?;
        let c29: Any<A> = Any::call(c10, [c28].to_array().to_any())?;
        let c30: Any<A> = Any::call(c7, [c29].to_array().to_any())?;
        let c31: Any<A> = Any::call(c4, [c30].to_array().to_any())?;
        Any::call(c31, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c7, c8.clone()].to_array(), Some("($4)=>$0(\"mkdir\",[$4+\"/b\",undefined],$1)($0(\"mkdir\",[$4+\"/a\",undefined],$1)($0(\"writeFile\",[$4+\"/z\",-59497n],$1)($0(\"writeFile\",[$4+\"/a/f\",-59497n],$1)($0(\"readdir\",[$4,{}],($5)=>[$2($5[0],\"name\"),$2($5[1],\"name\"),$2($5[2],\"name\")])($0(\"readdir\",[$4,{\"recursive\":true}],($6)=>[$2($6[0],\"name\"),$2($6[1],\"name\"),$2($6[2],\"name\"),$2($6[3],\"name\")])($0(\"readdir\",[$4+\"/none\",{}],$1)($3)))))))([])")).to_any();
    let c10: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c11: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c12: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c13: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c14: Any<A> = [string_any("a"), string_any("b"), string_any("z")].to_array().to_any();
    let c15: Any<A> = [string_any("ok"), c14].to_array().to_any();
    let c16: Any<A> = [string_any("a"), string_any("b"), string_any("z"), string_any("f")].to_array().to_any();
    let c17: Any<A> = [string_any("ok"), c16].to_array().to_any();
    let c18: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c19: Any<A> = [c10, c11, c12, c13, c15, c17, c18].to_array().to_any();
    let c20: Any<A> = [(string_key("run"), c9), (string_key("expected"), c19)].to_object().to_any();
    let c21: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c2: Any<A> = [c1].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("createExclusive"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c6: Any<A> = [c5].to_array().to_any();
        let c7: Any<A> = Any::call(c0.clone(), [string_any("createExclusive"), c6, c3.clone()].to_array().to_any())?;
        let c8: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c9: Any<A> = [bigint_any(-59497)].to_array().to_any();
        let c10: Any<A> = [c8, c9].to_array().to_any();
        let c11: Any<A> = Any::call(c0.clone(), [string_any("writeExclusive"), c10, c3.clone()].to_array().to_any())?;
        let c12: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/b"))?;
        let c13: Any<A> = [bigint_any(-59497), bigint_any(-59497)].to_array().to_any();
        let c14: Any<A> = [c12, c13].to_array().to_any();
        let c15: Any<A> = Any::call(c0.clone(), [string_any("writeExclusive"), c14, c3.clone()].to_array().to_any())?;
        let c16: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/b"))?;
        let c17: Any<A> = [c16].to_array().to_any();
        let c18: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-3899222121)) }, 1, Array::default(), Some("($0)=>$0===-3899222121n")).to_any();
        let c19: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c17, c18].to_array().to_any())?;
        let c20: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/n/c"))?;
        let c21: Any<A> = [bigint_any(-59497)].to_array().to_any();
        let c22: Any<A> = [c20, c21].to_array().to_any();
        let c23: Any<A> = Any::call(c0.clone(), [string_any("writeExclusive"), c22, c3.clone()].to_array().to_any())?;
        let c24: Any<A> = Any::call(c23, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c25: Any<A> = Any::call(c19, [c24].to_array().to_any())?;
        let c26: Any<A> = Any::call(c15, [c25].to_array().to_any())?;
        let c27: Any<A> = Any::call(c11, [c26].to_array().to_any())?;
        let c28: Any<A> = Any::call(c7, [c27].to_array().to_any())?;
        let c29: Any<A> = Any::call(c4, [c28].to_array().to_any())?;
        Any::call(c29, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"createExclusive\",[$3+\"/a\"],$1)($0(\"createExclusive\",[$3+\"/a\"],$1)($0(\"writeExclusive\",[$3+\"/a\",[-59497n]],$1)($0(\"writeExclusive\",[$3+\"/b\",[-59497n,-59497n]],$1)($0(\"readFile\",[$3+\"/b\"],($4)=>$4===-3899222121n)($0(\"writeExclusive\",[$3+\"/n/c\",[-59497n]],$1)($2))))))([])")).to_any();
    let c22: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c23: Any<A> = [string_any("error"), string_any("EEXIST")].to_array().to_any();
    let c24: Any<A> = [string_any("error"), string_any("EEXIST")].to_array().to_any();
    let c25: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c26: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c27: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c28: Any<A> = [c22, c23, c24, c25, c26, c27].to_array().to_any();
    let c29: Any<A> = [(string_key("run"), c21), (string_key("expected"), c28)].to_object().to_any();
    let c30: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c2: Any<A> = [c1, bigint_any(-59497)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c6: Any<A> = [c5].to_array().to_any();
        let c7: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-59497)) }, 1, Array::default(), Some("($0)=>$0===-59497n")).to_any();
        let c8: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c6, c7].to_array().to_any())?;
        let c9: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c10: Any<A> = [c9, bigint_any(-3899222121)].to_array().to_any();
        let c11: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c10, c3.clone()].to_array().to_any())?;
        let c12: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c13: Any<A> = [c12].to_array().to_any();
        let c14: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-3899222121)) }, 1, Array::default(), Some("($0)=>$0===-3899222121n")).to_any();
        let c15: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c13, c14].to_array().to_any())?;
        let c16: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c17: Any<A> = [c16].to_array().to_any();
        let c18: Any<A> = Any::call(c0.clone(), [string_any("rm"), c17, c3.clone()].to_array().to_any())?;
        let c19: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c20: Any<A> = [c19].to_array().to_any();
        let c21: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c20, c3.clone()].to_array().to_any())?;
        let c22: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c23: Any<A> = [c22].to_array().to_any();
        let c24: Any<A> = Any::call(c0.clone(), [string_any("rm"), c23, c3.clone()].to_array().to_any())?;
        let c25: Any<A> = Any::call(c24, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c26: Any<A> = Any::call(c21, [c25].to_array().to_any())?;
        let c27: Any<A> = Any::call(c18, [c26].to_array().to_any())?;
        let c28: Any<A> = Any::call(c15, [c27].to_array().to_any())?;
        let c29: Any<A> = Any::call(c11, [c28].to_array().to_any())?;
        let c30: Any<A> = Any::call(c8, [c29].to_array().to_any())?;
        let c31: Any<A> = Any::call(c4, [c30].to_array().to_any())?;
        Any::call(c31, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/f\",-59497n],$1)($0(\"readFile\",[$3+\"/f\"],($4)=>$4===-59497n)($0(\"writeFile\",[$3+\"/f\",-3899222121n],$1)($0(\"readFile\",[$3+\"/f\"],($5)=>$5===-3899222121n)($0(\"rm\",[$3+\"/f\"],$1)($0(\"readFile\",[$3+\"/f\"],$1)($0(\"rm\",[$3+\"/f\"],$1)($2)))))))([])")).to_any();
    let c31: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c32: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c33: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c34: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c35: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c36: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c37: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c38: Any<A> = [c31, c32, c33, c34, c35, c36, c37].to_array().to_any();
    let c39: Any<A> = [(string_key("run"), c30), (string_key("expected"), c38)].to_object().to_any();
    let c40: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a/b"))?;
        let c2: Any<A> = [(string_key("recursive"), true.to_any())].to_object().to_any();
        let c3: Any<A> = [c1, c2].to_array().to_any();
        let c4: Any<A> = A::frame(self_)[1].clone();
        let c5: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c3, c4.clone()].to_array().to_any())?;
        let c6: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a/b"))?;
        let c7: Any<A> = [(string_key("recursive"), true.to_any())].to_object().to_any();
        let c8: Any<A> = [c6, c7].to_array().to_any();
        let c9: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c8, c4.clone()].to_array().to_any())?;
        let c10: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a/b"))?;
        let c11: Any<A> = [c10, Nullish::Undefined.to_any()].to_array().to_any();
        let c12: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c11, c4.clone()].to_array().to_any())?;
        let c13: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/x/y"))?;
        let c14: Any<A> = [c13, Nullish::Undefined.to_any()].to_array().to_any();
        let c15: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c14, c4.clone()].to_array().to_any())?;
        let c16: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d"))?;
        let c17: Any<A> = [c16, Nullish::Undefined.to_any()].to_array().to_any();
        let c18: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c17, c4.clone()].to_array().to_any())?;
        let c19: Any<A> = Any::call(c18, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c20: Any<A> = Any::call(c15, [c19].to_array().to_any())?;
        let c21: Any<A> = Any::call(c12, [c20].to_array().to_any())?;
        let c22: Any<A> = Any::call(c9, [c21].to_array().to_any())?;
        let c23: Any<A> = Any::call(c5, [c22].to_array().to_any())?;
        Any::call(c23, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"mkdir\",[$3+\"/a/b\",{\"recursive\":true}],$1)($0(\"mkdir\",[$3+\"/a/b\",{\"recursive\":true}],$1)($0(\"mkdir\",[$3+\"/a/b\",undefined],$1)($0(\"mkdir\",[$3+\"/x/y\",undefined],$1)($0(\"mkdir\",[$3+\"/d\",undefined],$1)($2)))))([])")).to_any();
    let c41: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c42: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c43: Any<A> = [string_any("error"), string_any("EEXIST")].to_array().to_any();
    let c44: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c45: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c46: Any<A> = [c41, c42, c43, c44, c45].to_array().to_any();
    let c47: Any<A> = [(string_key("run"), c40), (string_key("expected"), c46)].to_object().to_any();
    let c48: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c2: Any<A> = [c1, bigint_any(-3899222121)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c6: Any<A> = [c5].to_array().to_any();
        let c7: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x0000000000000000)).end()?;
            strict_eq(c0, bigint_any(-3899222121))
        }, 1, Array::default(), Some("($0)=>$0[0]===-3899222121n")).to_any();
        let c8: Any<A> = Any::call(c0.clone(), [string_any("readWhole"), c6, c7].to_array().to_any())?;
        let c9: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array().to_any();
        let c10: Any<A> = Any::call(c0.clone(), [string_any("readWhole"), c9, c3.clone()].to_array().to_any())?;
        let c11: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none"))?;
        let c12: Any<A> = [c11].to_array().to_any();
        let c13: Any<A> = Any::call(c0.clone(), [string_any("readWhole"), c12, c3.clone()].to_array().to_any())?;
        let c14: Any<A> = Any::call(c13, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c15: Any<A> = Any::call(c10, [c14].to_array().to_any())?;
        let c16: Any<A> = Any::call(c8, [c15].to_array().to_any())?;
        let c17: Any<A> = Any::call(c4, [c16].to_array().to_any())?;
        Any::call(c17, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/f\",-3899222121n],$1)($0(\"readWhole\",[$3+\"/f\"],($4)=>$4[0]===-3899222121n)($0(\"readWhole\",[$3],$1)($0(\"readWhole\",[$3+\"/none\"],$1)($2))))([])")).to_any();
    let c49: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c50: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c51: Any<A> = [string_any("error"), string_any("ERR_NOT_A_FILE")].to_array().to_any();
    let c52: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c53: Any<A> = [c49, c50, c51, c52].to_array().to_any();
    let c54: Any<A> = [(string_key("run"), c48), (string_key("expected"), c53)].to_object().to_any();
    let c55: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c2: Any<A> = [c1, bigint_any(-59497)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/b"))?;
        let c6: Any<A> = [c5, bigint_any(-3899222121)].to_array().to_any();
        let c7: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c6, c3.clone()].to_array().to_any())?;
        let c8: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c9: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/b"))?;
        let c10: Any<A> = [c8, c9].to_array().to_any();
        let c11: Any<A> = Any::call(c0.clone(), [string_any("rename"), c10, c3.clone()].to_array().to_any())?;
        let c12: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/b"))?;
        let c13: Any<A> = [c12].to_array().to_any();
        let c14: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-59497)) }, 1, Array::default(), Some("($0)=>$0===-59497n")).to_any();
        let c15: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c13, c14].to_array().to_any())?;
        let c16: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c17: Any<A> = [c16].to_array().to_any();
        let c18: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c17, c3.clone()].to_array().to_any())?;
        let c19: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/a"))?;
        let c20: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/c"))?;
        let c21: Any<A> = [c19, c20].to_array().to_any();
        let c22: Any<A> = Any::call(c0.clone(), [string_any("rename"), c21, c3.clone()].to_array().to_any())?;
        let c23: Any<A> = Any::call(c22, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c24: Any<A> = Any::call(c18, [c23].to_array().to_any())?;
        let c25: Any<A> = Any::call(c15, [c24].to_array().to_any())?;
        let c26: Any<A> = Any::call(c11, [c25].to_array().to_any())?;
        let c27: Any<A> = Any::call(c7, [c26].to_array().to_any())?;
        let c28: Any<A> = Any::call(c4, [c27].to_array().to_any())?;
        Any::call(c28, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/a\",-59497n],$1)($0(\"writeFile\",[$3+\"/b\",-3899222121n],$1)($0(\"rename\",[$3+\"/a\",$3+\"/b\"],$1)($0(\"readFile\",[$3+\"/b\"],($4)=>$4===-59497n)($0(\"readFile\",[$3+\"/a\"],$1)($0(\"rename\",[$3+\"/a\",$3+\"/c\"],$1)($2))))))([])")).to_any();
    let c56: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c57: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c58: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c59: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c60: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c61: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c62: Any<A> = [c56, c57, c58, c59, c60, c61].to_array().to_any();
    let c63: Any<A> = [(string_key("run"), c55), (string_key("expected"), c62)].to_object().to_any();
    let c64: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/m.f.mjs"))?;
        let c2: Any<A> = [c1, bigint_any(-59497)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/m.f.mjs"))?;
        let c6: Any<A> = [c5, Nullish::Null.to_any()].to_array().to_any();
        let c7: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("id")).end()?;
            let c1 = || Ok([string_any("file:///")].to_array().to_any());
            let c2: Any<A> = Any::dot(c0, string_any("startsWith")).end_call(c1)?;
            let c3 = || {
                let c4: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("id")).end()?;
                let c5 = || Ok([string_any("/m.f.mjs")].to_array().to_any());
                Any::dot(c4, string_any("endsWith")).end_call(c5)
            };
            let c6: Any<A> = (Any::logical_and(c2, c3))?;
            let c7 = || {
                let c8: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("path")).end()?;
                let c9 = || Ok([string_any("m.f.mjs")].to_array().to_any());
                Any::dot(c8, string_any("endsWith")).end_call(c9)
            };
            Any::logical_and(c6, c7)
        }, 1, Array::default(), Some("($0)=>$0.id.startsWith(\"file:///\")&&$0.id.endsWith(\"/m.f.mjs\")&&$0.path.endsWith(\"m.f.mjs\")")).to_any();
        let c8: Any<A> = Any::call(c0.clone(), [string_any("resolveFileModule"), c6, c7].to_array().to_any())?;
        let c9: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none.f.mjs"))?;
        let c10: Any<A> = [c9, Nullish::Null.to_any()].to_array().to_any();
        let c11: Any<A> = Any::call(c0.clone(), [string_any("resolveFileModule"), c10, c3.clone()].to_array().to_any())?;
        let c12: Any<A> = Any::call(c11, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c13: Any<A> = Any::call(c8, [c12].to_array().to_any())?;
        let c14: Any<A> = Any::call(c4, [c13].to_array().to_any())?;
        Any::call(c14, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/m.f.mjs\",-59497n],$1)($0(\"resolveFileModule\",[$3+\"/m.f.mjs\",null],($4)=>$4.id.startsWith(\"file:///\")&&$4.id.endsWith(\"/m.f.mjs\")&&$4.path.endsWith(\"m.f.mjs\"))($0(\"resolveFileModule\",[$3+\"/none.f.mjs\",null],$1)($2)))([])")).to_any();
    let c65: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c66: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c67: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c68: Any<A> = [c65, c66, c67].to_array().to_any();
    let c69: Any<A> = [(string_key("run"), c64), (string_key("expected"), c68)].to_object().to_any();
    let c70: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array().to_any();
        let c1: Any<A> = Any::call(A::frame(self_)[0].clone(), [string_any("rm"), c0, A::frame(self_)[1].clone()].to_array().to_any())?;
        let c2: Any<A> = Any::call(c1, [A::frame(self_)[2].clone()].to_array().to_any())?;
        Any::call(c2, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"rm\",[$3],$1)($2)([])")).to_any();
    let c71: Any<A> = [string_any("error"), string_any("ERR_FS_EISDIR")].to_array().to_any();
    let c72: Any<A> = [c71].to_array().to_any();
    let c73: Any<A> = [(string_key("run"), c70), (string_key("expected"), c72)].to_object().to_any();
    let c74: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d"))?;
        let c2: Any<A> = [c1, Nullish::Undefined.to_any()].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("mkdir"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d/f"))?;
        let c6: Any<A> = [c5, bigint_any(-59497)].to_array().to_any();
        let c7: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c6, c3.clone()].to_array().to_any())?;
        let c8: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d"))?;
        let c9: Any<A> = [c8].to_array().to_any();
        let c10: Any<A> = Any::call(c0.clone(), [string_any("rmdir"), c9, c3.clone()].to_array().to_any())?;
        let c11: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d/f"))?;
        let c12: Any<A> = [c11].to_array().to_any();
        let c13: Any<A> = Any::call(c0.clone(), [string_any("rm"), c12, c3.clone()].to_array().to_any())?;
        let c14: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d"))?;
        let c15: Any<A> = [c14].to_array().to_any();
        let c16: Any<A> = Any::call(c0.clone(), [string_any("rmdir"), c15, c3.clone()].to_array().to_any())?;
        let c17: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/d"))?;
        let c18: Any<A> = [c17].to_array().to_any();
        let c19: Any<A> = Any::call(c0.clone(), [string_any("rmdir"), c18, c3.clone()].to_array().to_any())?;
        let c20: Any<A> = Any::call(c19, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c21: Any<A> = Any::call(c16, [c20].to_array().to_any())?;
        let c22: Any<A> = Any::call(c13, [c21].to_array().to_any())?;
        let c23: Any<A> = Any::call(c10, [c22].to_array().to_any())?;
        let c24: Any<A> = Any::call(c7, [c23].to_array().to_any())?;
        let c25: Any<A> = Any::call(c4, [c24].to_array().to_any())?;
        Any::call(c25, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"mkdir\",[$3+\"/d\",undefined],$1)($0(\"writeFile\",[$3+\"/d/f\",-59497n],$1)($0(\"rmdir\",[$3+\"/d\"],$1)($0(\"rm\",[$3+\"/d/f\"],$1)($0(\"rmdir\",[$3+\"/d\"],$1)($0(\"rmdir\",[$3+\"/d\"],$1)($2))))))([])")).to_any();
    let c75: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c76: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c77: Any<A> = [string_any("error"), string_any("ENOTEMPTY")].to_array().to_any();
    let c78: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c79: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c80: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c81: Any<A> = [c75, c76, c77, c78, c79, c80].to_array().to_any();
    let c82: Any<A> = [(string_key("run"), c74), (string_key("expected"), c81)].to_object().to_any();
    let c83: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c2: Any<A> = [c1, bigint_any(-59497)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c6: Any<A> = [c5].to_array().to_any();
        let c7: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("size")).end()?;
            let c1: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("isFile")).end()?;
            let c2: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("isDirectory")).end()?;
            Ok([c0, c1, c2].to_array().to_any())
        }, 1, Array::default(), Some("($0)=>[$0.size,$0.isFile,$0.isDirectory]")).to_any();
        let c8: Any<A> = Any::call(c0.clone(), [string_any("stat"), c6, c7].to_array().to_any())?;
        let c9: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array().to_any();
        let c10: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("isFile")).end()?;
            let c1: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("isDirectory")).end()?;
            Ok([c0, c1].to_array().to_any())
        }, 1, Array::default(), Some("($0)=>[$0.isFile,$0.isDirectory]")).to_any();
        let c11: Any<A> = Any::call(c0.clone(), [string_any("stat"), c9, c10].to_array().to_any())?;
        let c12: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none"))?;
        let c13: Any<A> = [c12].to_array().to_any();
        let c14: Any<A> = Any::call(c0.clone(), [string_any("stat"), c13, c3.clone()].to_array().to_any())?;
        let c15: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c16: Any<A> = [c15].to_array().to_any();
        let c17: Any<A> = Any::call(c0.clone(), [string_any("access"), c16, c3.clone()].to_array().to_any())?;
        let c18: Any<A> = [args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())].to_array().to_any();
        let c19: Any<A> = Any::call(c0.clone(), [string_any("access"), c18, c3.clone()].to_array().to_any())?;
        let c20: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none"))?;
        let c21: Any<A> = [c20].to_array().to_any();
        let c22: Any<A> = Any::call(c0.clone(), [string_any("access"), c21, c3.clone()].to_array().to_any())?;
        let c23: Any<A> = Any::call(c22, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c24: Any<A> = Any::call(c19, [c23].to_array().to_any())?;
        let c25: Any<A> = Any::call(c17, [c24].to_array().to_any())?;
        let c26: Any<A> = Any::call(c14, [c25].to_array().to_any())?;
        let c27: Any<A> = Any::call(c11, [c26].to_array().to_any())?;
        let c28: Any<A> = Any::call(c8, [c27].to_array().to_any())?;
        let c29: Any<A> = Any::call(c4, [c28].to_array().to_any())?;
        Any::call(c29, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/f\",-59497n],$1)($0(\"stat\",[$3+\"/f\"],($4)=>[$4.size,$4.isFile,$4.isDirectory])($0(\"stat\",[$3],($5)=>[$5.isFile,$5.isDirectory])($0(\"stat\",[$3+\"/none\"],$1)($0(\"access\",[$3+\"/f\"],$1)($0(\"access\",[$3],$1)($0(\"access\",[$3+\"/none\"],$1)($2)))))))([])")).to_any();
    let c84: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c85: Any<A> = [f64_any(0x4000000000000000), true.to_any(), false.to_any()].to_array().to_any();
    let c86: Any<A> = [string_any("ok"), c85].to_array().to_any();
    let c87: Any<A> = [false.to_any(), true.to_any()].to_array().to_any();
    let c88: Any<A> = [string_any("ok"), c87].to_array().to_any();
    let c89: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c90: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c91: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c92: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c93: Any<A> = [c84, c86, c88, c89, c90, c91, c92].to_array().to_any();
    let c94: Any<A> = [(string_key("run"), c83), (string_key("expected"), c93)].to_object().to_any();
    let c95: Any<A> = A::static_function(|_self, _args| { Err(string_any("boom")) }, 0, Array::default(), Some("()=>{throw \"boom\";}")).to_any();
    let c96: Any<A> = A::static_function(|self_, _args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = A::static_function(|_self, _args| { Ok(f64_any(0x401c000000000000)) }, 0, Array::default(), Some("()=>7")).to_any();
        let c2: Any<A> = [c1].to_array().to_any();
        let c3: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = (strict_eq(c0, string_any("ok")))?;
            let c2 = || {
                let c3: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
                strict_eq(c3, f64_any(0x401c000000000000))
            };
            Any::logical_and(c1, c2)
        }, 1, Array::default(), Some("($0)=>$0[0]===\"ok\"&&$0[1]===7")).to_any();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("catch"), c2, c3].to_array().to_any())?;
        let c5: Any<A> = A::frame(self_)[1].clone();
        let c6: Any<A> = [c5.clone()].to_array().to_any();
        let c7: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x0000000000000000)).end()?;
            let c1: Any<A> = (strict_eq(c0, string_any("error")))?;
            let c2 = || {
                let c3: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x3ff0000000000000)).end()?;
                strict_eq(c3, string_any("boom"))
            };
            Any::logical_and(c1, c2)
        }, 1, Array::default(), Some("($0)=>$0[0]===\"error\"&&$0[1]===\"boom\"")).to_any();
        let c8: Any<A> = Any::call(c0.clone(), [string_any("catch"), c6, c7].to_array().to_any())?;
        let c9: Any<A> = A::static_function(|_self, _args| { Ok(f64_any(0x4000000000000000)) }, 0, Array::default(), Some("()=>2")).to_any();
        let c10: Any<A> = [c9].to_array().to_any();
        let c11: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("result")).end()?;
            let c1: Any<A> = Any::dot(c0, f64_any(0x0000000000000000)).end()?;
            let c2: Any<A> = (strict_eq(c1, string_any("ok")))?;
            let c3 = || {
                let c4: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("result")).end()?;
                let c5: Any<A> = Any::dot(c4, f64_any(0x3ff0000000000000)).end()?;
                strict_eq(c5, f64_any(0x4000000000000000))
            };
            let c6: Any<A> = (Any::logical_and(c2, c3))?;
            let c7 = || {
                let c8: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("duration")).end()?;
                let c9: Any<A> = (c8 * f64_any(0x3ff0000000000000))?;
                let c10: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("duration")).end()?;
                strict_eq(c9, c10)
            };
            let c11: Any<A> = (Any::logical_and(c6, c7))?;
            let c12 = || {
                let c13: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("duration")).end()?;
                Any::ge(c13, f64_any(0x0000000000000000))
            };
            Any::logical_and(c11, c12)
        }, 1, Array::default(), Some("($0)=>$0.result[0]===\"ok\"&&$0.result[1]===2&&$0.duration*1===$0.duration&&$0.duration>=0")).to_any();
        let c12: Any<A> = Any::call(c0.clone(), [string_any("sandbox"), c10, c11].to_array().to_any())?;
        let c13: Any<A> = [c5.clone()].to_array().to_any();
        let c14: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("result")).end()?;
            let c1: Any<A> = Any::dot(c0, f64_any(0x0000000000000000)).end()?;
            let c2: Any<A> = (strict_eq(c1, string_any("error")))?;
            let c3 = || {
                let c4: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("result")).end()?;
                let c5: Any<A> = Any::dot(c4, f64_any(0x3ff0000000000000)).end()?;
                strict_eq(c5, string_any("boom"))
            };
            let c6: Any<A> = (Any::logical_and(c2, c3))?;
            let c7 = || {
                let c8: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("duration")).end()?;
                let c9: Any<A> = (c8 * f64_any(0x3ff0000000000000))?;
                let c10: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("duration")).end()?;
                strict_eq(c9, c10)
            };
            let c11: Any<A> = (Any::logical_and(c6, c7))?;
            let c12 = || {
                let c13: Any<A> = Any::dot(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), string_any("duration")).end()?;
                Any::ge(c13, f64_any(0x0000000000000000))
            };
            Any::logical_and(c11, c12)
        }, 1, Array::default(), Some("($0)=>$0.result[0]===\"error\"&&$0.result[1]===\"boom\"&&$0.duration*1===$0.duration&&$0.duration>=0")).to_any();
        let c15: Any<A> = Any::call(c0.clone(), [string_any("sandbox"), c13, c14].to_array().to_any())?;
        let c16: Any<A> = A::static_function(|_self, args| {
            let c0: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) * f64_any(0x3ff0000000000000))?;
            let c1: Any<A> = (strict_eq(c0, args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any())))?;
            let c2 = || {
                let c3: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) % f64_any(0x3ff0000000000000))?;
                strict_eq(c3, f64_any(0x0000000000000000))
            };
            let c4: Any<A> = (Any::logical_and(c1, c2))?;
            let c5 = || Any::gt(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x426d1a94a2000000));
            let c6: Any<A> = (Any::logical_and(c4, c5))?;
            let c7 = || Any::lt(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), f64_any(0x42d6bcc41e900000));
            Any::logical_and(c6, c7)
        }, 1, Array::default(), Some("($0)=>$0*1===$0&&$0%1===0&&$0>1000000000000&&$0<100000000000000")).to_any();
        let c17: Any<A> = Any::call(c0.clone(), [string_any("now"), Array::default().to_any(), c16].to_array().to_any())?;
        let c18: Any<A> = Any::call(c17, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c19: Any<A> = Any::call(c15, [c18].to_array().to_any())?;
        let c20: Any<A> = Any::call(c12, [c19].to_array().to_any())?;
        let c21: Any<A> = Any::call(c8, [c20].to_array().to_any())?;
        let c22: Any<A> = Any::call(c4, [c21].to_array().to_any())?;
        Any::call(c22, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c95, c8.clone()].to_array(), Some("($3)=>$0(\"catch\",[()=>7],($4)=>$4[0]===\"ok\"&&$4[1]===7)($0(\"catch\",[$1],($5)=>$5[0]===\"error\"&&$5[1]===\"boom\")($0(\"sandbox\",[()=>2],($6)=>$6.result[0]===\"ok\"&&$6.result[1]===2&&$6.duration*1===$6.duration&&$6.duration>=0)($0(\"sandbox\",[$1],($7)=>$7.result[0]===\"error\"&&$7.result[1]===\"boom\"&&$7.duration*1===$7.duration&&$7.duration>=0)($0(\"now\",[],($8)=>$8*1===$8&&$8%1===0&&$8>1000000000000&&$8<100000000000000)($2)))))([])")).to_any();
    let c97: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c98: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c99: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c100: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c101: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c102: Any<A> = [c97, c98, c99, c100, c101].to_array().to_any();
    let c103: Any<A> = [(string_key("run"), c96), (string_key("expected"), c102)].to_object().to_any();
    let c104: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c2: Any<A> = [c1, bigint_any(-3899222121)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c6: Any<A> = [c5, f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any();
        let c7: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-59752)) }, 1, Array::default(), Some("($0)=>$0===-59752n")).to_any();
        let c8: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c6, c7].to_array().to_any())?;
        let c9: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c10: Any<A> = [c9, f64_any(0x4008000000000000), f64_any(0x4024000000000000)].to_array().to_any();
        let c11: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-233)) }, 1, Array::default(), Some("($0)=>$0===-233n")).to_any();
        let c12: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c10, c11].to_array().to_any())?;
        let c13: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c14: Any<A> = [c13, f64_any(0x4022000000000000), f64_any(0x4010000000000000)].to_array().to_any();
        let c15: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(0)) }, 1, Array::default(), Some("($0)=>$0===0n")).to_any();
        let c16: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c14, c15].to_array().to_any())?;
        let c17: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c18: Any<A> = [c17, f64_any(0x0000000000000000), f64_any(0x0000000000000000)].to_array().to_any();
        let c19: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(0)) }, 1, Array::default(), Some("($0)=>$0===0n")).to_any();
        let c20: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c18, c19].to_array().to_any())?;
        let c21: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none"))?;
        let c22: Any<A> = [c21, f64_any(0x0000000000000000), f64_any(0x3ff0000000000000)].to_array().to_any();
        let c23: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c22, c3.clone()].to_array().to_any())?;
        let c24: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c25: Any<A> = [c24, f64_any(0xbff0000000000000), f64_any(0x3ff0000000000000)].to_array().to_any();
        let c26: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c25, c3.clone()].to_array().to_any())?;
        let c27: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c28: Any<A> = [c27, f64_any(0x0000000000000000), f64_any(0x4100000800000000)].to_array().to_any();
        let c29: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c28, c3.clone()].to_array().to_any())?;
        let c30: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c31: Any<A> = [c30, f64_any(0x3fe0000000000000), f64_any(0x3ff0000000000000)].to_array().to_any();
        let c32: Any<A> = Any::call(c0.clone(), [string_any("readBytes"), c31, c3.clone()].to_array().to_any())?;
        let c33: Any<A> = Any::call(c32, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c34: Any<A> = Any::call(c29, [c33].to_array().to_any())?;
        let c35: Any<A> = Any::call(c26, [c34].to_array().to_any())?;
        let c36: Any<A> = Any::call(c23, [c35].to_array().to_any())?;
        let c37: Any<A> = Any::call(c20, [c36].to_array().to_any())?;
        let c38: Any<A> = Any::call(c16, [c37].to_array().to_any())?;
        let c39: Any<A> = Any::call(c12, [c38].to_array().to_any())?;
        let c40: Any<A> = Any::call(c8, [c39].to_array().to_any())?;
        let c41: Any<A> = Any::call(c4, [c40].to_array().to_any())?;
        Any::call(c41, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/f\",-3899222121n],$1)($0(\"readBytes\",[$3+\"/f\",1,2],($4)=>$4===-59752n)($0(\"readBytes\",[$3+\"/f\",3,10],($5)=>$5===-233n)($0(\"readBytes\",[$3+\"/f\",9,4],($6)=>$6===0n)($0(\"readBytes\",[$3+\"/f\",0,0],($7)=>$7===0n)($0(\"readBytes\",[$3+\"/none\",0,1],$1)($0(\"readBytes\",[$3+\"/f\",-1,1],$1)($0(\"readBytes\",[$3+\"/f\",0,131073],$1)($0(\"readBytes\",[$3+\"/f\",0.5,1],$1)($2)))))))))([])")).to_any();
    let c105: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c106: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c107: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c108: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c109: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c110: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c111: Any<A> = [string_any("error"), Nullish::Null.to_any()].to_array().to_any();
    let c112: Any<A> = [string_any("error"), Nullish::Null.to_any()].to_array().to_any();
    let c113: Any<A> = [string_any("error"), Nullish::Null.to_any()].to_array().to_any();
    let c114: Any<A> = [c105, c106, c107, c108, c109, c110, c111, c112, c113].to_array().to_any();
    let c115: Any<A> = [(string_key("run"), c104), (string_key("expected"), c114)].to_object().to_any();
    let c116: Any<A> = A::static_function(|self_, args| {
        let c0: Any<A> = A::frame(self_)[0].clone();
        let c1: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c2: Any<A> = [c1, bigint_any(-3899222121)].to_array().to_any();
        let c3: Any<A> = A::frame(self_)[1].clone();
        let c4: Any<A> = Any::call(c0.clone(), [string_any("writeFile"), c2, c3.clone()].to_array().to_any())?;
        let c5: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c6: Any<A> = [c5, f64_any(0x3ff0000000000000), bigint_any(-55898)].to_array().to_any();
        let c7: Any<A> = Any::call(c0.clone(), [string_any("writeBytes"), c6, c3.clone()].to_array().to_any())?;
        let c8: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/f"))?;
        let c9: Any<A> = [c8].to_array().to_any();
        let c10: Any<A> = A::static_function(|_self, args| { strict_eq(args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()), bigint_any(-3898235497)) }, 1, Array::default(), Some("($0)=>$0===-3898235497n")).to_any();
        let c11: Any<A> = Any::call(c0.clone(), [string_any("readFile"), c9, c10].to_array().to_any())?;
        let c12: Any<A> = (args.clone().into_iter().next().unwrap_or_else(|| Nullish::Undefined.to_any()) + string_any("/none"))?;
        let c13: Any<A> = [c12, f64_any(0x0000000000000000), bigint_any(-59497)].to_array().to_any();
        let c14: Any<A> = Any::call(c0.clone(), [string_any("writeBytes"), c13, c3.clone()].to_array().to_any())?;
        let c15: Any<A> = Any::call(c14, [A::frame(self_)[2].clone()].to_array().to_any())?;
        let c16: Any<A> = Any::call(c11, [c15].to_array().to_any())?;
        let c17: Any<A> = Any::call(c7, [c16].to_array().to_any())?;
        let c18: Any<A> = Any::call(c4, [c17].to_array().to_any())?;
        Any::call(c18, [Array::default().to_any()].to_array().to_any())
    }, 1, [c1.clone(), c2.clone(), c8.clone()].to_array(), Some("($3)=>$0(\"writeFile\",[$3+\"/f\",-3899222121n],$1)($0(\"writeBytes\",[$3+\"/f\",1,-55898n],$1)($0(\"readFile\",[$3+\"/f\"],($4)=>$4===-3898235497n)($0(\"writeBytes\",[$3+\"/none\",0,-59497n],$1)($2))))([])")).to_any();
    let c117: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c118: Any<A> = [string_any("ok"), Nullish::Null.to_any()].to_array().to_any();
    let c119: Any<A> = [string_any("ok"), true.to_any()].to_array().to_any();
    let c120: Any<A> = [string_any("error"), string_any("ENOENT")].to_array().to_any();
    let c121: Any<A> = [c117, c118, c119, c120].to_array().to_any();
    let c122: Any<A> = [(string_key("run"), c116), (string_key("expected"), c121)].to_object().to_any();
    Ok([(string_key("directory"), c20), (string_key("exclusive"), c29), (string_key("files"), c39), (string_key("mkdirs"), c47), (string_key("readWhole"), c54), (string_key("renames"), c63), (string_key("resolution"), c69), (string_key("rmOfADirectory"), c73), (string_key("rmdirs"), c82), (string_key("stats"), c94), (string_key("thunks"), c103), (string_key("windows"), c115), (string_key("writeBytes"), c122)].to_object().to_any())
}
