// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::string_key;
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        Ok(rest.clone().to_any())
    }, 0, Array::default()).to_any();
    Ok([(string_key("default"), c0)].to_object().to_any())
}
