// @generated by `fjs compile`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{
    f64_any, spread_array, spread_call, spread_item, string_any, string_key, value_item,
};
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray, ToObject};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any();
    let c1: Any<A> = spread_array([value_item(f64_any(0x0000000000000000)), spread_item(c0.clone()), value_item(f64_any(0x4008000000000000))])?;
    let c2: Any<A> = spread_array([spread_item(string_any("a😀"))])?;
    let c3: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        Ok(rest.clone().to_any())
    }, 0, Array::default(), Some("(...a)=>a")).to_any();
    let c4: Any<A> = spread_call(c3, [spread_item(c0.clone()), value_item(f64_any(0x4010000000000000))])?;
    let c5: Any<A> = spread_array([spread_item(c0.clone()), spread_item(c0.clone())])?;
    let c6: Any<A> = Any::dot(c5, string_any("length")).end()?;
    let c7 = || {
        let c8: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
        spread_array([spread_item(c8)])
    };
    let c9: Any<A> = Any::dot(c0.clone(), string_any("at")).end_call(c7)?;
    let c10: Any<A> = [c1, c2, c4, c6, c9].to_array().to_any();
    Ok([(string_key("default"), c10)].to_object().to_any())
}
