/**
 * The `.rs` output branch of `fjs compile`: a linked EDAG printed as a
 * self-contained Rust module that builds the module's value through the
 * `nanvm-lib` API —
 * [mvp-roadmap](../../../nanvm-lib/todo/mvp-roadmap.md),
 * [fjs-nanvm-integration](../../../todo/fjs-nanvm-integration.md).
 *
 * The node printer, its temporaries and the lines of a scope are not this
 * module's own: they live in
 * [`fjs/edag/rust`](../../edag/rust/module.f.mjs), shared with
 * [`fjs/nanvm/rust`](../../nanvm/rust/module.f.mjs), which prints the
 * operator conformance corpus the same way. What is specific to this module:
 * laying a module's scope out as the body of the
 * `pub fn module<A: IVm>() -> Result<Any<A>, Any<A>>` a harness can call —
 * `A: IStaticFunction` once the module holds a function, the capability its
 * closures bind through — and importing exactly the `nanvm_lib` names the
 * printer reports its text spells (`scope`'s `uses`, `useLines`) — the
 * crate is the output's one dependency, so the functions a literal becomes
 * are `vm::unstable`'s, never copied here.
 *
 * @module
 *
 * @import { Exp } from '../../edag/types.ts'
 * @import { Scope } from '../../edag/rust/types.ts'
 * @import { Result } from '../../types/result/types.ts'
 */

import { error, mapOk, okThen, unwrap } from '../../types/result/module.f.mjs'
import { analysis, checked } from '../../edag/analysis/module.f.mjs'
import { holdsFunction, indent, readsArgs, scope, useLines } from '../../edag/rust/module.f.mjs'

/**
 * The bound on the module's VM parameter: `IVm`, or `IStaticFunction` —
 * which is `IVm` and the capability to bind a Rust static function — once
 * the module holds a function, read off the EDAG (`holdsFunction`) and not
 * the text: the bound is the output's public API, and no data may change it.
 *
 * @type {(root: Exp) => string}
 */
const vmBound = root => holdsFunction(root) ? 'IStaticFunction' : 'IVm'

/**
 * The module's scope, one line per temporary and its `Ok(…)`, indented into
 * the module's function, with the names it spells —
 * `fjs/edag/rust`'s {@link scope}, which also prints every function's body
 * the module holds, each a scope of its own inside its closure — or the
 * refusal. Validate bindings against their owning functions before printing:
 * a fixed read cannot reach past its owner's length, and a closure's frame
 * belongs to the enclosing scope. The fragment printer cannot perform that
 * check without the complete graph. A module has no arguments, so an
 * `['args']` node in its own scope — a function body's node, which the
 * lowering never puts here, handed in directly — is refused rather than
 * printed as a name nothing binds; a module has no frame either, and a
 * `['frame', i]` in its own scope is `checked`'s refusal.
 *
 * @type {(root: Exp) => Result<Scope, readonly unknown[]>}
 */
const body = root => {
    const [kind, a] = okThen(checked)(analysis(root))
    if (kind === 'error') { return error([a, root]) }
    return readsArgs(root)
    ? error(['no Rust for `args` in a module\'s own scope; a module has no arguments', root])
    : mapOk((/** @type {Scope} */ { lines, uses }) => ({ lines: lines.map(l => `${indent}${l}`), uses }))(scope(root))
}

/**
 * The EDAG as a generated Rust module, or the refusal: a node shape this
 * printer has no `nanvm-lib` spelling for, an invalid parameter binding, or
 * a function length above the language's limit.
 * Unsupported output is a `Result`, as in `fjs/edag/rust`'s `scope`.
 * Invalid length metadata or a node shared across invocation scopes is
 * refused through the same diagnostic channel.
 *
 * `pub fn module` carries `#[rustfmt::skip]`, the same as every function
 * [`fjs/nanvm/rust`](../../nanvm/rust/module.f.mjs) emits: the layout is
 * the printer's own — one temporary per line, a closure's body a block
 * under its `let` — and not rustfmt's, which breaks a closure argument
 * and a method chain its own way, and a line still grows with the items
 * of one literal. A layout-preserving printer would have to reproduce
 * rustfmt's own wrapping, which is what the skip avoids paying for.
 *
 * @type {(root: Exp) => Result<string, readonly unknown[]>}
 */
const generateResult = root => mapOk((/** @type {Scope} */ { lines, uses }) => {
    const bound = vmBound(root)
    return [
        '// @generated by `fjs compile`. Do not edit: recompile the source module instead.',
        '',
        ...useLines(uses, bound),
        '',
        '#[rustfmt::skip]',
        `pub fn module<A: ${bound}>() -> Result<Any<A>, Any<A>> {`,
        ...lines,
        '}',
        '',
    ].join('\n')
})(body(root))

/**
 * {@link generateResult} as a throwing convenience, for direct use and for
 * this module's own proofs — `unwrap`'s throw is the ordinary FunctionalScript
 * panic `fjs/AGENTS.md` §1.5 describes, not a caught exception: nothing here
 * recovers from it, so it propagates uncaught exactly as a thrown value with
 * no `try`/`catch` does.
 *
 * @type {(root: Exp) => string}
 */
export const generate = root => unwrap(generateResult(root))

/**
 * The reason {@link generateResult} refused, as text. Every refusal
 * `scope` reports (`fjs/edag/rust/module.f.mjs`) is a `[reason, detail]`
 * pair — `lookup`'s convention, kept by every refusal added since — never a
 * bare value, so joining the pair's own `String` forms is exact rather than
 * approximate.
 *
 * @type {(reason: readonly unknown[]) => string}
 */
const reasonText = reason => reason.map(String).join(': ')

/**
 * The EDAG as Rust, or the refusal: a node shape this printer has no
 * `nanvm-lib` spelling for, reported the same way a `.json` output's refusal
 * is — against the output rather than the input, since the module compiled
 * without complaint. Built directly from {@link generateResult}'s own
 * `Result`, including structural graph diagnostics from analysis.
 * No `try`/`catch` or host adapter is needed to report unsupported output.
 *
 * @type {(root: Exp) => Result<string, string>}
 */
export const toRust = root => {
    const result = generateResult(root)
    return result[0] === 'ok'
        ? result
        : error(`no Rust spelling for this module: ${reasonText(result[1])}`)
}
