/**
 * Proofs for the Rust printer.
 *
 * The interesting assertion is `generate`'s on a tiny synthetic corpus: it
 * pins the exact text of every construct the printer can emit, so a change in
 * layout is a visible diff here and not only in the generated file.
 *
 * @module
 */

/** @import { Data, Value } from '../types.ts' */
import { assert, assertEq } from '../../../fjs/asserts/module.f.mjs'
import {
    array,
    boolean,
    bigint,
    data,
    functionValue,
    nullValue,
    number,
    object,
    string,
    undefinedValue,
} from '../module.f.mjs'
import {
    bigintLiteral,
    call,
    directory,
    generate,
    numberLiteral,
    operandExpr,
    path,
    snakeCase,
    stringLiteral,
    valueExpr,
} from './module.f.mjs'

/** @type {(v: Value) => (expected: string) => void} */
const expr = v => expected => assertEq(valueExpr(v), expected)

/**
 * One case of every shape the printer can emit: a shared value and a
 * reference to it, a skipped case, a throwing case, and a commutative binary
 * operator.
 *
 * @type {Data}
 */
const sample = {
    eq: {
        shared: [['emptyArray', array([])]],
        cases: [
            { name: 'itself', a: ['ref', 'emptyArray'], b: ['ref', 'emptyArray'], eq: true },
            { name: 'skipped', a: nullValue, b: nullValue, eq: true, rust: 'not yet' },
        ],
    },
    groups: [
        {
            op: 'unaryPlus',
            cases: [{ name: 'bigint', args: [bigint(0n)], expected: ['throw'] }],
        },
        {
            op: 'mul',
            commutative: true,
            cases: [{
                name: 'oneByTwo',
                args: [number(1), number(2)],
                expected: ['value', number(2)],
            }],
        },
    ],
}

const expected = `// @generated by \`npm run ci-update\` from \`nanvm-lib/tests/module.f.mjs\`.
// Do not edit: change the shared operator test data and regenerate.

use super::harness::*;

#[rustfmt::skip]
fn eq<A: IVm>() {
    let empty_array: Any<A> = Array::default().to_any();
    check_eq::<A>("itself", empty_array.clone(), empty_array.clone(), true);
    // TODO: not yet
    // check_eq::<A>("skipped", Nullish::Null.to_any(), Nullish::Null.to_any(), true);
}

#[rustfmt::skip]
fn unary_plus<A: IVm>() {
    check_throws::<A>("bigint", Any::unary_plus(bigint_any(0)));
}

#[rustfmt::skip]
fn mul<A: IVm>() {
    check::<A>("oneByTwo", (1f64).to_any() * (2f64).to_any(), (2f64).to_any());
    check::<A>("oneByTwoSwapped", (2f64).to_any() * (1f64).to_any(), (2f64).to_any());
}

pub fn all<A: IVm>() {
    eq::<A>();
    unary_plus::<A>();
    mul::<A>();
}
`

export const proof = {
    path: () => {
        assertEq(directory, 'nanvm-lib/tests/test')
        assertEq(path, 'nanvm-lib/tests/test/generated.rs')
    },
    snakeCase: () => {
        assertEq(snakeCase('emptyArray'), 'empty_array')
        assertEq(snakeCase('stringCoercion'), 'string_coercion')
        assertEq(snakeCase('eq'), 'eq')
    },
    stringLiteral: () => {
        assertEq(stringLiteral('abc'), '"abc"')
        assertEq(stringLiteral('a\\b'), '"a\\\\b"')
        assertEq(stringLiteral('a"b'), '"a\\"b"')
        assertEq(stringLiteral('a\nb'), '"a\\nb"')
        assertEq(stringLiteral('a\rb'), '"a\\rb"')
        assertEq(stringLiteral('a\tb'), '"a\\tb"')
    },
    numberLiteral: () => {
        assertEq(numberLiteral(NaN), 'f64::NAN')
        assertEq(numberLiteral(Infinity), 'f64::INFINITY')
        assertEq(numberLiteral(-Infinity), 'f64::NEG_INFINITY')
        assertEq(numberLiteral(-0), '-0f64')
        assertEq(numberLiteral(0), '0f64')
        assertEq(numberLiteral(2.3), '2.3f64')
        assertEq(numberLiteral(-239), '-239f64')
    },
    bigintLiteral: () => {
        assertEq(bigintLiteral(0n), '0')
        assertEq(bigintLiteral(-456n), '-456')
        assertEq(bigintLiteral(-(2n ** 63n)), '-9223372036854775808')
        assertEq(bigintLiteral(2n ** 63n - 1n), '9223372036854775807')
    },
    valueExpr: () => {
        expr(nullValue)('Nullish::Null.to_any()')
        expr(undefinedValue)('Nullish::Undefined.to_any()')
        expr(boolean(true))('true.to_any()')
        expr(boolean(false))('false.to_any()')
        expr(number(-0.3))('(-0.3f64).to_any()')
        expr(string('a'))('string_any("a")')
        expr(bigint(-1n))('bigint_any(-1)')
        expr(array([]))('Array::default().to_any()')
        expr(array([nullValue]))('[Nullish::Null.to_any()].to_array().to_any()')
        expr(object([]))('Object::default().to_any()')
        expr(object([['k', nullValue]]))(
            '[(string_key("k"), Nullish::Null.to_any())].to_object().to_any()')
        expr(functionValue)('function_any()')
    },
    operandExpr: () => {
        assertEq(operandExpr(['ref', 'stringArray']), 'string_array.clone()')
        assertEq(operandExpr(nullValue), 'Nullish::Null.to_any()')
    },
    call: () => {
        assertEq(call('unaryPlus')(['x']), 'Any::unary_plus(x)')
        assertEq(call('unaryMinus')(['x']), '-(x)')
        assertEq(call('mul')(['x', 'y']), 'x * y')
        assertEq(call('stringCoercion')(['x']), 'x.to_string().map(|v| v.to_any())')
    },
    generate: () => {
        assertEq(generate(sample), expected)
    },
    generateData: () => {
        // The real corpus, which is what `ci-update` writes. Only its shape is
        // asserted here: its contents are checked by `cargo test`.
        const result = generate(data)
        assert(result.endsWith('}\n'), result)
        assert(result.includes('pub fn all<A: IVm>() {'), result)
        for (const g of data.groups) {
            assert(result.includes(`fn ${snakeCase(g.op)}<A: IVm>() {`), g.op)
            assert(result.includes(`    ${snakeCase(g.op)}::<A>();`), g.op)
        }
    },
    throw: {
        bigintTooLarge: () => bigintLiteral(2n ** 63n),
        bigintTooSmall: () => bigintLiteral(-(2n ** 63n) - 1n),
        controlCharacter: () => stringLiteral('a\u0000b'),
        deleteCharacter: () => stringLiteral('a\u007fb'),
    },
}
