/**
 * Proofs for the `.rs` output branch of `fjs compile`.
 *
 * @import { Exp } from '../../edag/types.ts'
 */

import { assert, assertEq } from '../../asserts/module.f.mjs'
import { generate, toRust } from './module.f.mjs'

export const proof = {
    /**
     * A whole module whose sharing is implicit — two references to the same
     * array by identity, as two `cref`s to one `const` lower — gets exactly
     * one `let` binding, cloned at each reference; picks only the
     * `nanvm_lib::vm` names its own body needs; and needs no private helper,
     * since it holds no string or bigint.
     */
    generate: () => {
        /** @type {Exp} */
        const base = ['[]', [1, 2]]
        /** @type {Exp} */
        const root = ['[]', [base, base]]
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(1f64).to_any(), (2f64).to_any()].to_array().to_any();
    Ok([c0.clone(), c0.clone()].to_array().to_any())
}
`)
    },
    /**
     * Property access on an object literal — new relative to the operator
     * test corpus — pulls in `string_any`/`string_key`, which have no
     * harness crate to come from here, so the generated module defines its
     * own, and the `String`/`ToObject` imports those need.
     */
    generatePropertyAccess: () => {
        /** @type {Exp} */
        const root = ['.', ['{}', [[':', 'a', 'x']]], 'a']
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, String, ToAny, ToObject};

fn string_any<A: IVm>(v: &str) -> Any<A> {
    v.into()
}

fn string_key<A: IVm>(v: &str) -> String<A> {
    v.into()
}

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(Any::own_property([(string_key("a"), string_any("x"))].to_object().to_any(), string_any("a")).unwrap())
}
`)
    },
    /** A constant default export needs no bindings, no helpers, one import. */
    generateConstant: () => {
        assertEq(generate(null), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, Nullish, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(Nullish::Null.to_any())
}
`)
    },
    /** A bigint literal pulls in `bigint_any` and the `BigInt` import it needs. */
    generateBigint: () => {
        assertEq(generate(-5n), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, BigInt, IVm, ToAny};

fn bigint_any<A: IVm>(v: i64) -> Any<A> {
    Into::<BigInt<A>>::into(v).to_any()
}

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(bigint_any(-5))
}
`)
    },
    /**
     * A module with an unreached `const` — `const unused = []; export default
     * 42;` — links to a `,` root (`fjs/fsc/edag/module.f.mjs`'s `resolve`
     * anchors what the export does not reach rather than dropping it), which
     * prints as a block: the unused `const` is still established, and the
     * export's value is the block's.
     */
    generateComma: () => {
        assertEq(generate([',', [['[]', []], 42]]), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, Array, IVm, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok({ let _: Any<A> = Array::default().to_any(); (42f64).to_any() })
}
`)
    },
    toRust: {
        ok: () => {
            const result = toRust(null)
            assertEq(result[0], 'ok')
            assert(result[1].includes('pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {'), result)
        },
        /**
         * A node shape the printer refuses — here, a numeric index, which has
         * no `nanvm-lib` spelling until `entry` lands
         * (`fjs/edag/todo/entry.md`) — is a `Result` error against the
         * output, not a thrown exception a compiler caller has to catch.
         */
        refused: () => {
            const result = toRust(['.', ['{}', []], 0])
            assertEq(result[0], 'error')
            assert(typeof result[1] === 'string' && result[1].length > 0, result)
        },
        /**
         * A property read on a nullish base compiles to a `Result` error
         * instead of Rust that panics at run time.
         */
        refusedNullishBase: () => {
            const result = toRust(['.', null, 'a'])
            assertEq(result[0], 'error')
        },
    },
}
