/**
 * Proofs for the `.rs` output branch of `fjs compile`.
 *
 * @import { Exp } from '../../edag/types.ts'
 */

import { assert, assertEq, assertStructurallySame } from '../../asserts/module.f.mjs'
import { generate, toRust } from './module.f.mjs'

export const proof = {
    throw: {
        invalidLength: [-0, -1, 0.5, NaN, Infinity].map(length => () => toRust(['=>', length, null, 1])),
        invalidBindingThroughGenerate: () => generate(['=>', 1, null, ['arg', 1]]),
        overLimitLengthThroughGenerate: () => generate(['=>', 17, null, 1]),
    },
    /**
     * A whole module whose sharing is implicit — two references to the same
     * array by identity, as two `cref`s to one `const` lower — gets exactly
     * one temporary, cloned at each reference, and picks only the
     * `nanvm_lib::vm` names and the one `unstable` helper its own body
     * needs.
     */
    generate: () => {
        /** @type {Exp} */
        const base = ['[]', [1, 2]]
        /** @type {Exp} */
        const root = ['[]', [base, base]]
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any();
    Ok([c0.clone(), c0.clone()].to_array().to_any())
}
`)
    },
    /**
     * Property access on an object literal — new relative to the operator
     * test corpus — calls `string_any`/`string_key`, imported from
     * `nanvm_lib::vm::unstable` as the corpus imports them, with the
     * `ToObject` import the object needs. The object is a temporary, the
     * read the module's own answer.
     */
    generatePropertyAccess: () => {
        /** @type {Exp} */
        const root = ['.', ['{}', [[':', 'a', 'x']]], 'a']
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("a"), string_any("x"))].to_object().to_any();
    Any::dot(c0, string_any("a")).end()
}
`)
    },
    /**
     * A two-level chain, one line per node: the inner read's own `?` is on
     * its `let`, so a throw anywhere in the chain propagates out of
     * `module`, not only from the read built on top.
     */
    generatePropertyChain: () => {
        /** @type {Exp} */
        const root = ['.', ['.', ['{}', [[':', 'a', ['{}', [[':', 'b', 1]]]]]], 'a'], 'b']
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [(string_key("b"), f64_any(0x3ff0000000000000))].to_object().to_any();
    let c1: Any<A> = [(string_key("a"), c0)].to_object().to_any();
    let c2: Any<A> = Any::dot(c1, string_any("a")).end()?;
    Any::dot(c2, string_any("b")).end()
}
`)
    },
    /** A constant default export needs no bindings, one literal, one import. */
    generateConstant: () => {
        assertEq(generate(null), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, Nullish, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(Nullish::Null.to_any())
}
`)
    },
    /** A bigint literal pulls in `bigint_any` alone: the `BigInt` it builds, and the `ToAny` that wraps it, are that function's business, not the module's. */
    generateBigint: () => {
        assertEq(generate(-5n), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::bigint_any;
use nanvm_lib::vm::{Any, IVm};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(bigint_any(-5))
}
`)
    },
    /**
     * A module with an unreached `const` — `const unused = [1]; export
     * default 42;` — links to a `,` root (`fjs/fsc/edag/module.f.mjs`'s
     * `resolve` anchors what the export does not reach rather than dropping
     * it): the unused `const` is still established, a temporary nothing
     * references and so named `_`, and the export's value is the module's.
     */
    generateComma: () => {
        assertEq(generate([',', [['[]', [1]], 42]]), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let _: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    Ok(f64_any(0x4045000000000000))
}
`)
    },
    /**
     * A module holding a function bounds on `IStaticFunction` — `IVm` and
     * the capability its closure binds through — and imports `Array` for
     * the empty frame: `const f = (...a) => a[0]; export default f(41);`,
     * the function and the arguments temporaries, its root the call, an
     * operation answering its own `Result`.
     */
    generateFunctionCall: () => {
        /** @type {Exp} */
        const root = ['()', ['=>', 0, null, ['.', ['rest'], 0]], ['[]', [41]]]
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()
    }, 0, Array::default()).to_any();
    let c1: Any<A> = [f64_any(0x4044800000000000)].to_array().to_any();
    Any::call(c0, c1)
}
`)
    },
    /**
     * A function whose body binds a temporary of its own — `const f =
     * (...a) => { const first = a[0]; return [first, first]; }; export
     * default f(1);` — is a closure over a block, one line under another
     * inside the `let` that holds it, its own `c0` distinct from the
     * module's.
     */
    generateFunctionScope: () => {
        /** @type {Exp} */
        const first = ['.', ['rest'], 0]
        assertEq(generate(['()', ['=>', 0, null, ['[]', [first, first]]], ['[]', [1]]]), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        let c0: Any<A> = Any::dot(rest.clone().to_any(), f64_any(0x0000000000000000)).end()?;
        Ok([c0.clone(), c0.clone()].to_array().to_any())
    }, 0, Array::default()).to_any();
    let c1: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    Any::call(c0, c1)
}
`)
    },
    /**
     * One function called twice is one shared node — `const f`, referenced
     * twice — bound once and cloned at each call, so the two calls share
     * an identity as they do in JavaScript; each call's arguments and its
     * value, referenced once, are moved.
     */
    generateSharedFunction: () => {
        /** @type {Exp} */
        const f = ['=>', 0, null, ['rest']]
        assertEq(generate(['[]', [['()', f, ['[]', [1]]], ['()', f, ['[]', [2]]]]]), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, Array, IStaticFunction, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IStaticFunction>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = A::static_function(|_self, args| {
        let rest = args.clone().into_iter().to_array();
        Ok(rest.clone().to_any())
    }, 0, Array::default()).to_any();
    let c1: Any<A> = [f64_any(0x3ff0000000000000)].to_array().to_any();
    let c2: Any<A> = Any::call(c0.clone(), c1)?;
    let c3: Any<A> = [f64_any(0x4000000000000000)].to_array().to_any();
    let c4: Any<A> = Any::call(c0.clone(), c3)?;
    Ok([c2, c4].to_array().to_any())
}
`)
    },
    /**
     * A string literal spelling a marker — the name of a helper, an
     * import, the function binding — is data: the module imports nothing
     * for it and stays on `IVm`, since the bound is read off the EDAG.
     */
    generateStringSpellingMarkers: () => {
        assertEq(generate(['[]', ['static_function(', 'Array::default', 'f64_any(']]), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::string_any;
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok([string_any("static_function("), string_any("Array::default"), string_any("f64_any(")].to_array().to_any())
}
`)
    },
    toRust: {
        lengthLimit: () => {
            for (const graph of /** @type {readonly Exp[]} */ ([
                ['=>', 17, null, 1],
                ['=>', 2 ** 32, null, 1],
                ['=>', 0, null, ['=>', 17, null, 1]],
                ['=>', 0, ['[]', [['=>', 17, null, 1]]], ['frame']],
                ['?:', true, 1, ['=>', 17, null, 1]],
                ['{}', [[':', 'f', ['=>', 17, null, 1]]]],
            ])) { assertEq(toRust(graph)[0], 'error') }
            for (const body of /** @type {readonly Exp[]} */ ([1, ['arg', 15], ['rest']])) {
                assertEq(toRust(['=>', 16, null, body])[0], 'ok')
            }
        },
        refusedParameterBindings: () => {
            assertStructurallySame(toRust(['=>', 1, null, ['arg', 1]]),
                ['error', 'no Rust spelling for this module: invalid fixed parameter index or scope: =>,1,,arg,1'])
            for (const index of [-0, -1, 0.5, NaN, Infinity]) {
                assertEq(toRust(['=>', 1, null, ['arg', index]])[0], 'error')
            }
            for (const e of /** @type {readonly Exp[]} */ ([
                ['arg', 0], ['rest'], ['=>', 0, null, ['arg', 0]],
                ['=>', 1, null, ['args']],
                ['=>', 1, null, ['?:', true, 0, ['arg', 1]]],
                // A nested body's index belongs to that function, not its parent.
                ['=>', 2, null, ['=>', 0, null, ['arg', 1]]],
                // A nested frame belongs to the parent, not the new function.
                ['=>', 1, null, ['=>', 2, ['[]', [['arg', 1]]], ['arg', 0]]],
            ])) { assertEq(toRust(e)[0], 'error') }
        },
        fixedAndCapturedBindings: () => {
            for (const e of /** @type {readonly Exp[]} */ ([
                ['=>', 1, null, ['arg', 0]],
                ['=>', 16, null, ['arg', 15]],
                ['=>', 2, null, ['=>', 0, ['[]', [['arg', 1], ['rest']]], ['frame']]],
            ])) { assertEq(toRust(e)[0], 'ok') }
        },
        ok: () => {
            const result = toRust(null)
            assertEq(result[0], 'ok')
            assert(result[1].includes('pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {'), result)
        },
        /**
         * A node shape the printer refuses — here, a `Number(...)` cast
         * index, which names a run-time coercion rather than a literal key
         * and has no `nanvm-lib` cast primitive to route it through — is a
         * `Result` error against the output, not a thrown exception a
         * compiler caller has to catch.
         */
        refused: () => {
            const result = toRust(['.', ['{}', []], ['Number', 1]])
            assertEq(result[0], 'error')
            assert(typeof result[1] === 'string' && result[1].length > 0, result)
        },
        /**
         * `false && (1n / 0n)`: the lazy operator's right operand is a
         * thunk answering the throwing operation's own `Result` — a
         * temporary of its own, the operation's line naming it — so the
         * module answers `false` where a by-value spelling would have
         * thrown. The node comes in directly, as every other node this
         * route is proven on does; the same four from source, through the
         * whole of `fjs compile`, are `nanvm-harness/fixtures/lazy.mjs`,
         * run against `nanvm-lib`.
         */
        lazyOperator: () => {
            assertStructurallySame(toRust(['&&', false, ['/', 1n, 0n]]), ['ok', `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::bigint_any;
use nanvm_lib::vm::{Any, IVm, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0 = || bigint_any(1) / bigint_any(0);
    Any::logical_and(false.to_any(), c0)
}
`])
            assertEq(toRust(['||', true, ['/', 1n, 0n]])[0], 'ok')
            assertEq(toRust(['??', 1, ['/', 1n, 0n]])[0], 'ok')
        },
        /**
         * `?:` with a throwing unselected arm: both arms are thunks — the
         * literal's where the operation is, the operation's a temporary —
         * and the one the condition selects is the only one established.
         */
        conditional: () => {
            assertStructurallySame(toRust(['?:', true, 1, ['/', 1n, 0n]]), ['ok', `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{bigint_any, f64_any};
use nanvm_lib::vm::{Any, IVm, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0 = || bigint_any(1) / bigint_any(0);
    Any::conditional(true.to_any(), || Ok(f64_any(0x3ff0000000000000)), c0)
}
`])
        },
        /**
         * A `const` reached eagerly once and lazily once — `const c = [];
         * export default [c, a && c]` — is a temporary before the root,
         * established there as JavaScript establishes a `const` at its
         * declaration, and the thunk clones it.
         */
        sharedThroughLazyOperand: () => {
            /** @type {Exp} */
            const c = ['[]', []]
            const result = toRust(['[]', [c, ['&&', false, c]]])
            assertEq(result[0], 'ok')
            assert(result[1].includes('    let c0: Any<A> = Array::default().to_any();\n    let c1: Any<A> = (Any::logical_and(false.to_any(), || Ok(c0.clone())))?;\n    Ok([c0.clone(), c1].to_array().to_any())'), result)
        },
        /**
         * A shared node reached only through lazy operands is refused: a
         * `let` binding would establish it before the root, where the
         * program may never establish it at all — `true ? 1 : [c, c]`
         * answers `1` with `c`'s `1n / 0n` never run. The lowering anchors
         * such a `const` eagerly, so no linked module has this shape; an
         * EDAG handed in directly can, and is refused rather than compiled
         * to a throw. An atom is not refused — `args` in a function, or an
         * empty container — since binding one establishes nothing.
         */
        refusedSharedOnlyThroughLazyOperands: () => {
            /** @type {Exp} */
            const boom = ['/', 1n, 0n]
            assertStructurallySame(
                toRust(['?:', true, 1, ['[]', [boom, boom]]]),
                ['error', 'no Rust spelling for this module: no Rust for a shared node reached only through lazy operands; a `let` binding would establish what the program may not: /,1,0'])
            /** @type {Exp} */
            const c = ['[]', [1]]
            assertEq(toRust(['[]', [['&&', true, c], ['&&', false, c]]])[0], 'error')
            /** @type {Exp} */
            const empty = ['[]', []]
            assertEq(toRust(['[]', [['&&', true, empty], ['&&', false, empty]]])[0], 'ok')
            assertEq(toRust(['=>', 0, null, ['?:', true, ['rest'], ['rest']]])[0], 'ok')
        },
        /**
         * Module imports must be linked before Rust output. Function-local
         * rest is bound by its invocation and remains valid.
         */
        refusedArgsInModuleScope: () => {
            assertEq(toRust(['args'])[0], 'error')
            assertEq(toRust(['[]', [['args']]])[0], 'error')
            assertEq(toRust(['=>', 0, null, ['rest']])[0], 'ok')
        },
        /** `frame` too: a module has none, a function body has its own. */
        refusedFrameInModuleScope: () => {
            assertEq(toRust(['frame'])[0], 'error')
            assertEq(toRust(['=>', 0, ['[]', [['[]', []]]], ['frame']])[0], 'ok')
        },
        /**
         * A property read on a nullish base compiles: the `.rs` output is a
         * program, and the throw is the VM's when it runs, reported by the
         * harness as `RunError::Thrown` — `nanvm-harness/fixtures/nullish.mjs`.
         */
        nullishBase: () => {
            assertEq(toRust(['.', null, 'a'])[0], 'ok')
        },
        /**
         * A string no Rust `&str` can hold, one with a lone surrogate, is
         * spelled by its code units and imports the helper that builds it.
         */
        loneSurrogate: () => {
            const result = toRust('\ud800')
            assertEq(result[0], 'ok')
            const text = /** @type {string} */ (result[1])
            assert(text.includes('string_any_utf16(&[0xd800])'), text)
            assert(text.includes('use nanvm_lib::vm::unstable::string_any_utf16;'), text)
        },
        /**
         * A bigint no `i64` can hold is refused against the output, naming
         * what could not be spelled, where it once threw past the compiler
         * uncaught.
         */
        refusedBigintOutOfRange: () => {
            const result = toRust(2n ** 63n)
            assertStructurallySame(
                result,
                ['error', 'no Rust spelling for this module: no Rust i64 for: 9223372036854775808'])
        },
    },
}
