/**
 * Proofs for the `.rs` output branch of `fjs compile`.
 *
 * @import { Exp } from '../../edag/types.ts'
 */

import { assert, assertEq, assertStructurallySame } from '../../asserts/module.f.mjs'
import { generate, toRust } from './module.f.mjs'

export const proof = {
    /**
     * A whole module whose sharing is implicit — two references to the same
     * array by identity, as two `cref`s to one `const` lower — gets exactly
     * one `let` binding, cloned at each reference, and picks only the
     * `nanvm_lib::vm` names and the one `unstable` helper its own body
     * needs.
     */
    generate: () => {
        /** @type {Exp} */
        const base = ['[]', [1, 2]]
        /** @type {Exp} */
        const root = ['[]', [base, base]]
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, IVm, ToAny, ToArray};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    let c0: Any<A> = [f64_any(0x3ff0000000000000), f64_any(0x4000000000000000)].to_array().to_any();
    Ok([c0.clone(), c0.clone()].to_array().to_any())
}
`)
    },
    /**
     * Property access on an object literal — new relative to the operator
     * test corpus — calls `string_any`/`string_key`, imported from
     * `nanvm_lib::vm::unstable` as the corpus imports them, with the
     * `ToObject` import the object needs.
     */
    generatePropertyAccess: () => {
        /** @type {Exp} */
        const root = ['.', ['{}', [[':', 'a', 'x']]], 'a']
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(Any::member_access([(string_key("a"), string_any("x"))].to_object().to_any(), string_any("a"))?)
}
`)
    },
    /**
     * A two-level chain: the inner read's own `?` sits inside the outer
     * call's argument, so a throw anywhere in the chain propagates out of
     * `module`, not only from the read built on top.
     */
    generatePropertyChain: () => {
        /** @type {Exp} */
        const root = ['.', ['.', ['{}', [[':', 'a', ['{}', [[':', 'b', 1]]]]]], 'a'], 'b']
        assertEq(generate(root), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::{f64_any, string_any, string_key};
use nanvm_lib::vm::{Any, IVm, ToAny, ToObject};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(Any::member_access(Any::member_access([(string_key("a"), [(string_key("b"), f64_any(0x3ff0000000000000))].to_object().to_any())].to_object().to_any(), string_any("a"))?, string_any("b"))?)
}
`)
    },
    /** A constant default export needs no bindings, one literal, one import. */
    generateConstant: () => {
        assertEq(generate(null), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::{Any, IVm, Nullish, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(Nullish::Null.to_any())
}
`)
    },
    /** A bigint literal pulls in `bigint_any` alone: the `BigInt` it builds, and the `ToAny` that wraps it, are that function's business, not the module's. */
    generateBigint: () => {
        assertEq(generate(-5n), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::bigint_any;
use nanvm_lib::vm::{Any, IVm};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok(bigint_any(-5))
}
`)
    },
    /**
     * A module with an unreached `const` — `const unused = []; export default
     * 42;` — links to a `,` root (`fjs/fsc/edag/module.f.mjs`'s `resolve`
     * anchors what the export does not reach rather than dropping it), which
     * prints as a block: the unused `const` is still established, and the
     * export's value is the block's.
     */
    generateComma: () => {
        assertEq(generate([',', [['[]', []], 42]]), `// @generated by \`fjs compile\`. Do not edit: recompile the source module instead.

use nanvm_lib::vm::unstable::f64_any;
use nanvm_lib::vm::{Any, Array, IVm, ToAny};

#[rustfmt::skip]
pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {
    Ok({ let _: Any<A> = Array::default().to_any(); f64_any(0x4045000000000000) })
}
`)
    },
    toRust: {
        ok: () => {
            const result = toRust(null)
            assertEq(result[0], 'ok')
            assert(result[1].includes('pub fn module<A: IVm>() -> Result<Any<A>, Any<A>> {'), result)
        },
        /**
         * A node shape the printer refuses — here, a `Number(...)` cast
         * index, which names a run-time coercion rather than a literal key
         * and has no `nanvm-lib` cast primitive to route it through — is a
         * `Result` error against the output, not a thrown exception a
         * compiler caller has to catch.
         */
        refused: () => {
            const result = toRust(['.', ['{}', []], ['Number', 1]])
            assertEq(result[0], 'error')
            assert(typeof result[1] === 'string' && result[1].length > 0, result)
        },
        /**
         * A property read on a nullish base compiles to a `Result` error
         * instead of Rust that panics at run time.
         */
        refusedNullishBase: () => {
            const result = toRust(['.', null, 'a'])
            assertEq(result[0], 'error')
        },
        /**
         * A string no Rust literal can hold and a bigint no `i64` can are
         * refused against the output, naming what could not be spelled,
         * where they once threw past the compiler uncaught or wrote a file
         * `rustc` could not read.
         */
        refusedLoneSurrogate: () => {
            const result = toRust('\ud800')
            assertStructurallySame(
                result,
                ['error', 'no Rust spelling for this module: no Rust string literal for a lone surrogate in: "\\ud800"'])
        },
        refusedBigintOutOfRange: () => {
            const result = toRust(2n ** 63n)
            assertStructurallySame(
                result,
                ['error', 'no Rust spelling for this module: no Rust i64 for: 9223372036854775808'])
        },
    },
}
