/**
 * Generate the arrow factory table at build time.
 * @module
 * @import { NodeProgram } from '../../../effects/node/types.ts'
 */

import { exitStep, writeUtf8File } from '../../../effects/node/module.f.mjs'

/** @type {(limit: number) => string} */
export const generate = limit => `// @generated by fjs/edag/callable/generate. Do not edit.
/** @import { Factory } from './types.ts' */

/** @type {readonly Factory[]} */
export const factories = [
${Array.from({ length: limit + 1 }, (_, length) => {
    const fixed = Array.from({ length }, (_, i) => `a${i}`)
    return `    g => (${[...fixed, '...rest'].join(', ')}) => g([${fixed.join(', ')}], rest),\n`
}).join('')}];
`

/** @type {NodeProgram} */
export const main = () => exitStep(writeUtf8File('fjs/edag/callable/table.f.mjs', generate(32)))
