name: Bun CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
    steps:
    - uses: actions/checkout@v2
    - run: curl https://bun.sh/install | bash 
    # export BUN_INSTALL="/Users/sergeyshandar/.bun"
    # export PATH="$BUN_INSTALL/bin:$PATH"
    - env: 
        BUN_INSTALL: /Users/sergeyshandar/.bun
    - env:
        PATH: $BUN_INSTALL/bin:$PATH
    - run: bun install
    - run: bun test
