name: Bun CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: curl https://bun.sh/install | bash 
    - run: export BUN_INSTALL="/home/runner/.bun"
    - run: export PATH="$BUN_INSTALL/bin:$PATH"
    - run: bun run ./test.f.js
