{
  "name": "CI",
  "on": {
    "pull_request": {},
    "merge_group": {}
  },
  "permissions": {
    "contents": "read"
  },
  "jobs": {
    "ubuntu-intel": {
      "runs-on": "ubuntu-26.04",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run node --version)\" = \"v26.7.0\""
        },
        {
          "run": "./nix/run npm ci"
        },
        {
          "run": "./nix/run cargo test"
        },
        {
          "run": "./nix/run cargo test --release"
        },
        {
          "run": "./nix/run cargo clippy -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --release -- -D warnings"
        },
        {
          "run": "./nix/run cargo test --target i686-unknown-linux-gnu"
        },
        {
          "run": "./nix/run cargo test --target i686-unknown-linux-gnu --release"
        },
        {
          "run": "./nix/run cargo clippy --target i686-unknown-linux-gnu -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --target i686-unknown-linux-gnu --release -- -D warnings"
        },
        {
          "run": "./nix/run node --test"
        }
      ]
    },
    "ubuntu-arm": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run node --version)\" = \"v26.7.0\""
        },
        {
          "run": "./nix/run npm ci"
        },
        {
          "run": "./nix/run cargo test"
        },
        {
          "run": "./nix/run cargo test --release"
        },
        {
          "run": "./nix/run cargo clippy -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --release -- -D warnings"
        },
        {
          "run": "./nix/run node --test"
        }
      ]
    },
    "macos-intel": {
      "runs-on": "macos-26-intel",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run node --version)\" = \"v26.7.0\""
        },
        {
          "run": "./nix/run npm ci"
        },
        {
          "run": "./nix/run cargo test"
        },
        {
          "run": "./nix/run cargo test --release"
        },
        {
          "run": "./nix/run cargo clippy -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --release -- -D warnings"
        },
        {
          "run": "./nix/run node --test"
        }
      ]
    },
    "macos-arm": {
      "runs-on": "macos-26",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run node --version)\" = \"v26.7.0\""
        },
        {
          "run": "./nix/run npm ci"
        },
        {
          "run": "./nix/run cargo test"
        },
        {
          "run": "./nix/run cargo test --release"
        },
        {
          "run": "./nix/run cargo clippy -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --release -- -D warnings"
        },
        {
          "run": "./nix/run node --test"
        }
      ]
    },
    "windows-intel": {
      "runs-on": "windows-2025",
      "steps": [
        {
          "uses": "dtolnay/rust-toolchain@1.98.0",
          "with": {
            "components": "rustfmt,clippy",
            "targets": "i686-pc-windows-msvc"
          }
        },
        {
          "uses": "actions/setup-node@v7.0.0",
          "with": {
            "node-version": "26.7.0"
          }
        },
        {
          "run": "npm install -g functionalscript@0.48.0"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "cargo test"
        },
        {
          "run": "cargo test --release"
        },
        {
          "run": "cargo clippy -- -D warnings"
        },
        {
          "run": "cargo clippy --release -- -D warnings"
        },
        {
          "run": "cargo test --target i686-pc-windows-msvc"
        },
        {
          "run": "cargo test --target i686-pc-windows-msvc --release"
        },
        {
          "run": "cargo clippy --target i686-pc-windows-msvc -- -D warnings"
        },
        {
          "run": "cargo clippy --target i686-pc-windows-msvc --release -- -D warnings"
        },
        {
          "run": "fjs test"
        }
      ]
    },
    "windows-arm": {
      "runs-on": "windows-11-arm",
      "steps": [
        {
          "uses": "dtolnay/rust-toolchain@1.98.0",
          "with": {
            "components": "rustfmt,clippy"
          }
        },
        {
          "uses": "actions/setup-node@v7.0.0",
          "with": {
            "node-version": "26.7.0"
          }
        },
        {
          "run": "npm install -g functionalscript@0.48.0"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "cargo test"
        },
        {
          "run": "cargo test --release"
        },
        {
          "run": "cargo clippy -- -D warnings"
        },
        {
          "run": "cargo clippy --release -- -D warnings"
        },
        {
          "run": "fjs test"
        }
      ]
    },
    "wasm": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run wasmtime --version)\" = \"wasmtime 45.0.2\""
        },
        {
          "run": "test \"$(./nix/run wasmer --version)\" = \"wasmer 7.1.0\""
        },
        {
          "run": "./nix/run cargo fmt -- --check"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip1"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip1 --release"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-wasip1 -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-wasip1 --release -- -D warnings"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip1 --config .cargo/config.wasmer.toml"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip1 --config .cargo/config.wasmer.toml --release"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip2"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip2 --release"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-wasip2 -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-wasip2 --release -- -D warnings"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip2 --config .cargo/config.wasmer.toml"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip2 --config .cargo/config.wasmer.toml --release"
        },
        {
          "run": "./nix/run cargo test --target wasm32-unknown-unknown"
        },
        {
          "run": "./nix/run cargo test --target wasm32-unknown-unknown --release"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-unknown-unknown -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-unknown-unknown --release -- -D warnings"
        },
        {
          "run": "./nix/run cargo test --target wasm32-unknown-unknown --config .cargo/config.wasmer.toml"
        },
        {
          "run": "./nix/run cargo test --target wasm32-unknown-unknown --config .cargo/config.wasmer.toml --release"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-wasip1-threads -- -D warnings"
        },
        {
          "run": "./nix/run cargo clippy --target wasm32-wasip1-threads --release -- -D warnings"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip1-threads --config .cargo/config.wasmer.toml"
        },
        {
          "run": "./nix/run cargo test --target wasm32-wasip1-threads --config .cargo/config.wasmer.toml --release"
        }
      ]
    },
    "deno": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run deno eval 'console.log(Deno.version.deno)')\" = \"2.8.3\""
        },
        {
          "run": "./nix/run deno install --frozen"
        },
        {
          "run": "./nix/run deno task cov"
        }
      ]
    },
    "bun": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run bun --version)\" = \"1.4.0\""
        },
        {
          "run": "./nix/run bun install --frozen-lockfile"
        },
        {
          "run": "./nix/run bun test --coverage"
        }
      ]
    },
    "node22": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/node22/run node --version)\" = \"v22.23.2\""
        },
        {
          "run": "./nix/node22/run npm ci"
        },
        {
          "run": "./nix/node22/run node --test"
        }
      ]
    },
    "node24": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/node24/run node --version)\" = \"v24.19.0\""
        },
        {
          "run": "./nix/node24/run npm ci"
        },
        {
          "run": "./nix/node24/run node --test"
        }
      ]
    },
    "node26": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "cachix/install-nix-action@v31.11.1"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "test \"$(./nix/run node --version)\" = \"v26.7.0\""
        },
        {
          "run": "test \"$(./nix/run tsc --version)\" = \"Version 7.0.2\""
        },
        {
          "run": "./nix/run npm ci"
        },
        {
          "run": "./nix/run tsc"
        },
        {
          "run": "./nix/run npm run cov"
        },
        {
          "run": "./nix/run npm pack"
        },
        {
          "run": "./nix/run npm run gen"
        },
        {
          "run": "git add -A && git diff --cached --exit-code"
        },
        {
          "uses": "actions/upload-artifact@v7.0.1",
          "with": {
            "name": "package-tarball",
            "path": "*.tgz",
            "if-no-files-found": "error"
          }
        }
      ]
    },
    "package-check": {
      "runs-on": "ubuntu-26.04-arm",
      "needs": [
        "node26"
      ],
      "steps": [
        {
          "uses": "actions/download-artifact@v8.0.1",
          "with": {
            "name": "package-tarball"
          }
        },
        {
          "uses": "actions/setup-node@v7.0.0",
          "with": {
            "node-version": "26.7.0"
          }
        },
        {
          "run": "npm init -y > /dev/null"
        },
        {
          "run": "npm install \"packed@file:$(echo *.tgz)\""
        },
        {
          "run": "npm install \"typescript@7.0.2\""
        },
        {
          "run": "echo '{\"include\":[\"node_modules/packed/**/*\",\"node_modules/packed/**/.*\",\"node_modules/packed/**/.*/**/*\"],\"exclude\":[],\"compilerOptions\":{\"module\":\"nodenext\",\"target\":\"esnext\",\"strict\":true,\"noEmit\":true,\"skipLibCheck\":false}}' > tsconfig.json"
        },
        {
          "run": "npx tsc"
        }
      ]
    }
  }
}