# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: COM Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-12']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 19
      uses: actions/setup-node@v2
      with:
        node-version: 19
    - uses: actions/setup-dotnet@2
      with:
        dotnet-version: 7
    - run: npm ci
    - run: npm run comtest
