name: Deno CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: *
    # - run: deno run --unstable --compat --allow-read --allow-env ./test.f.cjs
    - run: deno run --allow-read ./deno-test
