{
  "name": "npm publish",
  "on": {
    "push": {
      "branches": [
        "main"
      ]
    }
  },
  "permissions": {
    "contents": "read",
    "id-token": "write"
  },
  "jobs": {
    "publish-npm": {
      "runs-on": "ubuntu-26.04-arm",
      "steps": [
        {
          "uses": "actions/setup-node@v7.0.0",
          "with": {
            "node-version": "26.7.0",
            "registry-url": "https://registry.npmjs.org/"
          }
        },
        {
          "run": "npm install -g typescript@7.0.2"
        },
        {
          "uses": "actions/checkout@v7.0.1"
        },
        {
          "run": "npm ci"
        },
        {
          "run": "npm publish --provenance",
          "continue-on-error": true
        }
      ]
    }
  }
}